### ISSUE TITLE
fxLayoutGap grid can conflict with parent gap and causes inconsistent behavior on screen resize

### ISSUE THREAD

**Issue by rfuhrer** [angular/flex-layout#1000]
# Bug Report

#### What is the expected behavior?
The negative margin (gutter) should be applied on the `fxLayoutGap="8px grid"` element at all times.

#### What is the current behavior?
When a page loads for the first time the negative margin on the host element isn't applied until the screen hits a media query break point.

#### What are the steps to reproduce?
I wasn't able to reproduce this on Stackblitz probably because of the way it renders the live view might be triggering the fix.  Here's how it looks on my machine: ![resize](https://i.imgur.com/gT2vyTo.gif)

The div surrounding the buttons has a gap grid, but if you inspect it, there's no style on it until you shrink the page enough to hit a break. after that it correctly has the `0 -8px -8px 0` margin on it even if you return to the original size.

Here's the code that causes this for me: (buttons have to go in another div or else it screws them up with the gap margins, but it works fine on a tags with the mat-button style ¯\\\_(ツ)\_/¯ )
```
<div fxLayoutGap="8px grid" fxLayout="row wrap">
      <div>
        <button mat-raised-button class="btn-space" color="primary"
          (click)="newBha()">New BHA</button>
      </div>
      <div>
        <button mat-raised-button class="btn-space" color="primary"
          (click)="copyBha()">Copy This BHA</button>
      </div>
      <div>
        <button mat-raised-button class="btn-space" color="primary"
          (click)="deleteBha()">Delete BHA</button>
      </div>
      <a color="primary">
        <mat-icon>insert_drive_file</mat-icon>
        BHA Report
      </a>
      <a color="primary">
        <mat-icon>insert_drive_file</mat-icon>
        Strap Sheets
      </a>
</div>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
<pre><code>
Angular CLI: 7.2.1
Node: 11.2.0
OS: win32 x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cdk                      7.2.1
@angular/cli                      7.2.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
</code></pre>

**Comment by CaerusKaru** [comment]
If you can't get it to work on StackBlitz, can you provide another means to demo this? Just including the code snippet (unless it works on StackBlitz) is insufficient.

**Comment by rfuhrer** [comment]
No problem.  I created a new project and was able to reproduce it again.  The thing I was missing was that it has to be a grid gap inside a normal gap.
```html
<div fxLayout="column" fxLayoutGap="10px">
  <div fxLayoutGap="50px grid" fxLayout="row wrap">
```
Here's a working stackblitz: https://stackblitz.com/edit/angular-flex-layout-seed-xhzamw
You have to resize the live view to get it to happen.  So I guess the real issue is that grid inside of flex is not supported/working?  I can rework my page to not do this for now, but it seems odd that you can't say "Make all elements in this div space out by 10px, and then make all elements inside this inner div space out by 10px, and wrap them if the screen is too small".  I'm using the grid in this case so there's vertical spacing when wrapped but no wasted spacing when not wrapped.

**Comment by CaerusKaru** [comment]
Ok yeah now that makes sense. So there's a critical issue going on here in two parts:

1. The parent gap and the child gap are competing to place a margin on the child "parent" element
2. Does it matter?

I'll discuss this with @ThomasBurleson but my gut tells me this isn't supported behavior, or at the very least is not high enough priority to warrant an immediate fix.

There are several possible solutions:

1. We could add a new modifier that tells a parent gap not to apply a gap to a specific element (ie `fxNoGap`)
2. We could add a race-buster like we did for `show-hide`, where a child gap listens to its parent's gap for updates, and then refreshes the correct stylings

Again, this is behavior we _can_ support, it's just a question of making clear the intention.

**Comment by rfuhrer** [comment]
Yeah it's not an incredible scenario to say "Space out these things, and one of these things contains a bunch of things i want to wrap if there's no room".  But creating this ticket gave me a deeper understanding of how the gaps work.  So the outer gap is adding margins to all children, the inner gap grid is adding margins to itself, which means conflict.

So as usual, the solution is even more divs 😃 
```html
<div fxLayout="column" fxLayoutGap="10px">
  <div> <!-- gets the 10px margin-->
    <div fxLayoutGap="50px grid" fxLayout="row wrap"> <!-- gets the -50px margin -->
```

**Comment by CaerusKaru** [comment]
I think your workaround is reasonable, and I don't think this is something we're going to fix at the library-level. As always, you are welcome to implement a custom `StyleBuilder` to implement the behavior you'd like to see in your own library. Thanks for the discussion on this!
