### ISSUE TITLE
Responsive API Breakpoints

### ISSUE THREAD

**Issue by fastrde** [angular/flex-layout#1005]
# Proposal

#### What is the summary of the proposal?
Let's move the responsive breakpoints by 1 pixel. For example a medium screen is up to (and including) 1280px wide not 1279px

#### What is the proposal?
normal screens are up to 1280px and up to 1920px wide. On my macbook 1280px screen my design is in the lg-category when i maximize the window. When i shrink the window by one pixel to 1279px is in the md-category. This feels like the wrong behavior. The screen up to (and including) 1280px should be in the md-category and screen from 1281px up to (and including) 1920px should be in the lg-category.

Like this:
xs | 'screen and (max-width: 600px)'
-- | --
sm | 'screen and (min-width: 601px) and (max-width: 960px)'
md | 'screen and (min-width: 961px) and (max-width: 1280px)'
lg | 'screen and (min-width: 1281px) and (max-width: 1920px)'
xl | 'screen and (min-width: 1921px) and (max-width: 5000px)'
  |  
lt-sm | 'screen and (max-width: 600px)'
lt-md | 'screen and (max-width: 960px)'
lt-lg | 'screen and (max-width: 1280px)'
lt-xl | 'screen and (max-width: 1920px)'
  |  
gt-xs | 'screen and (min-width: 601px)'
gt-sm | 'screen and (min-width: 961px)'
gt-md | 'screen and (min-width: 1281px)'
gt-lg | 'screen and (min-width: 1921px)'

#### Is there anything else we should know?
nope.

**Comment by CaerusKaru** [comment]
Our pixel values are dictated by the Material Design spec. If you’d like to change this, please take it up with them. You may also feel free to override the default values yourself using Angular DI. Thank you for your interest!

**Comment by eprevot** [comment]
Maybe I missed something but from this page https://material.io/design/layout/responsive-layout-grid.html#breakpoints, it seems that  

Material Design uses:
- sm: 600-1023
- md: 1024-1439
- lg: 1440-1920


and FxLayout uses:
- sm: 600-959
- md: 960-1279
- lg: 1280-1920

Is that a recent change from Material Design ?
