### ISSUE TITLE
Add special flag in directives for IE 11

### ISSUE THREAD

**Issue by AdemHodzic** [angular/flex-layout#1008]
# Feature Request
Add flag for Internet Explorer (something like .ms)
#### What is the desired behavior?
Since there are a lot of bugs regarding flex layout and IE 11 (https://github.com/philipwalton/flexbugs), it would be nice we could have some way of saying use this only if IE or Edge is used.

#### What is the use-case or motivation for the desired behavior?
I think it would be really helpful for developers working in enterprise world. 

#### Is there anything else we should know?
Not that I can think of

**Comment by CaerusKaru** [comment]
Closing because hopefully my comment resolves this issue. If that's not the case, we can reopen.

**Comment by AdemHodzic** [comment]
Well when I try to use column layout on a div, it's content goes beyond it's container (it doesn't wrap). Do you know any workaround for this?

**Comment by CaerusKaru** [comment]
Try top-level config useColumnBasisZero:

`FlexLayoutModule.withConfig({useColumnBasisZero: true})`
