### ISSUE TITLE
inline-flex doesn't seem to apply when using fxLayoutAlign

### ISSUE THREAD

**Issue by captaincaius** [angular/flex-layout#1009]
# Bug Report

I tried to follow the examples in the tests in [PR 539](https://github.com/angular/flex-layout/pull/539) to get inline-flex applied.

<img width="1206" alt="screen shot 2019-01-25 at 5 47 14 pm" src="https://user-images.githubusercontent.com/210413/51778801-49c9fb80-20c9-11e9-8664-9c1096d76003.png">

#### What is the expected behavior?

When applying `fxLayout="row inline"` with `fxLayoutAlign="fill center"`, the containing element should have **inline-flex** applied instead of *flex*.

#### What is the current behavior?

without `fxLayoutAlign` it applies properly, but with fxLayoutAlign for some reason it doesn't.

#### What are the steps to reproduce?

Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz Demo](https://stackblitz.com/edit/angular-flex-layout-seed-btqmxf?file=app%2Fapp.component.ts) using latest `npm` nightly release: 

#### What is the use-case or motivation for changing an existing behavior?

`mat-button`'s wrap whatever you put inside it by span, so trying to use `fxLayout` within the body of a `mat-button` doesn't work right.

of course, my example shows that the problem isn't related to material and it shows even without it ;)

**Comment by CaerusKaru** [comment]
I prayed no one would actually encounter this, because it's really, really annoying. But it's a bug nonetheless, so we're on it!

**Comment by captaincaius** [comment]
:D sorry to ruin your prayers!  If it makes you feel better, mine rarely get answered either ;).

Thanks for the awesome quick reply!
