### ISSUE TITLE
Responsive example in the Performance Doc not working

### ISSUE THREAD

**Issue by NehalDamania** [angular/flex-layout#1012]
The example provided in the documentation page [Performance Considerations](https://github.com/angular/flex-layout/wiki/Performance-Considerations) 
https://stackblitz.com/edit/angular-flex-layout-seed-jmob2p is not working. The layout is not changing to column mode for "Use css" view.

I think it shoud be ngClass.xs instead of class.xs to make the responsive css example work.
Here is the fix I did just changed class to ngClass
https://stackblitz.com/edit/angular-flex-layout-seed-arilh5

**Comment by CaerusKaru** [comment]
The link you have still has references to `class.xs`. Can you find and replace all instances? We'd be happy to switch it over to the new syntax.

**Comment by CaerusKaru** [comment]
I've updated the Wiki. Thanks for your help!
