### ISSUE TITLE
safari 9, trim() on null error

### ISSUE THREAD

**Issue by JirkaBures** [angular/flex-layout#1014]
# Bug Report

#### What is the current behavior?
on Safari 9 (ipad), there is sometimes error in console trying to call trim() on null
style-utils.ts -> lookupStyle() { return value.trim(); }

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/flex-layout": "~7.0.0-beta.23",
"@angular/core": "~7.2.2",

**Comment by CaerusKaru** [comment]
You'll need to include polyfills for that functionality to use with Safari 9. For the record, we only support back two versions of Safari, which at this point is Safari 10.

**Comment by Matrosskin** [comment]
@CaerusKaru which exactly polyfill do you mean?
