### ISSUE TITLE
fxHide.print not working when using window.print

### ISSUE THREAD

**Issue by tanekim77** [angular/flex-layout#1015]
# Bug Report

#### What is the expected behavior?
window.print displays same as ctrl + p on chrome

#### What is the current behavior?
window.print method ignores fxHide.print 

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction we can investigate.

**Comment by CaerusKaru** [comment]
Haven't received a repro in almost a month, so closing. We can reopen if a demo is provided.
