### ISSUE TITLE
fxLayoutAlign center does not play nice with scrollbar

### ISSUE THREAD

**Issue by MicMicMon** [angular/flex-layout#1018]
# Bug Report

I have a div that spans all the page, with css `height: 100vh ; width: 100vw`, and a card displayed in the center.

I use a `fxLayout="row" fxLayoutAlign="center center"` on the `div`.

It works well when everything fits on screen.

But when the card expands outside the screen, the vertical scrollbar does not allow to see the entire card, even on its extreme values.

Changing to `fxLayoutAlign="start start"` solves the issue (but UI is different of course, so not a solution).

#### What is the expected behavior?

Card should be centered on screen, and scrollbars should scroll to card extremes

#### What is the current behavior?

Scrollbar does not allow to see the full card when it does not fit on screen.

[Correct behavior when size is available](https://user-images.githubusercontent.com/37897072/52329929-4d784f00-29f4-11e9-951d-beffce38866f.png)

[Bug appears: note the scrollbar is at maximum-top position and we can't see the top part of the card (logo)](https://user-images.githubusercontent.com/37897072/52329963-64b73c80-29f4-11e9-8f25-f3674837d618.png)

[With 'start start', scrollbar works ok (note the scrollbar top position and we can see the logo)](https://user-images.githubusercontent.com/37897072/52329984-78fb3980-29f4-11e9-8558-1a6456d1e24a.png)

#### What are the steps to reproduce?

*  [StackBlitz to reproduce](https://stackblitz.com/edit/angular-flex-layout-seed-nnon2y) using latest `npm` nightly release. Change to `start start` to see the scrolling work ok (you can always see 'test' whereas you can't if you resize browser size to tiny height).

**Comment by charsleysa** [comment]
Hi @MicMicMon 

This is a limitation / quirk of how Flexbox works.

Essentially it's not scrolling because Flexbox ensures it truly stays in the center of the container even if it's bigger than the container.

For more information consult this [StackOverflow answer](https://stackoverflow.com/a/33455342/5996202).

**Comment by CaerusKaru** [comment]
@charsleysa is correct. This is not an issue with Flex Layout, so I’m closing this issue.

**Comment by MicMicMon** [comment]
Ok thanks, putting `margin: auto` on the `div` inside the container works well.

Could be specified as a side note in the flex-layout doc?

I see on the [SO post](https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container/33455342#33455342) that flexbox has a `safe center` option, maybe it could be added to the flex-layout API if it makes sense? Don't know, just throwing the idea.
