### ISSUE TITLE
vertical fxLayoutAlign doesn't work

### ISSUE THREAD

**Issue by jbg77** [angular/flex-layout#102]
Hello 

I use the latest version of material and flex-layout, and I can't center on vertical axis, but on horizontal axis its working.
thank in advance
```html
 <div style='height: 100vh;'>
     <div>
       <div fxLayout="row" fxLayoutAlign="space-around center" >
        <div>one</div>
        <div>two</div>
        <div>three</div>
    </div>
     </div>
</div>
```

**Comment by ThomasBurleson** [comment]
Issues are considered invalid without a working Plunkr or CodePen demo. 

---- 

Also here are some important guidelines for investigating a Layout issue:

* The Layout API is case-sensitive
  *  `fxlayout` is not valid
  *  `fxLayout` is valid
*  If you cannot get Flex-Layout to work with an example, try to manually use CSS flexbox stylings. If that still does not work to achieve your goals, then Flex-Layout is <u>**not**</u> the issue.
*  If hand-crafted CSS resolves the issue, but Flex-Layout does not then we **definitely** have a bug in this repository.

---- 

#### Templates 

* [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=info)
* [Plunkr Template with Material2](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview)

**Comment by jbg77** [comment]
Sorry: https://embed.plnkr.co/18qrjZ87EuqE5diKNrI5/
Same problem, look at app/test-app.ts

**Comment by d3viant0ne** [comment]
@jbg77 - Switch `100vh` for `100%` on the height and it centers vertically just fine.

**Comment by jbg77** [comment]
@d3viant0ne Have you a demo ? Because that doesn't work and I lost the height of my div.

**Comment by d3viant0ne** [comment]
I edited your plunkr.

![screen shot 2017-01-09 at 8 38 35 am](https://cloud.githubusercontent.com/assets/8420490/21770006/0ecbdf7c-d647-11e6-9517-b65b57e626ab.png)

**Comment by jbg77** [comment]
@d3viant0ne That doesn't work 'one, two, three' are one the top of their div.
