### ISSUE TITLE
@angular/flex-layout/flex-layout"' has no exported member 'MediaObserver'. Did you mean 'MediaService'

### ISSUE THREAD

**Issue by Tashaa78** [angular/flex-layout#1021]
# Bug Report
I just upgraded my project to "@angular/flex-layout": "7.0.0-beta.19", and it's broken. Am getting an error:
".../node_modules/@angular/flex-layout/flex-layout"' has no exported member 'MediaObserver'. Did you mean 'MediaService'?

Am using : media$: Observable<MediaChange> API

#### What are the steps to reproduce?
Below is a reproduced error

*  [StackBlitz starter](https://stackblitz.com/edit/angular-flex-layout-seed-twwc9w) using latest `npm` 7.0.0-beta.19 :

**Comment by CaerusKaru** [comment]
We don't have LTS for past beta versions. The demo works fine with 7.0.0-beta.23.

**Comment by AnassL** [comment]
@CaerusKaru 
It doesn't work for me neither with 7.0.0-beta.19 nor with 7.0.0-beta.23.
Has anyone solved it ?
