### ISSUE TITLE
Ctrl + 12 Device mode wrong mobile size on chrome

### ISSUE THREAD

**Issue by diegomaceira** [angular/flex-layout#1023]
# Bug Report

#### What is the expected behavior?
The expected behavior is the correct size depending of the diffents devices.

#### What is the current behavior?
When i use run my application and press Ctrl + F12 and press on the device button, i choose for example  mobile and the screen always recognized like medium size but the actual size is less than 600 px.
This behavior is works ok on mozilla firefox. And in chrome if i dont select the device button and change the size of the screen using the mouse the problem doesnt appear.
I tried to install the differents version of flex layout for angular 7, from the 7.0.0-beta.19 to 7.0.0-beta.23
but its the same for all.
I have the last version of google chrome.

![captura](https://user-images.githubusercontent.com/22207809/53017454-c2a14680-342e-11e9-8294-e38a2081a439.PNG)
![captura2](https://user-images.githubusercontent.com/22207809/53017455-c2a14680-342e-11e9-8c2d-7e89e205201c.PNG)
![captura3](https://user-images.githubusercontent.com/22207809/53017458-c339dd00-342e-11e9-9f35-821dcf8a03d8.png)

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Im using angular 7 and flex layout 7.0.0-beta.22.

**Comment by diegomaceira** [comment]
Sorry i solved the issue. the tag <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, target-densitydpi=device-dpi" />
was missed.

**Comment by jcemelanda** [comment]
You know, you should at least say which tag was missing so if anyone comes to the issue trying to solve their own problem they can know if it's the same issue or not.
