### ISSUE TITLE
ERROR in Couldn't resolve original symbol for ./base/base2 from node_modules/@angular/flex-layout/core/typings/index.d.ts

### ISSUE THREAD

**Issue by anjali3122** [angular/flex-layout#1024]
# Bug Report

#### What is the expected behavior?
should be working smoothly

#### What is the current behavior?
ERROR in Couldn't resolve the original symbol for ./base/base2 from /node_modules/@angular/flex-layout/core/typings/index.d.ts
I am getting this error in trying to use an Angular 7 based theme components in my already existing Angular 6 app. The version of @angular/flex-layout used in theme was 7.0.0-beta.23 but it was causing issue with rxjs and angular version of my app so I went through suggestions and downgraded it. But it's still not working.
I also cannot upgrade rxjs as it's breaking state management functionalities in my app.
I need help with what version should be used to make them compatible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/core": "6.1.10",
    "@angular/material": "6.4.7",
    "@angular/flex-layout": "6.0.0-beta.18",
    "rxjs": "6.3.2",
    "typescript": "2.9.2"

    OS: Windows 10
    Browser: Chrome

**Comment by CaerusKaru** [comment]
We cannot support older versions than the latest release. Closing this as a compatibility issue with other libs and versions.
