### ISSUE TITLE
MediaObserver.isActive not working before subscribe MediaObserver.media$

### ISSUE THREAD

**Issue by keatkeat87** [angular/flex-layout#1025]
# Bug Report
```
ngOnInit() {
  let active = this.mediaObserver.isActive('xs');
  console.log(active); // always false

  this.mediaObserver.media$.subscribe((v) => {
    if (v.mqAlias === 'xs') {
      active = this.mediaObserver.isActive('xs');
      console.log(active);  // true
    }
  });
}
```

#### What is the expected behavior?
this.mediaObserver.isActive('xs') should get true

#### What is the current behavior?
this.mediaObserver.isActive('xs') always return false

#### What are the steps to reproduce?

F12 see the console
https://stackblitz.com/github/keatkeat87/angular-flex-is-active-issue
https://github.com/keatkeat87/angular-flex-is-active-issue

#### What is the use-case or motivation for changing an existing behavior?
this is a bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.x, 
flex-layout 7.0.0-beta.23

#### Is there anything else we should know?
i think this is because of the rxjs behavior.
if no subscribe, 
observe pipe won't run -> registerQuery no call -> _registry no set -> isActive always return false
```
isActive(mediaQuery: string): boolean {
  const mql = this._registry.get(mediaQuery);  // _registry must be set before calling isActive
  return !!mql ? mql.matches : false;
}
```

workaround : 
 `const isActive = await this.mediaObserver.media$.pipe(take(1), map(media => media.mqAlias === 'xs')).toPromise();`

**Comment by CaerusKaru** [comment]
I'm going to leave this up to @ThomasBurleson to investigate and drive towards a resolution.

**Comment by JayEnaR** [comment]
I have the same issue. In core.js, the `registry` has no entries to compare with my query, thus always returning false.

![image](https://user-images.githubusercontent.com/25684062/61358180-0f703880-a87a-11e9-9b40-ece583b672ab.png)

"@angular/core": "~8.1.1",
"@angular/flex-layout": "^8.0.0-beta.26",
"@angular/cdk": "^8.1.1",
"typescript": "~3.4.3"

**Comment by gedclack** [comment]
Hi, is this bug solved yet ?
I stumbled upon this when I want to use `isActive()` in angular material sidenav to make it responsive

**Comment by intellix** [comment]
This one is killing us. `media.asObservable()` is async so we get issues with mat-sidenav animating open -> closed when on mobile because first the observable is NULL and then it's TRUE.

One way to mitigate this was to add `startsWith(media.isActive('lt-sm'))` and surprisingly it emits the wrong value :/

BreakpointObserver is sync but doesn't have an SSR shim so the page will initially deliver the menu open when on mobile.

**Comment by intellix** [comment]
The hack above isn't working anymore in ivy 9 due to some error about:
```
ERROR in Tried to overwrite /Users/dominic/myproject/node_modules/@angular/flex-layout/core/typings/module.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```

**@angular+flex-layout+9.0.0-beta.29.patch**
```
diff --git a/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js b/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js
index fbce2f8..516495d 100644
--- a/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js
+++ b/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js
@@ -1349,6 +1349,8 @@ var MatchMedia = /** @class */ (function () {
         var _this = this;
         if (filterOthers === void 0) { filterOthers = false; }
         if (mqList && mqList.length) {
+            _this.registerQuery(mqList);
+
             /** @type {?} */
             var matchMedia$ = this._observable$.pipe(operators.filter((/**
              * @param {?} change
diff --git a/node_modules/@angular/flex-layout/bundles/flex-layout.umd.js b/node_modules/@angular/flex-layout/bundles/flex-layout.umd.js
index 939f0a3..9efdb98 100644
--- a/node_modules/@angular/flex-layout/bundles/flex-layout.umd.js
+++ b/node_modules/@angular/flex-layout/bundles/flex-layout.umd.js
@@ -1349,6 +1349,7 @@ var MatchMedia = /** @class */ (function () {
         var _this = this;
         if (filterOthers === void 0) { filterOthers = false; }
         if (mqList && mqList.length) {
+            _this.registerQuery(mqList);
             /** @type {?} */
             var matchMedia$ = this._observable$.pipe(operators.filter((/**
              * @param {?} change
diff --git a/node_modules/@angular/flex-layout/esm2015/core.js b/node_modules/@angular/flex-layout/esm2015/core.js
index 8981efd..c3ccf25 100644
--- a/node_modules/@angular/flex-layout/esm2015/core.js
+++ b/node_modules/@angular/flex-layout/esm2015/core.js
@@ -1082,6 +1082,7 @@ class MatchMedia {
      */
     observe(mqList, filterOthers = false) {
         if (mqList && mqList.length) {
+            _this.registerQuery(mqList);
             /** @type {?} */
             const matchMedia$ = this._observable$.pipe(filter((/**
              * @param {?} change
diff --git a/node_modules/@angular/flex-layout/esm5/core.es5.js b/node_modules/@angular/flex-layout/esm5/core.es5.js
index 97db726..c794689 100644
--- a/node_modules/@angular/flex-layout/esm5/core.es5.js
+++ b/node_modules/@angular/flex-layout/esm5/core.es5.js
@@ -1301,6 +1301,7 @@ var MatchMedia = /** @class */ (function () {
         var _this = this;
         if (filterOthers === void 0) { filterOthers = false; }
         if (mqList && mqList.length) {
+            _this.registerQuery(mqList);
             /** @type {?} */
             var matchMedia$ = this._observable$.pipe(filter((/**
              * @param {?} change
```

**Comment by danmana** [comment]
Alternatively, you can use an app initializer in `app.module.ts` to make sure the first media event is processed before your app loads. 
This way the `isActive` check will work directly in your component's constructor
```js
providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (media: MediaObserver) => {
        return () => {
          return media.asObservable()
            .pipe(first())
            .toPromise();
        }
      },
      multi: true,
      deps: [MediaObserver]
    }

  ]
```
