### ISSUE TITLE
Feature: Batching of media query events by MatchMedia 

### ISSUE THREAD

**Issue by simeyla** [angular/flex-layout#1027]
# Feature Request

#### What is the desired behavior?
When using `mm.observe` you should get batches of media queries and redundant changes should be removed (affects iOS screen rotation from landscape to portrait).

### What is the use-case or motivation for the desired behavior?

I noticed than when rotating my iPhone from landscape to portrait it would report my `tablet` breakpoint as being triggered and then *immediately* un-triggered. This could cause a flicker in updating of the UI that was beyond a normal rotation.

    (min-width: 768px) and (max-width: 1279px)    

Now the interesting things is that this is actually due to the iPhone X 'notch'. Here's what happens:

* Phone starts in landscape mode (Safari)
* The *normal* safari screen width does **not** trigger my `tablet` breakpoint (it is <768px wide)
* When I rotate the screen it seems that Safari forgets about the notch for calculations which triggers `tablet` breakpoint
* I'm now in portrait mode
* Safari sees that `tablet` breakpoint doesn't apply
* It sends me another media query change telling me `tablet = false`

So if I am responding to these events to affect my layout then a whole bunch of unnecessary calculations are taking place - and if I rotated my phone by mistake then they have to happen all over again.

In addition, I'm using `MediaMatch` directly to create custom observables which triggers all kinds of custom layout behavior, and i want them to be as fast as possible and updated in groups. So as a bonus the solution to the iOS flickering also solves that concern.

#### Suggestion
This is how I solved it:

        // custom operator
        export const bufferDebounce = (dueTime: number) => <T>(source: Observable<T>) => source.pipe(buffer(source.pipe(debounceTime(dueTime))));

        // buffer MediaChange events, remove duplicates and emit an array
        observeBatch$ = mm.observe().pipe(bufferDebounce(0), map(batchedChanges => {

            let mqMap: { [ mediaQuery: string ]: MediaChange } = {};

            batchedChanges.forEach(mc => {
                mqMap[mc.mediaQuery] = mc;
            });

            return Object.keys(mqMap).map(k => mqMap[k]);

        }));

Then `observeBatch$` is just `Observable<MediaChange[]>`.

I think this would be a very useful addition to `MediaMatch` to give me batches of changes. If I run something after a change then I can save myself half a dozen iterations of that.

Even with a debounce time of 0ms it still removes some of the duplicates media queries, but perhaps this value could be a parameter that defaults to 0.

**Comment by CaerusKaru** [comment]
This is now essentially the behavior of `MediaObserver::asObservable()`. Very cool that we were able to get here eventually 😄 .
