### ISSUE TITLE
Felx gap is not working correctly with fxShow fxHide

### ISSUE THREAD

**Issue by minchopm** [angular/flex-layout#1028]
# Bug Report

I am switching 2 buttons in a toolbar with fxShow and there si a gap set to 8px.
The normal rendered element has a margin but the hidden is not calculated. And when I switch the state the hidden still has no margin. This is an old problem but it happens again.

You can see the difference:

![image](https://user-images.githubusercontent.com/5762871/53394786-f3422c80-39a8-11e9-9efc-fa6dd5b2e005.png)

![image](https://user-images.githubusercontent.com/5762871/53394747-db6aa880-39a8-11e9-9c9f-69f8adfb5e50.png)

![image](https://user-images.githubusercontent.com/5762871/53394851-21c00780-39a9-11e9-96fe-67ae557e0131.png)

If you resize the browser the calculation has been triggered.

version: "7.0.0-beta.23"

**Comment by CaerusKaru** [comment]
Can you provide a StackBlitz demo we can investigate further?

**Comment by CaerusKaru** [comment]
It's been two weeks since I asked for a demo and none was provided. If you provide a demo, we can reopen this.
