### ISSUE TITLE
Changing fxFlex value in the Component with "setAttribute('fxFlex', '25%')" not Working in Angular 6

### ISSUE THREAD

**Issue by YoussefELHAYANI** [angular/flex-layout#1030]
# Bug Report
I'm trying to change the value of fxFlex from my Angular Component 
code in the component.ts:
` const nav = document.getElementById('nav2')
        nav.setAttribute('fxFlex', '5%')`
code in the html:
` <div id="nav2" fxFlex="25%" class="col-md-2.5 bg-white p-1"></div>`

#### What is the expected behavior?
the code should normally should change the size Layout to 5% .

####What is the current behavior?

but it's not the case, when i inspect the page I found that the attribute has been change but the layout still the same, **oddly when i change it manually in the html code to 5%, i get the result that i wanted.**  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular 6, and Typescript 3.1.1

Please, If there is any suggestion, do not hesitate.

Thank You !

**Comment by CaerusKaru** [comment]
Can you reproduce this with Angular v7 and latest Flex Layout? We don't support anything except the latest version, so we won't be supporting the Angular v6 use-case.

**Comment by YoussefELHAYANI** [comment]
Problem solved !

I used  `[fxFlex]="condensed ? '5%" : '25%'"` in the html code (condensed is boolean variable declared in the component ) instead of `const nav = document.getElementById('nav2') nav.setAttribute('fxFlex', '5%')` in the component.

**Comment by YoussefELHAYANI** [comment]
Problem solved !

I used` [fxFlex]="condensed ? '5%" : '25%'"` in the html code (condensed is boolean variable declared in the component ) instead of` const nav = document.getElementById('nav2') nav.setAttribute('fxFlex', '5%') `in the component.
