### ISSUE TITLE
Update a typo error in StyleBuilder wiki

### ISSUE THREAD

**Issue by PirunSeng** [angular/flex-layout#1032]
# Fix typo error in the import block

Hi There! First, sorry If I'm at the wrong place to ask for an update to a wiki.
I've found a typo error at the usage section [here](https://github.com/angular/flex-layout/wiki/Style-Builders#usage):
```
import {
  StyleBuilder, 
  StyleDefinition
  FlexAlignStyleBuilder, 
} from '@angular/flex-layout';
```
It should be
```
import {
  StyleBuilder, 
  StyleDefinition,
  FlexAlignStyleBuilder, 
} from '@angular/flex-layout';
```

**Comment by CaerusKaru** [comment]
Excellent catch, should be fixed now!
