### ISSUE TITLE
Update WIKI for inline-flex

### ISSUE THREAD

**Issue by jinbeomhong** [angular/flex-layout#1033]
# Bug Report

#### What is the current behavior?

There is no documentation for `inline-flex` added by https://github.com/angular/flex-layout/pull/539

#### Is there anything else we should know?

WIKI for this : https://github.com/angular/flex-layout/wiki/fxLayout-API#fxlayout-options

**Comment by CaerusKaru** [comment]
Added to the Wiki [here](https://github.com/angular/flex-layout/wiki/fxLayout-API#fxlayout--inline). Thanks!
