### ISSUE TITLE
_mq.scss using incorrect overlapping keys

### ISSUE THREAD

**Issue by maddockst** [angular/flex-layout#1034]
**Overview of the Issue**

_mq.scss is using the wrong keys for `$overlapping-gt` and `$overlapping-lt` and as such, I cannot target SCSS below a breakpoint. I can see that `src/lib/core/sass/_layout-bp.scss` uses the correct keys but I'm unsure as to how this file relates to `_mq.scss`.

**Angular and Flex Layout Versions -**

angular: 7.2.0
flex-layout: 7.0.0-beta.23

![flex-issue](https://user-images.githubusercontent.com/14302328/54435584-b99f4e80-4728-11e9-91a0-34ac8e2b6d54.png)

**Comment by CaerusKaru** [comment]
`_layout-bp.scss` is a 1:1 copy to `_mq.scss` at build time when we publish the library. Since this has been patched in master, it will be included in the next release.
