### ISSUE TITLE
Knowledge and Sharing

### ISSUE THREAD

**Issue by ShadowManu** [angular/flex-layout#104]
Hello folks. I open this issue as I just noticed you guys took a little focus on flexbox, from features I loved on Angular Material 1.

I started out from my own a Layout System implementation of their Layout System in CSS only in [ShadowManu/flexlay](https://github.com/ShadowManu/flexlay). Initially heavily based on their code. It does (I believe), many same features you're providing:

* Provides a Layout System similar to Angular Material 1
* Is independent of Angular Material (1 or 2)
* Uses HTML attributes (through [attribute selectors](https://developer.mozilla.org/en/docs/Web/CSS/Attribute_selectors))

but with a (core) difference: **does not depend on any JS**

There's of course, some differences like I don't work with px units (unfeasible with CSS-only whithout [custom `attr` wide support](https://developer.mozilla.org/en/docs/Web/CSS/attr)). I also removed things I felt too opinionated, like margin and padding, since people, have their own spacing requirements (like my team did). And still on development, so there's probably bugs, but it works a lot for us.

Anyhow, I wanted to share my project, what you guys think, if it could help you somehow (for inspiration at least) and say a hello ;)

**Comment by ThomasBurleson** [comment]
Thank you for sharing. Please repost this to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.
