### ISSUE TITLE
MediaObserver.asObservable() emits two events on each change

### ISSUE THREAD

**Issue by BobBDE** [angular/flex-layout#1041]
# Bug Report

#### What is the expected behavior?
The observable that emit an event each time the screen media change should emit only one event on the change.

#### What is the current behavior?
The MediaObserver.asObservable() emits 2 event each time the media changes.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
https://stackblitz.com/edit/angular-flex-layout-seed-uhwdfm?file=app%2Fapp.component.ts

Simple exemple here, check the console.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on version 7.0.0-beta.24

#### Is there anything else we should know?
There is also the problem with the deprecated media$ observable.

**Comment by Necroskillz** [comment]
also why does it fire immediately when subscribed to? shouldn't it only fire after you subscribe AND the media changes?

**Comment by mordka** [comment]
Still valid issue in `8.0.0-beta.27` 
As a workaround I'm filtering distinct values:
```
    const getAlias = (mediaChange) => {
      const indexFirstPriorityMedia = 0;
      return mediaChange[indexFirstPriorityMedia].mqAlias
    };
    this.mediaSub = this.observableMedia.asObservable()
      .pipe(
        distinctUntilChanged((p,c) => getAlias(p) === getAlias(c))
      )
      .subscribe(change => { /*....*/})
```

**Comment by intellix** [comment]
This doesn't just fire twice, it fires about 10x. We've created a service which wraps it and applies a distinctUntilChanged() to prevent people using the official and unperformant version
