### ISSUE TITLE
ngClass.xs not work propertly

### ISSUE THREAD

**Issue by avechuche** [angular/flex-layout#1042]
# Bug Report

I really do not know if it's a bug or works like that

#### What are the steps to reproduce?
I'm using `<mat-table ngClass.xs="my-class">`, it works perfectly when I get XS size. The problem is when I go out of XS size, the class "my-class" is not deleted. To solve this problem, I had to add a fake class (class = "fake-class"), is it possible to correct that problem without having to add a fake class without content? Thx

.scss
```
mat-table.my-class
{
     ...
}

```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.6
Node: 8.12.0
OS: win32 x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.5
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by CaerusKaru** [comment]
Please upgrade to version 7.0.0-beta.24
