### ISSUE TITLE
"fxShow fxHide.lt-lg" vs "fxHide fxShow.gt-md" 

### ISSUE THREAD

**Issue by NashIlli** [angular/flex-layout#1044]
# Bug Report

#### What is the expected behavior?
I think that this two uses have to produce the same result

- fxShow fxHide.lt-lg
- fxHide fxShow.gt-md

#### What is the current behavior?
I was using the first case and in some devices, not in all, the component wasn't show. And with the second combination, all works properly.

#### What are the steps to reproduce?

Try in Chrome (latest, version 73.0.3683.86), where I had the issue. In firefox, in the same devices, all works well.

https://angular-flex-layout-seed-vwutpz.stackblitz.io

I think that can be a problem with "lt-lg" alias. I recently did a test and in the device of the error I had the following results

- this.mediaObserver.isActive('gt-md') = false
- this.mediaObserver.isActive('lt-lg') = false

Thanks!

**Comment by CaerusKaru** [comment]
I'm unclear on what I'm supposed to see in the demo. All looks right to me.

**Comment by NashIlli** [comment]
*I have recently updated the demo.*

Yes, all looks righ to me alse in my notebook. But in some notebooks the second case (with fxShow.lt-lg) dont is showed.

**Comment by CaerusKaru** [comment]
Unless there is a deterministic way to present this problem, I'm closing this ticket. We can reopen if that changes.

**Comment by kaleb** [comment]
I have a TV that is 1280p and when the browser is 1280 pixels wide, both my fxHide.lt-lg and fxHide.gt-md are both not visible.
