### ISSUE TITLE
src/app/app.module.ts(48,34): error TS2306:  types/@angular/flex-layout.d.ts' is not a module.

### ISSUE THREAD

**Issue by dysonjm** [angular/flex-layout#1055]
I am getting the below error in my project 

src/app/app.module.ts(48,34): error TS2306: File 'E:/Project50/project50/types/@angular/flex-layout.d.ts' is not a module.

I have done some research and done some changes but nothing helped .

Versions .

"typescript": "^3.1.6"
"@angular/flex-layout": "^7.0.0-beta.24",

**Comment by CaerusKaru** [comment]
Your issue does not follow the issue template. It also doesn't seem like a bug with Flex Layout, likely it's an issue with your own configuration. Please utilize StackOverflow or Gitter for these types of support cases.
