### ISSUE TITLE
Parent row and child Column Layout Breaks in IE11 but works in other browsers

### ISSUE THREAD

**Issue by kundan52** [angular/flex-layout#1060]
If I use **fxLayout="row"** in parent div and **fxLayout="column"** in child div
its  should not be collapsed in E 11
------------------

When I use **fxLayout="row"** in parent div and **fxLayout="column"** in child div
its getting collapsed in or overlapped in IE 11, but works in other browsers

kindly refer the stackbliz link for the issue
https://stackblitz.com/edit/angular-wcmerb

```
<div fxLayout="row" fxLayoutAlign="none" fxFlex="1 1 auto">
          <div class="offer-text" fxLayout="column">
            <div class="m-b-15 text-14">
             Lorem Ipsum is simply dummy text of the printing and typesetting industry.  when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </div>
            <div  class="martop-20" fxLayout="row" fxLayoutAlign="end end" fxFlex="1 1 auto">
             Condition Apply
            </div>
          </div>

        </div>
```

    Flex layout version used flex-layout: "1.0.1"

**Comment by CaerusKaru** [comment]
This is just a shot in the dark, but maybe it’s because you haven’t installed Angular Flex Layout (`@angular/flex-layout`)?

**Comment by kundan52** [comment]
@CaerusKaru If I have not installed flexy layout then how its working in chrome and other browsers not in IE
