### ISSUE TITLE
Angular 8.0.0-rc.5 breaking change : Static Query

### ISSUE THREAD

**Issue by bogacg** [angular/flex-layout#1067]
# Bug Report

#### What is the expected behavior?
App with **flex-layout** serves/builds.

#### What is the current behavior?
Errors similar to this one pop up upon serve/build:
```
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 162:51-68
"export 'ΔdefineInjectable' was not found in '@angular/core'
```

See the related [Changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) entry, and more info about [Static Query Migration](https://next.angular.io/guide/static-query-migration).

#### What are the steps to reproduce?
Update an existing app with `8.0.0-rc.5` for Angular & `8.0.0-beta.25` for Flex-Layout to see errors yourself.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
    "@angular/core": "~8.0.0-rc.5",
    "@angular/flex-layout": "~8.0.0-beta.25",
```

**Update :** Though I thought error is related to static query change made in Angular, when I search Flex Layout source I can't find a reference to ViewChild or ContentChild. So my assumption about source of error may not be correct.

**Comment by bogacg** [comment]
Here is the full list of dependencies I've tested with in a clean project:
```
  "dependencies": {
    "@angular/animations": "~8.0.0-rc.5",
    "@angular/cdk": "~8.0.0-rc.1",
    "@angular/common": "~8.0.0-rc.5",
    "@angular/compiler": "~8.0.0-rc.5",
    "@angular/core": "~8.0.0-rc.5",
    "@angular/flex-layout": "^8.0.0-beta.25",
    "@angular/forms": "~8.0.0-rc.5",
    "@angular/material": "8.0.0-rc.1",
    "@angular/platform-browser": "~8.0.0-rc.5",
    "@angular/platform-browser-dynamic": "~8.0.0-rc.5",
    "@angular/pwa": "^0.13.9",
    "@angular/router": "~8.0.0-rc.5",
    "@angular/service-worker": "~8.0.0-rc.5",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0-rc.4",
    "@angular/cli": "~8.0.0-rc.4",
    "@angular/compiler-cli": "~8.0.0-rc.5",
    "@angular/language-service": "~8.0.0-rc.5",
    "@types/node": "~12.0.2",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "typescript": "~3.4.5"
  }
```

**Comment by Splaktar** [comment]
This is broken for me too. You can reproduce it on this branch: https://github.com/angular-hispano/angular-hispano/tree/angular-8-rc.5. The app won't compile in dev or prod.

**Comment by CaerusKaru** [comment]
The root cause of this is that a very specific syntax change internally was made in Angular v8.0.0-rc.5. Thus, any library built with v8.0.0-rc.4 will not work with RC 5. In our case, that means we need to wait for the next release of Angular Material before we bump our own version, likely later today or tomorrow.

**Comment by Splaktar** [comment]
The Angular change related to this in `rc.5` is here: https://github.com/angular/angular/commit/fdbe07982aeccb4d8ef04fc4486cdf8d8979225d

Material has updated to Angular `rc.5` (https://github.com/angular/components/commit/5c9c79d83891336239f73ba5d718c062acb7f736) and is planning a new RC soon.

**Comment by CaerusKaru** [comment]
Flex Layout v8.0.0-beta.26 has been published to NPM and should resolve this issue.

**Comment by Enngage** [comment]
Awesome, thanks for the quick fix! Can confirm it is working fine now.
