### ISSUE TITLE
Type error with ng8 and Ivy enabled

### ISSUE THREAD

**Issue by princemaple** [angular/flex-layout#1072]
# Bug Report

#### What is the expected behavior?
normal usage (directive only) of the library should compile fine

#### What is the current behavior?
```
ERROR in src/__ng_typecheck__.ts(41,62): error TS2344: Type '"fxLayout" | "fxLayout.xs" | "fxLayout.sm" | "fxLayout.md" | "fxLayout.lg" | "fxLayout.xl" |
"fxLayout.lt-sm" | "fxLayout.lt-md" | "fxLayout.lt-lg" | "fxLayout.lt-xl" | "fxLayout.gt-xs" | "fxLayout.gt-sm" | "fxLayout.gt-md" | "fxLayout.gt-lg"' doe
s not satisfy the constraint '"ngOnDestroy" | "activatedValue" | "ngOnChanges"'.
  Type '"fxLayout"' is not assignable to type '"ngOnDestroy" | "activatedValue" | "ngOnChanges"'.
src/__ng_typecheck__.ts(42,67): error TS2344: Type '"fxLayoutAlign" | "fxLayoutAlign.xs" | "fxLayoutAlign.sm" | "fxLayoutAlign.md" | "fxLayoutAlign.lg" |
"fxLayoutAlign.xl" | "fxLayoutAlign.lt-sm" | "fxLayoutAlign.lt-md" | ... 5 more ... | "fxLayoutAlign.gt-lg"' does not satisfy the constraint '"ngOnDestroy
" | "activatedValue" | "ngOnChanges"'.
  Type '"fxLayoutAlign"' is not assignable to type '"ngOnDestroy" | "activatedValue" | "ngOnChanges"'.
src/__ng_typecheck__.ts(56,66): error TS2344: Type '"fxLayoutGap" | "fxLayoutGap.xs" | "fxLayoutGap.sm" | "fxLayoutGap.md" | "fxLayoutGap.lg" | "fxLayoutG
ap.xl" | "fxLayoutGap.lt-sm" | "fxLayoutGap.lt-md" | "fxLayoutGap.lt-lg" | ... 4 more ... | "fxLayoutGap.gt-lg"' does not satisfy the constraint '"ngOnDes
troy" | "activatedValue" | "ngOnChanges" | "ngAfterContentInit"'.
  Type '"fxLayoutGap"' is not assignable to type '"ngOnDestroy" | "activatedValue" | "ngOnChanges" | "ngAfterContentInit"'.
src/__ng_typecheck__.ts(91,11): error TS2341: Property 'activated' is private and only accessible within class 'RouterOutlet'.
```

#### What are the steps to reproduce?
probably just compile any project that uses flex-layout, with ng8 + ivy

#### What is the use-case or motivation for changing an existing behavior?
wanted to try ivy

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng8
mat8
ts3.4
very standard ng8 versions, only just released

#### Is there anything else we should know?
N/A

**Comment by CaerusKaru** [comment]
Any issue with compiling with Ivy is strictly an Ivy issue, as it’s meant to be backwards.compatible with ViewEngine.

**Comment by WLun001** [comment]
I have the same issue here

**Comment by princemaple** [comment]
@CaerusKaru I thought it's because ivy has better type checking and revealing a type error in flex-layout. Well.

**Comment by greglarson** [comment]
It appears that the ivy compiler is creating invalid properties. For instance fxLayout.xs: "fxLayout.xs" is created rather than "fxLayout.xs": "fxLayout.xs". (error on .xs in the former).
Can you work with the angular team to get this fixed?

Thanks.
