### ISSUE TITLE
@angular/flex-layout version mismatch issue

### ISSUE THREAD

**Issue by mearleycf** [angular/flex-layout#1078]
# Bug Report

#### What is the expected behavior?
When I run `npm -v @angular/flex-layout` it returns `6.4.1`, but my package.json entry is:
`"@angular/flex-layout": "^8.0.0-beta.26"`
And I've run `npm i` after installing flex-layout and cdk. 

#### What is the current behavior?
See above. The issue is that my code isn't working. Here is an example of the rendered component's html:
`<div _ngcontent-wka-c1="" fxflexfill="" fxlayout="row" fxlayoutalign="start center" fxlayoutgap="20px grid"><div _ngcontent-wka-c1="">...content divs...</div></div>`

You can see it isn't adding the inline styling.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
I'm running angular 8/cli 8/material 8/etc. and should have the latest flex-layout, but I'm not sure b/c of the version mismatch. It's just all standard installation of angular stuff. 

#### What is the use-case or motivation for changing an existing behavior?
?? I want the tool to perform it's function? 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
It's all v8. I'm on Firefox 67.0b18 (64-bit) MacOS v10.14.4. 

#### Is there anything else we should know?
No

**Comment by CaerusKaru** [comment]
There is no Flex Layout v6.4.1. This sounds like an issue with NPM and not Flex Layout. If you can find a reproduction that shows the issue is with this library, we can reopen this issue.

**Comment by CaerusKaru** [comment]
By the by, `npm -v <anything else>` returns the version of NPM, not the library. To find library information, use `npm ls <library name>`

**Comment by mearleycf** [comment]
Cool. So, can you think of why the project might not be working? I've imported FlexLayoutModule into app.module.ts. 
```
import { FlexLayoutModule } from '@angular/flex-layout';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule,
    SharedModule,
    MaterialComponentsModule,
    ComponentsModule,
    FlexLayoutModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

This is the html:
```
<mat-toolbar color="primary">
    <div fxFlexFill="" fxLayout="row" fxLayoutAlign="start center" fxLayoutGap="20px grid">
        <div>How Did This LIST Get Made?</div>
        <div>Movies</div>
        <div>Episodes</div>
        <div>Actors</div>
        <div>Special Guests</div>
    </div>
</mat-toolbar>
```

**Comment by mearleycf** [comment]
> By the by, `npm -v <anything else>` returns the version of NPM, not the library. To find library information, use `npm ls <library name>`

Yeah I did npm list @angular/flex-layout and it's got the correct version. Thanks for the clarification. Doesn't explain why I'm having an issue ;)Sorry I was confused there.

**Comment by mearleycf** [comment]
NM I figured it out, I wasn't exporting it anywhere.
