### ISSUE TITLE
Document node 11 is required to build(for gulp 3.x)

### ISSUE THREAD

**Issue by epelc** [angular/flex-layout#1079]
Document that you must use node <12(ie 11.x) in order to build the project since gulp 3.X is being used(gulp 4 supports node 12).

The wiki mentions you must have > 8.x but no mention that > 12.x will no longer work. https://github.com/angular/flex-layout/wiki/Developer-Setup

I suggest using `nvm` since angular 8 projects now use node 12 so you have to switch between versions if you are working on this vs an angular 8 project using this.

**Comment by CaerusKaru** [comment]
I'd hate to limit people to using Node 11. @devversion is this something we can update, or is the long-term plan still "move to Bazel"?
