### ISSUE TITLE
ngClass constantly reapplies on every breakpoint when inside fxLayout/fxLayoutGap

### ISSUE THREAD

**Issue by ChristopherKiss** [angular/flex-layout#1083]
# Bug Report

#### What is the expected behavior?
ngClass, especially the base one that doesn't have any breakpoint modifiers should not toggle the class on/off.

#### What is the current behavior?
ngClass, without a breakpoint modifier is reapplying the classes on every breakpoint change.

#### What are the steps to reproduce?
Stackblitz to reproduce.
https://stackblitz.com/edit/angular-mfdecy
https://angular-mfdecy.stackblitz.io

Zip of video demonstrating the classes being constantly re-applied even though it's not possible to change on breakpoint since no modifier is used.
[2019-06-13_16-53-07.zip](https://github.com/angular/flex-layout/files/3284537/2019-06-13_16-53-07.zip)

#### What is the use-case or motivation for changing an existing behavior?
This is introducing performance issues when there are lots of ngClass directives inside a fxLayout/fxLayoutGap element.

A noticeable stutter as a result to fps drop can be seen when resizing between breakpoints.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Stackblitz is using Angular 8, locally we are using Angular 7.2.13
Flex Layout, stackblitz: beta.26, Locally: beta.24
Windows 10

#### Is there anything else we should know?
These screens are taken from our product (which has many more elements within an fxLayout/fxLayoutGap element) and not the stackblitz. We are also using OnPush change detection for all components.

These were captured in debug mode, but production mode results in the same result.

Performance chart focusing on one breakpoint toggle.
![image](https://user-images.githubusercontent.com/24984762/59410607-986bfe00-8dfc-11e9-9772-f851ab051aed.png)

Frames drop to 7fps
![image](https://user-images.githubusercontent.com/24984762/59410669-c3565200-8dfc-11e9-9af6-7cb373bf6613.png)

**Comment by CaerusKaru** [comment]
Can you provide instructions on how to reproduce the video?

**Comment by ChristopherKiss** [comment]
@CaerusKaru,

If you open the stackblitz that I linked https://angular-mfdecy.stackblitz.io/

Then make the browser height smaller and the width small. Open dev tools.

![image](https://user-images.githubusercontent.com/24984762/60636981-ed2ef180-9e5b-11e9-8dd8-c96b0e2f0b4f.png)

Like so.

![image](https://user-images.githubusercontent.com/24984762/60636947-dc7e7b80-9e5b-11e9-8a06-20dc7bb584ad.png)

You can now resize the browser window from left to right so that you go across the breakpoints. (particularly the breakpoint at 1280px) is easy to see. You'll see the is-full-width class get highlighted in purple (in chrome) as it's reapplying the styles.

Let me know if you need more information.

**Comment by ChristopherKiss** [comment]
@CaerusKaru,

Is there anything else I can provide to help you in reproducing this?
