### ISSUE TITLE
ERROR in Error during template compile of 'OpaqueToken'

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/flex-layout#1084]
Build is not working in angular 8

$ ng build --prod

Error :

ERROR in Error during template compile of 'OpaqueToken'
  Function calls are not supported in decorators but 'makeDecorator' was called in 'Injectable'
    'Injectable' calls 'makeDecorator'.

**Comment by CaerusKaru** [comment]
`OpaqueToken` was removed countless releases ago and is no longer used by Flex Layout.

**Comment by Gajendrasinh** [comment]
I have migrate angular 8. 

 "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/flex-layout": "^8.0.0-beta.25",
    "@angular/forms": "^8.0.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@ng-idle/core": "^7.0.0-beta.1",
    "@ng-idle/keepalive": "^7.0.0-beta.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/bootstrap": "3.3.33",
    "@types/crypto-js": "^3.1.43",
    "@types/file-saver": "^2.0.1",
    "@types/underscore": "^1.8.19",
    "angular-dual-listbox": "^5.0.1",
    "angular2-moment": "1.9.0",
    "angular2-multiselect-dropdown": "^4.2.3",
    "bootstrap": "^3.4.1",
    "core-js": "^3.1.3",
    "crypto-js": "^3.1.9-1",
    "enhanced-resolve": "^4.1.0",
    "file-saver": "^2.0.2",
    "flag-icon-css": "^3.3.0",
    "ng2-file-upload": "^1.3.0",
    "ng2-file-uploader": "^0.1.4",
    "ng2-translate": "^5.0.0",
    "ngx-bootstrap": "^4.3.0",
    "ngx-filesaver": "^2.2.1",
    "ngx-modialog": "^5.0.1",
    "ngx-mydatepicker": "^2.4.9",
    "ngx-webstorage": "^4.0.1",
    "primeng": "^8.0.0-rc.1",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "ts-helpers": "^1.1.2",
    "ts-metadata-helper": "^0.0.4",
    "tslib": "^1.9.0",
    "uglifyjs-webpack-plugin": "2.1.3",
    "underscore": "^1.9.1",
    "xlsx": "^0.14.3",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0",
    "@angular/cli": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/jasmine": "^3.3.13",
    "@types/jquery": "^3.3.29",
    "@types/node": "^12.0.8",
    "codelyzer": "^5.1.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "^8.2.0",
    "tslint": "^5.17.0",
    "typescript": "~3.4.5",
    "webpack": "^4.34.0"
  }

How can i identify where its used?

**Comment by CaerusKaru** [comment]
I’m not sure, you have a ton of third party libraries. All I can say for certain is that it’s not Flex Layout.

**Comment by Gajendrasinh** [comment]
I am not using flex layout in my application, you means i need to remove third party libraries ?
