### ISSUE TITLE
[fxLayoutGap]="null || undefined" crash

### ISSUE THREAD

**Issue by rovercoder** [angular/flex-layout#1090]
# Bug Report

#### What is the expected behavior?
Null or undefined fxLayoutGap value doesn't crash flex

`Uncaught TypeError: Cannot read property 'endsWith' of undefined at LayoutGapStyleBuilder.push../node_modules/@angular/flex-layout/esm5/flex.es5.js.LayoutGapStyleBuilder.buildStyles (flex.es5.js:228) at DefaultLayoutGapDirective.push../node_modules/@angular/flex-layout/esm5/core.es5.js.BaseDirective2.addStyles (core.es5.js:494)
`
#### What are the steps to reproduce?
`[fxLayoutGap]="null || undefined"`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Crash: 7.0.0-beta24
Same crash: 8.0.0-beta.26
Working fine: 7.0.0-beta.19

**Comment by CaerusKaru** [comment]
What do you expect the fallback value to be? I don't think this is a case that was ever defined, even though it "worked" in beta 19.

In the meantime, anyone encountering this issue can implement a fallback by registering a `StyleBuilder`.

**Comment by rovercoder** [comment]
As per usual Angular behaviour whenever an attribute directive is of null or undefined value, the respective attribute would be omitted.

Thus if one had to consider a default value for layoutGap, the unset value in my eyes would be '0px', as if it was never set.

Thanks for the suggestion.

**Comment by CaerusKaru** [comment]
That's definitely not usual Angular behavior. Usual Angular behavior simply passes that value to the directive, so long as the directive registers the input (and if not, it does nothing).

`0px` also isn't "unsetting", because there might be an upstream value/class that sets a default.

**Comment by rovercoder** [comment]
I see the reasoning behind is that you can provide a fallback value using your own implementation of StyleBuilder. Which makes sense. It may give users flexibility, but I personally don't see a time where I will be using e.g. '10px' as a fallback value for all my elements in a particular view. Hmm this is debatable, might make sense in some scenarios. 

Would be nice to use '0px' anyway if no custom StyleBuilder has been provided. If there is any way to detect that.

**Comment by CaerusKaru** [comment]
Unfortunately I don't think so. My suggestion would be to do something like this as a workaround:

`[fxLayoutGap]="value || '10px'"` as needed, or implement the `StyleBuilder` as discussed.
