### ISSUE TITLE
FxLayoutGap doesnt work when no measurement unit is provided

### ISSUE THREAD

**Issue by cedricschweizer** [angular/flex-layout#1093]
If no measurement unit is provided for the fxLayoutGap-directive, there's no fallback to percentage (Gap with percentage only works when it's explicitly specified).

**Comment by CaerusKaru** [comment]
Since you've chosen to eschew the issue template, I can only guess that this is a feature request? That API was not designed to fallback on percentage, so this would have to be something we would add. In the interim, you can implement your own `StyleBuilder` to achieve this behavior.

**Comment by CaerusKaru** [comment]
I've opened a PR to introduce this at the library level in #1384. This would mean that you could specify a library config default unit, which as of that PR would support your use case. If you need other use cases supported (or anyone else does), you/they can open separate issues so we can track introducing it elsewhere on a case-by-case basis.
