### ISSUE TITLE
Issue while upgrading from angular 5 to angular 7

### ISSUE THREAD

**Issue by vsssunder** [angular/flex-layout#1094]
I have been upgrading my angular project from version 5 to version 7 , but facing issues with flex layout while compiling:

ERROR in node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(25,15): error TS2416: Property '_registry' in type 'MockMatchMedia' is not assignable to the same property in base type 'MatchMedia'.
  Type 'Map<string, MockMediaQueryList>' is not assignable to type 'Map<string, MediaQueryList>'.
    Type 'MockMediaQueryList' is not assignable to type 'MediaQueryList'.
      Property 'onchange' is missing in type 'MockMediaQueryList'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(63,22): error TS2420: Class 'MockMediaQueryList' incorrectly implements interface 'MediaQueryList'.
  Property 'onchange' is missing in type 'MockMediaQueryList'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(80,27): error TS2304: Cannot find name 'MediaQueryListListener'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(82,23): error TS2304: Cannot find name 'MediaQueryListListener'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(11,22): error TS2420: Class 'ServerMediaQueryList' incorrectly implements interface 'MediaQueryList'.
  Property 'onchange' is missing in type 'ServerMediaQueryList'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(28,27): error TS2304: Cannot find name 'MediaQueryListListener'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(30,23): error TS2304: Cannot find name 'MediaQueryListListener'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(42,15): error TS2416: Property '_registry' in type 'ServerMatchMedia' is not assignable to the same property in base type 'MatchMedia'.

Tried installing flex-layout version 6.0.0-beta.18 and compiling as mentioned in some other sources.

**Comment by CaerusKaru** [comment]
What is your version of TypeScript? You need to have whatever version is compatible with the version of Flex you have installed (since Flex Layout depends on TypeScript's definition of the DOM, which changes).

**Comment by vsssunder** [comment]
Sorry for the delay. I have been using typescript version 3.1.1

**Comment by CaerusKaru** [comment]
Ok, you need to upgrade to at least TypeScript v3.2 (the actual version you need may be higher; I recommend incrementally updating until the version works - my recollection is it’s v3.4)

**Comment by vsssunder** [comment]
I have tried with upgrading typescript incrementally till 3.2.4 beyond that which I cant as angular 7 is not compatible with typescript beyond that version.

**Comment by CaerusKaru** [comment]
Yeah, upgrading to TypeScript v3.2 should solve this issue. Please ensure that the version in your project is actually this version, along with a v7 version of Flex Layout. Beyond this, there's no further support we can provide on v7, since we don't maintain an LTS.
