### ISSUE TITLE
Link to gdColumns API in wiki is dead

### ISSUE THREAD

**Issue by takahser** [angular/flex-layout#1099]
# Bug Report

#### What is the expected behavior?

The [gdColumns API link](https://github.com/angular/flex-layout/wiki/gdColumns-API) shouldn't be dead.

#### What is the current behavior?

The [gdColumns API link](https://github.com/angular/flex-layout/wiki/gdColumns-API) is dead.

The following wiki pages contain this dead link:

- https://github.com/angular/flex-layout/wiki/API-Documentation
- https://github.com/angular/flex-layout/wiki/Declarative-API-Overview

**Comment by 4val0v** [comment]
there is no API instructions for `Grid` directives
all links related to the `Grid` - redirect to /wiki

**Comment by CaerusKaru** [comment]
Duplicate of #1026
