### ISSUE TITLE
Missing backtick in Declarative API Overview causes gdAreas documentation to not render correctly

### ISSUE THREAD

**Issue by bkad** [angular/flex-layout#1102]
# Bug Report

#### What is the expected behavior?
The API column for the "gdAreas" row in https://github.com/angular/flex-layout/wiki/Declarative-API-Overview#api-for-dom-containers should render correctly.

#### What is the current behavior?
It's missing a backtick, so it doesn't. Should change `` `gdAreas="area1 | area2 | area3" `` to `` `gdAreas="area1 | area2 | area3"` ``

**Comment by CaerusKaru** [comment]
Fixed, thanks! It was also missing escaped pipes (e.g. `\|` instead of just `|`)
