### ISSUE TITLE
Ivy Compilation Failed: ERROR in ENOENT: no such file or directory. ngx-segment-analytics

### ISSUE THREAD

**Issue by rudineymc** [angular/flex-layout#1108]
# Bug Report

#### What is the expected behavior?
Should compile correctly with Ivy

#### What is the current behavior?
Only if Ivy is disabled compiles correctly

#### What are the steps to reproduce?
* Install ngx-segment-analytics dependency
* Import the module and compile with Ivy.
* It should fetch the index.js not ngx-segment-analytics.js
* ERROR in ENOENT: no such file or directory, open '/node_modules/ngx-segment-analytics/ngx-segment-analytics.js'.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version: 8.1.2
Material: 8.1.2
TypeScript: 3.4.3

**Comment by CaerusKaru** [comment]
Why would this be a Flex Layout issue?
