### ISSUE TITLE
fxFlex.xs fxLayout.xs and more not working in Angular 8.1.2

### ISSUE THREAD

**Issue by AgileCabaleiro** [angular/flex-layout#1111]
# Bug Report

#### What is the expected behavior?
Change property value on resize to sm, xs...

#### What is the current behavior?
Nothing happens after resize.

#### What are the steps to reproduce?
Can be tested with any basic example in Angular 8.1.2

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 "dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/flex-layout": "github:angular/flex-layout-builds",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "ngx-build-plus": "^8.1.3",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.801.3",
    "@angular/cli": "^8.2.0",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }

#### Is there anything else we should know?
Ask for further info, sorry for my english.

**Comment by amoomoohq** [comment]
I'm experiencing the same issue with angular 8.2.2.

**Comment by jrosseel** [comment]
+1

**Comment by Splaktar** [comment]
Can you please provide a StackBlitz reproduction?

**Comment by buster95** [comment]
I'm trying to use fxFlex.xs or fxFlex.sm but not working, I'm using Angular 8.2.4 and AngularFlexLayout 8.0.0-beta.26

**Comment by Splaktar** [comment]
@buster95 Can you please provide a StackBlitz reproduction?

**Comment by CaerusKaru** [comment]
It's been almost three months since we've asked for reproductions. We cannot debug this without a demo. If one is provided, we can reopen this issue.

**Comment by gundupatil** [comment]
Experiencing the same issue with Angular 8.2 this should be reopened

**Comment by CaerusKaru** [comment]
@gundupatil This issue will not be reopened unless a reproduction is provided.
