### ISSUE TITLE
2.0.0-beta.2 is not available in npm

### ISSUE THREAD

**Issue by thekalinga** [angular/flex-layout#112]
Tho this repository says, `2.0.0-beta.2` is released, the npm repository contains only `2.0.0-beta.1`

Here is the command I have used to list

```sh
npm show @angular/flex-layout versions
```

**Comment by NNemec** [comment]
Indeed - same problem here

**Comment by datumgeek** [comment]
Would be nice to get this out there :smile:

**Comment by ThomasBurleson** [comment]
@thekalinga  - We are aware of the issue we an incorrect Beta.2 release. 
> The goal is to quick release a Beta.3 tomorrow.

**Comment by datumgeek** [comment]
waiting (patiently) :wink:  -  very grateful for this - flex box rules :smile:

**Comment by ThomasBurleson** [comment]
@datumgeek  - you can always install directly using:

```terminal
yarn install https://github.com/angular/flex-layout-builds.git
```

**Comment by amcdnl** [comment]
Why was this closed? Still having issue today. :(

**Comment by ThomasBurleson** [comment]
@here - nom updated.

**Comment by ThomasBurleson** [comment]
Npm updated
