### ISSUE TITLE
fxLayout not working on init load, only when window resolution is changed

### ISSUE THREAD

**Issue by jorj0** [angular/flex-layout#1122]
# Bug Report
I am using fxLayout.gt-sm="row" fxlayout.lt-md="column" to change the position of the components depending on the resolution.

It works when I am resizing the window, but not on init load.

#### What is the expected behavior?
Put the elements in a column in small devices and in a row in larger devices. 

#### What is the current behavior?
It only works on chaging the window size, not on init load.

#### What are the steps to reproduce?
Here is a stackblitz:
https://stackblitz.com/edit/angular-yanmhz

#### What is the use-case or motivation for changing an existing behavior?
If someone enters from a mobile phone, the elements would be in the incorrect position.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cli": "~7.0.2",
"@angular/compiler-cli": "~7.0.0",
"@angular/flex-layout": "^8.0.0-beta.27",
It also happens with "@angular/flex-layout": "^7.0.0-beta.24". This is the version used in my current project

**Comment by jdmassard** [comment]
I tried with these versions :

- "@angular/cdk": "~7.0.0"
- "@angular/common": "~7.0.0"
- "@angular/compiler": "~7.0.0"
- "@angular/core": "~7.0.0"
- "@angular/flex-layout": "^7.0.0-beta.24"
- "@angular/forms": "~7.0.0"
- "@angular/platform-browser": "~7.0.0"
- "@angular/platform-browser-dynamic": "~7.0.0"
- "core-js": "2.6.9"
- "rxjs": "6.5.2"
- "zone.js": "0.9.1"

There is no problem with Firefox / Edge / Chrome under Windows 10.

Check if you don't made mistakes while writing attributes binding like in your stackblitz :
`<div fxLayout.gt-sm="row" fxlayout.lt-md="column">` should become `<div fxLayout.gt-sm="row" fxLayout.lt-md="column">`

> You can use directly : `<div [fxLayout.gt-sm]="'row'" [fxLayout.lt-md]="'column'">`, to avoid these types of errors

**Comment by jorj0** [comment]
Thank you so much, I couldn't see that the "l" was in lowercase...

Tried in my project and works. I will use [xxxx] from now to get alerts from possible spelling errors.
