### ISSUE TITLE
Developer Setup npm install broken

### ISSUE THREAD

**Issue by bunnyfly** [angular/flex-layout#1123]
# Bug Report

When following the developer setup guide, `npm install` fails  with `npm ERR! Cannot read property 'match' of undefined`. See [npm log here](https://gist.github.com/bunnyfly/4f9e89afeb4c0a78f8eeebeb786def77).

I'm guessing there are undocumented node/npm/gulp version requirements, but I can't figure out which.

I tried the most recent commit `951ce4f` and `f00e232` from 2 weeks ago. Same thing.

I'm on macOS and tried 3 node versions which all gave the same result: `12.10.0`, `11.15.0`, and `10.something`.
npm version: `6.10.3`
gulp CLI version: `2.2.0`
gulp Local version: `3.9.1`

#### What is the expected behavior?

Following the developer setup guide should work.

#### What is the current behavior?

`npm install` fails with `npm ERR! Cannot read property 'match' of undefined`. See [npm log here](https://gist.github.com/bunnyfly/4f9e89afeb4c0a78f8eeebeb786def77).

#### What are the steps to reproduce?

* Install node 11.15.0, npm 6.10.3, and gulp.
* Fork and clone `angular/flex-layout`
* Run `npm install`

#### What is the use-case or motivation for changing an existing behavior?

Trying to submit a bug-fix PR.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

MacOS 10.14.3
Angular 8.2.4

**Comment by CaerusKaru** [comment]
Please use Yarn

**Comment by CaerusKaru** [comment]
I apologize for the curt remarks. On further investigation, it looks like I added a package-lock file when I shouldn't have, and this was breaking npm install. This should be fixed now, so feel free to use NPM or Yarn. And feel free to ping me when you submit your bugfix for PR!

**Comment by bunnyfly** [comment]
Working fine now! Thank you 😁
