### ISSUE TITLE
[Sass] Breakpoints lt-md issue

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#1127]
# Bug Report
lt-md not working properly

#### What is the expected behavior?
````
    @include layout-bp(lt-md) {
      h1 {
        font-size: 16px;
      }
    }
````

this should set size for 959 and less.

#### What is the current behavior?
css is used on 960 as well (but not at 961)

#### What are the steps to reproduce?
*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 
`Stackblitz url (template) is broken`

**Comment by CaerusKaru** [comment]
What browser are you using? The breakpoints are set to go up to `959.9px` for `lt-md`, which might not be correct for all browsers.

**Comment by mackelito** [comment]
I was testing on Mac, Chrome Version 76.0.3809.132 (Official Build) (64-bit),

**Comment by CaerusKaru** [comment]
@mackelito Can you provide a minimal reproduction repository?

**Comment by mackelito** [comment]
Sure, as soon as the template is fixed :)

**Comment by CaerusKaru** [comment]
@mackelito Were you able to fix the demo? (I understand the template is broken, but it should be simple to fix manually)

**Comment by CaerusKaru** [comment]
@mackelito I'm going to close this for now; our support for the Sass template is minimal, and there's nothing about it that looks obvious enough to fix (though if you know of a fix, I'm happy to review a PR). We can reopen this if there is a more direct reproduction I can look at.
