### ISSUE TITLE
Flex 33 + flex 66 doesn't fill 100 percent #306 regression

### ISSUE THREAD

**Issue by epelc** [angular/flex-layout#1128]
# Bug Report

Seems like https://github.com/angular/flex-layout/issues/306 is back

#### What is the expected behavior?

`fxFlex="33"` and `fxFlex="66"` should fill to 100%.

#### What is the current behavior?
It doesn't fill fully. Leaves 1 percent empty.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 
Starter is broken with 404 error but here is example output from using `fxFlex="33"`. It just uses 33% instead of replacing with 33.33%. Same with 66.

![image](https://user-images.githubusercontent.com/5204642/65524956-b5fd3900-debc-11e9-8d53-049f1bdfa9df.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Flex layout 8.0.0-beta.26

**Comment by CaerusKaru** [comment]
I tried looking for past logic that would've handled this transformation and couldn't find anything. Maybe @ThomasBurleson has some context? My inclination is that we _can_ support this behavior, but our contract doesn't explicitly make this a bug.

**Comment by epelc** [comment]
I thought it was a specific feature but I couldn't find any docs referencing it(maybe from angular.js layout days?) but the previous bug and comments say it is supposed to work. I just noticed today when some buttons didn't line up.

You can easily workaround with a manual `33.33` or `34` for the percentage but it just working with 33/66 would be convenient since who ever really needs 33 explicitly? You always want a third.

**Comment by CaerusKaru** [comment]
The intended behavior is for users to use 33.33. If you want customized behavior, you can create a `StyleBuilder` to have the behavior you need.
