### ISSUE TITLE
Bug report stack blitz starter link is broken

### ISSUE THREAD

**Issue by epelc** [angular/flex-layout#1129]
# Bug Report

#### What is the expected behavior?

Bug report starter stack blitz is currently broken.

#### What is the current behavior?

The provided stack blitz starter link for bug reports is broken with a 404 link. Not sure if this is stackblitz or an issue with how the nightly build is linked.

The stackblitz link from issue templates(template uses the goo.gl shortlink).

https://goo.gl/y38GUZ

![image](https://user-images.githubusercontent.com/5204642/65525657-e2658500-debd-11e9-95a1-e55a6fabda94.png)

![image](https://user-images.githubusercontent.com/5204642/65525697-ef827400-debd-11e9-8251-839a84caaa97.png)

**Comment by CaerusKaru** [comment]
@ThomasBurleson needs to fix this; he's the only one with permissions

**Comment by CaerusKaru** [comment]
I'm not seeing a 404 but I am seeing an issue with the `AppModule`.

**Comment by CaerusKaru** [comment]
No longer seeing an issue; we'll update the StackBlitz template to the latest version separately.
