### ISSUE TITLE
Support IE11 CSS Grid using auto-prefixer

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#1133]
# Bug Report

#### What is the expected behavior?
Grid functionality works in IE11

#### What is the current behavior?
Grid functionality is entirely ignored in IE11

#### What are the steps to reproduce?
navigate to your demo app in IE11: https://tburleson-layouts-demos.firebaseapp.com/#/grid

#### What is the use-case or motivation for changing an existing behavior?
I'm not sure what the supported browsers are for flex-layout, as [your browser support section on your wiki](https://github.com/angular/flex-layout/wiki/Browser-Support) is literally just a screenshot from [caniuse.com](https://caniuse.com/#feat=flexbox) (this should probably be updated)

If IE11 is a supported browser, all features should work. [It looks like autoprefixers can convert modern syntax to the original IE11 syntax with success](https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66). This seems like something flex-layout could do for us.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 8.2.10
Material 8.2.3
Flex-layout beta 27
IE11

#### Is there anything else we should know?
If it's decided that flex-layout won't support IE11, there needs to be a big fat warning in the docs saying so, as many of us in corporate environments still try to support it.

**Comment by Polyterative** [comment]
Even the plain flex does not work in IE 11

Trying this basic test layout shows difference with Chrome or Edge

```html
<div fxLayout='row'>
  <div fxLayout='column'
       fxFlex='grow'
       fxLayoutAlign='center center'
  >
    <div fxFlex='grow'
    >
      1A
    </div>
    <div fxFlex='auto'
    >
      1B
    </div>
    <div fxFlex='5rem'
    >
      1C
    </div>
    <div fxFlex='2'
    >
      1D
    </div>
  </div>
  
  <div fxLayout='row'
       fxFlex='auto'
  >
    <div fxLayout='column'
         fxFlex='grow'
         fxLayoutAlign='center center'
    >
      <div fxFlex='grow'
      >
        2A
      </div>
      <div fxFlex='auto'
      >
        2B
      </div>
      <div fxFlex='5rem'
      >
        2C
      </div>
      <div fxFlex='2'
      >
        2D
      </div>
    </div>
    
    <div fxFlex='auto'
         fxLayoutAlign='center center'
    >
      B
    </div>
    <div fxFlex='5rem'
         fxLayoutAlign='center center'
    >
      C
    </div>
    <div fxFlex='2'
         fxLayoutAlign='center center'
    >
      D
    </div>
  </div>
  
  <div fxFlex='5rem'
       fxLayoutAlign='center center'
  >
    C
  </div>
  <div fxFlex='2'
       fxLayoutAlign='center center'
  >
    D
  </div>
</div>

```

**Comment by CaerusKaru** [comment]
@Polyterative can you open a separate issue and provide a StackBlitz with specific reproduction instructions?

@adamdport Thank you for doing the research on this and finding the auto-prefixer fix! I am more than happy to provide for official psuedo-support for CSS Grid in this package (previously it was somewhat acknowledged that we don't support IE11 for Grid only).

Is this something you would want to contribute? My bandwidth is unfortunately very limited for new features right now.

**Comment by adamdport** [comment]
@CaerusKaru it looks like [Angular CLI already has an autoprefixer built in](https://angular.io/guide/build#configuring-browser-compatibility)? It can be enabled by adding `/* autoprefixer grid: autoplace */` at the top of the component's style sheet. Any grid styles in the style sheet will get automatically compiled into the code needed by the browsers identified in `browserslist`. 

Since flex-layout chose to manipulate `style` attributes, this is less straightforward, as there _is_ no style sheet to compile. I'd think that the entirety of the autoprefixer project would have to get manually placed into flex-layout so that it could place it on the dom like it does?

**Comment by martinmcwhorter** [comment]
I see there are options to make this work. 

1. Give the option to include Autoprefixer (341kb) and pipe the generated contents of  `style` through it.
2. Take the Grid spec 1 to Grid spec 0 cross compilation that Autoprefixer does and bake it into grid layout. 

There may be other options here we are missing...

**Comment by CaerusKaru** [comment]
The Angular ecosystem is dropping support for IE 11, and while I'm not going to actively say that this library is following that verbatim and immediately, we are not going to consider this feature for inclusion in the library. I recommend using it as a wrapper on an _ad hoc_ basis for your applications, or whatever works best for you (even if that means forking this library). Thank you for submitting this idea; it was very cool at the time.
