### ISSUE TITLE
SSR styles have precedent issues

### ISSUE THREAD

**Issue by rkajbaf** [angular/flex-layout#1135]
# Bug Report

#### What is the expected behavior?

Using [ngStyle.xs]="{'display': 'none'}" and [ngStyle.lg]="{'display': 'block'}" would create 2 @media styles for the 2 respective sizes.

#### What is the current behavior?

Actually, you get the 2 above plus an inline style 'display': 'none' that overrides everything.  If I remove the inline style, the issue goes away and things appear to work as expected.
 
#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

Hard to use a StackBlitz for this as it is an SSR related issue.

#### What is the use-case or motivation for changing an existing behavior?

Avoid FOUC

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 8.2.9
Angular-Flex 8.0.0-beta.27
Angular Material 8.2.2
Typescript 3.5.3
Windows Chrome Latest (All Browsers woudl be affected)

#### Is there anything else we should know?

I have a feeling 'm doing something wrong here because I've tried a long list of ways to get SSR working as I would expect to no avail.

**Comment by CaerusKaru** [comment]
Please provide a GitHub repository that minimally reproduces this issue.

**Comment by rkajbaf** [comment]
https://github.com/rkajbaf/flexlayout-bug

Remember to disable javascript so you can see the issue.

**Comment by rkajbaf** [comment]
I can't be sure but I think this is related somewhat to #1065.

**Comment by rkajbaf** [comment]
So this change to 
`src/lib/extended/style/style.ts `

appears to fix my issue... not sure what kind of ramifications it has though.

![image](https://user-images.githubusercontent.com/4194060/67599653-8a30d580-f73e-11e9-9f02-3f285a6e768e.png)

**Comment by rkajbaf** [comment]
Sorry to pile on here.. but I see related looking issues in using ngShow/ngHide as well...

**Comment by rkajbaf** [comment]
Any updates on this?

**Comment by rkajbaf** [comment]
Couple of years later, and I think we're still in the same boat. When using flex-layout with SSR there content comes in incorrectly initially until the JS kicks in and the layout self-corrects. This results in content jumping around. Am I missing something here?

**Comment by CaerusKaru** [comment]
Fixed by #1378

**Comment by CaerusKaru** [comment]
@rkajbaf Investigating this issue took me all the way around and back again, but using your test case I was able to solve the underlying issue. It came down to breakpoint activation and deactivation. I wasn't able to replicate the issue you were facing with inline style, but I did notice the stylesheet was incorrectly adding breakpoint blocks where none were needed. By fixing that behavior, I got the stylesheet and rendering behavior to work as expected. Please feel free to try out the nightly build to confirm this fixes your issue.
