### ISSUE TITLE
Custom breakpoint directive for print is not working

### ISSUE THREAD

**Issue by kaushikam** [angular/flex-layout#1139]
# Bug Report

#### What is the expected behavior?
fxHide.xs.print should work as explained in the example provided [https://github.com/angular/flex-layout/wiki/Breakpoints](url)

#### What is the current behavior?
fxHide.xs.print does not have any effect.  Upon ctrl + p it is not hiding the element with 'fxHide.xs.print'

#### What are the steps to reproduce?
*  I have created a stackblitz [https://stackblitz.com/edit/angular-zffkvwcustom-show-hide-directive](url) here:

**Comment by CaerusKaru** [comment]
Please set the priority higher than the default print event (currently 1000).
