### ISSUE TITLE
flex-shrink not applied

### ISSUE THREAD

**Issue by jstaffans** [angular/flex-layout#114]
See [Plunkr](https://plnkr.co/edit/svsTmUOVNboB3bsd4VxO?p=preview). 

If I use `fxFlex="1 0 200px"`, the element ends up having the correct `flex-shrink` value of 0 set.
But if I use `fxFlex="1 0 auto"`, the `flex-shrink` attribute gets a value of 1.

Is this a bug or am I misunderstanding the way flexbox flex-shrink and flex-basis are interconnected?

**Comment by jstaffans** [comment]
I see now that there is a special case for `fxFlex="1 0 auto"` called [`noshrink`](https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/flex.ts#L271-L274). 

Would be great to include this in a more visible way in the documentation!

**Comment by ThomasBurleson** [comment]
Improved docs are in progress.
