### ISSUE TITLE
Live Demo Brocken

### ISSUE THREAD

**Issue by GrilleGustav** [angular/flex-layout#1147]
Live Demo on Stackbliz fails to load View

`
ERROR

Error: rxjs_BehaviorSubject.BehaviorSubject is not a constructor
Unable to display error. Open your browser's console to view.
ERROR

Error: rxjs_BehaviorSubject.BehaviorSubject is not a constructor
Unable to display error. Open your browser's console to view.
Unhandled Promise rejection:

[Object, Object, Object, Object]

; Zone:

<root>

; Task:

null

; Value:

[Object, Object, Object, Object]

undefined
`

**Comment by CaerusKaru** [comment]
Unable to replicate, closing.
