### ISSUE TITLE
Split layoutAlign attribute into two attributes

### ISSUE THREAD

**Issue by ryanlangton** [angular/flex-layout#115]
Current API has you write layout containers like this:

`<div fxLayout="row" fxLayoutAlign="center end"></div>`

This would translate to css of:

```
justify-content: center;
align-items: flex-end;
```

I would like to see an API that maps more closely to the pure flexbox solution so that there isn't that convention based disconnect.  A more intuitive markup would be:

`<div fxLayout="row" fxJustifyContent="center" fxAlignItems="flex-end">`

An attribute that takes multiple strings separated by a space (how fxLayoutAlign is used currently) is especially counter intuitive.

**Comment by ThomasBurleson** [comment]
Will not change.

**Comment by ryanlangton** [comment]
Sure, create an intentional disconnect from pure CSS for no benefit.  Makes sense.  This is why frameworks and libraries get a bad rap.  The creators think they know a "better way".

**Comment by ThomasBurleson** [comment]
@ryanlangton - The @angular architectures and implementations are based on many months of exploration, usage, and validation from large groups of developers. With that said we realize that there is always areas for improvements and collaborations.

>  Please note that the @angular repos have a [strict code of conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md).  We encourage positive contributions.
