### ISSUE TITLE
Export ServerMatchMedia or allow to disable flex-layout-X classes

### ISSUE THREAD

**Issue by intellix** [angular/flex-layout#1152]
# Proposal

#### What is the summary of the proposal?
Export **ServerMatchMedia** or at least add the ability to disable flex-layout-X class injections or only add flex-layout-X classes for FlexLayout directives inside index.html

#### What is the proposal?
We're using Universal with FlexLayout and noticed that there were 100kb of classes being added to index.html. After investigating it a little I noticed that each of them were repeated 10x. We've decided to go mostly cold turkey and axe FlexLayout to reduce bundle size and increase perf by just using Flex utility classes.

The bits we're still using are:
 - ExtendedModule (ngClass.xs, ngStyle.xs etc)
 - MediaObserver (we're faking **ssrObserveBreakpoints** using detected user agent to improve the initial load experience).

In order for us to provide **ssrObserveBreakpoints** we've got something like this:

```ts
import { Request } from 'express';
import { UAParser } from 'ua-parser-js';

export function getFlexLayoutConfig(request: Request) {
  const uaParser = new UAParser(request.headers['user-agent']);
  const device = String(uaParser.getDevice().type);
  let ssrObserveBreakpoints = ['gt-xs', 'gt-sm', 'gt-md', 'lg', 'lt-xl'];
  const breakpoints: Record<string, string[]> = {
    mobile: ['xs', 'lt-sm', 'lt-md', 'lt-lg', 'lt-xl'],
    tablet: ['gt-xs', 'gt-sm', 'md', 'lt-lg', 'lt-xl'],
  };

  if (device in breakpoints) {
    ssrObserveBreakpoints = breakpoints[device];
  }

  return { ssrObserveBreakpoints };
}
```

Initially we removed `FlexLayoutServerModule` to stop the 100kb of class injection into index.html so lost access to ServerMatchMedia being provided and it isn't exported.

As a temporary workaround we've just copy/pasted ServerMatchMedia and provide it ourselves.

#### Is there anything else we should know?
I should probably open an issue as well but:
 - Server injected classes are repeated 10x (I need a repo)
 - Those classes are also being added when I don't use fxLayout/fxFlex at all. It's literally being added to anything with flex styles.

**Comment by CaerusKaru** [comment]
Please follow the instructions in the SSR guide [here](https://github.com/angular/flex-layout/blob/28bc2ae7476367f111edfce39a05b3f9041501f7/guides/SSR.md#option-3-generate-no-flex-layout-stylings-on-the-server)
