### ISSUE TITLE
ERROR TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ingluca888** [angular/flex-layout#1157]
When I run an Angular App 8  with Flex Layout using SSR, I get the following error:

ERROR TypeError: Cannot read property 'match' of undefined

it work fine when the same work on client side with ng serve.

Any idea?
Thanks.

**Comment by CaerusKaru** [comment]
Please follow the issue template. It exists for a reason. As it is it's impossible to tell from your message. If you do not provide a minimal reproduction of the issue with clear steps to reproduce, this issue will be closed.

**Comment by CaerusKaru** [comment]
It's been two months with no reply. Closing this issue for now, we can reopen if a demo is provided.
