### ISSUE TITLE
Documentation lacks clear definition of API features

### ISSUE THREAD

**Issue by NNemec** [angular/flex-layout#116]
Currently, the API Overview lists the available features without much explanation and a small set of examples that allow very limited extrapolation.
In experimenting with flex-layout, I observe unexpected behavior, but I cannot say whether it is due to bugs or misunderstanding. Please provide a detailed definition of the intended behavior to allow working with flex-layout in a predictable way and providing proper feedback & bug-reports.

**Comment by ThomasBurleson** [comment]
@NNemec - improvements to our document are *in-progress*. 

During the interim, please use \

*  the lib source code as a reference point for internals and 
*  the demo-app source for reference points on usages.
