### ISSUE TITLE
fxFlex not switching max-width and max-height

### ISSUE THREAD

**Issue by bhenderson** [angular/flex-layout#1160]
# Bug Report

#### What is the expected behavior?
Updating fxLayout from column to row (or vice versa) fxFlex should switch between max-width and max-height when inside an ngFor loop.

#### What is the current behavior?
It does not switch when inside an ngFor loop.
*update* it is also broken in ngIf, which leads me to think any ng-content type block.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-dvunso?file=app/app.component.ts

thank you for your time.

**Comment by olliechick** [comment]
One workaround is to use [the grid layout](https://github.com/angular/flex-layout/issues/753#issuecomment-393050686).

**Comment by d0cz** [comment]
and looks like this is still going on! Well kind of...

In my case I'm simply using <mat-table> + flex-layout and it works locally but when deploying to our DEV environment the columns are just missing the max-width (set by the fxFlex directive) property.

Disabling `angularCompilerOptions.enableIvy` (false) does the trick and my deploys are now getting the max-width.
