### ISSUE TITLE
ERROR TypeError: this.ngClassInstance.ngDoCheck is not a function when compiling with --aot 

### ISSUE THREAD

**Issue by matthewmazzuca** [angular/flex-layout#1164]
# Bug Report

#### What is the expected behavior?
No error

#### What is the current behavior?
When compiling the project in AOT, certain components for the app throw the above error when in specific components. From reading through the issues, I suspect this has something to do with ngClass but cannot pinpoint what it is. Any help would be greatly appreciated

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 
1) Install with same versions of angular packages/typescript listed below
2) Add standard ngClass to a component's HTML

#### What is the use-case or motivation for changing an existing behavior?
Currently it does not work

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

package.json (relevant packages)
`"@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/fire": "^5.2.3",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/platform-server": "^8.2.14",
    "@angular/router": "^8.2.14",
    "typescript": "^3.5.3",`

#### Is there anything else we should know?
No

**Comment by CaerusKaru** [comment]
Can you replicate this with v9?

**Comment by CaerusKaru** [comment]
No comment for two months, closing. We can reopen if this can be replicated with a newer version.

**Comment by kvnngn** [comment]
I have the same issue, no update?
