### ISSUE TITLE
Create a release on NPM for v9

### ISSUE THREAD

**Issue by matthewerwin** [angular/flex-layout#1166]
Currently the latest that can be pulled without going directly to a git reference on NPM is a release from 4 months ago. Can the team put out a release on NPM that stays on mark with the v9 work by the main angular team rc.7 or at least compatible with v9 pre-release?

**Comment by CaerusKaru** [comment]
Like with the release of Angular v9, we decided to hold off on the v9 beta until after the holidays. We'll cut one once the team is back.

**Comment by Betalos** [comment]
@CaerusKaru any progress on this ????

**Comment by paulstelzer** [comment]
@CaerusKaru would be great to see a new version because beta.28 isn't working with angular rc.11 anymore. I have to stay at Angular rc.9

**Comment by CaerusKaru** [comment]
I’m aware, that was patched literally last night (I was made aware of it yesterday morning). If we had cut a v9 release, that would’ve been unusable as well.

As it is, there will now be a planned v9 release early next week. In the meantime, feel free to use the nightly release to unblock your upgrade.

**Comment by paulstelzer** [comment]
@CaerusKaru Thanks! Can you tell me where is the nightly build? In https://www.npmjs.com/package/@angular/flex-layout there is only beta.27 as latest release

**Comment by CaerusKaru** [comment]
See [here](https://github.com/angular/flex-layout/wiki/NPM-Installs#install-from-nightly-build-head)

**Comment by virshu** [comment]
To minimize the changes, I recommend to use git just for flex-layout itself. That is, instead of `npm install angular/flex-layout-builds angular/cdk-builds --save` use `npm install angular/flex-layout-builds`

**Comment by CaerusKaru** [comment]
New release has been published to `@latest` on NPM

**Comment by matthewerwin** [comment]
Thank you!
