### ISSUE TITLE
fxLayout="row|column" inverted

### ISSUE THREAD

**Issue by rocketkittens** [angular/flex-layout#1169]
Rows are suppose to be horizontal.
Columns are suppose to be vertical.

This library inverts these terms and does not match the effects (inverted) the values have when using flexbox.

**Comment by CaerusKaru** [comment]
Can you elaborate or add any supporting details? You are the first person in three-plus years to make this claim.

**Comment by rocketkittens** [comment]
Okay i wrote the following code which i should have before creating this issue and i got the result i expected which means my brain is just playing tricks on me, should drink some coffee.

Confirmed everything is as it should be and i was wrong. Sorry to raise concern.

```
<div style="display:flex;flex-direction: row">
	<div>1</div>
	<div>2</div>
	<div>2</div>
</div>

<div style="display:flex;flex-direction: column">
	<div>1</div>
	<div>2</div>
	<div>2</div>
</div>

<div fxLayout="row">
	<div>1</div>
	<div>2</div>
	<div>2</div>
</div>

<div fxLayout="column">
	<div>1</div>
	<div>2</div>
	<div>2</div>
</div>
```
