### ISSUE TITLE
Unmet peer dependency rxjs@5.0.3

### ISSUE THREAD

**Issue by dzena** [angular/flex-layout#117]
When running `npm install --save @angular/flex-layout` i get the following error `UNMET PEER DEPENDENCY rxjs@5.0.3`. And `npm WARN` says `@angular/flex-layout@2.0.0-beta.3 requires a peer of rxjs@5.0.0-rc.4 but none was installed.`

I guess that everything will work (since I run the newest version of rxjs than required), but this message shouldn't appear.

My setup:
`angular-cli: 1.0.0-beta.25.5`
`node: 6.9.1`
`os: darwin x64`
`@angular/common: 2.4.3`
`@angular/compiler: 2.4.3`
`@angular/core: 2.4.3`
`@angular/flex-layout: 2.0.0-beta.3`
`@angular/forms: 2.4.3`
`@angular/http: 2.4.3`
`@angular/material: 2.0.0-beta.1`
`@angular/platform-browser: 2.4.3`
`@angular/platform-browser-dynamic: 2.4.3`
`@angular/router: 3.4.3`
`@angular/compiler-cli: 2.4.3`

**Comment by ThomasBurleson** [comment]
Yes. Everything will still work. 
This issue is annoying, however, so let's get the team to fix it! 👍
