### ISSUE TITLE
fxFlex directive long form seems to be useless, replace with a real long form

### ISSUE THREAD

**Issue by loicbefve** [angular/flex-layout#1171]
# Proposal

#### What is the summary of the proposal?

Remove the long form of fxFlex directive and create an other long form version with the real css flex behavior.

#### What is the proposal?

It seems that the fxFLex long form **fxFlex="1 1 5em"** is kind of useless. Indeed, as fxFlex set both min-(width/height) and max-(width/height) to the basis value (here 5em), **shrink** and **grow** value are useless.

**Example:**
```html
<div fxLayout=row>
  <div fxFlex="1 1 5em"></div>
  <div fxFlex="2 2 5em"></div>
  <div fxFlex="3 3 5em"></div>
</div>
```
The three divs will have exactly the same size: **5em**. So it's a lot confusing to be able to set grow and shrink without any effect.  

I know that changing the behavior of **fxFlex** is difficult for compatibility reasons. I also know that there is now a way to change the style that produce directives but that add a lot of complexity.

I think one better option could be to add a new directive **fxFlexCss** ?? That could stick to the flex css attribute.

Thanks for your reading

**Comment by CaerusKaru** [comment]
Thank you for your interest in this, but we will not be adding a new directive for this purpose. If you’d like, you’re more than welcome to alter the default `fxFlex` behavior by building your own `StyleBuilder`. You can even distribute it for others if you believe it would be helpful!

There are very specific reasons that the directive is built the way it is. You can search the closed issues on this subject to learn more about why. In the meantime, we will not be altering or adding the behavior of long-standing directives without profound reasoning.
