### ISSUE TITLE
Documentation - Typo on the StyleBuilder documentation, example code false

### ISSUE THREAD

**Issue by loicbefve** [angular/flex-layout#1172]
# Bug Report

#### What is the expected behavior?

In order to provide the new StyleBuilder the syntax is:

```typescript
@NgModule({
  ...,
  providers: [
    {
        provide : FlexAlignStyleBuilder,    // when default is requested
        useClass: CustomAlignStyleBuilder  // provide instead custom builder
    }  
]
})
```

#### What is the current behavior?

The documentation forgot the **{}**

```typescript
@NgModule({
  ...,
  providers: [
    provide : FlexAlignStyleBuilder,    // when default is requested
    useClass: CustomAlignStyleBuilder  // provide instead custom builder
  ]
})
```

#### What is the use-case or motivation for changing an existing behavior?
This can be confusing for beginners and the documentation will be more accurate.

**Comment by CaerusKaru** [comment]
Fixed, thanks!
