### ISSUE TITLE
ngcc fails when upgraded angular to 9.0.0-rc.11

### ISSUE THREAD

**Issue by AlexKirilov** [angular/flex-layout#1183]
After I migrate from angular 8.3 to angular 9.0.0-rc.11 and try to build or on ng serve I have the following error.
![image](https://user-images.githubusercontent.com/5669746/73435274-3a1a6e00-4340-11ea-9611-eadc7401d9ef.png)

if I set Ive to false it starts passing the build.

I checked the previous issue: https://github.com/angular/flex-layout/issues/1156
Should I downgrade to version 9.0.0-rc.6 or they're as another solution?

Thanks

**Comment by olivierlevy** [comment]
Hi @AlexKirilov , I have had the same issue than you, after many attempts with angular versions and flex-layout, those are the versions working for me today :
```json
  "dependencies": {
    "@angular/animations": "^9.0.0-rc.10",
    "@angular/cdk": "^9.0.0-rc.8",
    "@angular/common": "^9.0.0-rc.8",
    "@angular/core": "^9.0.0-rc.8",
    "@angular/fire": "^5.3.0",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^9.0.0-rc.8",
    "@angular/material": "^9.0.0-rc.8",
    "@angular/platform-browser": "^9.0.0-rc.8",
    "@angular/platform-browser-dynamic": "^9.0.0-rc.8",
    "@angular/pwa": "^0.900.0-rc.11",
    "@angular/router": "^9.0.0-rc.8",
    "@angular/service-worker": "^9.0.0-rc.10",
    "@angular/youtube-player": "^9.0.0-rc.8",
    "core-js": "^3.6.4",
    "rxjs": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.23",
    "@angular-devkit/build-angular": "^0.900.0-rc.11",
    "@angular-devkit/core": "^8.3.23",
    "@angular-devkit/schematics": "^8.3.23",
    "@angular/cli": "^9.0.0-rc.11",
    "@angular/compiler": "^9.0.0-rc.10",
    "@angular/compiler-cli": "^9.0.0-rc.7",
    "@angular/language-service": "^9.0.0-rc.10",
    "@types/node": "^13.5.2",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5"
  }
```

Ypu should also follow the update recommandations here :
https://www.angularjswiki.com/angular/update-angular-cli-version-ng-update-to-latest-6-7-versions/

`ng update --next` is quite usefull

And this one updated many of my .ts files :
`ng update @angular/cdk @angular/core @angular/material --next`

**Comment by AlexKirilov** [comment]
Thanks, I revers all changes and did it again. At seams running the "npm audit fix" make the real mess an update extra dependencies.  Now the code is working correctly

**Comment by CaerusKaru** [comment]
Please use the v9 release of Flex Layout with the latest RC of Angular (and TypeScript 3.7)
