### ISSUE TITLE
Angular 9 (> rc 10) missing ɵNgStyleR2Impl

### ISSUE THREAD

**Issue by zehavibarak** [angular/flex-layout#1184]
# Bug Report

Latest Angular version build fails with message:

> ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts:9:19 - error TS2305: Module '"/node_modules/@angular/common/common"' has no exported member 'ɵNgClassImpl'.

> import { NgClass, ɵNgClassImpl, **ɵNgClassR2Impl** } from '@angular/common';

## Reproduce

Update angular to >9.0.0-rc.10 with latest flex-layout and build.

**Comment by CaerusKaru** [comment]
You’re not using the v9 release of Flex Layout. Please upgrade to that version.

**Comment by zehavibarak** [comment]
You’re right, thanks
