### ISSUE TITLE
Version Issue in flex Layout

### ISSUE THREAD

**Issue by usman074** [angular/flex-layout#1187]
I have installed flex layout version 8.0.0-beta.25
following are some dependencies in my package.json file
"@angular/animations": "~8.2.8",
"@angular/cdk": "~8.2.3",
"@angular/flex-layout": "^8.0.0-beta.25",
 "@angular/material": "^8.2.3",
"typescript": "~3.5.3",
"@angular/cli": "~8.3.6"

It is expected to behave normally but I am getting the following error
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 162:51-68
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 1168:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 1071:57-74
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1028:48-65
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 970:57-74
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 865:61-78
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 768:60-77
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1584:47-64
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 668:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 559:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1830:51-68
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 473:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 328:63-80
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 162:66-83
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2069:50-67
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/grid.js 32:59-76
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 1348:61-78
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 1228:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 1144:59-76
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 1013:60-77
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2367:48-65
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 921:59-76
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 736:54-71
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 259:59-76
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 130:56-73
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2806:53-70
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 884:56-73
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/extended.js 248:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/extended.js 31:56-73
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2069:166-173
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2806:196-203
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2367:206-213
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2367:184-191
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 259:164-171
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2367:158-165
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/flex.js 736:149-156
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2367:131-138
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2069:233-240
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2069:211-218
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2069:187-194
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2806:167-174
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2069:137-144
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1830:190-197
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1830:169-176
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1830:140-147
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1584:157-164
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1584:128-135
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1028:170-177
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1028:148-155
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 1028:131-138
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 884:155-162
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm2015/core.js 2806:146-153
"export 'Δinject' was not found in '@angular/core'

**Comment by CaerusKaru** [comment]
This is not an issue with Flex Layout. Please try clearing and reinstalling you dependencies, and use the latest v8 beta of Flex Layout (beta 27).
