### ISSUE TITLE
Failed to compile entry-point @angular/flex-layout/extended

### ISSUE THREAD

**Issue by bazookon** [angular/flex-layout#1196]
# Bug Report

### Compilation errors

**ERROR in Failed to compile entry-point @angular/flex-layout/extended (module as esm5) due to compilation errors:**

Angular 9.0.0

`  
node_modules/@angular/flex-layout/esm5/extended.es5.js:903:35 - error NG1010: Expected array when reading the NgModule.declarations of ExtendedModule

903                     declarations: __spreadArrays(ALL_DIRECTIVES),
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by CaerusKaru** [comment]
Two things: the issue template exists for a reason, please follow it or your issues will be closed, and more importantly this is an issue with Angular, not Flex Layout, please file your issue with them.

**Comment by silentsnooc** [comment]
@CaerusKaru Hi! Just for me to understand: How is this an issue with Angular and not Flex Layout?
