### ISSUE TITLE
gdRows All row same height

### ISSUE THREAD

**Issue by Toso82** [angular/flex-layout#1204]
# Feature Request

#### What is the desired behavior?

I don't find the way to have all height same height.  I can use gdRows but there isn't nothing to specify all row.

**Comment by CaerusKaru** [comment]
Can you be more specific about this problem in any way?

**Comment by Toso82** [comment]
Hi sorry i see later the request but notthing special i try to use gdRows. But my problem it is if i want for example 3 row with same height there isn't notthing like grid-template-rows to define template.

**Comment by CaerusKaru** [comment]
`gdRows` is a direct counterpart to `grid-template-rows`, aka you can use them interchangeably. I think the syntax you’re looking for is `gdRows=“repeat(3, 1fr)”`. Either way, this is not an issue with Angular Layout, closing.
