### ISSUE TITLE
Class FlexLayoutModule is not an Angular module

### ISSUE THREAD

**Issue by CKiD2011** [angular/flex-layout#1208]
I wanted to start working with this framework. I installed flex-layout via npm and imported it in app.module.ts like this:

import { FlexLayoutModule } from '@angular/flex-layout';

imports: [
          FlexLayoutModule
  ],

IntelliJ says always: "Class FlexLayoutModule is not an Angular module"

Is this a known issue? How to work with this framework?

**Comment by iamsrk** [comment]
I also faced this issue
I believe you have ran 
`npm install --save @angular/flex-layout`

After this I faced the same issue.
but I then found that we should install and update the @angular/cdk

run below to fix the issue
`npm install --save @angular/flex-layout @angular/cdk`

now cdk get updated and you can use flex-layout.
