### ISSUE TITLE
Vertical align don't work NG9

### ISSUE THREAD

**Issue by Sartori-RIA** [angular/flex-layout#1209]
# Bug Report

#### What is the expected behavior?

align content vertical center and horizontal center

#### What is the current behavior?

align only horizontal

#### What are the steps to reproduce?
```html
    <div fxFlex
         fxLayout="row"
         fxLayoutAlign="center center"
    >
      <div
        fxLayoutGap="500px"
        fxFlexAlign="center center"
        style="text-align: center;"
      >
        <router-outlet></router-outlet>
      </div>
    </div>

```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular an angular material:   9.0.0
angular/flex-layout: ^9.0.0-beta.29
typescript: 3.7.5"

**Comment by CaerusKaru** [comment]
`fxFlexAlign` only takes one argument, not two. You need to provide more of a description of expected/actual behavior re actual CSS styles, layout, etc. A StackBlitz example would be best.

**Comment by CaerusKaru** [comment]
It's been almost two months without followup, closing. We can reopen if demo is provided.
