### ISSUE TITLE
Responsive directive tags are order-sensitive with Angular 9 Ivy under certain conditions

### ISSUE THREAD

**Issue by cmolodo** [angular/flex-layout#1210]
# Bug Report

#### What is the expected behavior?
Responsive directive tags may be added in any order to an HTML element and will be applied correctly when the application starts based on the initial window width and breakpoints.

#### What is the current behavior?
Under certain specific conditions, the initial layout is incorrect (all of the following must be true):
* Ivy compiler is enabled (tested in Angular 9 only, not sure if this also applies in Angular 8).
* A template element has multiple responsive directive tags added
* The tags on that element are ordered from highest priority to lowest priority rather than lowest to highest (e.g. ordered gt-xl, gt-lg, gt-md, gt-sm, gt-xs, base)
* At least one of the higher priority directive tags is set to null, undefined, or empty
* At least one of the higher priority non-null tags are specified using brackets for Angular to compute the value, rather than just using a String
* The initial window is opened such that a null tag would be highest priority

For example, given the following element:
`<div [fxFlex.gt-sm]="null" [fxFlex.gt-xs]="50" fxFlex="100">Item</div>`
The expected layout when starting the application with a small or larger breakpoint would be a 50% width, given the fxFlex.gt-xs directive.  
However, it starts with a 100% width instead, matching the base fxFlex directive, because that's specified directly.  (If the fxFlex directive were also in brackets, **no** flex-layout style elements would be applied.)

Note that if the application is resized such that a non-null breakpoint is hit (either larger or smaller), the layout will be fixed.  If it's then resized again back to a null breakpoint, it will (correctly) be unchanged.

That is, given the example element above, if the window is resized down to a small breakpoint, the layout will switch to 50% width, and will remain at that width if resized back up to a medium breakpoint.

#### What are the steps to reproduce?
Unfortunately, I couldn't get StackBlitz to support flex-layout 9 with Angular 9 Ivy - it gives an error when the "Enable Ivy" box is checked, likely related to [this issue](https://github.com/angular/flex-layout/issues/1203), even with Angular CLI v9.0.3.

Minimal template to see the problem - open with a medium or larger breakpoint, and the inner div will be full width rather than half:
```
<div fxLayout="row">
  <div [fxFlex.gt-sm]="null" [fxFlex.gt-xs]="50" fxFlex="100" style="height: 30px; border: 2px black solid;">Item</div>
</div>
```

Also, this github project illustrates the issue, with multiple examples:  
[https://github.com/cmolodo/flex-layout-ivy](https://github.com/cmolodo/flex-layout-ivy)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular core 9.0.2, CLI 9.0.3, with Ivy compiler enabled  
Flex-layout 9.0.0-beta.29

OS: Windows 10 Pro  
Browsers: Edge, Chrome, Firefox

#### Is there anything else we should know?
Note that this **only** happens with the Ivy compiler enabled.  If it's disabled, the order dependency disappears and responsive tags fall back as expected.

Based on some initial debugging, it looks like the original compiler re-orders the directives before processing them, which is why the order doesn't matter.  However, Ivy processes them in the order they're listed.

Given that there's an easy workaround, simply making sure the directive tags are ordered from lowest priority to highest priority, I'm not sure how urgent this is.  However, it might be helpful to add a note to the documentation explicitly stating that tags should be ordered this way.

**Comment by CaerusKaru** [comment]
Can you try this with latest master? We fixed an issue where `null` or `undefined` values were screwing up the fallback mechanism.

**Comment by cmolodo** [comment]
@CaerusKaru Yes, that seems to have fixed it, thank you!
