### ISSUE TITLE
Error after upgrading to Version 9

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/flex-layout#1216]
# Bug Report

Updated my application to Angular 9 and flex-layout version 9.0.0-beta.29.

After update getting below error 
"export 'LayoutNgClassImplProvider' was not found in '@angular/flex-layout'

Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.6
@angular-devkit/build-angular      0.900.6
@angular-devkit/build-ng-packagr   0.900.6
@angular-devkit/build-optimizer    0.900.6
@angular-devkit/build-webpack      0.900.6
@angular-devkit/core               9.0.6
@angular-devkit/schematics         9.0.6
@angular/cdk                       9.1.2
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.1.2
@ngtools/webpack                   9.0.6
@schematics/angular                9.0.6
@schematics/update                 0.900.6
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

#### Is there anything else we should know?

I am not even able to find LayoutNgClassImplProvider in code-base also changelog doesn't mention anything about this class being removed.

**Comment by CaerusKaru** [comment]
It's likely you still have a latent reference either in your code base, or that node_modules never got updated correctly. Either way, this is not an issue with Flex Layout.

**Comment by santoshyadav198613** [comment]
You mean LayoutNgClassImplProvider is not required anymore, if yes, we should document it somewhere or let ng update handle it.

**Comment by CaerusKaru** [comment]
It was never an “official” part of the API, and anyone using it would’ve read the commit message saying that it’s a stopgap and to use at their own risk.

**Comment by santoshyadav198613** [comment]
Thanks @CaerusKaru for explanation.

**Comment by SerkanSipahi** [comment]
@CaerusKaru is there an official way?
