### ISSUE TITLE
auto code suggestion/completion 

### ISSUE THREAD

**Issue by jagdishjadeja** [angular/flex-layout#1222]
# Feature Request

#### What is the desired behavior?
I was hoping if it can have auto code completion for directives/attributes we use in HTML files
so that while typing we can see multiple options in the editor itself without going back to documentation for information about it.

#### What is the use-case or motivation for the desired behavior?
using it in HTML or file for more info about using attributes

**Comment by CaerusKaru** [comment]
If you use an IDE like WebStorm or VS Code, this is already included.
