### ISSUE TITLE
Have flex ignore 'router-outlet' tags

### ISSUE THREAD

**Issue by davoutuk** [angular/flex-layout#1227]
# Feature Request

Whenever flex is used with Angular 'router-outlet' tags it completely messes up the layout intentions.  The Flex logic seems to treat the 'router-outlet' tag as an item to manage alongside other tags.

#### What is the use-case or motivation for the desired behavior?
The ideal solution would be for the Flex framework to specifically ignore 'router-outlet' tags.

**Comment by CaerusKaru** [comment]
Can you more clearly demonstrate the negative impact this has on your project? I imagine this happens for many users, but none have reported any issue so far.

**Comment by LoganDupont** [comment]
Do you mean this kind of problem #171?

**Comment by CaerusKaru** [comment]
Yeah I agree with @LoganDupont, marking this as a duplicate.

**Comment by CaerusKaru** [comment]
Duplicate of #171
