### ISSUE TITLE
No longer create branches for releases

### ISSUE THREAD

**Issue by DevVersion** [angular/flex-layout#123]
This more like a proposal for the release script

As we had like thousands of branches in the Material 1 repository we were considering stopping to create branches for releases because those are unnecessary.

Those are unnecessary because you can always `checkout` the Git Tag and have the same functionalities as for the branch.

Removing the branches also has other benefits, because it also prevents PR's from users that are trying to merge the release branches into `master` (we had that quite often IIRC)

cc. @ThomasBurleson

**Comment by ThomasBurleson** [comment]
@DevVersion - can you propose changes to the release script via an PR?

**Comment by DevVersion** [comment]
@ThomasBurleson Sure. I will take a look at this in the weekend (writing tests). Can you try assigning it to me?
