### ISSUE TITLE
 fxLayout="row" is not right !

### ISSUE THREAD

**Issue by qqaimh** [angular/flex-layout#1230]
# Bug Report
<img src="https://user-images.githubusercontent.com/10569979/79190762-a6910d80-7e57-11ea-93e6-7184ba162f16.png">
#### What is the expected behavior?
It should show in a row.
#### What is the current behavior?
<img src="https://user-images.githubusercontent.com/10569979/79189530-94fa3680-7e54-11ea-82c6-8911c7f96a64.png">

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

"dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.1",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "rxjs": "~6.5.5",
    "socket.io-client": "^2.3.0",
    "tslib": "^1.11.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^13.11.1",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "~5.0.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "~5.4.3",
    "ts-node": "~8.8.2",
    "tslint": "~6.1.1",
    "typescript": "^3.8.3"
  }

**Comment by janatgit** [comment]
I have the exact same set up as qqaimh and I am getting the exact same result: the divs are being rendered as a column instead in a row as expected. 

The one additional piece of information is that I did import FlexLayoutModule into my app.module.ts file.

**Comment by CaerusKaru** [comment]
@GabrielGil is correct, closing. If you provide an updated demo that demonstrates this, we can reopen.
