### ISSUE TITLE
fxFlex flex-basis max-width

### ISSUE THREAD

**Issue by IainAdamsLabs** [angular/flex-layout#1232]
# Bug Report

#### What is the expected behavior?
The documentation for fxFlex says that the flex-basis field "controls the default size of an element, before it is manipulated by other Flexbox properties" - just like the standard flex-basis field in CSS.

In which case, why does it apply the max-width property. This constrains the item to not enforcing the flex-grow property. 

When applying fxFlex="1 1 5em" I would envisage that the item would grow according to the free space.

Maybe I have misunderstood the fxFlex flex-basis property.

#### What is the current behavior?

The max-width restricts the item from expanding.

#### What are the steps to reproduce?

See this stackblitz.

https://stackblitz.com/edit/angular-flex-layout-seed-sxuz9b

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with Angular7, Angular9, Mac OS X, Chrome.

**Comment by CaerusKaru** [comment]
This is done to overcome bugs with CSS Flexbox in all browsers, and has the same (or similar) intended effect as regular flex-basis. If you really notice a difference, you can override this behavior by creating your own `StyleBuilder` in place of the default.
