### ISSUE TITLE
Responsive API (endsWith-)Error when Default Value is not provided

### ISSUE THREAD

**Issue by nickwinger** [angular/flex-layout#1233]
# Bug Report
buildStyles(gapValue, parent) {
        if (gapValue.endsWith(GRID_SPECIFIER)) { <--- error is here
            gapValue = gapValue.slice(0, gapValue.indexOf(GRID_SPECIFIER));
            // Add the margin to the host element
            return buildGridMargin(gapValue, parent.directionality);
        }
        else {
            return {};
        }
    }
#### What is the expected behavior?
Don't check gapValue.endsWith when it's undefined

#### What is the current behavior?
if you specifiy e.g.
fxLayout="row wrap" fxLayoutGap.gt-xs="20px"
but you don't provide the default (fxLayoutGap="something")
and you start with a smaller screen (below xs) then the layout engine is checking
for the gap value, but it is not there.
But there is no check for gapValue === undefined in buildStyles, therefore an error comes
that endsWith does not exist on undefined

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
it's simple to reproduce by sourself...

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

**Comment by CaerusKaru** [comment]
We have a unit test specifically for this case. Can you provide a reproduction of this issue?

**Comment by nickwinger** [comment]
actually i cannot reproduce this anymore. maybe it has to do with my upgrade to angular 9 (from 8)

**Comment by nickwinger** [comment]
actually i cannot reproduce this anymore. maybe it has to do with my upgrade to angular 9 (from 8)

**Comment by adamdport** [comment]
I still see it on 9.0.0-beta.29. I was about to make a reproduction but the starter stackblitz seems to be broken? It just says "starting dev server" perpetually

seems to be the same issue from a year ago, others were reporting that the PR didn't resolve it but has since been locked https://github.com/angular/flex-layout/issues/1011
