### ISSUE TITLE
Angular 9 Warning: Flex Layout loaded on the server without FlexLayoutServerModule

### ISSUE THREAD

**Issue by RCala** [angular/flex-layout#1241]
# Bug Report

#### What is the expected behavior?
Get FlexLayoutServerModule working in Angular v9 as it used to on Angular 8

#### What is the current behavior?
Console warnings: Flex Layout loaded on the server without FlexLayoutServerModule, and layout on looks broken and unstyled on SSR.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 9.

This my current implementation that if failed after the Angular 9 upgrade:

**app.server.module.ts**

 imports: [
    AppModule,
    **FlexLayoutServerModule**,
    NoopAnimationsModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: translateFactory,
        deps: [TransferState, ServerLangService]
      }
    }),
    ServerModule,
    ServerTransferStateModule,
  ],

**app.module.ts**

imports: [
    BrowserModule.withServerTransition({ appId: 'app' }),
    FormsModule,
    LayoutModule,
    QuicklinkModule,
    HomeModule,
    CommonModule,
    BrowserTransferStateModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: exportTranslateStaticLoader,
        deps: [HttpClient, TransferState]
      }
    }),
    BrowserAnimationsModule,
    ReactiveFormsModule,
    HttpClientModule,
    SAPFailureModule,
    **FlexLayoutModule**,
    AppRoutingModule

  ],

Hope it helps, many thanks for your help!

**Comment by CaerusKaru** [comment]
Can you provide a minimal reproduction repository that demonstrates this issue?

**Comment by CaerusKaru** [comment]
I'm going to close this. We can reopen if a demo is provided.
