### ISSUE TITLE
Custom breakpoins not working with ngClass.xx

### ISSUE THREAD

**Issue by elementalPRESS** [angular/flex-layout#1242]
# Bug Report

#### What is the expected behavior?

Following the documentation I expected that I can overwrite the existing breakpoints with new ones. I tried to replace the existing breakpoints with breakpoints used by Bootstrap 4.

#### What is the current behavior?

It compiles without errors, but nothing happened, which means that the defined breakpoints were not applied.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

curious is that it is working the StackBlitz but when I implement the MediaQueryObserver in my project it doesn't work. Any known problems with Angular 9?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 9.1.4

**Comment by CaerusKaru** [comment]
Can you please provide a minimal reproduction (StackBlitz or equivalent)?

**Comment by elementalPRESS** [comment]
> Can you please provide a minimal reproduction (StackBlitz or equivalent)?

Please check out the StackBlitz from your template. Everything is running fine. But when you run the same code with Angular 9 (9.1.6), it doesn't work anymore and the custom breakpoints are not listed.

https://stackblitz.com/edit/angular-flex-layout-seed-ldpquw

**Comment by CaerusKaru** [comment]
Can you use the [latest StackBlitz template](https://stackblitz.com/edit/flex-layout-seed)? I can't get yours to upgrade to the latest versions.

**Comment by CaerusKaru** [comment]
Closing as stale.
