### ISSUE TITLE
Is fxLayoutGap really working as expected?

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#1249]
# Bug Report

#### What is the expected behavior?
Padding/Margin should be applied properly

#### What is the current behavior?
Looks like it's not applying correct styles

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-kb5gr4

**Comment by CaerusKaru** [comment]
Your StackBlitz does not use the latest versions. Can you update and try again?

**Comment by mackelito** [comment]
Oh ok.. I used the template provided in the issue template, and also the link in ReadMe seems to use the same version so I guess that should be updated as well :)

Currently using `"@angular/flex-layout": "https://github.com/angular/flex-layout-builds#master-8cf36ce"` but what version should I use?

**Comment by CaerusKaru** [comment]
Latest release is beta.30 (released yesterday)

**Comment by mackelito** [comment]
Not sure what but I'm doing something wrong as I can't get it working when using `942c507`

**Comment by CaerusKaru** [comment]
Can you create a GitHub repo I can clone? I'm working on fixing the StackBlitz but it might take some time.

**Comment by mackelito** [comment]
No rush.. I'm using the "old way" for now :)

**Comment by CaerusKaru** [comment]
I've updated the StackBlitz template, it's now available [here](https://stackblitz.com/edit/flex-layout-seed-nightly)

**Comment by Totati** [comment]
@CaerusKaru for me it won't load and says "Cannot find module '@angular/flex-layout'."

**Comment by mackelito** [comment]
Here's a new stackblitz:
https://stackblitz.com/edit/flex-layout-seed-9tmnvg?file=src%2Fapp%2Fapp.component.html

**Comment by CaerusKaru** [comment]
@mackelito `fxLayoutGap` is working exactly as expected in all cases. In your last case, you need to use `16px 16px grid`. In the first case, you need to wrap containing divs with other divs. Just one consequence of our grid solution, but it does work. My preferred method is divs wrapping spans with content. Everything else looks right.

**Comment by mackelito** [comment]
hmm.. I fail to correct this stackblitz...
My assumption of how this works is that the first 16px is margin-right and second 16px is margin-bottom.. right?

**Comment by CaerusKaru** [comment]
That's correct, and that's exactly what you get in the template

**Comment by mackelito** [comment]
Sorry for beeing away.. but here's another blitz where it shows my wonderings..

https://stackblitz.com/edit/flex-layout-seed-bdvwst?file=src/app/app.component.html


so the normal fxLayoutGap="16px" adds margin-right, when using "16px 16px grid" I was expecting it to just add margins right and bottom.. but instead it uses padding.. this approach seems wrong. ?

When talking about grid and gaps in designs this often means the spacing between (margin) and not the inner padding so I guess that's why I'm confused.

What is the thinking behind this where the gap is margin in one senario and padding in the other?

**Comment by CaerusKaru** [comment]
@mackelito I’m not going to go into the entire design behind this approach, but needless to say grid mode is an entirely different approach. The behavior you see is completely expected and working correctly. As I mentioned previously, to get the desired visual behavior, you may want to wrap the content inside the divs with spans. If you need more detail, this approach was based on a StackOverflow solution for achieving grid gutters using margin/padding alone.
