### ISSUE TITLE
Show/Hide bug beta30  caused by display:initial

### ISSUE THREAD

**Issue by fetters5** [angular/flex-layout#1250]
# Bug Report
In beta30 the following commit causes issues with show/hide because of `display:initial`

>  show-hide: use initial value as fallback instead of parent (#1243) (bf2355b) 

#### What is the expected behavior?
the footer should be centered and displaying as it was with beta29

#### What is the current behavior?
See stackblitz

#### What are the steps to reproduce?

see the following stackblitz to reproduce. I hide the footer by default and `show.gt-sm`. 

https://stackblitz.com/edit/angular-flex-layout-seed-jyuaqd

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using the latest versions

**Comment by CaerusKaru** [comment]
I was worried this might happen. I'll get a fix in for the v10 release, but it'll be merged into the nightly v9 if you need a v9-compatible version. In the meantime, you can downgrade to beta.29 as a workaround.

**Comment by fetters5** [comment]
Thanks.  I will see how the nightly works, b/c I was hoping this would fix our issues related to the print hooks

**Comment by CaerusKaru** [comment]
I've reverted the offending commit in master. You should be able to NPM/Yarn install using `angular/flex-layout-builds` to get the working version.

**Comment by CaerusKaru** [comment]
We've published 9.0.0-beta.31 to include this fix for everyone. Please upgrade to that version to resolve this issue.
