### ISSUE TITLE
incorrect width of `fxFlexFill` when parent has padding

### ISSUE THREAD

**Issue by fxck** [angular/flex-layout#126]
see https://plnkr.co/edit/djkmWJbn3pnTOuuCY8p0?p=preview this shouldn't happen, I think?

**Comment by fxck** [comment]
looks like using `fxFlex` without anything actually fixes it.. I'm confused, what is `fxFlexFill` used for then?

**Comment by ThomasBurleson** [comment]
*  `fxFlex` - adjusts size along the main axis.
*  `fxFlexFill` - maximizes width and height of element in a layout container

----

General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.
