### ISSUE TITLE
MockMatchMedia doesn't register overlaps ranges

### ISSUE THREAD

**Issue by Xesenix** [angular/flex-layout#1263]
# Bug Report

#### What is the expected behavior?
When using `MockMatchMedia` for mocking activation of breakpoint range it doesn't properly register overlapped ranges.
```
it('should return correct activation state', inject([
  ɵMatchMedia,
  MediaObserver,
], (
  matchMedia: ɵMockMatchMedia,
  media: MediaObserver,
) => {
  matchMedia.activate('xs', true);
  expect(media.isActive('xs')).toBe(true); // works
  expect(media.isActive('sm')).toBe(false);
  expect(media.isActive('lt-sm')).toBe(true); // doesn't work
  expect(media.isActive('gt-sm')).toBe(false);
  expect(media.isActive('md')).toBe(false);
  expect(media.isActive('lt-md')).toBe(true); // doesn't work
  expect(media.isActive('gt-md')).toBe(false);
  expect(media.isActive('lg')).toBe(false);
  expect(media.isActive('lt-lg')).toBe(true); // doesn't work
  expect(media.isActive('gt-lg')).toBe(false);
  expect(media.isActive('xl')).toBe(false);
  expect(media.isActive('lt-xl')).toBe(true); // doesn't work
  expect(media.isActive('gt-xl')).toBe(false);
}))
```
In general it should work as described in unit test provided in [here](https://stackblitz.com/edit/flex-layout-match-media-test?file=unit-tests%2Fexamples.spec.ts) without need to manualy register aliases.

#### What is the current behavior?
```
it('should return correct activation state', inject([
  ɵMatchMedia,
  MediaObserver,
], (
  matchMedia: ɵMockMatchMedia,
  media: MediaObserver,
) => {
  matchMedia.activate('xs', true);
  expect(media.isActive('xs')).toBe(true);
  expect(media.isActive('sm')).toBe(false);
  expect(media.isActive('lt-sm')).toBe(false);
  expect(media.isActive('gt-sm')).toBe(false);
  expect(media.isActive('md')).toBe(false);
  expect(media.isActive('lt-md')).toBe(false);
  expect(media.isActive('gt-md')).toBe(false);
  expect(media.isActive('lg')).toBe(false);
  expect(media.isActive('lt-lg')).toBe(false);
  expect(media.isActive('gt-lg')).toBe(false);
  expect(media.isActive('xl')).toBe(false);
  expect(media.isActive('lt-xl')).toBe(false);
  expect(media.isActive('gt-xl')).toBe(false);
}))
```
Similar for other ranges activation with useOverlaps to true activates sets activation only to activated alias and for no overlaps.
For those test to pass correctly we need to manualy register ranges like this:
```
beforeEach(() => {
    const matchMedia = TestBed.get(ɵMatchMedia) as any as ɵMockMatchMedia;
    [
      'xl',
      'lt-xl',
      'gt-lg',
      'lg',
      'lt-lg',
      'gt-md',
      'md',
      'lt-md',
      'gt-sm',
      'sm',
      'lt-sm',
      'gt-xs',
      'xs',
    ].forEach((alias) => {
      // as any to get to private methods available in ɵMockMatchMedia
      (matchMedia as any)._registerMediaQuery((matchMedia as any)._validateQuery(alias));
    });
  });
```

#### What are the steps to reproduce?
[See those tests](https://stackblitz.com/edit/flex-layout-match-media-test)

#### What is the use-case or motivation for changing an existing behavior?
To be able to use `ɵMockMatchMedia` as mocking mechanism for unit tests without needing to hack into private methods that are already available there.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Angular 8 so that is on `"@angular/flex-layout": "^8.0.0-beta.27",`

#### Is there anything else we should know?
Having documentation for ` ɵMatchMedia, ɵMockMatchMedia, ɵMockMatchMediaProvider` would be nice to have. Reading through source code to be able to use it is quite time consuming.

**Comment by Xesenix** [comment]
One of possible solutions may be:
In https://github.com/angular/flex-layout/blob/master/src/lib/core/match-media/mock/mock-match-media.ts#L42
```

  activate(mediaQuery: string, useOverlaps = false): boolean {
    useOverlaps = useOverlaps || this.useOverlaps;
    mediaQuery = this._validateQuery(mediaQuery);

    if (useOverlaps || !this.isActive(mediaQuery)) {
      this._deactivateAll();
      [
        'xl',
        'lt-xl',
        'gt-lg',
        'lg',
        'lt-lg',
        'gt-md',
        'md',
        'lt-md',
        'gt-sm',
        'sm',
        'lt-sm',
        'gt-xs',
        'xs',
      ].forEach((alias) => {
        this._registerMediaQuery(this._validateQuery(alias));
      });
      this._activateWithOverlaps(mediaQuery, useOverlaps);
    }

    return this.hasActivated;
  }
```
But I guess users can also have other ranges registered and that wouldn't be enough for those custome cases...

**Comment by CaerusKaru** [comment]
@Xesenix Strictly speaking, this is a very unsupported API, and **should not** be used by downstream consumers. That being said, thank you for identifying this issue, and I've developed a fix that I think aligns with your expectations.

**Comment by Xesenix** [comment]
@CaerusKaru Thank you for fast action. I would consider mocks being consider public api as alternative would be for me to create exactly the same mock or some inferior version from what you have already have created.

**Comment by CaerusKaru** [comment]
@Xesenix we may well add a testing API if/when the library goes public. In the meantime it is not.
