### ISSUE TITLE
When using flex-layout ContentChildren is unavailable

### ISSUE THREAD

**Issue by phmello** [angular/flex-layout#127]
I've noticed that when Im using flex-layout inside a component's content the ContentChildren QueryList is empty when the directive is removed everything works normally.
I've created a [plunker](https://plnkr.co/edit/8E3PGNJW7s9als2gCAuQ?p=preview) with the example

**Comment by ThomasBurleson** [comment]
@phmello - very odd bug. And when it do this:

```html
<parent-component fxLayout="column">
          <child-component></child-component>
          <child-component></child-component>
          <child-component></child-component>
      </parent-component>
```

all works great again.

**Comment by nhhockeyplayer** [comment]
fxLayout doesn't hold water thru hierarchies/levels of selectors

try adding <header></header> within the level and it will be taken out
try adding <my-component></my-component> within the level and it will be taken out

**Comment by ThomasBurleson** [comment]
@phmello - this is not an issue with Flex-Layout.

`@ContentChildren()` by default only queries top-level elements. But you can specify additional options to query for all descendents in the projected content:

```
@ContentChildren(ChildComponent, {descendants: true}) children: QueryList<ChildComponent>;
```

See this working [Plunker here](https://plnkr.co/edit/ONmGUYAjvaxqfxqzZU3Q?p=preview).

> Closing this issue as not-an-issue.
