### ISSUE TITLE
Flex Layout not working in IE 11

### ISSUE THREAD

**Issue by haricharank9** [angular/flex-layout#1270]
FlexLayout not working in IE11 especially with the column.

#### What is the expected behavior?
This should be the expected behavior from chrome, safari and other browsers
<img width="1440" alt="Screen Shot 2020-06-14 at 2 23 52 PM" src="https://user-images.githubusercontent.com/41965610/84602250-998a9d80-ae4b-11ea-9794-7cf0893a3c7a.png">
#### What is the current behavior?
Below attached is the current behavior in IE11
<img width="1218" alt="Screen Shot 2020-06-14 at 2 29 03 PM" src="https://user-images.githubusercontent.com/41965610/84602260-b1fab800-ae4b-11ea-92b1-191c8929f11a.png">

Below is the link for stackblitz, Open this is IE11 and you can see the unexpected behavior
*  [angular-felxlayout-ie11-issue](https://stackblitz.com/edit/angular-felxlayout-ie11-issue?embed=1&file=src/app/app.component.html) 

FlexLayout should be supported by all the browsers, but IE11 has a weird behavior

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`"dependencies": {
    "@angular/animations": "~9.1.2",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "~9.1.2",
    "@angular/compiler": "~9.1.2",
    "@angular/core": "~9.1.2",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.2",
    "@angular/material": "^9.2.1",
    "@angular/platform-browser": "~9.1.2",
    "@angular/platform-browser-dynamic": "~9.1.2",
    "@angular/router": "~9.1.2",
    "rxjs": "~6.5.5",
    "stylelint": "^13.3.3",
    "stylelint-scss": "^3.17.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  }`

Please suggest me the fix I had to do to make it work in IE11, Please let me know if anything else is needed to solve this issue.

**Comment by mena149f** [comment]
I don't know if you have seen this
https://github.com/angular/flex-layout#browser-support
but they already saying that IE is Partial support is due to large amount of bugs present
and you can have a look on the known issues here
https://caniuse.com/#feat=flexbox

**Comment by duluca** [comment]
With Edge Chromium becoming the new default on Windows and end-of-life for IE 11 announced by Microsoft, I doubt it is worthwhile to resolve any IE 11 related issues. I recommend putting a browser check and redirect users to newer browsers.

**Comment by haricharank9** [comment]
Yes, I agree with that, I think this issue doesn't need any more resolution. 
@mena149f Yeah, We decided to show the user a message based on their browser. Thanks, @duluca  for your suggestions.
