### ISSUE TITLE
fxFlex directive is broken with a *ngIf directive and both layouts(row, column) on parent

### ISSUE THREAD

**Issue by devkirr** [angular/flex-layout#1273]
# Bug Report

#### What is the expected behavior?

The fxFlex with a value (ex: 250px) is suppose to apply the flex effect on a html element (ex: div) in a specified direction according to the fxLayout directive of his parent.

For example: 

```html
<div fxLayout.lg="row" fxLayout="column">
  <div *ngIf="true" fxFlex="250px" class="div1">div1 with ngIf</div>
  <div fxFlex="250px" class="div2">div2</div>
</div>
```

The div1 when displayed as row should have a flex effect on his width with a 250px max/min width and when the layout changes to column, this same div should now have his flex effect on his height with a 250px max/min height.

#### What is the current behavior?

After the first render (which is good), if you resize the window the flex effect **on the div with an `*ngIf` directive**, stays on the same attribute that it was firstly used and don't update with the layout change.

#### What are the steps to reproduce?

Use this link and resize the embeded window.

*  [StackBlitz demo](https://fxflexwithngif.stackblitz.io) **using flex-layout@8.0.0-beta.27**

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

flex-layout@8.0.0.25/26/27
Angular 8
Browser: Chrome

**Seems fixed in 9.0.0**

**Comment by CaerusKaru** [comment]
We do not patch older versions of Flex Layout. As you mentioned, this is fixed in the v9 versions.

**Comment by devkirr** [comment]
Wow! That is a fast answer! 

Ok thanks!

As for workaround I use the [hidden] attribute.

David
