### ISSUE TITLE
Review release version to keep compatibility with latest Angular and Angular/CDK

### ISSUE THREAD

**Issue by baumblatt** [angular/flex-layout#1278]
# Proposal

#### What is the summary of the proposal?
Please, tag 10.0.0-beta.xx as `next`, keeping version 9.0.0-beta.xx as `latest`.

#### What is the proposal?
Better compatibility with Angular and Angular/CDK latest versions.

#### Is there anything else we should know?
There is a compilation error if you follow this steps
```
ng new flex-playground
cd flex-playground
npm i -s @angular/flex-layout @angular/cdk
ng build
```

The error:
```
Error: Error on worker #7: Error: No typings declaration can be found for the referenced NgModule class in static withConfig(configOptions, 
        // tslint:disable-next-line:max-line-length
        breakpoints = []) {
            return {
                ngModule: FlexLayoutModule,
                providers: configOptions.serverLoaded ?
                    [
                        { provide: LAYOUT_CONFIG, useValue: Object.assign(Object.assign({}, DEFAULT_CONFIG), configOptions) },
                        { provide: BREAKPOINT, useValue: breakpoints, multi: true },
                        { provide: SERVER_TOKEN, useValue: true },
                    ] : [
                    { provide: LAYOUT_CONFIG, useValue: Object.assign(Object.assign({}, DEFAULT_CONFIG), configOptions) },
                    { provide: BREAKPOINT, useValue: breakpoints, multi: true },
                ]
            };
        }.
```

#### Workarounds:

Create a new project follow this steps
```
ng new flex-playground
cd flex-playground
npm i -s @angular/flex-layout@9.0.0-beta.31 @angular/cdk
ng build
```
or fix the same project with:
```
npm i --save  @angular/flex-layout@9.0.0-beta.31
ng build
```

Best regards,
Bernardo Baumblatt

**Comment by CaerusKaru** [comment]
Angular v10 final is set to be released soon, as evidenced by the RC period drawing to a close. This will be a non-issue at that time. If the release is delayed, we will consider this, but otherwise the peer dependency warning on install should serve as a reminder that the correct versions are needed.
