### ISSUE TITLE
Bug (or expected behavior) when i add items to existing fxLayout or use HTTP with *ngFor

### ISSUE THREAD

**Issue by oshri551** [angular/flex-layout#128]
I tried to use fxLayout="column" with fxLayoutGap

I get my appDetails via object http get, the expected behavior is that there will be 10px gap between the items, but there is no gap.

```
<div fxLayoutAlign="start center" fxLayout="column" fxLayoutGap="10px">
   <button *ngFor="let action of appDetails.Actions" md-raised-button color="primary"   
   {{action.ActionName}}
   </button>
</div>
```

What i did to replicate it is to create static array with few items and then use the *ngFor to show them and that works (but it's not async) so i made a button to add items to the array, those items rendered without the fxLayoutGap.

I made [plunker](https://plnkr.co/edit/fGFqsPVNsvTdrt1oQqyY?p=preview) based on the plunker template

You can see the items that were before in the array rendered perfectly, but if i add new item it rendered without to flexLayoutGap (same for row and column)

**Comment by d3viant0ne** [comment]
https://github.com/angular/flex-layout/issues/95

**Comment by ThomasBurleson** [comment]
@oshri551  - this has been fixed in **#master** and will be available on **npm** in the upcoming Beta.4.

> See fixes here:  https://github.com/angular/flex-layout/pull/124

**Comment by ThomasBurleson** [comment]
@oshri551  - this has been fixed in **#master** and will be available on **npm** in the upcoming Beta.4.

> See fixes here:  https://github.com/angular/flex-layout/pull/124

**Comment by oshri551** [comment]
@ThomasBurleson  It works perfectly now, thanks!
