### ISSUE TITLE
export 'ɵgrid_privatez' was not found in '@angular/flex-layout/grid

### ISSUE THREAD

**Issue by efronic** [angular/flex-layout#1280]
# Bug Report
Hi there,

I have issues on build:

I have just updated to Angular 10 (final release) and am on the latest @angular/flex-layout version too.
"@angular/flex-layout": "10.0.0-beta.32"

#### What is the current behavior?
On ng serve:
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privateq' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privater' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privates' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privatet' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privateu' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privatev' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privatew' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privatex' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privatey' was not found in '@angular/flex-layout/grid'
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex-layout.js 18:0-590
"export 'ɵgrid_privatez' was not found in '@angular/flex-layout/grid'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk": "^10.0.0",
"@angular/flex-layout": "10.0.0-beta.32",
"@angular/material": "^9.2.4",
"@angular/cli": "^10.0.0",
"@angular/common": "^10.0.0",
"@angular/compiler": "^10.0.0",
"@angular/core": "^10.0.0",

**Comment by CaerusKaru** [comment]
That’s strange. Can you please provide a minimal reproduction that we can investigate? Our sample app also runs on latest and has no issue.

**Comment by efronic** [comment]
I fixed it by:
- Removing node_modules entirely
- **Downgrading @angular/flex-layout to "@angular/flex-layout": "9.0.0-beta.31",**
- Upgrading @angular/material to "@angular/material": "^10.0.0",

I suspect there is a problem in "@angular/flex-layout": "10.0.0-beta.32", don't upgrade to it for time being if you have the same problem.

Not related to this issue, but worth mentioning:
Don't forget to remove BrowserModule from app.module. I was getting this error until I removed it: "Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType"

**Comment by efronic** [comment]
This is getting really weird, I just restarted my machine and the error came back again!

**Comment by bilalshaikh42** [comment]
I am having similar issues when updating to angular 10. 

Are you using the post install script to run the angular compiler? if so, In your package.json,  removing the "--create-ivy-entrypoints" flag from ngcc might be helpful.

**Comment by efronic** [comment]
> I am having similar issues when updating to angular 10.
> 
> Are you using the post install script to run the angular compiler? if so, In your package.json, removing the "--create-ivy-entrypoints" flag from ngcc might be helpful.

No I am not using post install script, package.json does not have that flag.

"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.0.2",
    "@angular/cdk": "^10.0.1",
    "@angular/common": "^10.0.2",
    "@angular/compiler": "^10.0.2",
    "@angular/core": "^10.0.2",
    "@angular/flex-layout": "9.0.0-beta.31",
    "@angular/forms": "^10.0.2",
    "@angular/material": "^10.0.1",
    "@angular/platform-browser": "^10.0.2",
    "@angular/platform-browser-dynamic": "^10.0.2",
    "@angular/router": "^10.0.2",
    "@auth0/angular-jwt": "^4.2.0",
    "@ngrx/effects": "^9.2.0",
    "@ngrx/store": "^9.2.0",
    "@ngrx/store-devtools": "^9.2.0",
    "adal-angular4": "^4.0.12",
    "core-js": "^3.6.5",
    "jspdf": "^1.5.3",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "xlsx": "^0.16.3",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.1",
    "@angular/cli": "^10.0.1",
    "@angular/compiler-cli": "^10.0.2",
    "@angular/language-service": "^10.0.2",
    "@types/jasmine": "^3.5.11",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^14.0.14",
    "codelyzer": "^5.2.2",
    "html2canvas": "~1.0.0-rc.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.2",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~3.3.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.2",
    "typescript": "^3.9.5"
  }

**Comment by kishoreaoe** [comment]
Me too facing exactly same issue. can some one help in this waste around a day for the same.

**Comment by CaerusKaru** [comment]
No demo provided after several months, so I'm closing this issue. We can reopen if a demo is provided.
