### ISSUE TITLE
Latest version of flex layout (10.0.0-beta.32) is not working in Angular 9

### ISSUE THREAD

**Issue by vijhhh2** [angular/flex-layout#1281]
# Bug Report

#### What is the expected behaviour?
While angular trying to compile the flex layout library it should compile without any issues and start the server.

#### What is the current behaviour?
While angular trying to compile the flex layout library, compiler showing the below error.
**ERROR in node_modules/@angular/flex-layout/typings/module.d.ts:16:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/flex-layout) which declares FlexLayoutModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.**

#### What are the steps to reproduce?
create a new angular application and install flex layout library. Then serve the app.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v9, Windows 10

**Comment by CaerusKaru** [comment]
If you look at your installation, you’ll notice that beta 32 has a peer dependency on Angular v10. It does not work with Angular v9, and never will.
