### ISSUE TITLE
noticable performance regression on v10

### ISSUE THREAD

**Issue by fxck** [angular/flex-layout#1284]
I noticed pretty a big performance / rendering speed regression after updating everything to v10. It's pretty hard to track down and measure what's actually going on, but after some testing by deleting / commenting everything out, I'm pretty sure the biggest culprit is flex-layout.

Check these two videos (and ignore that creepy slow mo sound) I took in slow motion. There's content with router-outlet on the right side, when card border becomes blue, it's pretty much equivalent of the content actually rendering. "cost" has no content at all and can then be used as control. it takes about 3 seconds for the border to become blue when activating cost.

This video is when components inside the content are using flex-layout https://www.youtube.com/watch?v=dtatRv5USWo, it takes about 8 seconds to activate, between 0:24 - 0:32.

This video when I remove all flex-layout https://www.youtube.com/watch?v=KSLVfz-Pszs, it now takes about 5 seconds, from 0:21 - 0:26. 

It's only 6 items in a flex layout grid with each having 3 components utilising flex layout inside, none has more than 4 `fxFlex`s.

![image](https://user-images.githubusercontent.com/1303561/87588747-72421d00-c6e4-11ea-94b5-c2c9f746860e.png)

And it gets progressively worse the more components using flex layout I add back. This didn't happen when I was using v9.

Anyone else having problem? Any idea how to properly debug it?

**Comment by CaerusKaru** [comment]
@fxck Can you provide a minimal reproduction showing the regression?

**Comment by fxck** [comment]
yeah, I couldn't quite reproduce it, it must be a combination with other parts of my app, I'll investigate further, closing this for now
