### ISSUE TITLE
ObservableMedia is throwing error : Error: ERROR in src/app/app.component.ts:1:10 - error TS2305: Module '"../../node_modules/@angular/flex-layout/flex-layout"' has no exported member 'ObservableMedia'.

### ISSUE THREAD

**Issue by bpskishore** [angular/flex-layout#1286]
Error: ERROR in src/app/app.component.ts:1:10 - error TS2305: Module '"../../node_modules/@angular/flex-layout/flex-layout"' has no exported member 'ObservableMedia'.

1 import { ObservableMedia } from '@angular/flex-layout';

        "tslib": "^2.0.0",       
        "@angular-devkit/build-angular": "~0.1000.0",
        "@angular/cdk": "github:angular/cdk-builds",
        "@angular/cli": "~10.0.0",
        "@angular/compiler-cli": "~10.0.0",
        "@angular/flex-layout": "github:angular/flex-layout-builds",

app.component.ts

import { ObservableMedia } from '@angular/flex-layout';

TS Module Error: [ts] Module '"/FlexLayout/flexApp/node_modules/@angular/flex-layout/flex-layout"' has no exported member 'ObservableMedia'.

**Comment by CaerusKaru** [comment]
ObservableMedia hasn't been on the main branch for a very long time at this point. This is expected behavior. Please use MediaObserver instead.
