### ISSUE TITLE
Using flex-layout attributes like css | Directive

### ISSUE THREAD

**Issue by GlauberF** [angular/flex-layout#1287]
# Feature Request
I need, in a few moments, to be able to define the flex-layout attributes as a class in a project I'm working on, which is a cms.
For that, I'm trying to create a directive that checks if a certain class obeys some rules, if it obeys it turns into attributes.

I was able to assign the attributes, but that doesn't work, because the html has already been rendered and what the flex layout does is to define styles.

**html**
```html (fxHide.xs:true)
<div class="header accent vb-ca fxHide.xs:true" fxLayout="row" fxLayoutAlign="start center">
```

**result**
![Captura de Tela_selecionar área_20200826171202](https://user-images.githubusercontent.com/11314585/91351806-4627ba80-e7bf-11ea-9b49-305891ec0665.png)

**Directive**
```typescript
import {
    AfterViewInit,
    Directive,
    ElementRef,
    OnDestroy,
    Renderer2
} from '@angular/core';
import { Subject } from 'rxjs';

@Directive({
    selector: '.vb-ca'
})
export class VimboClassToAttributeDirective implements AfterViewInit, OnDestroy {
    isCreated: boolean;
    private _unsubscribeAll$: Subject<any>;

    /**
     * Constructor
     * @param {ElementRef} el
     * @param {Renderer2} _renderer
     */
    constructor(
        private el: ElementRef,
        private _renderer: Renderer2
    ) {
        this._unsubscribeAll$ = new Subject();
        // Set the defaults
        this.isCreated = false;
    }

    /**
     * After View Init
     */
    ngAfterViewInit(): void {
        this._classToAttribute();
    }

    /**
     * On Destroy
     */
    ngOnDestroy() {}

    /**
     * Private function class to attribute
     * @private
     */
    private _classToAttribute(): void {
        // Is Server
        if (typeof window === 'undefined') {
            return;
        }

        const el = this.el.nativeElement;

        // ClassList
        el.classList.forEach(value => {
            // Find (:)
            if( String(value)?.indexOf(':') !== -1 ) {

                // here I need to make the directive apply the flex layout attribute

                const _vl = String(value).trim().split(':');
                this._renderer.setAttribute(el, _vl?.[0], _vl?.[1]);
            }
        })
    }
}
```

StackBlitz: https://stackblitz.com/edit/flex-layout-seed-1lf2gd?file=src%2Fapp%2Fvimbo-class-to-attribute.directive.ts

**Obs:** The solution it needs to be performatic, because it will analyze many elements

**Comment by epelc** [comment]
You can bind to the directives ie `[fxHide.xs]="someDynamicVariable"`

**Comment by epelc** [comment]
You can bind to the directive to toggle it instead of a breakpoint. `[fxHide]="someVar"`

You can combine that with another directive or use the breakpoint observer as part of your variable that you toggle.

**Comment by GlauberF** [comment]
@epelc In my case, I really need to transform a "css" to an attribute.
As I mentioned the value / html in string format comes from the database.

So I need a way to create a directive, which looks for this css if it exists and turns it into flex-layout attributes

**Comment by CaerusKaru** [comment]
I don't think this falls under the purview of this project. I'm going to close this issue. We can reopen it if there's a more concrete use case that maybe has broader appeal.

**Comment by GlauberF** [comment]
thank you @CaerusKaru .
is there any way for me to use the attributes as if it were css, example:

```html
<div class="fxHide.xs"></div>
```
or

fxFlex="100%"
```html
<div class="fxFlex.100.p"></div>
```

**Comment by CaerusKaru** [comment]
Not at this time, no.

**Comment by GlauberF** [comment]
exact, so that was the reason for opening this issue.

The user can define this way in the class:
```html
<div class="fxFlex.100.p"></div>
```
and I convert it to a flex-layout directive.
```html
<div fxFlex="100%"></div>
```

if it is something that is not of interest to the library, I would like some idea of how I could achieve this result.
And let it be performance.
