### ISSUE TITLE
fxFlexOrder.gt-md only applies first time

### ISSUE THREAD

**Issue by epelc** [angular/flex-layout#1291]
# Bug Report

#### What is the expected behavior?

The flex order gt-md should apply every time the gt-md breakpoint is activated.

#### What is the current behavior?

It only works the first time. 

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

https://stackblitz.com/edit/flex-layout-seed-y3zkrt?file=src%2Fapp%2Fapp.component.html

start with a small window, make it gt-md width, it will show blue box on left correctly, make the window small again, box goes back to last place(correctly), make window above gt-md again and it remains on the right instead of on the left in the first position with order=-1 applied(the order css property is not applied on the second breakpoint trigger).

#### What is the use-case or motivation for changing an existing behavior?

Positioning a logo before content but after text in html.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 10.0.8

flex layout 10.0.0-beta.32

Chrome 85.0.4183.102 

Firefox 80.0.1

#### Is there anything else we should know?

I tested this on three separate projects(one was freshly created) and stackblitz. Same issue on all.

**Comment by IngoVals** [comment]
I have a similar issue, that might be related.

I have a column span on set on a _greater than sm_ breakpoint. It works fine, but if I reduce to _sm_ and back up again to _md_ the span is lost.

[Here is a stackblitz example](https://grid-column-span-reset.stackblitz.io/)

**Comment by IngoVals** [comment]
Ok it seems this is happening when the default value is not explicitly given. I'm guessing when it switches to a default value the observable subscription is lost or something.

In op's case he could fix the issue by adding `fxFlexOrder="0"`

**Comment by epelc** [comment]
Thanks @IngoVals I will have to try out that workaround. It'd be very helpful! Hopefully a bug fix could just fix this entirely at some point.

**Comment by epelc** [comment]
I did some testing recently and @IngoVals seems to be correct.

Specifically if you have only `fxLayout.gt-md="row"` then it will behave as a row the first time you trigger the gt-md breakpoint but afterwords it enters a stuck layout in column mode. The fix is to also add a default `fxLayout` ie `fxLayout="column" fxLayout.gt-md="row"` together fixes this.


I'm pretty sure this isn't documented. Hopefully the underlying bug could just be fixed but knowing to use a default for `fxLayout` when using breakpoints is also a good workaround.
