### ISSUE TITLE
I would like to get involved with the project

### ISSUE THREAD

**Issue by DuncanFaulkner** [angular/flex-layout#1295]
# Proposal
Help out on the project

#### What is the summary of the proposal?
Initially work on docs or on the demo website (similar to Material)

#### What is the proposal?
To help out on project

#### Is there anything else we should know?
Not sure where to start or how to get involved.

**Comment by CaerusKaru** [comment]
Hey @DuncanFaulkner, thank you so much for your interest! I apologize for taking so long to reply to this thread. If you have something specific you'd like to work on, I'm more than happy to help in any way that I can.

In terms of direction, whatever you want to focus on is fine, but one of the most-requested docs issues is #1026, adding grid docs to the Wiki. If this interests you, the best way to work through it is to cut PRs to the documentation folder in the repo. Once merged, I'll upload them to the Wiki.

If there's anything else you'd like guidance on, please let me know.

Thanks!

**Comment by DuncanFaulkner** [comment]
Hi @CaerusKaru thanks for the reply, I will take a look at #1026 and see if it is something I can help with, also a good opportunity to learn CSS Grid at the same time.

**Comment by DuncanFaulkner** [comment]
Hi @CaerusKaru is there a way to contact you outside of this project? I've tried to connect with on Twitter but you have your DM's off.

**Comment by CaerusKaru** [comment]
Pro tip is you can find people's emails from the commit history for the repo 😄. In this case, it's caerus DOT karu AT gmail DOT com.

**Comment by mackelito** [comment]
So there are docs for grid on it's way? :)
