### ISSUE TITLE
Cannot use FlexLayout

### ISSUE THREAD

**Issue by sjc01234** [angular/flex-layout#130]
Getting a `Uncaught TypeError: ctorParameters.map is not a function` in the console when I run my app. I have `import { FlexLayoutModule } from '@angular/flex-layout'` and `FlexLayoutModule.forRoot()` in the `imports:` in my app.module. 

I'm new enough with Angular(2) that I may have just done something wrong and/or don't know the steps to troubleshoot this problem.  Do I have some dependencies that don't work with this package?  Version of npm or node that won't work?  I couldn't find information about compatibility.

**Comment by d3viant0ne** [comment]
What version of Angular are you trying to use?

This is an error you get when you are trying to import a module compiled with `angular < 2.3.1` into an application running `angular > 2.3.1`.

The change being `ctorParameters` in older versions i an array and a function in newer versions.

**Comment by sjc01234** [comment]
Ah yea. I am on angular 2.4.2 - I didn't see any mention of compatible versions for flex-layout. Did I miss that? Do I have no options here?

**Comment by sjc01234** [comment]
Sorry I take that back. The readme says angular 2.x or higher.  I meet that requirement...

**Comment by ThomasBurleson** [comment]
Are you importing the RxJS `map` operator ?

```js
import 'rxjs/add/operator/map';
``

**Comment by ThomasBurleson** [comment]
This is not a flex-layout issue.
