### ISSUE TITLE
Not working with Angular 11, cdk version 11

### ISSUE THREAD

**Issue by rkchaudhary4** [angular/flex-layout#1303]
The 11 version of angular, @angular/material and @angular/cdk has been released. Flex-layout is not compatible with @angular/cdk ^11.0.0. Kindly update flex-layout to work with it.

**Comment by CaerusKaru** [comment]
We hope to get a new release cut some time this week. Thanks for opening this; I'll post an update when we're published to NPM. Tracking PR is #1307.

**Comment by CaerusKaru** [comment]
https://www.npmjs.com/package/@angular/flex-layout v11.0.0-beta33 has been published.

**Comment by arun-mishra** [comment]
angular material is also not compatible with flex-layout v11.0.0-beta.33.

**Comment by kathemica** [comment]
flex-layout v11.0.0-beta.33 is not working with angular v11.0.2

**Comment by jfoxworth** [comment]
Mine is still not working. This is a pretty big deal for me.

**Comment by snahammond** [comment]
Any updates on this please?

**Comment by jfoxworth** [comment]
I went back down to 10. I was upgrading from 8. For me, there were package conflicts in 11 and it works fine with 10.
