### ISSUE TITLE
fxFlex generates issue with sticky footer in OSX safari

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/flex-layout#1310]
# Bug Report

#### What is the expected behavior?
For fxFlex to create the maximum height in a flex column layout

#### What is the current behavior?
it adds `flex: 1 1  1e-9px` which creates a issue with Safari 14 on OSX (latest). The issue I have manifest it self that my footer is not sticky but actually floats over the content of the bottom of the fold (when you are not scrolling), but the page has scroll space below. So the footer is just floating over content.
When changing the flex to `1 1 100%` the issue disappears.

I am not sure if it because the content that is fxFlexed is loaded with an *ngIf and it is rendered a fraction later which makes Safari confused?

**Comment by CaerusKaru** [comment]
Can you set `useColumnBasisZero` to fix your problem?

**Comment by mattiLeBlanc** [comment]
@CaerusKaru  sorry for immensely late reply, I must have missed this comment.
I ran into the issue again on something and found my original question.

Your suggestion works.

Just to make it more clear for others, import your FlexLayoutModule like this:
```
FlexLayoutModule.withConfig({
      useColumnBasisZero: false,
    }),
```

**Comment by CaerusKaru** [comment]
Closing as resolved.
