### ISSUE TITLE
ngClass.xl not working properly Ubuntu

### ISSUE THREAD

**Issue by gscarva4** [angular/flex-layout#1312]
# Bug Report

#### What is the expected behavior?
To apply ngClass.xl when resolution is Full HD (1920px x 1080px)

#### What is the current behavior?
It is applying ngClass.lg (HD resolution) (1280px x 720px) 

In your [docs](https://github.com/angular/flex-layout/wiki/Responsive-API)
> lg: 'screen and (min-width: 1280px) and (max-width: 1919px)'
> xl: 'screen and (min-width: 1920px) and (max-width: 5000px)'

#### What are the steps to reproduce?
Using Ubuntu 20.04, Google Chrome, open: https://angular-ivy-j9ywh2.stackblitz.io/
Try opening on Full HD screen and HD screen. 

https://stackblitz.com/edit/angular-ivy-j9ywh2?file=src/app/app.component.html

**Result expected**:
When full HD resolution, the result is red.
When HD resolution, the result is blue.

**Received results**: 
When full HD resolution, the result is blue.
When HD resolution, the result is blue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Created with @angular/cli@8.3.29
Using flexLayout ^8.0.0-beta.27
Google Chrome: 86.0.4240.111

#### Is there anything else we should know?
It works with Mac OS.
It worked when seeing with Chrome Dev Tools > Settings > Emulated Device and creating a Mobile view with Full HD resolution
![image](https://user-images.githubusercontent.com/67905341/100633354-c0ab2d80-330c-11eb-94ef-e5742fa9fa38.png)

**Comment by CaerusKaru** [comment]
We don't support any version except the current version. Can you try upgrading and see if the issue persists?

**Comment by CaerusKaru** [comment]
Closing as stale for almost a year now.
