### ISSUE TITLE
why forever in beta ?

### ISSUE THREAD

**Issue by jagdishjadeja** [angular/flex-layout#1315]
why is flex-layout in beta from inital ?
is it ever going to be available for production ? 
or is it enforcing to use core CSS ?

**Comment by DuncanFaulkner** [comment]
Hi @jagdishjadeja 

1) duplicate #1300 #824 #835 #752 #1051, @CaerusKaru did write a full explanation of Googles reasons of why this is in perpetual beta (but I can't find it at the moment @CaerusKaru you have a copy to hand?). 

2) This is a stable product (I use it in a production application) and it is widely used by many other developers in production applications.

3) Not sure I fully understand your question but... Flex-layout uses directives to write out CSS - that's based on Flex-box, it is also possible to use Flex-layout to write CSS Grid style CSS.

**Comment by CaerusKaru** [comment]
Duplicate of #835
