### ISSUE TITLE
error NG2006: The directive DefaultLayoutDirective inherits its constructor from LayoutDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of LayoutDirective's constructor. Either add a @Directive decorator to LayoutDirective, or add an explicit constructor to DefaultLayoutDirective.

### ISSUE THREAD

**Issue by satish10105** [angular/flex-layout#1322]
I try to upgrade  angular 8.2 to 9.1
am facing the following issue 

The directive DefaultLayoutAlignDirective inherits its constructor from LayoutAlignDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of LayoutAlignDirective's constructor. Either add a @Directive decorator to 
LayoutAlignDirective, or add an explicit constructor to DefaultLayoutAlignDirective.

![image](https://user-images.githubusercontent.com/31982941/108039076-a3f7d980-7061-11eb-9f6f-6b7b7e6a1625.png)

**Comment by CaerusKaru** [comment]
Sorry, but we don't support anything but the current version of this library. Please try upgrading if you can, and open a new issue if the problem persists. Otherwise, you can turn to Gitter or StackOverflow for further support.
