### ISSUE TITLE
flex-layout angular cdk`/ material incompatiblity

### ISSUE THREAD

**Issue by pitrackster** [angular/flex-layout#1326]
# Bug Report

#### What is the expected behavior?
I would expect to be able to use the latest version of angular cdk alongside  angular-material and angular flex-layout

#### What is the current behavior?
```bash
 Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/cdk" (requires "^10.0.0-rc.0", would install "11.2.6").
```

#### What are the steps to reproduce?
- update angular `ng update @angular/core @angular/cli`
- update angular cdk and angular material to  latest versions (i.e. 11.2.6)
```json
"dependencies": {
    "@angular/cdk": "^11.2.6",
    "@angular/flex-layout": "11.0.0-beta.33",
    "@angular/material": "^11.2.6",
....
```
- run `ng update ng update @angular/flex-layout `

#### What is the use-case or motivation for changing an existing behavior?
Just ti be able to use latest features of angular framework ;-)

#### Is there anything else we should know?
well thanks for the work anyway !

**Comment by bsparacino** [comment]
I just ran into this issue as well.
I delete the  "@angular/flex-layout" line from my package.json file, ran ng update, then added back the line:
"@angular/flex-layout": "^10.0.0-beta.32"

I'm not sure if there is a more recent version than that, but so far my application appears to be working fine.
