### ISSUE TITLE
FxFlex Calc sets min-height, while raw value sets max-height

### ISSUE THREAD

**Issue by gregz07** [angular/flex-layout#1327]
```
<div fxFill fxLayout="column">
    <div fxFlex="8" fxLayout="column"> Fixed Header </div>
    <div fxFlex="20" fxLayout="row" [fxHide]="isShow"> Colapsable Header </div>
    <div fxFlex="72" fxLayout="column"> Page content </div>
</div>
```

Like this, if I hide the header, 20% of the page remains blank, cause the div containing the pagecontent occupies still only 72%
But if I use the with calc <div fxFlex="calc(92% - 20%)">, this respective div modifies her height depending if the above div is hidden or shown, so there's never a blank space even if the div gets collapsed..

After observing the generated Html I've gathered that

```
fxFlex="72" sets a max-height="72%"
fxFlex="calc(92%-20%)" sets min-height="72%"
```

Why does it work like this ? calc(92% - 20%) its always 72%, so why does it behave differently ?

**Comment by CaerusKaru** [comment]
Historical reasons. You can see more information based on [the comment in source](https://github.com/angular/flex-layout/blob/master/projects/libs/flex-layout/flex/flex/flex.ts#L151-L155). Feel free to look through those issues for more context.
