### ISSUE TITLE
Custom breakpoints with custom names does not work

### ISSUE THREAD

**Issue by Magmaruss** [angular/flex-layout#1329]
# Bug Report

#### What is the expected behavior?
Specifying any number of breakpoints with any names which will be respected by fx-layout.
#### What is the current behavior?
Only the overwritten breakpoints work.
#### What are the steps to reproduce?
Simple reproduction: https://stackblitz.com/edit/angular-ivy-jrhcyq?file=src%2Fapp%2Fbreakpoints.ts
#### What is the use-case or motivation for changing an existing behavior?
Existence of ultra-wide monitors, where forms and grid elements is too wide for user and it looks unsightly. The developer should be able to handle an unlimited amount of resolutions.
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions.
#### Is there anything else we should know?
Nothing.

**Comment by CaerusKaru** [comment]
You need to follow the custom breakpoints doc on the Wiki and actually implement the new breakpoint components. Angular does not allow arbitrary extension using a Map syntax. We get around this by actually declaring the directive syntax for every single breakpoint. There is currently no other way. Closing as working as expected.
