### ISSUE TITLE
GitHub Claims 10 is the latest version and NpmJs Claims its 11

### ISSUE THREAD

**Issue by jamesg-gxg** [angular/flex-layout#1338]
# Bug Report

#### What is the expected behavior?
GitHub to have latest V11 code

#### What is the current behavior?
GitHub Shows v10 being the latest release

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://stackblitz.com/edit/flex-layout-seed-nightly) using latest `npm` nightly release: 
Commit 11?

#### What is the use-case or motivation for changing an existing behavior?
Seeing the code in v11

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 11

**Comment by CaerusKaru** [comment]
Added, thanks!

**Comment by jamesg-gxg** [comment]
> Added, thanks!

Awesome!
