### ISSUE TITLE
Directive not applied on Angular 11

### ISSUE THREAD

**Issue by mmazloum** [angular/flex-layout#1339]
# Bug Report
It seems flexlayout doesn't work on Angular 11, flex version beta33 and cdk 11.2.8. Any pattern I've been used to is not applied. And no error is thrown in the console. ex :
`<div fxLayout="row wrap" fxLayoutAlign="space-around center" fxLayoutGap="15px grid">
<div fxFlex="calc(50% -15px)">
...
</div>
<div fxFlex="calc(50% -15px)">
...
</div>
</div>`
#### What is the expected behavior?
I should find my 2 components displayed side by side on the same row, and they are not, not css has been added to the page through flex directives

#### What is the current behavior?
My components are not side by side, no flex css is injected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 11.2.9
cdk 11.2.8
flex 11 beta33

**Comment by CaerusKaru** [comment]
There is no reproduction included here, can you please provide one?

**Comment by mmazloum** [comment]
Sorry i didn't see my source sample was empty, Here you go : 
https://angular-ivy-u2snzo.stackblitz.io

**Comment by mmazloum** [comment]
Sorry I had a mistake in my code, I close
