### ISSUE TITLE
better way of handling gap/gutter

### ISSUE THREAD

**Issue by fxck** [angular/flex-layout#134]
Currently when you want to have a grid of items with gutter between them, this happens https://plnkr.co/edit/eEWOqBJA4rq0PFKl1XyT?p=preview (unless there's some different hidden way of doing gaps other than the obvious `fxLayoutGap`.. I swear I've seen some `calc` example somewhere, but can't find it again).. 

![image](https://cloud.githubusercontent.com/assets/1303561/22315131/27aadf04-e365-11e6-8951-4665b1397598.png)

but ideally you'd want 4 items(25% each) in a row like this
![image](https://cloud.githubusercontent.com/assets/1303561/22315224/b9bdfcdc-e365-11e6-9226-1008478d8352.png)

There's a simple method for this which has been used for grid systems all over the place(and works fine with flex as well) and that is using negative margin on the container and padding on items(see https://plnkr.co/edit/ZhNvWutftQ1qRMO6cHzZ?p=preview) 

the only real downside is that you have to use `fxFlex` elements only as a "container" for your content(ie. you can't add background or horizontal paddings to them)... but it's much more performant than say calc and much more usable than the way `fxLayoutGap` currently works. Could it perhaps be added as a new attribute, say `fxLayoutGutter`?

**Comment by ThomasBurleson** [comment]
See our JSFiddle Grid example here:  https://tburleson-layouts-demos.firebaseapp.com/#/stackoverflow that shows how to achieve cell-aligned layouts.

**Comment by fxck** [comment]
@ThomasBurleson oh yes, that's the calc example I was looking for. But anyway, I have a couple of "problems" with that.

- it feels a little bit hacky and counterintuitive from api standpoint
    - not using `fxLayout`
    - not using `fxLayoutGap` which to me, as an user, feel like a very obvious thing to do when I want a gap, especially given that it does some sort of manually setting or margin depending on the position of the element
    - there seems to be a lot of manual "work" in css required https://github.com/angular/flex-layout/blob/master/src/demo-app/app/stack-overflow/columnSpan.demo.css#L35-L48 
- that gap is defined on two places(in css and then in `fxFlex`), so it's gonna be harder to control
- it's using calc, which I'd like to avoid if possible, maybe it's not that much of a problem nowadays, but it used to have performance problems at reflows 


wouldn't this https://plnkr.co/edit/ZhNvWutftQ1qRMO6cHzZ?p=preview be worth considering adding as an option? I could try and make a PR..

**Comment by fxck** [comment]
@ThomasBurleson here's a rough idea of how it could work https://github.com/fxck/flex-layout/commit/1fd4881ff8ea1828fc6a61aeaeff54d3101de7ed I think it only makes sense for row/row-reverse direction, so it should probably be turned off or not turned on at all when the direction is anything other than those.. and then there's the little disadvantage that you can't really put much styling on neither fxLayout element not fxFlex elements(border, backgrounds), but that's easily fixable by putting those to child elements(as shown in demo).. but I think the payoff is still there, it's much more straightforward and easier to use than those calcs.

**Comment by MystK** [comment]
I'm running into this issue also.

Using flex-layout, I assumed that I wouldn't need to use flex css.

I was under the assume that fsLayoutGap would achieve this "grid" layout when I set fxLayoutWrap to wrap.

Unfortunately, it only adds margins to the right when fxLayout is row or bottom when fxLayout is column.

Is there any timeline to add this feature to flex-layout or is the recommended solution to combine vanilla css and flex-layout?

**Comment by fxck** [comment]
@ThomasBurleson can we talk about this? I'm up for trying to implement this, but I feel you are still not quite on board with the idea itself

**Comment by miguelcaravantes** [comment]
my solution is this

.gap
{
    margin-right: -15px;
    margin-left: -15px;
}

.gap > *
{
    padding-right: 15px;
    padding-left: 15px;
}

/* if use material 2 components */
.gap .mat-input-underline
{
    width: calc(100% - 30px);
}

**Comment by niwrA** [comment]
I also came here because I was surprised that fxLayoutGap only considered left-right, not up-down gaps ...

**Comment by mackelito** [comment]
@ThomasBurleson will this get some love and attention any time soon?

**Comment by ChristianLieven** [comment]
I've found myself running into the same issues, and it has been about a month now so I'm giving this another friendly bump.

**Comment by stellasoft-will** [comment]
not sure if anyone has considered this 

`<div fxLayout="row" fxLayoutAlign="start" fxLayoutGap="20px" fxLayoutWrap>
       <div [ngStyle.gt-sm]="{'max-width': 'calc(25% - 20px)'}" fxFlex="calc(25% -20px)"></div>
  </div>
`

managed to get this to work for me, by using their upgraded ngStyle attribute i can still use the break points while also maintaining the layout i want. example above would be 4 column grid at gt-sm sizes but gt-sm can be replaced as suits.

**Comment by simeyla** [comment]
How do I see the source code for any of these demos? Honestly this project has some of the worst documentation I've seen in a long time - and isn't this an official Google project? It's very frustrating just trying to get up and running. Most API links all go to the same place and they all assume you're already a flex-box expert. It's like sending someone to read the W3C docs in order to learn HTML. Would love just a big long page with a tonne of examples that build on each other. 

What's the point of a demo page if I can't get easy access to the source. Trying to view the DOM isn't especially helpful 
https://tburleson-layouts-demos.firebaseapp.com/#/stackoverflow

**Comment by CaerusKaru** [comment]
@simeyla You are correct, documentation is a sore spot right now for the library, but we are making strides in improving it, especially with #520 and #540, each of which should see movement in the coming week. Please also note that Flex Layout is not as much of a priority as the main Angular repository, for obvious reasons, but that does not mean that we're not still actively working to improve it.

Speaking of the demo-app, the src lives in... [src/demo-app](https://github.com/angular/flex-layout/tree/master/src/demo-app)! This is conveniently located both in the README underneath `Explore Online` as `Source Code` and under the `Live Online` link in the sidebar on the Wiki as `Source Code`.

Finally, PRs are always welcome to improve both the demo-app and any other part of the documentation (which will admittedly be easier after #520 lands). There are also [tutorials](https://alligator.io/angular/flex-layout/) [available](http://www.dzurico.com/angular-flex-layout/) for Flex Layout, [and](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) [even](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) [more](https://internetingishard.com/html-and-css/flexbox/) [for](https://www.w3schools.com/css/css3_flexbox.asp) Flexbox. StackOverflow is also available as a resource for any issues you may come up with.

**Comment by simeyla** [comment]
I'm finding the following works quite well for most cases I've come across so far, especially with flex-wrap enabled. You don't use a `fxLayoutGap`, but just set css. 

```
.container {
   margin: -5px;
}
.container > * {
   margin: 5px;
}
```

I know that negative margins can be dangerous but this is certainly simpler than some other ways.

Remember that for flex layouts margin's don't collapse. This is to give a 10 pixel gutter and to cancel it out on the container.

**Comment by nosliwsirhc** [comment]
Could we bind the gap to a media query in TS?

**Comment by CaerusKaru** [comment]
I've submitted a preliminary PR for this, please see #667. If any of you have comments on that solution, we'd welcome them on that PR.

**Comment by nzbin** [comment]
I'm also think `fxLayoutGutter` is a good idea. It's perfect than `fxLayoutGap`.
