### ISSUE TITLE
Bump to angular 12

### ISSUE THREAD

**Issue by princemaple** [angular/flex-layout#1343]
Please release a new version that supports angular 12.

**Comment by qortex** [comment]
Blocking my update atm. Hope the release can happen soon.

**Comment by princemaple** [comment]
@qortex I used the forbidden --force flag. 😄

**Comment by qortex** [comment]
> @qortex I used the forbidden --force flag. 😄 

I'm too scared 😅

**Comment by dopsun** [comment]
Upgrade core to 12 and leave CDK and Material to 11, so far works for me.

**Comment by princemaple** [comment]
I have everything on 12 just flex-layout lagging behind.

**Comment by CaerusKaru** [comment]
Tracking in https://github.com/angular/flex-layout/pull/1344. Ideally will merge and publish tomorrow.

**Comment by ianvink** [comment]
Thank you so much for your hard work and service to the community @CaerusKaru 

A truly wonderful project.

**Comment by CaerusKaru** [comment]
Released to NPM: https://www.npmjs.com/package/@angular/flex-layout/v/12.0.0-beta.34
