### ISSUE TITLE
Font size doesn't change row height when fxLayout="column" and using Angular Material typography

### ISSUE THREAD

**Issue by Gimly** [angular/flex-layout#1347]
# Bug Report

I'm havig an issue when using flex layout with Angular Material, specifically angular material where the "global Angular Material typography styles" have been set.

I am setting a specific font size for texts that is displayed in rows and the rows' heights are not correctly calculated. They behave as if they had a standard font size instead of the bigger size.

More precisely, I have a project setup with Angular Material and the body has the "mat-typography" class.

```html
<body class="mat-typography">
  <my-app></my-app>
</body>
```

In an angular component's html I have the following layout:

```html
  <div fxLayout="row">
    <div fxLayout="column">
      <div>Hello</div>
      <div class="large">World</div>
    </div>

    <div fxFlex fxLayout="column">
      <div>Hello</div>
      <div class="large">World</div>
    </div>
  </div>
```

and css:
```css
.large {
  font-size: 4em;
}
```
#### What is the expected behavior?

We should have two "Hello World" text in two columns with a small hello and a big world, the text should not overflow.

Something like that:
![image](https://user-images.githubusercontent.com/168669/120481354-52751f80-c3b0-11eb-882d-770ac98d021e.png)

#### What is the current behavior?

World ends up being written on top of hello:

![image](https://user-images.githubusercontent.com/168669/120481510-76386580-c3b0-11eb-9f58-61531644e50a.png)

#### What are the steps to reproduce?

Here's a StackBlitz link for the issue:
https://stackblitz.com/edit/angular-ivy-omaraf

#### What is the use-case or motivation for changing an existing behavior?

We should be able to use Flex layout with Angular Material global typography configured.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I could reproduce with 11, seemingly on all browsers.

**Comment by CaerusKaru** [comment]
I may be a little ignorant here, but how is this an issue with Angular Layout? As far as I can tell, this is an issue with how you use the components, not the components themselves.

If you have a specific feature request or bug report (including specific CSS styles that should be there but aren't, or are incorrect), please list it here, otherwise I'm going to close this as not broken.

**Comment by mackelito** [comment]
@Gimly I'm no css guru but if you add like `line-height: 1em` it will solve you issue..
https://stackblitz.com/edit/angular-ivy-myng1c?file=src%2Fapp%2Fapp.component.css

**Comment by Gimly** [comment]
@CaerusKaru I'm not 100% sure that this is an issue with FlexLayout, but I'm surprised by the behavior.

Basically, if I don't use Angular Material's typography (if in index.html you remove the `mat-typography` class) it works correctly without having to define the `line-height`.

If I add the `mat-typography` class in the body, then it behaves as if the font isn't took into consideration for the calculation of the line height, which mandates what @mackelito suggests, adding a line-height.

It's this change in behavior that surprises me, and made me think of a bug, why does the behavior change between having the mat-typography and not?

**Comment by mackelito** [comment]
@Gimly I would suggest you post this in the Materials/Angular Component repo and not flex-layout .. this has nothing to do with this lib... :)

**Comment by Gimly** [comment]
@mackelito OK, fair enough, I'll have to check if I can reproduce something similar removing this library from the equation...
