### ISSUE TITLE
fxLayoutGap defaults in config

### ISSUE THREAD

**Issue by worthy7** [angular/flex-layout#1349]
# Feature Request

#### What is the desired behavior?
Allow a config parameter to set the default fxLayouGap

#### What is the use-case or motivation for the desired behavior?
I want to standardize this accross my app, without having to write it everywhere.

**Comment by CaerusKaru** [comment]
Please use [Style Builders](https://github.com/angular/flex-layout/wiki/Style-Builders) for this.
