### ISSUE TITLE
Layout with fxFlex="auto" not restoring max-height values properly

### ISSUE THREAD

**Issue by TylerDev6** [angular/flex-layout#135]
**on page load** scans breakpoint overlaps too aggressively [and matches the smallest instead of the largest matching].

```html
<div fxFlex="auto" fxFlex.gt-xs="33%" fxFlex.gt-sm="50%"></div>
```

I'm using fxFlex with 3 breakpoints and IE seems to only pick the first one it passes:

**on page load**, in spite of gt-sm qualifying, it defaults to the gt-xs value. However if I manually re-size the browser it will correct itself. This happens in IE11 only.

**Comment by ThomasBurleson** [comment]
Need a plunked plz

**Comment by TylerDev6** [comment]
Do you have an existing plunkr I can start from?

**Comment by TylerDev6** [comment]
I've also found that it happens outside of IE now too

**Comment by ThomasBurleson** [comment]
@TylerDev6 - please update with Beta.4 (from npm) and see if the problem persists.

**Comment by ThomasBurleson** [comment]
@TylerDev6 - Try this Starter Plunkr: https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview

**Comment by TylerDev6** [comment]
https://plnkr.co/edit/o6zKj8?p=preview

Thanks for the help. Here's a plunk showing the problem.... I noticed a few things:

1. It is also reproducible in Chrome / Firefox.
2. It didn't start happening until I added fxLayoutGap properties.

Essentially, on initial page load the widths are being set to 33-33-33, instead of 50-23.4-23.4. Manually resizing the window will correct it.

**Comment by TylerDev6** [comment]
I am also noticing now that going from a % based fxFlex to fxFlex="auto" does not remove the % restriction.

**Comment by ThomasBurleson** [comment]
If you are using the code from HEAD, you should see this:

https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/flex.ts#L264

which means the applied inline style should be `flex: 1 1 auto`.

**Comment by TylerDev6** [comment]
so I should check out @latest? I'm running beta.4 at the moment

**Comment by TylerDev6** [comment]
and what's going is as follows:

fxFlex.gt-sm=33% will apply a max-width: 33% in addition to the flex 1 1 100% style.....
fxFlex="auto" will switch to flex 1 1 auto, but the max-width: 33% remains.

**Comment by ThomasBurleson** [comment]
@TylerDev6 - please file distinct issues separately.

**Comment by ThomasBurleson** [comment]
This is working well with the latest code in master: [Plunkr Demo](https://plnkr.co/edit/6gDUkq?p=preview)

-XS-
![screen shot 2017-02-09 at 2 08 12 pm](https://cloud.githubusercontent.com/assets/210413/22801132/4d52bad4-eed1-11e6-8d8a-cecff662dbb2.png)

-SM-
![screen shot 2017-02-09 at 2 07 47 pm](https://cloud.githubusercontent.com/assets/210413/22801148/5939999e-eed1-11e6-9e04-dce1cc517087.png)

-MD-
![screen shot 2017-02-09 at 2 08 12 pm](https://cloud.githubusercontent.com/assets/210413/22801153/5ed96532-eed1-11e6-8e4d-68379b1347be.png)

**Comment by TylerDev6** [comment]
I can still break your plunk.... expand to largest viewport, then refresh.... it's only on initial load of the page that it breaks.

**Comment by TylerDev6** [comment]
and the "active media query" field in your plunk lists the wrong one. So I guess that's where the problem lies.

**Comment by ThomasBurleson** [comment]
Reopening as valid issue. Thx @TylerDev6

**Comment by TylerDev6** [comment]
Cool. Thanks @ThomasBurleson for your work on this library. It's fantastic.

**Comment by ThomasBurleson** [comment]
![fix_135](https://cloud.githubusercontent.com/assets/210413/22961268/5f0ded74-f30a-11e6-95fa-29673fed5696.png)


Fixed with #183

**Comment by ThomasBurleson** [comment]
@TylerDev6 - When one or more mediaQueries activate (which may happen when the current viewport size is in the range of 1 or more mediaQuery ranges),  the `ObservableMedia` will report each... and perhaps the UI only shows the last one to arrive. 

Based on current code in HEAD, what specifically is the issue you are reporting ?

**Comment by TylerDev6** [comment]
So when testing with the Plunk, I see that the ObservableMedia is accurately reporting the correct media query now, however the UI is still displaying the first matching result.

**Comment by ThomasBurleson** [comment]
@TylerDev6 - Thank you.. we will investigate.

**Comment by TylerDev6** [comment]
basically, <fxFlex="auto" fxFlex.gt-sm="33%" fxFlex.gt-md="50%" is choosing 33% even though gt-md qualifies.... only on initial page load.

**Comment by ThomasBurleson** [comment]
@TylerDev6 - please file a separate issue for this ^.

**Comment by ThomasBurleson** [comment]
Closing as fixed.
