### ISSUE TITLE
Allow rxjs 7

### ISSUE THREAD

**Issue by princemaple** [angular/flex-layout#1358]
Please update this repo to match with core and components to allow rxjs 7. Thanks!

**Comment by DuncanFaulkner** [comment]
I believe rxjs v7 will be in the next release of Angular (v13) and as flex-layout is kept inline with angular it will probably also appear in version 13.

**Comment by princemaple** [comment]
Yeah rxjs 7 will probably be the default for 13, but it's already allowed in 12.2. It's still pinned at 6 in this repo, not in sync with the core.
