### ISSUE TITLE
fxLayoutGap should consider hidden elements

### ISSUE THREAD

**Issue by myrddraall** [angular/flex-layout#136]
When an item in a layout is hidden (usually conditionally) then fxLayoutGap should not apply a gap to the first displayed element

```html
<style>
   .col1{
    display:none !important;
  }
</style>
<div class="container" fxLayout="row" fxLayoutGap="16px">
  <div fxFlex class="col1">Div 1</div>
  <div fxFlex class="col2">Div 2</div>
  <div fxFlex class="col3">Div 3</div>
</div>
```

In this example `Div 2` should not have a gap in front of it.

**Comment by therafi** [comment]
Part of this issue is still present with this in 2.0.0-beta.9
If there is a conditional fxHide on Div 3 (from the example), when Div 3 is hidden, then Div 2's margin-right (correponding to fxLayoutGap) should collapse.

**Comment by darkbasic** [comment]
> if the page loads as small, then we expand, there will be no gap between 2 and 3. If the page loads as big, then we shrink it, there will be an excess gap after 2.

I confirm, please reopen.

**Comment by CaerusKaru** [comment]
@darkbasic This is being considered as part of #606 and will not be reopened separately

**Comment by darkbasic** [comment]
No need to reopen if it's tracked somewhere else. Thanks.
