### ISSUE TITLE
Layout of the Application gets distorted/broken when press Ctrl + P

### ISSUE THREAD

**Issue by Muazzam001** [angular/flex-layout#1363]
# Bug Report

#### What is the expected behavior?
The expected behavior should be like as the page is designed. & Only the print preview should not have the layout queries of Flex.

#### What is the current behavior?

When press Ctrl + P, the distorted page comes out with preview screen, 

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://stackblitz.com/edit/flex-layout-seed-nightly) using latest `npm` nightly release: 

Any page created with Flex Layout, When press Ctrl + P, the distorted page comes out with preview screen, 
Upon cancelling the print preview screen, the distorted page remain as is unless you refresh the page.

#### What is the use-case or motivation for changing an existing behavior?
Not much but at least it should not make the designed page distorted. Only this distorted issue should be resolved on the least.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 12, 
Material IO 12.2.3,
Windows 10,
Typescript: 4.2.4,
Browsers: Firefox 92.0, Chrome 93.0.4577.63, Opera 78

#### Actual Screenshots
![Screenshot_7](https://user-images.githubusercontent.com/24399579/133116203-dcf32d8f-d159-48e1-b714-dfaebb3c7d64.png)
![Screenshot_8](https://user-images.githubusercontent.com/24399579/133116218-0249fa83-69f4-47a9-bc7e-64448bfc6618.png)

#### Distorted Screenshots
**_Firefox_**
![Screenshot_5](https://user-images.githubusercontent.com/24399579/133116339-a4a81f6b-de05-4fa8-b826-537c53b39a9e.png)
![Screenshot_6](https://user-images.githubusercontent.com/24399579/133116346-dcf8a9e4-cc4c-4bc0-9cfa-fe49974f8493.png)

**_Chrome_**
![Screenshot_2](https://user-images.githubusercontent.com/24399579/133116399-92d85847-0dfd-4616-9956-64643a93ae9e.png)
![Screenshot_3](https://user-images.githubusercontent.com/24399579/133116408-5064b8ee-7e9a-476e-b0f9-3174c74ea61c.png)
![Screenshot_4](https://user-images.githubusercontent.com/24399579/133116413-ede3b9cd-fe94-4f10-b882-7bcee028c1e2.png)

#### Is there anything else we should know?
N A

**Comment by kek-Sec** [comment]
stackblitz is not setup correctly

**Comment by CaerusKaru** [comment]
If you would like to configure this manually, the library supports doing so via config [here](https://github.com/angular/flex-layout/blob/master/src/lib/core/tokens/library-config.ts#L30). The intention is that when you print, you should have a consistent breakpoint, otherwise the browser behavior is inconsistent at best. Figuring out one breakpoint format for print is recommended best practice when dealing with media-query. By default, this library assumes `md` for print size.
