### ISSUE TITLE
Dependency on rxjs 

### ISSUE THREAD

**Issue by samdevx1029** [angular/flex-layout#137]
I tried to update all packages in an angular2 app with npm update and I got the following warning.

    `@angular/flex-layout@2.0.0-beta.3 requires a peer of rxjs@5.0.0-rc.4 but none was installed.`

However, rxjs is already on 5.0.3, angular is on 2.4.5. 

Is it reasonable to expect flex-layout to work with rxjs@5.0.3 despite the warning?

**Comment by d3viant0ne** [comment]
Yes, there aren't any major ( non backwards compatible ) changes in rxjs from rc.4 to 5.0.3 that would prevent flex-layout from working properly.

**Comment by ThomasBurleson** [comment]
Peer dependencies are improved with Beta4.
