### ISSUE TITLE
13.0.0-beta.37 release broken build related to importing rxjs distinctUntilChanged operator

### ISSUE THREAD

**Issue by tkutcher** [angular/flex-layout#1392]
# Bug Report

There is an issue when using the `13.0.0-beta.37` version that has some sort of broken module with rxjs and not seeing the  distinctUntilChanged operator - project `ng build` is failing but succeeds if rolling back to `13.0.0-beta.36`

#### What is the expected behavior?

ng build succeeds

#### What is the current behavior?

ng build fails with message:

```
./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout-core.mjs:2582:229-249 - Error: export 
'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: 
ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, 
GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, 
Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, 
animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, 
combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, 
isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, 
range, scheduled, throwError, timer, using, zip)
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Project is on angular 13.2, rxjs `~6.6.0`, typescript `~4.5.5`

#### Is there anything else we should know?

Googled the issue I was facing and came across this  post with similar issue https://stackoverflow.com/questions/70972097/how-to-import-angular-flex-layout-properly - I looked and did not find an issue for this in this repository yet.

**Comment by CaerusKaru** [comment]
beta.38 has been released to address this. Apologies for the disruption.
