### ISSUE TITLE
fxHide / fxShow ignores breakpoint aliases

### ISSUE THREAD

**Issue by phil294** [angular/flex-layout#140]
Tried in both FF & Chrome.
The following span is always hidden, although it should be shown when 'screen and (min-width: 960px) and (max-width: 1279px)'.

    <span fxHide fxShow.gt-xs>Text</span>

Another example:

    		<span fxHide.lg>text</span>

Never hides.

**Comment by ThomasBurleson** [comment]
Fixed in PR #143
