### ISSUE TITLE
Support for Angular14

### ISSUE THREAD

**Issue by eskinderg** [angular/flex-layout#1407]
Any plans on supporting Angular 14 ?

Run npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/flex-layout@13.0.0-beta.38
npm ERR! Found: @angular/cdk@1[4](https://github.com/eskinderg/eskinderg.github.io/runs/6849186553?check_suite_focus=true#step:4:5).0.0
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^14.0.0" from the root project
npm ERR!   peer @angular/cdk@"14.0.0" from @angular/material@14.0.0
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^13.0.0" from @angular/flex-layout@13.0.0-beta.38
npm ERR! node_modules/@angular/flex-layout
npm ERR!   @angular/flex-layout@"^13.0.0-beta.38" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/cdk@13.3.9
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"^13.0.0" from @angular/flex-layout@13.0.0-beta.38
npm ERR!   node_modules/@angular/flex-layout
npm ERR!     @angular/flex-layout@"^13.0.0-beta.38" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-12T10_03_[5](https://github.com/eskinderg/eskinderg.github.io/runs/6849186553?check_suite_focus=true#step:4:6)3_[9](https://github.com/eskinderg/eskinderg.github.io/runs/6849186553?check_suite_focus=true#step:4:10)01Z-debug-0.log
Error: Process completed with exit code 1.

**Comment by KhizerRehan** [comment]
Same Error CI pipeline and local `npm` installation fails.

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/flex-layout@13.0.0-beta.38
npm ERR! Found: @angular/cdk@14.0.0
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"14.0.0" from the root project
npm ERR!   peer @angular/cdk@"14.0.0" from @angular/material@14.0.0

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^13.0.0" from @angular/flex-layout@13.0.0-beta.38
npm ERR! node_modules/@angular/flex-layout
npm ERR!   @angular/flex-layout@"13.0.0-beta.38" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/cdk@13.3.9
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"^13.0.0" from @angular/flex-layout@13.0.0-beta.38
npm ERR!   node_modules/@angular/flex-layout
npm ERR!     @angular/flex-layout@"13.0.0-beta.38" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-15T07_09_4
```

**Comment by Acdesignart** [comment]
angular flex-layout 14.0.0-beta.39 🧶 😒

**Comment by eskinderg** [comment]
@Acdesignart thanks for the info. Looks like angular flex-layout 14 is in development and is due in early July.
