### ISSUE TITLE
How outdated are the DOCS?

### ISSUE THREAD

**Issue by mcwebdev** [angular/flex-layout#1421]
Its been awhile since I've visited the docs section but to be frank, it's quite disappointing. I can't even imagine the level of frustration a new developer would run into, take for example this image.

https://cloud.githubusercontent.com/assets/210413/24045169/247bad3c-0aec-11e7-827a-6ece0775ff39.jpg

When was the last time `[fx-flex]` was used? 1, 2, 3, or was it like 6 years ago? If it's going to be half-assed and wasting a ton of folks time, perhaps it's time to can this project?

**Comment by CaerusKaru** [comment]
I understand the point you're trying to make, but please realize this is entirely the wrong way to go about this. If you have issues with a doc in particular, you have two choices that would actually be helpful: 1) you can submit a PR to correct the doc in question; or 2) you can identify the issue specifically so we may correct the docs on your behalf.

While docs may become out of date, that does not mean that they do not work or are not helpful as a whole, nor is it an indictment of a project. I would ask you to find a project with docs 100% up to date, and while I'm waiting well into the next century for that, plenty of users will come to this project and use it without issue, either using the existing docs, or any number of guides written by our wonderful community.

What I will not oblige is negativity. A lot of work goes into maintaining projects like this, and without funding from Google it is entirely community-driven. So please, don't disparage the collective effort of others if you yourself are not willing to at least contribute back.
