### ISSUE TITLE
Demo code link borken, demo page outdated 

### ISSUE THREAD

**Issue by KissBalazs** [angular/flex-layout#1428]
# Bug Report

#### What is the expected behavior?
The [Demo Source Code](https://github.com/angular/flex-layout/blob/master/src/apps/demo-app/src/app/app.module.ts) should be linked to the demo source code. It's mentioned in the [Readme.md](https://github.com/angular/flex-layout/blob/master/README.md#demos) file.

Also, the Demo link (at the same place) (https://tburleson-layouts-demos.firebaseapp.com/#/docs) points to a place which shows the following:
"
Layout Demos:
Version: 7.0.0-beta.23
These Layout demos are curated from the AngularJS Material documentation, GitHub Issues, StackOverflow, and CodePen.
"
I think the current version is different, and it's not "AngularJS Material", as it's not for the https://material.angularjs.org/latest/ unsupported project anymore. 

#### What is the current behavior?
[Demo Source Code](https://github.com/angular/flex-layout/blob/master/src/apps/demo-app/src/app/app.module.ts) shows a 404 error. 

#### What are the steps to reproduce?
Click on the links.

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
-

#### Is there anything else we should know?
-

**Comment by CaerusKaru** [comment]
Unfortunately we won't be addressing this as the library goes into LTS. Thank you for raising this issue though.
