### ISSUE TITLE
Status angular 15

### ISSUE THREAD

**Issue by ajtowf** [angular/flex-layout#1432]
Could we get an update ? 

Existing issue regarding status and PR has closed down comments and several "end of week", "early next week" estimates are overdue.

Is this repo already abandoned by the team?

**Comment by wernert75** [comment]
I´m also waiting for the new version with Angular 15 support.

**Comment by ivanpolish5** [comment]
Everybody is waiting for it they keep promising it but they do nothing about it unfortunately. Im gonna switch to react on all new project.

**Comment by Dzivo** [comment]
@ivanpolish5 no shit they even blocked the PR comments cause we called their bullshit

**Comment by jackwootton** [comment]
The [recommendation to use TailwindCSS](https://blog.angular.io/modern-css-in-angular-layouts-4a259dca9127) is interesting. I can imagine that after making the effort to adopt Tailwind, it's tempting to move off Angular Material entirety, and just use Tailwind?

**Comment by CaerusKaru** [comment]
All updates will be given on the PR and the already open issue.
