### ISSUE TITLE
Angular 15 Support

### ISSUE THREAD

**Issue by MNorgren** [angular/flex-layout#1435]
I apologize for the delay, and also for locking down this issue. The comments here were getting too heated. That being said, after much work on our end, we have unblocked the v15 release. Now we are just waiting until the holidays end and everyone is back from break so that we can cut a release. We appreciate your patience in the meantime. It's been a frustrating process for us as well.

_Originally posted by @CaerusKaru in https://github.com/angular/flex-layout/issues/1430#issuecomment-1363578061_

**Comment by broomfn** [comment]
Just curious if there is a release date for V15?

We'd be keen to use if while we come up with a more permanent migration strategy.

Thanks :-)

**Comment by ajtowf** [comment]
*crickets* I think we're due yet another "soon" estimate any day now, it's only been 3 months, what a joke

**Comment by alanpurple** [comment]
this project is deprecated, no plans for 15 support

**Comment by CaerusKaru** [comment]
I'm trying to coordinate with the Angular team for a release. Unfortunately they have the only permissions to do this, and I do not. I'm going to close this in favor of our other tracking items. This has not been forgotten; it's just a busy time for everyone (and has been since before the holidays).

**Comment by broomfn** [comment]
@CaerusKaru, many thanks for the update :-)

**Comment by gvlachos** [comment]
> I'm trying to coordinate with the Angular team for a release. Unfortunately they have the only permissions to do this, and I do not. I'm going to close this in favor of our other tracking items. This has not been forgotten; it's just a busy time for everyone (and has been since before the holidays).

@CaerusKaru  If I may ask in case you can tell  :

1. does this mean that support for angular 15 will not be provided ?  or
2. the Angular team is too busy, will do it, but cannot provide an estimate when ?

Also, in the second case, will you update this or #1430 when  angular 15 support is released ?

**Comment by CaerusKaru** [comment]
1. No
2. Yes
