### ISSUE TITLE
Angular 15 Pull request status

### ISSUE THREAD

**Issue by ivanpolish5** [angular/flex-layout#1436]
What is the status of angular 15 pull request ?

**Comment by blogcraft** [comment]
I wouldn't hold my breath for this library. It's caught up in internal politics and it's not clear where it is going, if it's going anywhere at all.

I removed completely flex layout from my projects to be abe to move on.

**Comment by ajtowf** [comment]
Any day now https://github.com/angular/flex-layout/issues/1430#issuecomment-1321320073

**Comment by ivanpolish5** [comment]
> Any day now [#1430 (comment)](https://github.com/angular/flex-layout/issues/1430#issuecomment-1321320073)

That comment is from november haha :D
