### ISSUE TITLE
flex-layout Should support angular 16 version

### ISSUE THREAD

**Issue by ankurrai2602** [angular/flex-layout#1440]
# Bug Report

#### What is the expected behavior?
flex-layout Should support angular 16 version

#### What is the current behavior?
flex-layout support angular 15 version

**Comment by anisabboud** [comment]
`flex-layout` was deprecated last year - see https://blog.angular.io/modern-css-in-angular-layouts-4a259dca9127

There's a community fork that's updated to Angular 17: https://github.com/ngbracket/ngx-layout

And there are migration guides to pure CSS Flexbox in this thread: https://github.com/angular/flex-layout/issues/1426#issuecomment-1304100298
