### ISSUE TITLE
Tested with Material 2 components?

### ISSUE THREAD

**Issue by Fiontan** [angular/flex-layout#146]
I've seen similar threads mentioning responsive behaviour being broken etc. I have noticed a few issues too specifically when integrating with material 2 and am wondering if anyone is actively looking into how these two (material 2/flex-layout) play together? This is more of a suggestion for discussion than anything else.

**Comment by ThomasBurleson** [comment]
@Fiontan  - Issue is not the place for general questions or discussions.

General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.

> BTW, we are aware of issues with Material2 which uses internal wrappers and hand-crafted flexBox CSS. If you are aware of **specific** issues, please post those on this repository. That will help the team resolve component-level issues more quickly.
