### ISSUE TITLE
Root element of application seems out of scope

### ISSUE THREAD

**Issue by Undrium** [angular/flex-layout#150]
When creating a project with the for instance root element <app-root> this should be possible to add flex-layout properties to. 

```html
<app-root fxFlex>
  <header fxFlex> Awesome header</header>
  <main   fxFlex> Awesome main</main>
  <footer fxFlex> Awesome footer</footer>
</app-root>
```

Does not add flex-style to the app-root but only its children. Workaround at the moment is to add another div within, wrapping the children as a holder. Including top-element would make it much tidier, though.

**Comment by ThomasBurleson** [comment]
@Undrium - The `index.html` is not compiled. It is only used to bootstrap the app (root) component. 

>  If the above markup is in the `index.html` then **fxFlex** directive will not fire... and content projection will not work into the `app-root` template (if any).

Closing as this is not a flex-layout issue.

**Comment by Undrium** [comment]
Perhaps this could be added to documentation? Whichever element you choose as root will get Angular selectors which could be confusing for developers when for instance fxFlex doesn't work. It's understandable it can't be compiled when all root-elements start in index.html but from what I can read it is not entirely clear (like the projection-problem) that root is a special case. From a GUI-developers POV they could just start the entire Angular2-application from the Body-element and expect fxFlex-flexbox to work out of the box (heh).

**Comment by d3viant0ne** [comment]
It's an Angular concept that has nothing to do with flex-layout.  Nothing exists outside of the root component and it is documented right where it belongs, at http://angular.io.

This would be a [good place to start](https://angular.io/docs/ts/latest/quickstart.html)
