### ISSUE TITLE
flex-item in @Component host.class doesn't work

### ISSUE THREAD

**Issue by datumgeek** [angular/flex-layout#151]
i have work-arounds for this, but when you are trying to use multiple (named) router-outlets, you have to rely on the router to instantiate your components so you can't use the flex classes and attributes the way you can in a template.  i tried this:

```javascript
@Component({
  selector: 'app-field-results',
  templateUrl: './field-results.component.html',
  styleUrls: ['./field-results.component.css'],
  host: { 'class': 'flex-item' }
})
```

and the class is set properly to `flex-item`, but it isn't expanded into its corresponding flex classes and attributes

**Comment by ThomasBurleson** [comment]
I am confused; what does this have to do with flex-layout?

**Comment by datumgeek** [comment]
I could be confused, but here's my thinking...

flex-layout provides classes and directives that make it possible to leverage flexbox without dropping down into css.

the case i outlined is one where you have to drop down into css and can't use what's provided in flex-layout...

that make sense @ThomasBurleson ?

**Comment by ThomasBurleson** [comment]
Closing as not a flex-layout issue.

**Comment by datumgeek** [comment]
ok :smile:

**Comment by jefbarn** [comment]
I think this is a valid issue.
Specifically you can't add flex-layout directives to a component host. The main problem is when instantiating a component with a router-outlet.  A workaround is to use css, but that also misses extra functionality provided by this library like responsiveness.
Can this be re-opened?
