### ISSUE TITLE
namespace prefix - identify best prefix use in markup and code

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#16]
The current directives use `fx-` prefixes with as HTML markup:

*  `fx-layout`
*  `fx-layout-wrap`
*  `fx-layout-align`
*  `fx-flex`             
*  `fx-flex-fill`
*  `fx-flex-order`
*  `fx-flex-offset`
*  `fx-flex-align`

#### Questions

* Is the `fx-` namespace the best choice ?
* What about the `fxOnMediaQueryChanges` lifecycle method ?

**Comment by ryancampbell** [comment]
Honestly I'd prefer to stick with flex- instead of fx-

**Comment by ThomasBurleson** [comment]
Will not change. 

> Just as an aside this would be things like `flex-flex`... not good.

**Comment by ThomasBurleson** [comment]
Angular team decision to use the `fx-` namespace prefixes.

**Comment by ryancampbell** [comment]
Obviously you would just do flex-align, not flex-flex-align. Just like it was in Material 1. There was no good reason to change it, but sure fx- it is.
