### ISSUE TITLE
Breakpoints are not working properly in ipad portrait view 

### ISSUE THREAD

**Issue by GGSMNandathilaka** [angular/flex-layout#164]
Following is the component's div structure. In chrome developer mode, this works properly for ipad portrait view (768 x 1024). But it is not working in a proper manner in ipad (native). I am using **"@angular/flex-layout": "^2.0.0-beta.4"** 

```html
<div class="flex-container"
         *ngIf="data && data.length > 0" style="width: 100%">
      <div *ngFor="let result of data " (click)="onSelect($event, result.bookingID)">
        <div fxFlex [fxLayout.gt-sm]="'row'" [fxLayout]="'column'" [fxLayoutAlign]="'space-around'"
             [class]="'pad-10 card-space'">
          <div fxFlex>
            <div [fxLayout]="'row'" class="tc-searh-flex-result">
              <div fxFlex="20" [fxLayoutAlign]="'start center'">
                <div>Div 1</div>
              </div>
              <div fxFlex="20" [fxLayout]="'direction'" [fxLayoutAlign]="'start center'" fxHide.sm fxHide.xs>
                <div [fxLayout]="'column'">
                  <div>Div 2</div>
                </div>
              </div>
              <div fxFlex="20" [fxLayoutAlign]="'start center'">
                <div [fxLayout]="'column'">
                  <div>Div 3</div>
                  <div>Div 4</div>
                </div>
              </div>
              <div fxFlex="40" [fxLayoutAlign]="'start center'">
                <div [fxLayout]="'column'">
                  <div>Div 5</div>
                  <div>Div 6</div>
                </div>
              </div>
              <div fxFlex="20" [fxLayout]="'direction'" [fxLayoutAlign]="'start center'" fxHide.gt-sm>
                <div>Div 7</div>
              </div>
            </div>
          </div>
          <div fxFlex>
            <div [fxLayout]="'row'" class="tc-searh-flex-result">
              <div fxFlex="20" [fxLayout]="'direction'" [fxLayoutAlign]="'start center'" fxHide.gt-sm>
                <div>Div 8</div>
              </div>
              <div fxFlex="40" [fxLayoutAlign]="'start center'">
                <div>Div 9</div>
              </div>
              <div fxFlex="20" [fxLayout]="'direction'" [fxLayoutAlign]="'start center'" fxHide.sm fxHide.xs>
                <div [fxLayout]="'column'" class="tc-set-width">
                  <div>Div 10</div>
                  <div>Div 11</div>
                </div>
              </div>
              <div fxFlex="40" [fxLayoutAlign]="'end center'">
                <div>Div 12</div>
              </div>
            </div>
          </div>
          <div [fxLayout]="'row'" [fxLayoutAlign]="'end end'">
            <div>Div 13</div>
          </div>
        </div>
      </div>
    </div>
```

**Comment by mackelito** [comment]
Please recreate the issue:
https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview

**Comment by GGSMNandathilaka** [comment]
I have recreated the issue : `https://plnkr.co/edit/9mbM2Wx8x2qXpD3y4ilX?p=preview`

I have checked this example with chrome browser in windows 10(checked in developer mode for ipad - 768 x 1024 resolution) & ipad pro device (ios 10.2.1). Following I have attached the screen shots in those 2 scenarios. (both landscape and portrait view of ipad)
## 
# **1. Chrome browser in windows 10**

_**Landscape**_
![landscape](https://cloud.githubusercontent.com/assets/4043668/22688752/ae749514-ed53-11e6-8754-250331971b96.png)


**_Poratrait_**
![portrait](https://cloud.githubusercontent.com/assets/4043668/22688767/bf877f60-ed53-11e6-9e90-5191121f0946.png)

## **2. Ipad pro**

**_Landscape_**
![img_0135](https://cloud.githubusercontent.com/assets/4043668/22688811/dee36dd8-ed53-11e6-8bcd-7fad443f4a1f.PNG)

**_Portrait_**
![img_0133](https://cloud.githubusercontent.com/assets/4043668/22688839/ef70dbea-ed53-11e6-8a1f-f34ca422b9ac.PNG)

I have used **'gt-sm'** break point. in the windows 10 chrome browser this break point works properly as the above. But in the ipad pro it didn't work. And also I have tried with samsung galaxy mobile phone. Also this break point didn't work in that scenario.

**Comment by mackelito** [comment]
Please update the url. Right now it´s pointing to github ;)

**Comment by mackelito** [comment]
iPad Pro Landscape = 1024px in width.
So by setting gt-sm ('screen and (min-width: 960px)') you are telling that if width is 960 or more it should have the row layout correct?

I might be misunderstanding your isssue but what happens if you use
`<div fxFlex [fxLayout.gt-md]="'row'" [fxLayout]="'column'">`
instead?

**Comment by GGSMNandathilaka** [comment]
Thanks for your support :)
This is the link for the project : [https://embed.plnkr.co/9mbM2Wx8x2qXpD3y4ilX/](url)

"So by setting gt-sm ('screen and (min-width: 960px)') you are telling that if width is 960 or more it should have the row layout correct?"
**Yes**

I will try the solution which you have suggested and will inform

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.

**Comment by ThomasBurleson** [comment]
@GGSMNandathilaka - Careful when you use column as the outer wrapper layout. Only use `fxLayout=column` when absolutely necessary.


![screen shot 2017-02-09 at 8 53 37 am](https://cloud.githubusercontent.com/assets/210413/22788376/4d7c3f98-eea5-11e6-9a97-937a3b5ee9ed.png)

Demo: [Plunkr for ^](https://plnkr.co/edit/JxfN5JAMIybWdnxPjcao?p=preview)
