### ISSUE TITLE
Combination of fxLayoutWrap fxLayoutGap modification

### ISSUE THREAD

**Issue by Jonatthu** [angular/flex-layout#165]
```html
<div class="first" fxFlex="100%" fxFlex.xs="auto" fxLayout="row" fxLayoutWrap fxLayoutGap="20px">
        <div class="title" fxFlex="100%"><b>Contact Information</b></div>
        <div class="item" fxFlex="25%" *ngFor="let i in [1,2,3,4,5,6]">
          <b>Phone</b> <br>
          {{listing.contact.phoneNumber}}
        </div>
</div>
```
Ok I'm using beta 4 and I've seen beta 5 milestones but i'm not seeing something to my question.
Right now this code above is generating the items with margin-left 20px all of them but is not doing groups of 4 as I intended with 25% (1/4 of the container per item).

Intead apply margin-left of 20px I would recommend to apply padding-left of 20px and the parent layout
have margin-left of -20px (margin-left: -20px) so the list is align  for every group of 100% insert a div parent for example:

```html
<div class="first" fxFlex="100%" fxFlex.xs="auto" fxLayout="row" fxLayoutWrap fxLayoutGap="20px">
        <div class="title" fxFlex="100%"><b>Contact Information</b></div>
        <!-- Insert for every group of 100% or almost 100% by example if in 5 elements are 75% and the next item is 40% is 115% so just insert the parent div in the 75% and the other 40% item put it in another parent of 100%--->
        <div class="auto-inserted-parent-by-flex" style="margin-left:-20px">
              <div class="item" fxFlex="25%" *ngFor="let i in [1,2,3,4,5,6]">
              <b>Phone</b> <br>
              {{listing.contact.phoneNumber}}
             </div>
        </div>
</div>
```
 Insert for every group of 100% or almost 100% by example if in 5 elements are 75% and the next item is 40% is 115% so just insert the parent div in the 75% and the other 40% item put it in another parent of 100%

![fx](https://cloud.githubusercontent.com/assets/3742176/22705357/0e4ee5f4-ed20-11e6-82e4-eb30ef652a35.jpg)

For each parent is a width of calc(100% + 20px)
My picture seems like the items are separated but they are not

**Comment by macjohnny** [comment]
@Jonatthu I stumbled upon the same issue. I agree with your approach.

**Comment by Jonatthu** [comment]
Maybe with just a general parent for the children (a general Orange box for the blue ones) with a margin left of -20px or the gap that you put in fxLayoutGap

**Comment by ThomasBurleson** [comment]
**fxLayoutGap** now only applies margin-right (for fxLayout=row) and margin-bottom (for fxLayout=column). All other styles must be done with CSS by the SPA developer.

> See SHA 9f7137ed3 for detals

**Comment by Jonatthu** [comment]
@ThomasBurleson is not working, because margin left is breaking the columns when is 25% to be instead of 4 to 3 columns now happening in beta 4, maybe you should read the post, I'm talking about when you use fxLayoutGap and fxLayoutWrap please open the issue again

**Comment by macjohnny** [comment]
@ThomasBurleson this is actually something that should be improved in flex-layout, since the first element gets `margin-left: 0px`, which makes it impossible to apply the correct style with css.

here is the very simple solution to this issue:
apply `margin-left: xx px` to all elements of a child with fxLayoutGap, add a wrapper around the children with a `margin-left: -xx px`. that's it. 

what do you think about this?

**Comment by ThomasBurleson** [comment]
@Jonatthu, @macjohnny - plz retry with the latest code for HEAD on master. The API does not do anything with margin-left.

**Comment by macjohnny** [comment]
@ThomasBurleson this shifts the problem to the right side, since the element wraps too early, i.e. it should "ignore" the margin-right for the last element in the row (not necessarily the very last element). the proposed solution also works for margin-right.

**Comment by Jonatthu** [comment]
@ThomasBurleson This only applies when we are using **fxLayoutWrap**  and **fxLayoutGap**
for make columns if we try to do columns of 4 with a fxFlex="25%" this will give us columns of 3 instead of 4 because the margin-left

**Comment by Jonatthu** [comment]
@ThomasBurleson I insist this should be open again, #9f7137e is not resolving this issue

**Comment by macjohnny** [comment]
@Jonatthu this is the behaviour of the "too early wrap" I described in https://github.com/angular/flex-layout/issues/165#issuecomment-278360563

**Comment by Jonatthu** [comment]
@macjohnny  yes I know, right know I'm fixing the issue manually with css but this should not be like this, is more easily if angular flex box handle this when is applying **fxLayoutWrap**

**Comment by macjohnny** [comment]
@Jonatthu you are right, i am also in favour of flex-layout fixing this issue.

**Comment by ThomasBurleson** [comment]
@Jonatthu - To paraphrase what you are saying: 

![screen shot 2017-02-08 at 10 49 31 am](https://cloud.githubusercontent.com/assets/210413/22747320/64dbba56-edec-11e6-9db5-47e151ec416c.png)

The intent is to display 4 cells / row. Using *margins* for gaps interferes with the layout and wrapping.

----

The issue here is that the fxLayoutGap cannot use padding inside the child items. That may interfere with the layouts within those child items. And using margin + wrap has the above possible issues. 

I am not aware of any solution that adequately solves this problem. You would have the same issues using manually constructed FlexBox CSS.

**Comment by ThomasBurleson** [comment]
One possibility is to use:

* **margins** (right or bottom) for the gap when NO wrap is specified
* **paddings** (right or bottom) for the gap when fxLayoutWrap is also specified.

**Comment by Jonatthu** [comment]
@ThomasBurleson @macjohnny 
Please see the next plunker
http://plnkr.co/edit/Ji0BdVgoK9k6Ahj5I7eI?p=preview

Put fxFlex="calc(25% - 20px)"

but do this automatically  calc(25% - 20px) where the 20px is the value of fxLayoutGap

**Comment by Jonatthu** [comment]
@ThomasBurleson @macjohnny 
http://plnkr.co/edit/GYdG6abt0kmRUnewsDcH?p=preview

But the problem with that is this next plunker maybe we need to figure out another idea

**Comment by ThomasBurleson** [comment]
@Jonatthu - that is a great solution. except here is a possible side-affect:

![screen shot 2017-02-08 at 11 24 11 am](https://cloud.githubusercontent.com/assets/210413/22748879/280d87da-edf1-11e6-9f3a-0e0ebd194d6c.png)

**Comment by Jonatthu** [comment]
@ThomasBurleson @macjohnny 
http://plnkr.co/edit/Lu2xQIm0F5ONxaMBHIn0?p=preview
this is another solution

**Comment by Jonatthu** [comment]
@ThomasBurleson with that last one, flex box just needs to figure out when **fxLayoutWrap** is been applied and apply the css rules as showed in the last plunker

**Comment by ThomasBurleson** [comment]
@Jonatthu - I like this demo!

* Why don't you submit a PR to add this demo to the static demos page: https://github.com/angular/flex-layout/tree/master/src/demo-app/app/docs-layout
* Ref this issue in the PR submission

> I do not want to distort fxFlex with such edge conditions. These are easily added to the CSS manually (as you have done).

**Comment by Jonatthu** [comment]
@ThomasBurleson I thought that **fxLayoutWrap** was intended for achieved something similar to that demo with **fxLayoutGap** so that's why we can add that css rules to fxFlex childs and the parent, or flex-box can create a new directive like fxLayoutWrapGrip for example if this is too different , but this should be native from flex-box, Don't you think?

**Comment by ThomasBurleson** [comment]
Enhancing **fxFlex** to account for **fxLayoutGap** values when **fxLayoutWrap** is specified is an edge case and creates *magical* code that is brittle. This feature will not be done.

> Developers can easily add the calc expression with the gap value to their own `fxFlex` attributes.

**Comment by Jonatthu** [comment]
@ThomasBurleson Just for reference this flex box grid system is doing the same
http://gridlex.devlint.fr/
They are doing the calculations and the margin-left to the parent as well with out need to do it each time manually :)

**Comment by Jonatthu** [comment]
Maybe we can create a extension directive for flex-layout for approach this, should be a thrid party npm package or a pull request? @ThomasBurleson

**Comment by macjohnny** [comment]
@ThomasBurleson using calc would still lead to a gap to the right of the container, since all children have a margin to the right, including those that are in the outer right column.
as a mitigation, you could add an additional wrapper element around the children and allow setting the negative margin on that element by the developer.

**Comment by ThomasBurleson** [comment]
@Jonatthu - Please do not create an public extension for this. That will pollute the flex-layout eco-system. Please explain clearly the justification for embedding this edge-case feature within **flex-layout**. 

> Note that flex-layout is intended to solve the major issues... but it is not presented as the magic-bullet to solve 100% of all layout problems.

**Comment by macjohnny** [comment]
@ThomasBurleson it would represent a suitable replacement of the `layout-margin` option in angular material 1

**Comment by ThomasBurleson** [comment]
Close this issue. Further discussions on this should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Thank you.
