### ISSUE TITLE
fxLayout is breaking if DOM element has *ngIf

### ISSUE THREAD

**Issue by mac4manu** [angular/flex-layout#172]
Hi ,
FxLayout is breaking if I have *ngIf in the same DOM element. Any thought on this?
Eg - 
<<div *ngIf="condition"  fxLayout="column" fxLayoutGap="10px" ....>

<</div>

**Comment by ThomasBurleson** [comment]
@mac4manu - please provide a Plunkr Demo manifesting this issue.

---- 

#### Templates 

* [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=info)
* [Plunkr Template with Material2](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview)

**Comment by mac4manu** [comment]
@ThomasBurleson  
I'm unable to create in Material2 Plunkr, It's not loading for me

**Comment by mac4manu** [comment]
@ThomasBurleson - 
Including the code snippet 
```<div *ngIf="condition">
        <div fxLayout="column" fxLayoutGap="15px">
            <div fxLayout="row" fxLayoutWrap="wrap" fxLayoutAlign="start start">
                <md-card fxFlex="30" fxLayoutGap="15px" *ngFor="let d of details" fxLayout="column">
                    <md-card-sub-title>Title</md-card-sub-title>
                    <md-card-content>
                        Content
                    </md-card-content>
                </md-card>
            </div>
        </div>
</div>```

**Comment by ThomasBurleson** [comment]
@mac4manu - [Plunkr Template with Material2](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview) has been fixed and is working as a tempalte.

> It is using the latest code from flex-layout/master and needed to use `ObservableMedia`

**Comment by ThomasBurleson** [comment]
This works for me:  https://plnkr.co/edit/xTTkYjQaa4hJxhqSn7AA?p=preview

![screen shot 2017-02-08 at 6 42 58 pm](https://cloud.githubusercontent.com/assets/210413/22764135/71ce6848-ee2e-11e6-8fa4-6af8dfc98eb8.png)

**Comment by mac4manu** [comment]
@ThomasBurleson  Thank you!!
Let me check my code again if I'm doing any crazy thing. 
But I have one question regarding fxLayoutGap --> that adds only margin-left.  In column layout we need to explicitly give margin-top.

https://plnkr.co/edit/xTTkYjQaa4hJxhqSn7AA?p=preview
Here there is no space between md-card

**Comment by ThomasBurleson** [comment]
fxLayoutGap now applies gaps as margin-right or margin-bottom. 
You had the fxLayoutGap on the wrong element.

```html
<div *ngIf="condition == true">
    <div fxLayout="row" fxLayoutWrap="wrap" fxLayoutAlign="start start" fxLayoutGap="15px" >
        <md-card fxFlex="calc(25%+15px)" *ngFor="let d of details">
            <md-card-content>
                Content
            </md-card-content>
        </md-card>
    </div>
  </div>    
    <button md-button (click)="condition = !condition">Toggle</button>
```

> Notice the `fxFlex="calc(25%+15px)"` that accounts for the gaps.

![screen shot 2017-02-08 at 7 23 17 pm](https://cloud.githubusercontent.com/assets/210413/22765104/1cbae79a-ee34-11e6-87fc-9c6761559b54.png)

> Coming soon is documentation for fxLayoutGap.

**Comment by mac4manu** [comment]
@ThomasBurleson  Thank you!!
