### ISSUE TITLE
FlexLayoutModule.forRoot() causing error in 2.0.0-beta.5

### ISSUE THREAD

**Issue by HarkSolDev** [angular/flex-layout#175]
Just updated to the latest beta ( 2.0.0-beta.5 ) and my project is become very unhappy with the FlexLayoutModule.forRoot() in my angular modules definitions... . did I miss something?

Output:

```console
ERROR in Error encountered resolving symbol values statically. 

Calling function 'FlexLayoutModule', function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function, 
resolving symbol SidenavModule in D:/[REDACTED]/sidenav/sidenav.module.ts,
resolving symbol SidenavModule in D:/[REDACTED]/src/app/modules/sidenav/sidenav.module.ts
```

**Comment by ThomasBurleson** [comment]
I would imagine you are using angular CLI ? Did you upgrade to @angular/cli Beta.30 or higher? That has upgrade issues with existing CLI projects; nothing to do with flex-layout.

Fresh projects (using @angular/CLI beta.30) work great with Flex-Layout Beta.5. Also this plunkr works without issues:  http://plnkr.co/edit/QrDjtafk138RVrpS3KBD?p=preview

Closing as "not a flex-layout" issue. 

----

General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

**Comment by HarkSolDev** [comment]
Apologies.. your quite right.. Here's the link to a discussion in the angular CLI camp...
https://github.com/angular/angular-cli/issues/4425

Thanks for the heads up !

**Comment by ThomasBurleson** [comment]
@HarkSolDev - great link. Thx. 

> Solutions re the @angular-cli issue:  https://github.com/angular/angular-cli/issues/4425#issuecomment-278646371

**Comment by cre8** [comment]
I got the same error with an older project version. removing `.forRoot()` worked for me.

**Comment by ThomasBurleson** [comment]
Do you have the `forRoot()` method in your local `flex-layout.umd.js` file:

> Here is the beta.5 version [flex-layout.umd.js]( https://github.com/angular/flex-layout-builds/blob/v2.0.0-beta.5/bundles/flex-layout.umd.js#L4025)

**Comment by ThomasBurleson** [comment]
@HarkSolDev, @cre8 - @see https://github.com/angular/flex-layout/issues/176#issuecomment-279056717
