### ISSUE TITLE
Need Help with Angular Material2 List and Responsive Design

### ISSUE THREAD

**Issue by bailejl** [angular/flex-layout#177]
I am working on making a page responsive using the flex-layout system and it is going well, but I have an issue I cannot easily solve.  I would appreciate help in solving my problem, which might benefit others.  

I have a Material2 list which is fine on a large display, but is too huge for a phone.  The `<p>` elements in `<div fxLayout="row" md-line>` work great as a row on the big screen, but need to be a column on smaller screens.  When I convert to a column structure for small screens the elements in `<div fxLayout="row" md-line>` bunch up because they need `md-line` entries in the `<p>` elements.  This allows the list to allocate the correct space.  Any suggestions on how to get this to work?

Thanks in advance,
Joe

```html
    <md-list>
      <md-list-item *ngFor="let meeting of (meetings | pgDataFilter:meetingFilter)" fxLayoutAlign="center center">
        <strong md-line class="meeting-title">{{meeting.name}}</strong>
        <p md-line fxHide.xs="true">{{meeting.objective}}</p>
        <div fxLayout="row" md-line>
          <p fxLayoutAlign="center center" fxLayout="row" xfFlex mdTooltip="Ends at: {{meeting.endDate}}">
            <md-icon svgIcon="pg-clock"></md-icon>
            {{meeting.endDate | countDownFormatter}}
          </p>
          <p fxLayoutAlign="center center" fxLayout="row" fxFlex mdTooltip="Closed Decisions / Total Decisions">
            <md-icon svgIcon="pg-check-mark"></md-icon>
            {{meeting.closedDecisions}}/{{meeting.totalDecisions}}
          </p>
          <p fxLayoutAlign="center center" fxLayout="row" fxFlex mdTooltip="Closed Action Items / Total Action Items">
            <md-icon svgIcon="pg-action-item"></md-icon>
            {{meeting.closedActionItems}}/{{meeting.totalActionItems}}
          </p>
        </div>
      </md-list-item>
    </md-list>
```

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you. 

> I will try to help on the Gitter.
