### ISSUE TITLE
Calling function 'FlexLayoutModule', function calls are not supported.

### ISSUE THREAD

**Issue by cocaux** [angular/flex-layout#180]
Hi, 

When I do ng serve, I now get an error: 
ERROR in Error encountered resolving symbol values statically. Calling function 'FlexLayoutModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol SharedModule in ...

In my Shared module: 
```
...
import { FlexLayoutModule } from '@angular/flex-layout';
...
@NgModule({
  imports: [
...
    FlexLayoutModule.forRoot(),
...
  ],
...
  exports: [
...
    FlexLayoutModule,
...
  ]
})
```
Did something change in the setup of the module ?

**Comment by d3viant0ne** [comment]
https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#200-beta5-2017-02-09

remove the `.forRoot()`

**Comment by beve** [comment]
Okay but i got: Error: Unexpected value 'undefined' imported by the module 'EstablishmentModule'

**Comment by d3viant0ne** [comment]
That's something else entirely. I'd have to see the project to figure out where the problem is.

I've already upgraded 2 of my work projects ( CLI beta.30 & .31 ) to Flex-Layout-Beta.5 without issue less the whole `ngc / forRoot()` thing.

**Comment by beve** [comment]
Fixed for me after updating to latest ngc. Thank you d3viant0ne.

**Comment by ThomasBurleson** [comment]
@cocaux, @beve - please see https://github.com/angular/flex-layout/commit/0797c859aa023a86c2a95927f43e06a48a0bf127  (that is on HEAD... not in Beta.5)

**Comment by ethanmick** [comment]
This page needs to be updated as well: https://github.com/angular/flex-layout/wiki/Integration-with-Angular-CLI

Thanks!

**Comment by ThomasBurleson** [comment]
@ethanmick - updated. Thx.
