### ISSUE TITLE
Wrong layout with fxHide / fxShow sometimes ignoring breakpoint aliases

### ISSUE THREAD

**Issue by phil294** [angular/flex-layout#181]
Hellou,
https://github.com/angular/flex-layout/issues/140 has been marked as solved, but I just found another few errors in `2.0.0-beta.5`, in regards to `fxShow fxHide.md` and the alike. Consider the following example for reproducing:

```html
	<div fxHide fxShow.gt-xs>Type 1, row a</div>
	<div fxHide fxShow.gt-xs>Type 1, row b</div>
	<div fxHide fxShow.gt-xs>Type 1, row c</div>
	<br/>
	<div fxShow fxHide.md>Type 2, row a</div>
	<div fxShow fxHide.md>Type 2, row b</div>
	<div fxShow fxHide.md>Type 2, row c</div>
```

Set your browser to `md` width and refresh the page. You'd expect to see

	Type 1, row a
	Type 1, row b
	Type 1, row c

, but the output is

	Type 1, row a
	Type 1, row b
	
	Type 2, row c

which is wrong on multiple levels. It seems the views fix themselves on update. Meaning when you resize the window width to `gt-md` and back to `md`, `Type 2, row c` will then be correctly hidden. And when you resize the window to `xs` and back to `gt-xs`, the missing `Type 1, row c` pops up.

So, I see wrong initialization and weird interference of multiple elements. I might be missing something.

Best regards,

**Comment by ThomasBurleson** [comment]
@phil294 - how are you getting a **Type 3, row c**? I do not see that in your markup.

**Comment by phil294** [comment]
@ThomasBurleson sorry, Typo. Meant `type 2`

**Comment by ThomasBurleson** [comment]
@phil294 - I think this is related to #135.

**Comment by ThomasBurleson** [comment]
@phil294  - PR #190 Now renders this:

![fix_185](https://cloud.githubusercontent.com/assets/210413/23096448/2f4b63ac-f5e2-11e6-9fd9-752d0b891201.png)

**Comment by phil294** [comment]
Idk if I should test it out or how I could in the first place, but it looks excellent! Good job & thank you very much

**Comment by ThomasBurleson** [comment]
@phil294 - try:

```bash
git remote add upstream https://github.com/angular/flex-layout.git
git co master
git pull --rebase upstream master
git pull --rebase upstream fix/issue_181
```

This should update your local repos with latest from **master** AND from the PR above.
