### ISSUE TITLE
Using flex-layout with Angular Universal

### ISSUE THREAD

**Issue by BirdInTheCity** [angular/flex-layout#187]
From my limited knowledge of Node, I gather that anything referencing `Document` or `Window` will throw a server-side error.

That said, I'd like to incorporate flex-layout into my Angular Universal app. Is that possible? My initial attempt (simply following the readme) throws the following error:

> ReferenceError: document is not defined

**Comment by ThomasBurleson** [comment]
Currently we do NOT support flex-layout with Angular Universal.

**Comment by ThomasBurleson** [comment]
@alexeagle - any thoughts how we should change our use of:

*  Render - see https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/base.ts#L130
*  getDOM() - see https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/base.ts#L95

**Comment by alexeagle** [comment]
@alxhub is probably the better person to answer

**Comment by Josmorsot** [comment]
@BirdInTheCity I had the same problem so I decided to use Layouts from MDL [https://getmdl.io/](url).
Also I had this problem with Material2 buttons and other components but this can be solved using **'isNode'** for check if request are being sent by node or browser

**Comment by ThomasBurleson** [comment]
@BirdInTheCity - can you provide a simple project (zip) that demonstrates this ? We will investigate. 

Currently I am unclear how does Angular Universal handle issues with references to `document` ?

> I think you are encountering code in `match-media.ts::prepareQueryCSS()`; which really is patch code for some browsers.

**Comment by nicky-lenaers** [comment]
Is this going to make it into the `rc.2` release?

**Comment by ThomasBurleson** [comment]
@nicky-lenaers - no. There are unknowns that still need to be resolved? (see above questions).

**Comment by paullryan** [comment]
When working with this you should focus on angular4 support instead of angular/universal given that 4 has universal built into @angular/platform-browser and @angular/platform-server.

@ThomasBurleson when working with document for universal you want to manipulate the renderer instead of document for rendering updates like your doing on https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/base.ts#L138. If you have direct need for getDOM() you'll want to check for getDom() first and if it exists then isBrowser is true else your in node and probably won't be able to directly make that call. 

Side note; a quick search through the current master is showing that you don't have any glaring issues with universal support so it should be pretty close to ready as is.

**Comment by nicky-lenaers** [comment]
@paullryan nice, I really hope it'll be available soon!

**Comment by alxhub** [comment]
Both `getDOM()` and the renderer will work fine on `@angular/platform-server` - it's direct DOM access that needs to be avoided.

**Comment by nicky-lenaers** [comment]
I see errors on the `matchMedia` function server-side. Any thoughts on how to fix that?

**Comment by ThomasBurleson** [comment]
@nicky-lenaers - The current issue is that `window.matchMedia()` is needs actually run on the client. 
* the server-side can should/mock an "all" matches 
* client-side rendering needs to force a **re-register** of the media queries to trigger the appropriate match announcements.

**Comment by nicky-lenaers** [comment]
@ThomasBurleson great to here there is a solution. Is this already in development?

**Comment by DmitryEfimenko** [comment]
With the yesterday's [2.0.0-beta-4](https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta4-unobtainium-sunglasses-2017-05-12) release of `angular/material2`, one of the highlights of which was improved Angular Universal support via [PR 4251](https://github.com/angular/material2/pull/4251), I'm surprised `angular/flex-layout` didn't have similar changes. I'd think they go hand in hand.

**Comment by nicky-lenaers** [comment]
Just curious, is there any progress on implementing flex-layout for SSR? Like @DmitryEfimenko said, isn't similar implementation done for angular/material?

**Comment by ThomasBurleson** [comment]
@nicky-lenaers - we are waiting on the Angular Universal team for feedback regarding SSR. The Flex-Layout/SSR effort is planned to start mid-July.

**Comment by nicky-lenaers** [comment]
I see, thanks for the update @ThomasBurleson . Looking forward to it 😄

**Comment by mariohmol** [comment]
Hi there!!! This is really needed =(  
Anyone have tips about substitution for flex-layout that works with SSR?
Thanks

**Comment by chrisvfabio** [comment]
@mariohmol I have been using https://github.com/devlint/gridlex in production

**Comment by glebmachine** [comment]
Any updates?

**Comment by ThomasBurleson** [comment]
Once PR #342  has been merged we will submit a revised PR for Angular Universal support.

**Comment by glebmachine** [comment]
@ThomasBurleson Merged!
https://github.com/angular/flex-layout/pull/342#event-1182589647

**Comment by ThomasBurleson** [comment]
@glebmachine - We appreciate your passion, thank you. We are working on this issue now! ;-)

**Comment by ThomasBurleson** [comment]
FYI - The team is hoping to close this issue within the next 2-3 workdays.

**Comment by glebmachine** [comment]
Awesome!

**Comment by fdambrosio** [comment]
I'm using beta.9 and I have the error
`ReferenceError: document is not defined`

**Comment by glebmachine** [comment]
Thank you! I following this guide, but suddenly got error into ShowHideDirective : (
I hope it was due some external issues
