### ISSUE TITLE
fxFlexOrder and fxLayoutGap

### ISSUE THREAD

**Issue by MihailoVasovic** [angular/flex-layout#188]
I have a problem with gap when using fxFlexOrder. As you see, ther is no initial gap between item 3 and item 2 when fxFlexOrder is used on item 2 div. Am i doing something wrong or is this bug?
![angular gap](https://cloud.githubusercontent.com/assets/20172984/23078211/ff4cdd6a-f547-11e6-83ec-389f805ec427.jpg)

![code](https://cloud.githubusercontent.com/assets/20172984/23078265/45dfc648-f548-11e6-8c16-e5ce137faa2d.jpg)

**Comment by ThomasBurleson** [comment]
This is an invalid issues submission. Please provide a Plunkr.

> We will re-open at that time.
