### ISSUE TITLE
Importing FlexLayoutModule issue

### ISSUE THREAD

**Issue by MingyuJeon** [angular/flex-layout#192]
Hi,
I was using flex-layout well, and I deleted all of npm packages and reinstalled npm packages today.
I think something changed when I updated packages.
So, importing FlexLayoutModule makes an error in app.module.ts,
`Error: Unexpected value 'undefined' imported by the module 'AppModule' at SyntaxError.ZoneAwareError`

If I delete flexLayoutModule, then it works well.
I have no idea why it happens.

**Comment by ThomasBurleson** [comment]
Angular CLI or WebPack most likely changed. Please see https://github.com/angular/flex-layout/wiki/Integration-with-Angular-CLI.

* In your app module imports, use `FlexLayoutModule` instead of `FlexLayoutModule.forRoot()`.

**Comment by 1ambda** [comment]
It would be nice to change https://github.com/angular/flex-layout/wiki/Webpack-Configuration#import-the-angular-flex-layout-module too, 

```
@NgModule({
  imports: [
    ...
    FlexLayoutModule.forRoot()  // -> `FlexLayoutModule`
  ],
```

**Comment by ThomasBurleson** [comment]
@1ambda - Done. Thank you.
