### ISSUE TITLE
Remove private Angular API usage

### ISSUE THREAD

**Issue by IgorMinar** [angular/flex-layout#193]
When testing Angular 4 in google3 we discovered that flex-layout uses private APIs from `@angular/core`. These apis are no longer available in A4. Please remove the usage:

https://github.com/angular/flex-layout/blob/f9f16f5fce2fea05b4c9fdbb1b4d78b977ec1e56/src/lib/flexbox/api/base.ts#L10-L11
https://github.com/angular/flex-layout/blob/f9f16f5fce2fea05b4c9fdbb1b4d78b977ec1e56/src/lib/flexbox/api/base.ts#L95

in google3 we made the following local modification:

before:
```
import {ElementRef, Renderer, OnDestroy} from '@angular/core';

import {__platform_browser_private__} from '@angular/platform-browser';
const getDOM = __platform_browser_private__.getDOM;

import {applyCssPrefixes} from '../../utils/auto-prefixer';

...

    let value = (element.style as any)['display'] || getDOM().getComputedStyle(element)['display'];
```

after:

```
import {ElementRef, Renderer, OnDestroy} from '@angular/core';

import {applyCssPrefixes} from '../../utils/auto-prefixer';

...

    let value = (element.style as any)['display'] || getComputedStyle(element)['display'];
```

please note that the global `window` object has `getComputedStyle` which `getDOM` delegated the call, so this modification is equivalent to the original both at design time and at run time.

**Comment by ThomasBurleson** [comment]
@IgorMinar - Can you provide some insight how Angular Universal addresses calls such as the previous `getDOM()` and now the implicit `window.getComputedStyle(....)` ?

**Comment by ThomasBurleson** [comment]
Refs #191

**Comment by IgorMinar** [comment]
@vikerman can help with the universal support question.
