### ISSUE TITLE
fxLayoutWrap with horizontal scrolling

### ISSUE THREAD

**Issue by bm-software** [angular/flex-layout#194]
Is there any way to use the Layout-Wrap functionality so that the elements are scrolled horizontally.

To better explain. I would like to reach a result like that:

![cattura](https://cloud.githubusercontent.com/assets/19502861/23209356/42920e24-f8f9-11e6-8667-bca3df1161bf.PNG)

How can I achieve this with wrap layout? Is it possible?
If not, someone knows how to do it?

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...
*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)

Closing this issue as 'invalid'. Thank you.
