### ISSUE TITLE
Issue Displaying Grid List when using fxLayoutAlign="center"

### ISSUE THREAD

**Issue by fv42wid** [angular/flex-layout#196]
I cannot figure out how to get a md-grid-list to display properly when using it in a div with **fxLayoutAlign="center"**.  Below code will not display the grid-list, but if I remove fxLayoutAlign="center" it displays.  Am I doing something wrong?

```html
<div fxLayout="row">
  <div fxFlex="80%" fxFlexOffset="20%" fxLayoutAlign="center">
    <h2>What We Do</h2>
    <md-grid-list cols="2">
      ...
    </md-grid-list>
 </div>
</div>
```

https://plnkr.co/edit/01FjQknMPNH9qz90l6iL?p=preview

**Comment by ThomasBurleson** [comment]
@fv42wid  - Your markup does not make sense:

*  Why do you use a row layout for a single item ?
*  fxLayoutAlign should be used on the same container as the fxLayout
* Why are you trying to center the gridlist+title when you already flex its size to 80% width with 20% offset?

When you specify the [unneeded] **fxLayoutAlign**, the title+gridlist style `{ display : flex }` is used; which appears to interfere with **md-grid-list**. 

Here is an updated, colorized Plunkr: https://plnkr.co/edit/gqMZg3bpDiBksRUTuNiz?p=preview

----

MdGridList is a brittle component that has complicated tile sizings using `calc`:

```css
left: calc(((50% - 0.5px) + 1px) * 0);
  width: calc(((50% - 0.5px) * 1) + 0px);
  margin-top: calc(((50% - 0.5px) + 1px) * 0);
  padding-top: calc(((50% - 0.5px) * 1) + 0px);
```
I recommend you escalate this issue to the Angular Material2 team.

----

> For future issues, please note that general discussion and how-to questions should be posted to the [Gitter Channel](https://gitter.im/angular/flex-layout).
