### ISSUE TITLE
ObservableMediaService has no exported member

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#199]
I´m running rc.1 and importing this is not working.. what am I missing?
`
import { ObservableMediaService, MediaChange } from '@angular/flex-layout';
`

**Comment by mackelito** [comment]
Looks as it has been renamed back to 'ObservableMedia' ?

**Comment by ThomasBurleson** [comment]
Please see our Wiki API documentation:  [ObservableMedia API](https://github.com/angular/flex-layout/wiki/ObservableMedia)
