### ISSUE TITLE
Convert Pesto adaptive SPA to use @angular/flex-layout

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#202]
[ng1 + ngM1 Source](https://github.com/angular/material-adaptive)
[Demo](https://material-adaptive.firebaseapp.com/pesto/app/dist.html#/home)

**Comment by CaerusKaru** [comment]
It looks like the entire app would need to be upgraded to Angular and Angular Material. Is this really something we want to commit to?

**Comment by ThomasBurleson** [comment]
This is outside our focus area. Closing.
