### ISSUE TITLE
ngClass and ngStyle causing errors

### ISSUE THREAD

**Issue by alexwbbr** [angular/flex-layout#208]
Hello,

I am using version 2.0.0-rc.1 but whenever I add ngClass.xs to my html I get this error in the console.
`Error: Template parse errors:
Can't bind to 'ngClass.md' since it isn't a known property of 'div'. ` this is what I have added to my div: ` [ngClass.md]="{'class1' : true}"`.
I have included the flexLayoutModule and other directives work inside the same page such as ` [style.md]`  and `fxLayout.xs ="column"`

**Comment by ThomasBurleson** [comment]
I believe that the [ngClass}(https://github.com/angular/flex-layout/commit/eb22fe53316ae2cb84408ee88b82a23320f16dc5) options were published on master AFTER the 2.0.0-rc.1 release.  

> We plan a release of 2.0.0-rc.2 today or tomorrow.
