### ISSUE TITLE
Add support for divider (both horizontal & vertical)

### ISSUE THREAD

**Issue by thekalinga** [angular/flex-layout#210]
Since one of the most common things people do when using layout is adding dividers, its better to have a divider provided out of the box that supports both row & column layouts.

Do let me know what you think?

**Comment by ThomasBurleson** [comment]
@thekalinga - can you elaborate with more details and perhaps drawings/examples ?

**Comment by thekalinga** [comment]
@ThomasBurleson You seem to have commented here

https://github.com/angular/material/issues/2228#issuecomment-91526153

I'm look at it along the lines of this change

https://github.com/angular/material/commit/5e5e6cd2b02e2bb8d52580a49e1c5811568fdff6

**Comment by ThomasBurleson** [comment]
IMO, that is a Material component issue/feature NOT an @angular/flex-layout issue.

**Comment by thekalinga** [comment]
This a component that falls somewhere in between material & flex-layout.

We need the component framework to get the color, but we need the layout to support the dividers.

So, the core component should be in flex-layout, with option to set color, which can be set using material theme scss.

**Comment by thekalinga** [comment]
If you see the commits of that ticket, the style applied to this component has a lot to do with the layout, not any material component
