### ISSUE TITLE
fxFlex choosing wrong overlapping breakpoint on initial load

### ISSUE THREAD

**Issue by TylerDev6** [angular/flex-layout#213]
basically, <fxFlex="auto" fxFlex.gt-sm="33%" fxFlex.gt-md="50%" is choosing 33% even though gt-md qualifies.... only on initial page load.

Using 2.0.0-rc1. Behaviour is consistent across all browsers, and changing breakpoints corrects it.

**Comment by ThomasBurleson** [comment]
On page load, the mediaQueries will announce possible activations in the following order `gt-lg`, `gt-md`, `gt-sm`, `gt-xs`.  If both breakpoints qualify , the small (gt-sm) should show/activate; since gt-sm activates last; and has a greater range than gt-md.

Closing as "works as expected"

**Comment by TylerDev6** [comment]
Hmm, ok, so you're saying I need to change my targeting then?

**Comment by ThomasBurleson** [comment]
Perhaps you should provide a code Plunkr and explain your objectives/needs. But let's do that on the Forum.

**Comment by TylerDev6** [comment]
My approach has been "mobile first", so fxFlex="auto" is the setting I wish for my smallest viewport. I was then expecting it to expand as space allowed. 

If the observable announces changes in reverse order, then I just need to reverse my approach, using fxFlex for my largest viewport and switching to lt- aliases instead.

**Comment by ThomasBurleson** [comment]
Currently with @angular/flex-layout supports the following default breakpoint aliases:

*  **`xl`**, **`lg`**,  **`md`**, **`sm`**, **`xs`**, 
*  **`gt-xl`**,  **`gt-lg`**,  **`gt-md`**,  **`gt-sm`** ,   **`gt-xs`**, 

With release 2.0.0-rc.2, we will also have the following aliases:  

*  **`lt-xl`**,   **`lt-lg`**,  **`lt-md`**,   **`lt-sm`**,

**Comment by TylerDev6** [comment]
that's perfect, thanks!
