### ISSUE TITLE
Custom media query

### ISSUE THREAD

**Issue by patrikx3** [angular/flex-layout#219]
How can I trigger a media change for like custom 700px?

**Comment by ThomasBurleson** [comment]
We will document this **after** the RC2 release this week.

**Comment by c22shen** [comment]
Hi there, is there a way to customize the breakpoints for sm, md, lg etc. using flex-layout at this current moment? 

Thanks

**Comment by ThomasBurleson** [comment]
https://github.com/angular/flex-layout/wiki/Custom-Breakpoints

**Comment by skimcm** [comment]
Hi, when I follow the wiki page, I get errors such as  `RAW_DEFAULTS was not found`, `cannot find @angular/flex`, `cannot find name BREAKPOINTS`, etc. The doc seems not to be up to date. Did anyone successfully customized their own breakpoints?

Thanks!

**Comment by nivram80** [comment]
@skimcm I ran into the same issue.  It looks like `RAW_DEFAULTS` is now named `DEFAULT_BREAKPOINTS`.  However, I get a `Cannot read property 'mediaQuery' of undefined` error now.  I've posted a SO question addressing this issue:
http://stackoverflow.com/questions/43480783/cannot-read-property-mediaquery-of-undefined-custom-breakpoints-for-angular

**Comment by ThomasBurleson** [comment]
@nivram80 - Please open a new issue and include a Plunkr that demonstrates your issue.
