### ISSUE TITLE
Can't bind to ngClass.<breakpoint> or ngStyle.<breakpoint>

### ISSUE THREAD

**Issue by gatimus** [angular/flex-layout#221]
I get `Can't bind to 'ngClass.sm' since it isn't a known property of 'div'.` on this [plunker][1]. Could this be a bug or am I using the [flex-layout][2] api wrong?

  [1]: https://embed.plnkr.co/m8ZcRR2ZXgWdUwmdRXuc/
  [2]: https://github.com/angular/flex-layout

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.

**Comment by CDDelta** [comment]
Its a bug. Refer to #215. Should be fixed in the next release.
