### ISSUE TITLE
using gt-sm and gt-md at the same time

### ISSUE THREAD

**Issue by rkajbaf** [angular/flex-layout#222]
If you try to use both break point alias at the same time, the smaller "gt-sm" takes precedence and "gt-md" is never triggered.  Resizing the window such that the break points are triggered fixes things. Example code is below.

` <div class="content-container" class.gt-md="content-container xlg" class.gt-sm="content-container lg">
  <router-outlet ></router-outlet>
  </ div>
`

**Comment by ThomasBurleson** [comment]
This works as expected. Plz read [Using Responsive API](https://github.com/angular/flex-layout/wiki/fxShow-API#using-responsive-api)
