### ISSUE TITLE
Scrollbar issue in FF, IE11, Edge

### ISSUE THREAD

**Issue by gimmi** [angular/flex-layout#224]
The following HTML

```html
<div fxLayout="column" style="height: 150px;">
    <div fxFlex="50px">Header content</div>
    <div fxFlex fxLayout="row">
        <div fxFlex="300px" style="overflow: auto;">
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
            <p>Should scroll</p>
        </div>
        <div fxFlex>Main content</div>
    </div>
</div>
```

Render like this in Chrome

![image](https://cloud.githubusercontent.com/assets/6589/24021923/b256ef7a-0aa3-11e7-9b68-4447f64b585c.png)

But like this in FF, IE11 and Edge

![image](https://cloud.githubusercontent.com/assets/6589/24021953/e2e1450a-0aa3-11e7-9427-f9a7cdba6e4f.png)

With normal CSS Flexbox the solution is to add the following styling:

```css
div {
	min-width: 0;
	max-width: 100%;
	min-height: 0;
	max-height: 100%;
}
```

but this cannot be done using `flex-layout` because they will be override by stile on elements

**Comment by ThomasBurleson** [comment]
Issues are considered invalid without a working Plunkr or CodePen demo. 

---- 

#### Templates 

* [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=info)

**Comment by gimmi** [comment]
Here it is: [Demo](https://plnkr.co/edit/4sE3mxsdRaH5BxX3EPdp?p=preview)

**Comment by ThomasBurleson** [comment]
You need an overflow on the row below the header:

```html
<div fxLayout="column" style="height: 150px;">
    <div fxFlex="50px">Header</div>
    <div fxFlex fxLayout="row" style="overflow:auto;">
        <div fxFlex="300px" style="overflow: auto;">Column 1 </div>
        <div fxFlex> Column 2 </div>
    </div>
</div>
```

**Comment by gimmi** [comment]
Brillant! Thanks! 😄
