### ISSUE TITLE
Nested container breaking column layout in IE11

### ISSUE THREAD

**Issue by julianobrasil** [angular/flex-layout#226]
One project I recently deployed was supposed to run only in Chrome. Some of the users asked to use it in IE, and I said there was no problem with that since they avoided old versions of IE. Some of them, using Windows 10, like to use IE11, that is shipped  with Windows 10 as a legacy option. They reported one of the pages were completely messed up. I did some tests and, aparently, the problem is with nested containers.

I have an example plunkr of it: https://plnkr.co/edit/F21UkN60wm8jr7NaviGk?p=preview

There are no error messages in console.

Bellow is the page of the production environment in Chrome and then the same page in IE11:

Chrome:
![image](https://cloud.githubusercontent.com/assets/25405143/24046248/ab724076-0b00-11e7-838c-0ac3d6e1c10e.png)

IE11:
![image](https://cloud.githubusercontent.com/assets/25405143/24046131/4433a7e2-0b00-11e7-8f1d-4219671e5ca4.png)

**Comment by julianobrasil** [comment]
I think it's related to issue #5441. I'll try the fix later.

**Comment by ThomasBurleson** [comment]
@julianobrasil - We updated our Plunkr template. Please make sure your version(s) use these polyfills in the `index.html`:

```html
    <!-- Polyfills -->
    <script src="https://unpkg.com/core-js/client/shim.min.js"></script>
    <script src="https://unpkg.com/zone.js@0.7.4?main=browser"></script>
    <script src="https://unpkg.com/systemjs@0.19.39/dist/system.src.js"></script>

    <script src="lib/config.js"></script>
    <script>
    System.import('app')
      .catch(console.error.bind(console));
  </script>
```

**Comment by ThomasBurleson** [comment]
Here is what I see in my Chrome:

![screen shot 2017-03-19 at 7 56 05 am](https://cloud.githubusercontent.com/assets/210413/24081074/92cfb0c4-0c79-11e7-9b5b-8485e8f43da8.png)

> Which, of course, is not even close to your version above. 

General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'general discussion'. Thank you.
