### ISSUE TITLE
Source map path in npm release causing warnings

### ISSUE THREAD

**Issue by Londovir** [angular/flex-layout#227]
For 2.0.0-rc.1, the official package pulled down from npm has most of the compiled JavaScript files ending with a terminating `#sourceMappingURL` element bearing what appears to be a path to one of the author's folders. Namely, `/usr/local/google/home/mmalerba/flex-layout/src/lib...`. This causes most of my tooling (including webpack if an angular-cli project using this flex-layout is later ejected) to throw off a ton of warnings because the sourcemap url is invalid. These warnings also collect in Chrome's developer panel as well when Chrome attempts to load symbols from the sourcemaps.

Based upon other npm packages, it would seem the pathing shouldn't be included in the distribution so that the associated sourcemap provided in the package can be loaded.

**Comment by ThomasBurleson** [comment]
@mmalerba - I think we still need the `#sourcMappingURL`; but at least it should be a relative URL.  any thoughts? I

**Comment by mmalerba** [comment]
@hansl Do you know why these are being generated with an absolute path?

**Comment by ThomasBurleson** [comment]
Closing as not valid with Angular 4.1.x and beta.8
