### ISSUE TITLE
No way to center an image into a flex layout

### ISSUE THREAD

**Issue by frosiere** [angular/flex-layout#229]
The simple following piece of code does not seem to work:

```
<div fxFlex fxLayout="row" fxFlexAlign="center center">
  <img src="PATH_TO_A_PICTURE">
</div>
```
Plunker demo can be found [here](https://plnkr.co/edit/ATdKK0mVCqWBMTwAemv2?p=preview).

In a browser, the div covers the full width (can be checked by changing the background color or using the inspect tools of chrome) but the picture always stays at the beginning of the area. 

No way to center the picture horizontally or vertically.

Any ideas or workaround?

**Comment by ThomasBurleson** [comment]
The API you are using is wrong. Try this:

```html
 <div fxLayout fxLayoutAlign="center center" style="background-color:blue">
    <img src="https://blog.netapsys.fr/wp-content/uploads/2015/04/angularjs_logo.png">
    <h2>Another text</h2>
</div>
```

Closing as "invalid" (not an issue).
