### ISSUE TITLE
Full height (fxFlex - height 100%) does not seems to work

### ISSUE THREAD

**Issue by frosiere** [angular/flex-layout#230]
It looks difficult to have a div covering the full height of a screen.

Can you provide some support to define a div covering the full height?

The idea is to have an application footer but this footer will never appear to the end of the page due to this issue.

Some details can be found [here](https://plnkr.co/edit/gknT6wkWijBXBUr7qRWe?p=preview).

**Comment by peluprvi** [comment]
I also think the documentation can be improved (maybe the project is too young, but it can have simple examples).

Try out these changes:
```css
html, body {
  box-sizing: border-box;
  height: 100%;
  margin: 0;
}
```

```html
<div fxFlexFill fxLayout="column">
  <div fxFlex style="background-color:blue;">
    <h2>My app content</h2>    
  </div>
  <div>My footer</div>
</div>
````

`fxFlexFill` will fulfill the height of his parent (which comes from body).

**Comment by denkan** [comment]
Just ran into this myself. 
And what I needed, beside set `height: 100%` to `html,body` as @peluprvi  suggests, was to also add custom flex css for app root-element (the fx-directives won't affect the very root elem):
```
/* <app-root></app-root> */
:host { 
    min-height: 100%;
    display: flex;
}
```

@frosiere: Forked your plunkr:
https://plnkr.co/edit/0NqDpjCmzwMDubbwcIDJ?p=preview

**Comment by somombo** [comment]
@everyone  Is this not the same as https://github.com/angular/flex-layout/issues/162 ?

**Comment by somombo** [comment]
I am closing in favor of #162

**Comment by Upimage** [comment]
@denkan 
Redarding your plunker: https://plnkr.co/edit/0NqDpjCmzwMDubbwcIDJ?p=preview
There is a scrollbar visible on different browsers (FF, Chrome, Edge) and the footer is not readable. 
To get rid of the scrollbar, add the following lines in style.css
`test-app {
  height: 100vh;
  display: flex;
  min-height: 100vh;
}
`

**Comment by vikasrocky17** [comment]
**Instead of using** 
{
height : 100%
} 
**Use**
{
height: 100vh;
}

**Comment by simeyla** [comment]
Be super careful with 100vh on mobile devices. Test on a real device early to avoid disappointment!

100vh can be taller than the visible screen, due to toolbars appearing / disappearing or shrinking. It was concluded by browser vendors not to ever change the vh due to such activity. 

Note rotation is fine, but scrolling up and down `vh` won't change
