### ISSUE TITLE
fxShow and fxHide not working properly for phone and large device

### ISSUE THREAD

**Issue by lokeshdaiya** [angular/flex-layout#231]
```
<div fxHide  fxShow.gt-md  fxShow.xs fxFlex >
              Display on phone and large desktop.
    </div>
```

See behavior in chrome developer tool by changing device

**Comment by ThomasBurleson** [comment]
@lokeshdaiya - please provide a Plunkr.

**Comment by lokeshdaiya** [comment]
Here is the Plunkr  https://plnkr.co/edit/kUTzEB8WvJqDVRqTiT8j 
Standalone link for preview https://run.plnkr.co/l1sNZSDmAKjcq1WR/ 
Repro Steps
1. Open Standalone link  in chrome
2. Open developer tool and change the device for mobile view

----Large Desktop view-----
![image](https://cloud.githubusercontent.com/assets/7831299/24396582/51ce3010-13c1-11e7-8c4c-fdaba2e010ce.png)

-----Mobile view--------
![image](https://cloud.githubusercontent.com/assets/7831299/24396625/746601b6-13c1-11e7-8e18-602b6e7d0437.png)

Here we can see text is not displaying on mobile device

**Comment by ThomasBurleson** [comment]
This is working with the latest code in master. 

![showhide](https://cloud.githubusercontent.com/assets/210413/24409627/633172ca-1396-11e7-9714-9e0cd8101cd4.jpg)

> Here is the [Plunkr](https://plnkr.co/edit/kl7losZ0ZOVbnHW3ZRhS?p=preview).


Closing as *not an issue*.

**Comment by lokeshdaiya** [comment]
Thanks @ThomasBurleson
