### ISSUE TITLE
FxLayoutAlign="flex-end" renders as flex-start

### ISSUE THREAD

**Issue by cellsheet** [angular/flex-layout#232]
I'm wrapping my html in a div that looks something like `<div class="flex" fxLayout="column" fxLayoutAlign="flex-end center" fxLayoutGap="10px">` but when I go to inspect element, `justify-content` is set to `flex-start` and not `flex-end`

**Comment by xban1x** [comment]
Use "end center"

**Comment by ThomasBurleson** [comment]
While not a recommended usage, we should support the flexbox CSS versions also.
