### ISSUE TITLE
Support for Angular 4

### ISSUE THREAD

**Issue by jvbianchi** [angular/flex-layout#234]
Does this library has support for Angular 4?

**Comment by Jmadih** [comment]
Apparently not yet...
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/common@^2.2.3 but none was installed.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/core@^2.2.3 but none was installed.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none was installed.

Same thing for material ^^

**Comment by intellix** [comment]
I can confirm that it works with Angular 4. Have been using it for ages in production

**Comment by vangorra** [comment]
Sounds like the peer dependency needs to be set to 2 or 4.

**Comment by ThomasBurleson** [comment]
Fixed with https://github.com/angular/flex-layout-builds/blob/master/package.json#L25-L28

**Comment by matheusdavidson** [comment]
Not sure if i did something wrong, but i've started a new ng-4 project, installed flex-layout, load on app.module but flex-layout won't do(apply css) nothing.

**Comment by vinujan59** [comment]
Is this library supporting now?

**Comment by mackelito** [comment]
Yes
