### ISSUE TITLE
Enhanced ngClass directive not working

### ISSUE THREAD

**Issue by jurafa** [angular/flex-layout#241]
Trying to use enhanced ngClass directive gives this error:

```
Can't bind to 'ngClass.sm' since it isn't a known property of 'div'. 
("<div class="browser" [ERROR ->][ngClass.sm]="'small-device'">
```

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.
