### ISSUE TITLE
using fxLayoutGap does not consider children fxFlex?

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#242]
Might be me using this in the wrong way but here we go...
using fxLayoutGap together with fxFlex="33" results a broken layout

![screen shot 2017-03-29 at 9 04 49 am](https://cloud.githubusercontent.com/assets/210413/24458526/cc880e3c-145e-11e7-969d-a630fc5f16a6.png)

https://plnkr.co/edit/uGK8xUVyHbjGvjEqbDci?p=preview

> I guess this can be solved by setting it all in % like `fxLayoutGap="3%"`  `fxFlex="30%"`... but what if I want flex in 33% and then a 8px gap?

**Comment by ThomasBurleson** [comment]
**`fxLayoutGap`** adds a **margin-right**` for `layout="row"` and **margin-bottom** for `layout="column"` to all content children.

What layout are you trying to achieve (picture plz)?

**Comment by ocarreterom** [comment]
I can see `xfFlex="33"` in your code instead of `fxFlex="33"`. Is it the issue?

**Comment by mackelito** [comment]
The "issue" is when using fxLayoutWrap.
In the image you see that we have 2 items per rows.. but it should be 3 per row when using 33% right?

**Comment by mackelito** [comment]
I just saw this discussion https://github.com/angular/flex-layout/issues/165 and think it might be the same issue I´m having..

**Comment by fxck** [comment]
@mackelito https://github.com/angular/flex-layout/issues/134 would this solve your problem?
