### ISSUE TITLE
style is being added to parent element

### ISSUE THREAD

**Issue by dsoltesz** [angular/flex-layout#243]
`<div>`

    <div fxLayout="row" fxLayoutAlign="start start" fxFlex.xs="100" fxFlex.sm="50" fxFlex.md="33" fxFlex.lg="33" fxFlex="25">
        <div [routerLink]="['/program/search']" routerLinkActive="active" class="homeModule" fxLayout="column" fxLayoutAlign="center center">
            <i class="fa fa-search" aria-hidden="true"></i>
                    </div>
    </div>
`</div>`

when I run the parent div is getting a style added onto which is throwing off my layout

`<div style="display: flex;box-sizing: border-box;flex-direction: row;-webkit-box-orient: `horizontal;-webkit-'box-direction: normal;">

Have no idea where or why this style is being added.  I'm using angular animiations so it could be added something to parent  If I remove the flexLayoutModule that style no longer appears in the markup

**Comment by dsoltesz** [comment]
This seems to be an issue with angular animations and not flex

**Comment by LennyThompson** [comment]
I am having the same issue since updating to angular 4.1 and it is not related to angular animations, but does seem to be related to recent updates, just wondering if anyone else has been having the same issue?

**Comment by ThomasBurleson** [comment]
@LennyThompson - this is related to #272

**Comment by LennyThompson** [comment]
Thanks Thomas, I have 'resolved' my problem by adding a suitable fxLayout to the parent element to preserve the layout.
