### ISSUE TITLE
IPad Rendering Issues -- flex ordering and nested fxFlexFill

### ISSUE THREAD

**Issue by mmartimo** [angular/flex-layout#244]
I have an application that is experiencing a couple issues (hopefully just user error???) as demonstrated at: https://plnkr.co/fcsPtbnXVVxTmTuVcpoa

With the desktop versions of Chrome or Edge, the application shows as:
![chromefine](https://cloud.githubusercontent.com/assets/874426/24624321/7e01a510-1879-11e7-8e28-5622db4f0b07.png)

However on an iPad with either Safari or Chrome it shows as:
![ipadfail](https://cloud.githubusercontent.com/assets/874426/24624391/bbb76d0e-1879-11e7-97fb-60048f23621c.png)

First issue is the ordering of the flex div...   on the desktop it shows (as desired) in the order in the HTML, on the iPad the plain fxFlex (yellow) shifts to the bottom.
`<div fxFlexFill fxLayout="column" fxLayoutAlign="start stretch">`
`    <div fxFlex="100px"...>`
`    <div fxFlex="100px"...>`
`    <div fxFlex></div>`
`    <div fxFlex="100px"...>`
`</div>`

Second issue is the nesting of a fxFlexFill div...   on the desktop it shows as all blue (as desired), on the iPad it sizes to the content (small blue div in large black area).
`<div fxFlex style="background-color:black; color: white;">`
`  <div fxFlexFill style="background-color:blue; ...>`
`</div>`

**Comment by intellix** [comment]
Safari doesn't support Flex :)

**Comment by mackelito** [comment]
@intellix http://caniuse.com/#search=flex%20box

**Comment by mackelito** [comment]
This problem will also appear on Safari on Mac. 
Perhaps this will give you some idea to a solution: https://plnkr.co/edit/DT8oplpg68QCriPbgQKQ?p=preview

Happy coding! :)

**Comment by intellix** [comment]
Related:
https://github.com/angular/flex-layout/issues/103
https://github.com/angular/flex-layout/issues/162
https://github.com/angular/flex-layout/issues/201

**Comment by mmartimo** [comment]
I'm really sorry, but I'm really stuck...   somehow I am missing something fundamental.  

@mackelito I'm not sure what to take away from the fork to my Plunker you prepared.  Beyond the "display: block;" on the body?

I get the concept that the parent needs to have height defined to calculate/display correctly in safari...   I however don't observe any difference when attempting to implement others' solutions via issues 103, 162, 201.    I have an updated Plunker where I've attempted each of the following with no change in display:
1. add "display: block;" to full screen body and friends to initialize.
2. For any naked "flex" that could be a "column", add style="flex: 1 1 100%; min-height:100vh;" to the element.
3. Add "flex: 1 0 auto !important;" to the parent layout elements that are not correctly being filled to their children's heights.

https://plnkr.co/VxJ7CHEDRK04j65uaytn

Thanks for your patience with me...  any additional guidance is very much appreciated.

**Comment by HarelM** [comment]
I had what I believe is a similar issue.
See the following issues:
https://github.com/IsraelHikingMap/Site/issues/461
https://github.com/IsraelHikingMap/Site/issues/458
What solved the problem for me was to remove all usages of `flexLayout='column'` from the html.
You can see the relevant commits related to these issues.

Any plans to fix this?
This is affecting iPhone and iPad users - which is a big portion of my mobile traffic...

**Comment by sofarojo** [comment]
Having this problem on Safari on MAC. This is not only a IPhone/Ipad issue.

Is it possible to raise the priority? Thanks :)

**Comment by CaerusKaru** [comment]
The Plunkrs no longer work. Can anyone confirm if this is still an issue with the latest beta?

**Comment by HarelM** [comment]
If this wasn't a year old reported issue I might have been able to help. But since then and due to the fact that this was completely ignored I have changed all my code to workaround this issue.
You can still try and use the code that is linked in the issues I fixed.

**Comment by CaerusKaru** [comment]
I'm going to close this issue. We can reopen if someone else runs into this and can produce a new demo.

**Comment by HarelM** [comment]
So you can ignore it for a year? thanks, but I'll pass...
