### ISSUE TITLE
FxLayout binding using ternary operator

### ISSUE THREAD

**Issue by gbagretsov** [angular/flex-layout#247]
Is it possible to use a ternary operator as a value for `fxLayout` attribute? None of the following work:

```html
<div [fxLayout]="true ?  column  :  row "></div>
<div [fxLayout]="true ? 'column' : 'row'"></div>
<div   fxLayout="true ?  column  :  row "></div>
<div   fxLayout="true ? 'column' : 'row'"></div>
```

**Comment by CaerusKaru** [comment]
The second option you provided should work, I just tested it on the latest version of Flex.

Intuitively, this is more of an Angular issue that a Flex issue. We can't possibly interpolate/coerce values based on template variables we don't have access to.

If you want this functionality, my suggestion is use option 2 listed above, or better yet, store the value in a variable in your component that is set to either `row` or `column` based on some action.

Closing as a non-issue.
