### ISSUE TITLE
Importing the FlexLayoutModule breaks fxFlex usage in my templates

### ISSUE THREAD

**Issue by scionwest** [angular/flex-layout#251]
I have the following template, using Material 2.

```html
<div fxLayout="column" fxFlex>

  <md-toolbar color="primary">
    <span>Foo Bar</span>
  </md-toolbar>

  <md-sidenav-container fxFlex>
    
    <md-sidenav mode="side" opened>
      <span>Sidenav</span>
    </md-sidenav>

    <div class="content" fxLayout="column">      
      <span>Foo</span>
      <span>Foo</span>
      <span>Foo</span>
      <span>Foo</span>
    </div>
  </md-sidenav-container>

  <button md-fab class="fab-bottom-right">
    <md-icon>add</md-icon>
  </button>

</div>
```

When I add the `FlexLayoutModule` to my app module, the `fxFlex` usage on the `md-sidenav-container` breaks. It has it's calculated height set to 0px for some reason. I can remove the import, and the `fxFlex` directive goes back to working as intended.

This is a plunker demonstrating the issue. Uncomment the `FlexLayoutModule` import in `main.ts` to see the `md-sidenav-container` not respect the `fxFlex` directive. http://plnkr.co/edit/QcUDfRNiLmRLvl2hBZB7?p=preview

Why does importing a module change the behavior of a directive?

**Comment by ThomasBurleson** [comment]
In vertical mode (aka `flex-direction:column`), Flexbox has known layout issues without a specific parent sizing.  See [Plunkr](https://plnkr.co/edit/CqtbrvaxPyDY3IW3waWA?p=preview) where I simply explicitly set the wrapper div height:

```html
<div fxLayout="column" style="min-height:98vh;width:100%">
```

![screen shot 2017-08-28 at 9 42 02 pm](https://user-images.githubusercontent.com/210413/29802273-c5254148-8c39-11e7-9d78-096c35fad20b.png)


> Closing as not a flex-layout issue!
