### ISSUE TITLE
Significant performance overhead with Flex Layout

### ISSUE THREAD

**Issue by tuanl** [angular/flex-layout#253]
In our performance benchmark test, I am seeing a noticeable increase in Javascript execution time when using the Flex Layout library.
With flex-layout: 967 ms
Without flex-layout: 358 ms
For the test without flex-layout, I did not install the flex-layout module.

**Comment by jelbourn** [comment]
Would be good to profile this with static CSS classes and media queries vs. them being applied via Angular directives.

**Comment by ThomasBurleson** [comment]
@tuanl - There are identified situations where manual flexbox CSS will be more performant than inject Flex-Layout, inline CSS:  

Tables with LARGE rows should NOT use Flex-Layout API on the table's child row items.

Flex-Layout will address these situations only with Best-Practices documentation. If your situation is different, you will need to provide a Plunker that demonstrates this performance issue.

**Comment by ThomasBurleson** [comment]
@tuanl, @jelbourn - FYI  https://github.com/angular/flex-layout/issues/233#issuecomment-289578370.
