### ISSUE TITLE
layout not working in Safari v8

### ISSUE THREAD

**Issue by karlhaas** [angular/flex-layout#259]
According to http://caniuse.com/#feat=flexbox there are many browser versions which just support flexbox with a prefix. Currently we can see that the layout is not working in Safari 8. Is this a bug or does the project not support prefixes? 97% of all browsers would be ok for our project, 86% not really.

**Comment by ThomasBurleson** [comment]
Evergreen browsers do not include S8. See

http://caniuse.com/#feat=flexbox

**Comment by karlhaas** [comment]
@ThomasBurleson why does the project not support browsers which need a webkit prefix?

**Comment by karlhaas** [comment]
Maybe just https://github.com/angular/flex-layout/blob/master/src/lib/utils/auto-prefixer.ts#L18 causes the issue. 
I will provide a PR (https://github.com/angular/flex-layout/compare/master...karlhaas:fix-display-prefixes) if it works on Safari 8.

**Comment by ThomasBurleson** [comment]
Thx @karlhaas. Is this legal:

```js
switch (key) {
      case 'display':
        if (value === 'flex') {
          target['display'] = [
            '-webkit-box',
            '-moz-box',
            '-ms-flexbox',
            '-webkit-flex',
            'flex'
          ];
        } else {
          target['display'] = value;
        }
        break;
```

**Comment by karlhaas** [comment]
@ThomasBurleson I found this solution [here](https://css-tricks.com/using-flexbox/)

**Comment by karlhaas** [comment]
@ThomasBurleson it works in iOS8 now. PR: https://github.com/angular/flex-layout/pull/276

**Comment by karlhaas** [comment]
@ThomasBurleson see https://github.com/angular/material2/issues/4385#issuecomment-306304467
