### ISSUE TITLE
waterfall layout

### ISSUE THREAD

**Issue by lghinet** [angular/flex-layout#261]
hello,
any idea how can i implement a waterfall layout like this one https://xudafeng.github.io/autoresponsive-react/ 

![screen shot 2017-06-22 at 5 25 46 pm](https://user-images.githubusercontent.com/210413/27458685-e410e660-576f-11e7-8e0e-d5abdd7663e8.png)

**Comment by CaerusKaru** [comment]
As far as I can tell, that module and other jQuery plugins that implement the "masonry" layout all use manual positioning hacks to calculate the position of the tiles. I don't see an obvious way to do this with CSS Flexbox, so I think you're out of luck for an easy solution. Fortunately, if you don't mind using jQuery, there are plenty of plugins that will do this for you that do not require React.

Closing for now unless someone else can come up with a Flexbox solution, in which case I would be happy to add it to the docs.

**Comment by ThomasBurleson** [comment]
@lghinet - AngularJS Material has a [GridList Component](https://material.angularjs.org/latest/demo/gridList) that does something similar:

![screen shot 2018-03-21 at 10 25 58 pm](https://user-images.githubusercontent.com/210413/37749656-f6c48f9c-2d56-11e8-94a5-117a3d0bbdee.png)

You will see that the component source is quite manual and non-trivial. It does not use CSS Grid nor Flexbox CSS.
