### ISSUE TITLE
add npm install for the angular 4 

### ISSUE THREAD

**Issue by George35mk** [angular/flex-layout#264]
I use angular 4 and I don't know from were to install that lib - component in my project

some repositories have npm install lib-name on top of the readme
the flex layout  don't have that on readme, were I know that, is not the wrong repository

i and by using that lib https://www.npmjs.com/package/ng2-flex-layout i was thinkig that is the  npm package for that lib

**Comment by ThomasBurleson** [comment]
@George35mk - use `npm install @angular/flex-layout`
