### ISSUE TITLE
I suggest you update README.md

### ISSUE THREAD

**Issue by TaylorPzreal** [angular/flex-layout#265]
When i find this and want to use it in my workstation, i can't find how to use from README.md and npm straight, i found it in gitter, so i hope add how to use flex-layout in README.md.
for example: 
```
INSTALL:
yarn add @angular/flex-layout@latest

ADD TO app.module.ts:
import { FlexLayoutModul } from '@angular/flex-layout';

@NgModule({
  imports: [ 
    FlexLayoutModul
  ]
})

```
and more api documentation is [here](https://github.com/angular/flex-layout/wiki/API-Documentation)

**Comment by ThomasBurleson** [comment]
*  Updated Npm README:  https://github.com/angular/flex-layout/blob/master/tools/scripts/release/npm_assets/README.md
> available on/after next release.

*  Updated [Wiki: Fast Start](https://github.com/angular/flex-layout/wiki/Fast-Starts)
