### ISSUE TITLE
was not found in '@angular/core'

### ISSUE THREAD

**Issue by yubeen** [angular/flex-layout#267]
![2017-04-27 10 52 08](https://cloud.githubusercontent.com/assets/25659743/25464494/a7cc356a-2b37-11e7-890a-6e99d5c3c6c1.png)

I want no versions upgrade. 
before, no error. suddenly made error
Solution is only versions upgrade?
any idea?
if solution is only versions upgrade, What do I need to amend?

"dependencies": {
    "@angular/animations": "^4.0.3",
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.0.7",
    "@angular/flex-layout": "^2.0.0-beta.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "browser-sync": "^2.18.6",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "ng2-charts": "^1.5.0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "typescript": "^2.2.2",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }

**Comment by Lyoko-Jeremie** [comment]
maybe case by version [2.0.0-beta.8 (2017-04-18)](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#200-beta8-2017-04-18)

```
BREAKING CHANGES
These changes to @angular/flex-layout will require Angular v4.x and will not be compatible with Angular v2.x.
```

**Comment by ThomasBurleson** [comment]
@Lyoko-Jeremie - Thx. In fact, Angular 4.1 or higher is required... due to changes in AOT requirements.
