### ISSUE TITLE
ngStyle conflict with ngStyle.alias

### ISSUE THREAD

**Issue by alexfung888** [angular/flex-layout#273]
Supposedly they are independent

```
<div
  [ngStyle]="{'transform': slideStyleString, 'transition': 'transform 0.75s ease-in-out'}"
  [ngStyle.xs]="{'color': 'green'}"
>TESTING</div>
```
However, if you can the value of `slideStyleString` above, the color will be lost.

Problem exists in 2.0.0-beta.7 and 2.0.0-beta.8.
Problem not present in 2.0.0-rc.1

[See plunker. HTML is in src/app/test-app.ts](https://plnkr.co/edit/AnvTM3rL473EMqBqKWHY?p=preview)
The first DIV stays in color. Click the slide out button and the second DIV loses color and turns black.

**Comment by alexfung888** [comment]
An even simply example:
```
<div
  [ngStyle]="{'fontSize': sizeString}"
  [ngStyle.xs]="{'color': 'green'}"
  [ngStyle.sm]="{'color': 'red'}"
  [ngStyle.md]="{'color': 'blue'}"
  [ngStyle.lg]="{'color': 'purple'}"
  [ngStyle.xl]="{'color': 'pink'}"
>TESTING</div>
<button (click)='sizeString="20pt"'>Size 20</button>
<button (click)='sizeString="10pt"'>Size 10</button>   
```

**Comment by ThomasBurleson** [comment]
@alexfung888 - While the [ngStyle Wiki](https://github.com/angular/flex-layout/wiki/ngStyle-API#merging-styles) says styles will be merged. Let me confirm again Angular core expectations.

**Comment by M-Adoo** [comment]
@ThomasBurleson  Any progress on this one ?

**Comment by mackelito** [comment]
@ThomasBurleson will this be fixed in the upcoming release?

**Comment by ThomasBurleson** [comment]
no. This fix will be available in Beta.10 (or new RC1 if we can overwrite the existing invalid one).

**Comment by ThomasBurleson** [comment]
The latest nightly build provides fixes for ngStyle

![screen shot 2017-09-15 at 5 54 22 pm](https://user-images.githubusercontent.com/210413/30506125-f8c4b6e2-9a3e-11e7-8b47-de6b5c98da43.png)

```html
<div
        [ngStyle]="{'color': 'red', 'fontSize': sizeString}"
        [ngStyle.xs]="{'color': 'green'}"
        [ngStyle.sm]="{'color': 'red', 'fontSize': '12pt'}"
        [ngStyle.md]="{'color': 'blue'}"
        [ngStyle.lg]="{'color': 'purple'}"
        [ngStyle.xl]="{'color': 'pink'}" >
</div>
```

If the responsive key will override a default, the default must contain that style key.

**Comment by ThomasBurleson** [comment]
This is now working similar in functionality to [ngStyle] in core. 

![sample1](https://user-images.githubusercontent.com/210413/30512495-e974c33a-9ab6-11e7-8dec-9805219baaac.jpg)

**Comment by ricardosaracino** [comment]
is this broken again? or is it just me? I just updated to angular 8

> TypeError: this._delegate.setNgStyle is not a function

`<span [ngStyle.xs]="{'display': 'block'}">{{buildNumber}}</span>`

`"@angular/flex-layout": "^7.0.0-beta.19",`
