### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by HarelM** [angular/flex-layout#274]
I'm not sure if I'm configuring this incorrect of that this library doesn't support RTL content.
The following is my layout html:
```html
<div fxLayout="row" fxLayoutAlign="space-between none">
        <div fxFlex="20">
            <md-slide-toggle [(ngModel)]="advanced"></md-slide-toggle>
        </div>
        <div fxFlex="60">
            <span (click)="advanced = !advanced"><i class="fa icon-gear"></i> {{resources.toggleAdvancedSettings}}</span>
        </div>
        <div fxFlex>
            <div fxLayout="col" fxLayoutAlign="start end">
                <span class="cursor-pointer" (click)="closeSidebar()"><i class="fa fa-lg icon-close"></i></span>
            </div>
        </div>
    </div>
```
What I want to accomplish is close to the following:
![image](https://cloud.githubusercontent.com/assets/3269297/25639690/7d16b004-2f95-11e7-9e53-f8b2e1cbe443.png)
Only the "X" in the image should be aligned to the end, which in RTL case is left instead of right.
I'm using angular 4 with `[dir]="rtl"` directive so I was hoping this is in sync with angular's RTL support...

**Comment by HarelM** [comment]
Sorry, my mistake.
Here is the correct code:
```html
<div fxLayout="row" fxLayoutAlign="none none">
        <div fxFlex="20">
            <md-slide-toggle [(ngModel)]="advanced"></md-slide-toggle>
        </div>
        <div fxFlex="60">
            <span (click)="advanced = !advanced" class="cursor-pointer"><i class="fa icon-gear"></i> {{resources.toggleAdvancedSettings}}</span>
        </div>
        <div fxFlex>
            <div fxLayout="col" fxFill>
                <span fxFill fxLayoutAlign="end start" class="cursor-pointer" (click)="closeSidebar()"><i class="fa fa-lg icon-close"></i></span>
            </div>
        </div>
    </div>
```

**Comment by HarelM** [comment]
Well, now I'm not sure again...
The offset seems to be in the wrong place:
![image](https://cloud.githubusercontent.com/assets/3269297/25641300/094375c0-2f9c-11e7-8782-db1afff1fc24.png)
The css of the above elements shows:

```
element.style {
    flex: 1 1 100%;
    box-sizing: border-box;
    -webkit-box-flex: 1;
    max-width: 75%;
    margin-left: 15%;
}
```
setting margin-right:15% solves this, but I'm not sure how to really solve this, does seems like a bug.
the following is the html:
```html
<div fxFlexOffset="15" fxFlex="75">
            <span>{{resources.addBaseLayer}}</span>
        </div>
```

**Comment by ThomasBurleson** [comment]
@HarelM - We need a Plunkr to test and validate against. Thx.

**Comment by HarelM** [comment]
remove the dir="'rtl'". when putting it back on you should get a mirror image of the ltr version.
https://plnkr.co/edit/Pdmk94iCqGjmquDPcfU3?p=preview
This is not the case.
I haven't fully checked all other scenarios and it does feel that it's not exactly mirroring as it should but I don't have another case to show currently.

**Comment by ThomasBurleson** [comment]
Thx. We will investigate.

**Comment by Eddygn** [comment]
Hi, 

Any (non manual CSS) workaround/solution for this issue ?

https://plnkr.co/edit/HOuHtMbH6mznoQpgHl6a?p=preview

**Comment by HarelM** [comment]
The following is another issue I now see with the RTL support:

FlexLayoutGap="10px" inside a [dir]="'rtl'" 
`margin-right="10px"` is added

Expected behavior:
`margin-left="10px"` should be used in this case

Version: 2.0.0-beta.9

basically the following code, thought not fully tested:
```html
<div  [dir]="'rtl">
  <div fxLayout="row" fxLayoutGap="10px">
    <div fxFlex="70">
      the gap is before this element instead of after
    </div>
    <div fxFlex>
       Should be a gap between this and the previous one
    </div>
  </div>
</div>

**Comment by axmad22** [comment]
Did you find a solution to this, by the way this happens even with fxLayout="row-reverse", it places the gap on the wrong side

**Comment by HarelM** [comment]
The workaround I found was to use css instead, I know this is a poor workaround but unfortunately I don't have time to fix the bug here...

**Comment by atscott** [comment]
Can I ask why this was set to P5? This seems very important in order to support RTL languages.

**Comment by Eddygn** [comment]
Looks like the plunkers no longer work, so here the same with the stackblitz template. 

https://stackblitz.com/edit/angular-flex-layout-seed-eb7gve?file=app/test.component.ts

As of now, in practice it can't be used in RTL, it's easier to just use pure CSS (or any other solution).

**Comment by atscott** [comment]
Thanks for the demo!
I would really like to help fix this problem, as it's more like a P0 for any team (including my own) that needs to support RTL.
At least a partial fix seems relatively straightforward. The material2 library has this injectable for looking at the direction on the document/body: https://github.com/angular/material2/blob/master/src/cdk/bidi/directionality.ts
If this library had a similar one and then simply set margin-left in layout-gap instead of margin-right and margin-right instead of margin-left in flex-offset, that would be really helpful.

Unfortunately, I can't get the tests to run so I can't really make much progress on this myself.
