### ISSUE TITLE
Flex-layout with angular4

### ISSUE THREAD

**Issue by kirtiesl** [angular/flex-layout#278]
Could you please provide an working demo of fxShow and fxHide with angular 4.
I am using 2.0.0-beta.4 version of flex-layout.

**Comment by kirtiesl** [comment]
any update??

**Comment by ThomasBurleson** [comment]
@kirtiesl - @angular/flex-layout (beta.8) requires Angular 4.1.or higher: https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes
