### ISSUE TITLE
Using fxFlex attribute affects component container

### ISSUE THREAD

**Issue by Samushel** [angular/flex-layout#281]
When using the `fxFlex` attribute in a element inside a component the component container is being affected with flex styling.

I went and modified the official Plunkr from the documentation and this is what I get:

![withflex](https://cloud.githubusercontent.com/assets/14022771/25918035/993c2070-358f-11e7-9188-7025faf7d32f.png)

After removing `fxFlex` from the container the component behaves as it should:

![withoutflex](https://cloud.githubusercontent.com/assets/14022771/25918066/b656e24e-358f-11e7-8469-6fc903faeb59.png)

[Here is the modified code](https://plnkr.co/edit/pSOjIN)

**Comment by ThomasBurleson** [comment]
Related to #272

**Comment by ThomasBurleson** [comment]
Closing as duplicate
