### ISSUE TITLE
fix(auto-prefixer): resolve perf impacts as reported by LightHouse

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#282]
*  Order of flex properties should be improved to use `display: flex` last.
*  missing standard property `display: -webkit-flex;`
*  mistakenly using `display: -moz-box;`

See

*  https://github.com/GoogleChrome/lighthouse/issues/1710#issuecomment-294470505
*  https://github.com/GoogleChrome/lighthouse/issues/2022#issuecomment-295022719

**Comment by ThomasBurleson** [comment]
Has PR #283

**Comment by ethanroday** [comment]
@ThomasBurleson, removal of `--webkit-box` in #283 means that flex layouts will no longer work in UC Browser, which has ~10% share WW.
Was there a functional reason for this change, or was it just to save some lines of CSS?

**Comment by jelbourn** [comment]
We aim to mostly support "modern" browsers- ultimately we have to draw the line somewhere. In this case we decided that supporting the final flex spec is necessary to be considered "modern".
