### ISSUE TITLE
Which version of flex-layout is supported in Angular v2.4.10?

### ISSUE THREAD

**Issue by MythriManjunath** [angular/flex-layout#284]
I am using Angular v2.4.10. I want to install flex-layout for Angular v2. But the latest version (2.0.0-beta.8) of @angular/flex-layout will require Angular v4.x and will not be compatible with Angular v2.x from this link https://github.com/angular/flex-layout-builds/blob/master/CHANGELOG.md. And it says that flex-layout is supported in Angular(v2.4.3 and higher)from this link https://github.com/angular/flex-layout/wiki. I tried to install previous beta version, but it doesn,t work.Which version of flex-layout is compatible with Angular v2?

**Comment by ThomasBurleson** [comment]
2.0.0-beta.7 will work with NG2.4.10 + AOT.
> Note this version will not be supported for issues.

**Comment by MythriManjunath** [comment]
@ThomasBurleson Okay Thank you.
