### ISSUE TITLE
NativeScript support

### ISSUE THREAD

**Issue by buu700** [angular/flex-layout#285]
In theory, it should be possible for @angular/flex-layout and NativeScript to work great together, since recent releases of NativeScript support Flexbox CSS. I haven't tested using the two together yet, but based on the comments in #187 I see that there is still some dependency on the DOM.

How much effort would need to go into making this work? Will solving #187 get us close?

**Comment by NickIliev** [comment]
Hey @buu700 we have alredy implemented a [FlexBoxLayout ](http://docs.nativescript.org/angular/code-samples/ui/layouts.html#flexbox-layout-one)for NativeScript Angular. That said it is not our priority to implement features that already has related modules created in NativeScript but of course NativeScript is open source and each community member may become a contributo.

**Comment by ThomasBurleson** [comment]
@buu700 - Let's have a conf call next week and solve this with a pairing on ideas ?

**Comment by buu700** [comment]
Sure, sounds good to me. I'll go ahead and email you to schedule that.

**Comment by ThomasBurleson** [comment]
@buu700 - sent you a Hangout invite for July 13.

**Comment by CaerusKaru** [comment]
#187 has been closed and Flex Layout now no longer relies explicitly on the DOM. Is this sufficient, @buu700?

**Comment by buu700** [comment]
Nice, glad to hear that! I don't know enough about flex-layout or NativeScript internals to answer that offhand with certainty, but I'll test out the combination some time soon and report back here on the result.

**Comment by CaerusKaru** [comment]
Closing this for now, if there is a renewed need for involvement from us, we can reopen.
