### ISSUE TITLE
router-outlet issues

### ISSUE THREAD

**Issue by henriqueweiand** [angular/flex-layout#287]
I'm trying to put three divs with fxFlex inside a router-outlet and it does not seem to work correctly. I took some prints to try to better exemplify my problem.

In this case, no router-outlet is correct.

![print1](https://cloud.githubusercontent.com/assets/6539492/26062536/7a4b6b6e-3961-11e7-919d-ebc744d5ee92.png)

With router-outlet and content passed into the called component, it goes wrong:

![print2](https://cloud.githubusercontent.com/assets/6539492/26062541/7d844c56-3961-11e7-88d2-a038d891b36d.png)

This imported FlexLayoutModule in the root module as well as for the component called in the rotuer-outlet

**Comment by ThomasBurleson** [comment]
@henriqueweiand - `<router-outlet>` is not really a DOM container. It is a actually a marker for projected content. So attributes and directives on the `<router-outlet>` are useless. 

You will need to use encapsulate your projected content in a class within a wrapper child:

```js
@Component({
  select : 'main-content',
  template : `
    <div fxLayout="row" fxFlex>
      <div fxFlex       style="..."> content_1 </div>
      <div fxFlex="70"  style="..."> content_2 </div>
      <div fxFlex       style="..."> content_3 </div>
    </div>
  `
})
Class MainContent { }
```
