### ISSUE TITLE
Space between fxFlex not work with fxLayoutWrap and fxLayoutGap?

### ISSUE THREAD

**Issue by henriqueweiand** [angular/flex-layout#288]
I'm using layout-flex to format the fields of a form and in this format I have the following problem:

![sem titulo](https://cloud.githubusercontent.com/assets/6539492/26154764/29776d00-3ae7-11e7-9f5d-681679051107.png)

Code:
![2](https://cloud.githubusercontent.com/assets/6539492/26154862/9858cc28-3ae7-11e7-969c-8159eb4e64d2.png)

Should not the spacing applied by fxLayoutGap be between the elements? So in the example above what should happen would not be a reduction of the first two fxFlex = "50" to contain the spacing and still mater in only one line?

**Comment by mackelito** [comment]
What happens if you wrapp each <md-input-container> inside a div?

**Comment by henriqueweiand** [comment]
You mean like that?

![3](https://cloud.githubusercontent.com/assets/6539492/26155441/88148058-3ae9-11e7-838a-b124ec71c9ba.png)

The result is the same ... :(

**Comment by mackelito** [comment]
I think it´s a good idea to seperate material components and layout.
Try putting all fx* attributes to divs and have the material components inside..

something like this:
```
<div fxLayout="row" fxLayoutWrap fxLayoutAlign="center">
  <div class="product-wrapper" fxLayoutAlign="strech" fxFlex="50">
    <md-card></md-card>
  </div>
  <div class="product-wrapper" fxLayoutAlign="strech" fxFlex="50">
    <md-card></md-card>
  </div>
  <div class="product-wrapper" fxLayoutAlign="strech" fxFlex="50">
    <md-card></md-card>
  </div>
</div>
```

**Comment by MiguelAngelLV** [comment]
I have the same problem.

I see that fxFlex="50" add "max-width=50%"  to the style and fxLayoutGap="25px" to the margin...

So,  (50% + 25px) * 2 = 100% + 50px

**Comment by ThomasBurleson** [comment]
Please refer to the [fxLayoutGap Wiki Docs](https://github.com/angular/flex-layout/wiki/fxLayoutGap-API).

#### Rendered Layout without gap considerations:

![screen shot 2017-05-20 at 4 03 37 pm](https://cloud.githubusercontent.com/assets/210413/26279328/19c32142-3d76-11e7-826c-837603a6db76.png)

#### Rendered Layout **WITH* gap considerations:

![image](https://cloud.githubusercontent.com/assets/210413/26279332/2dfe9d76-3d76-11e7-810b-e15cbcd5dd21.png)

----

```html
<md-card fxFlex fxFlexAlign="start">

    <md-card-content>
      <div fxLayout fxLayout.xs="column" fxLayoutWrap fxLayoutGap="25px">
        <md-input-container fxFlex="calc(50%-25px)">
          <input mdInput placeholder="Name">
        </md-input-container>
        <md-input-container fxFlex="calc(50%-25px)">
          <input mdInput placeholder="Occupation">
        </md-input-container>
        <md-input-container fxFlex="calc(50%-25px)">
          <input mdInput placeholder="Compnay">
        </md-input-container>
      </div>
    </md-card-content>

    <md-card-actions>
      <button md-button>Anterior</button>
      <button md-button>Proximo</button>
    </md-card-actions>
</md-card>

**Comment by ThomasBurleson** [comment]
Works as expected.

**Comment by henriqueweiand** [comment]
Right, but in his example, should the occupation of the "company" field not have applied the same calculation? Why are you taking 100%?

![2dfe9d76-3d76-11e7-810b-e15cbcd5dd21](https://cloud.githubusercontent.com/assets/6539492/26428237/fb68a58e-40b6-11e7-883f-d402ab6ba238.png)

**Comment by awhitehouse104** [comment]
@ThomasBurleson In your example, you have `fxFlex="calc(50% - 25px)"` for 3 fields, and one of them takes up the full width. Why would that be expected?

**Comment by ThomasBurleson** [comment]
@awhitehouse104 

* fxLayoutGap does not apply a margin-right to the last element.
* `fxLayout="calc(50% - 25px);"` applies the following css:

```css
  flex: 1 1 calc(50% - 25px);
  min-width: calc(50% - 25px);
```
So the flex-basis is `calc(50% - 25px)` which applies constraints after the element default content sizing is determined.

Here is the [StackBlitz Demo](https://stackblitz.com/edit/angular-fxlayoutgap-calc?file=app%2Fapp.component.html) for this. 

>  If you have any suggestions on how to improve this... we would be interested.

**Comment by awhitehouse104** [comment]
@ThomasBurleson Thanks for the quick response. I do think it's non intuitive and it also creates an issue where the inputs don't quite line up correctly (you can see how Company in the example extends further than the others and it's even more obvious when there are 4 inputs rather than 3). I don't have a solution yet but I'll play around with it.

**Comment by CaerusKaru** [comment]
Should be fixed by #667. Please take a look at the PR and add any comments you might have there. You can pull from the remote branch and build the library to test in your own apps.

**Comment by blogcraft** [comment]
fxLayoutGap and wrap leave an anoying margin at the end of the rows.

Is there a way to fix this?

[https://angular-fxlayoutgap-calc-mralnz.stackblitz.io](url)

**Comment by webia1** [comment]
Suggestion: `fxLayoutGap`  should be taken into account out of the box, without the necessity to calculate anything anew manually.  All these extra efforts simply make the code illegible. 

If I have two div boxes with 50% width, I mean 50% of the remainder: 

    i. E. 50% of `current-screen-width` - `fxLayoutGap`. 

In my humble opinion, such a thing would be really intuitive, what do you think?
