### ISSUE TITLE
(chore): Remove reflect-metadata as a dependency

### ISSUE THREAD

**Issue by amcdnl** [angular/flex-layout#29]
reflect-metadata is a dependency but it is not needed when used with core-js...
 
```
"dependencies": {
    "reflect-metadata": "^0.1.8",
  },
```

instead use:

```
import 'core-js/es7/object';
import 'core-js/es7/reflect';
```

**Comment by ThomasBurleson** [comment]
Will not change.

> Our build processes use WebPack, Rollup, and SystemJS: builds for both demos and library.
