### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by codemysoul** [angular/flex-layout#292]
I'm trying to create a SEO friendly Angular 4 app by implementing Universal build. 
My Node server gives the following error when it tries to turn on the application:

"
C:\Work\node\angular\seo\node_modules\@angular\flex-layout\media-query\_module.js:1
(function (exports, require, module, __filename, __dirname) {*** import *** { NgModule } from '@angular/core';
                                                              
SyntaxError: Unexpected token import..
"

**Comment by ThomasBurleson** [comment]
Flex-Layout is not yet compatible with Angular Universal.

**Comment by ggarg2** [comment]
@ThomasBurleson is there any workaround available ? I am also trying to create SEO friendly Angular 4 app.

**Comment by bliitzkrieg** [comment]
Any update on this?

**Comment by ThomasBurleson** [comment]
@codemysoul - If you install latest build, you should see this issue resolved.

```
rm -f ./node_modules
npm i angular/flex-layout-builds --save
```

> Latest builds support Angular 4.x, AOT, and Universal.
