### ISSUE TITLE
How to create this layout below?

### ISSUE THREAD

**Issue by sweetim** [angular/flex-layout#293]
I want to make a simple layout, 2 columns and 3 rows, as shown in the image below,

The red box, should be horizontally center align, and each cell inside of the red box should be flex 50%, and with a max width of 350px

![image](https://cloud.githubusercontent.com/assets/6851767/26285352/0313fab6-3e89-11e7-9b3f-82ec9ad248fd.png)

How can I achieve this? i try figuring for hours without any good result..
Tried the code below, but it doesnt work..
```
<div fxLayout="row" 
        fxLayoutWrap>
        <div *ngFor="let cell of redCells; 
            let i = index;"
            fxFlex="50"
            fxLayout="row">
            <red-cell
                fxFlex
                [index]="i" >
            </red-cell>
        </div>
    </div>
```

**Comment by ThomasBurleson** [comment]
Plz repost on the forum.
