### ISSUE TITLE
"Allowed values" in documentation is all messed up

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#294]
https://github.com/angular/flex-layout/wiki/Declarative-API-Overview

There are a ton of missing values in the documentation. Here's what I see in Chrome: 

> API for DOM containers:
> 
> HTML API    	Allowed values
> fxLayout	row
> fxLayoutAlign	start
> fxLayoutWrap	""
> fxLayoutGap	%, px, vw, vh
> These directives ^ affect the flow and layout children elements in the container
> API for DOM elements:
> 
> HTML API	Allowed values
> fxFlex	"" , px , %, vw, vh, " ",
> fxFlexOrder	int
> fxFlexOffset	%, px, vw, vh
> fxFlexAlign	start
> fxFlexFill	

fxLayout should have "column", fxLayoutAlign should have "center" and "end", etc.

**Comment by ThomasBurleson** [comment]
Fixed https://github.com/angular/flex-layout/wiki/Declarative-API-Overview
