### ISSUE TITLE
feat(ObservableMedia): extend Observable

### ISSUE THREAD

**Issue by jeffbcross** [angular/flex-layout#297]
I know it's a little ugly to have non-operator methods on `Observable`, but I think the `ObservableMedia` API would be a little nicer if it were an actual RxJS `Observable` instead of just implementing `Subscribable`. Maybe @benlesh has stronger feelings about not mixing Observables with other types :).

To support this would basically just require implementing `lift` method, and extending `Observable`. Happy to submit a PR.

**Comment by ThomasBurleson** [comment]
@jeffbcross - go ahead and submit a PR plz. Then we will get @benlesh to review.

**Comment by ThomasBurleson** [comment]
@jeffbcross - any progress on this one ?

**Comment by CaerusKaru** [comment]
Closing this in favor of moving the CDK's media engine.
