### ISSUE TITLE
(bug): Package not published on npm

### ISSUE THREAD

**Issue by amcdnl** [angular/flex-layout#30]
The package is not published on npm

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/flex-layout#fast-start
> Note: With gulp build:components the files are depolyed to node_modules/@angular/flex-layout. The formal deploy process to npm (and use of npm i @angular/flex-layout) is not yet available and is pending public release of the Github repository!

**Comment by d3viant0ne** [comment]
@DzmitryShylovich - It's not actually on npm per that documentation. Given it's pre-alpha state, i'm betting that's on purpose.

@amcdnl - I'm running a local build of it on an internal prod app where a pre-alpha oops isn't a big deal. What it does it does surprisingly well given that whole `pre-alpha` thing.

**Comment by trainerbill** [comment]
To get this working I did the following:

1.  Clone the repo
2.  Remove "noEmitHelpers": true from tsconfig.  May be a bug?
3.  gulp build:components
4.  change package.json main and add types
```
"main": "dist/@angular/flex-layout/index.js",
"types": "dist/@angular/flex-layout/index.d.ts",
```
5.  copy the directory to your ng2 app node_modules folder
6.  Continue:  https://github.com/angular/flex-layout#application-usages

anyone know when this will hit NPM?

**Comment by aberwag** [comment]
You can juste add this repo to your dependencies 

run this command (yout can change #master to your favorite branch or tag :wink:  )
```
npm install --save https://github.com/angular/flex-layout.git#master
```
result:
```
...
"@angular/flex-layout": "git+https://github.com/angular/flex-layout.git#master",
...
```

**Comment by ThomasBurleson** [comment]
This will be resolve when v1.0.0-beta.1 is published to NPM.

**Comment by trainerbill** [comment]
@ThomasBurleson Is there a timeframe on when a first version will be published to npm?  days/weeks/months?

**Comment by amcdnl** [comment]
@aberwag - side note: u have to build it, that install doesn't run a build.

**Comment by ThomasBurleson** [comment]
Use `gulp build:lib` and find the deployed files in `./dist/@angular/flex-layout`

**Comment by ThomasBurleson** [comment]
Note: earlier commands have been deprecated. Please use `gulp build:release`
