### ISSUE TITLE
Layouts with variable numbers of grid children

### ISSUE THREAD

**Issue by georgeedwards** [angular/flex-layout#302]
Is it possible to define a grid layout where the cells auto fit, up to a certain number, e.g. max 4 per row, so the 5th will start a new line?

in a setup like:
```
<div class="container" fxLayout  fxLayoutAlign="center" fxLayoutGap="15px" >
    <div fxFlex *ngFor="let line of lines | async">
        <md-card (click)="onSelect(line)">
        </md-card>
    </div>
</div>
```

**Comment by alexfung888** [comment]
fxFlex='25'?

**Comment by ThomasBurleson** [comment]
That ^ is the correct idea, but you must account for the gaps also. Look at
our demo source and online at
https://tburleson-layouts-demos.firebaseapp.com/#/stackoverflow

**Comment by georgeedwards** [comment]
@alexfung888 @ThomasBurleson Yes I understand that, which works fine when you have 4 elements (presumably if you have 8 elements that will wrap and form 2 nice lines?). But if there are only 3 elements, then the elements will be squeezed into a quarter of the screen whilst the 4th quarter remains blank?

**Comment by alexfung888** [comment]
at first I thought that `fxFlex='0 1 25%'` would work. but it doesn't. when I inspect it at run time, it generated `flex=0 1 100%'`. Do you know why?

**Comment by intellix** [comment]
I think you're talking about elements that are the same size that wrap right? The problem is that the item that wraps gets stupidly large, but you can achieve this with empty fillers:

```scss
.items {
  margin-right: -.5rem;
}

.item,
.filler {
  margin-right: .5rem;
}

.item {
  background: red;
  height: 3rem;
  margin-bottom: .5rem;
}
```

```html
<div class="items" fxLayoutWrap>
  <div class="item" *ngFor="let i of items" fxFlex="1 0 10rem">{{ i }}</div>
  <div class="filler" *ngFor="let i of [0, 1, 2, 3, 4, 5]" fxFlex="1 0 10rem"></div>
</div>
```

Or I could be talking about something completely different...

**Comment by ThomasBurleson** [comment]
Please move this discussion to the Forum.
