### ISSUE TITLE
Disable fx-query-test

### ISSUE THREAD

**Issue by allocenx** [angular/flex-layout#303]
On the <head> it injects so many style tags with .fx-query-test class and they are useless to me, how can i disable them?

Proof:
![image](https://cloud.githubusercontent.com/assets/12731515/26694103/0cc75df8-470f-11e7-99a6-9601709a3e61.png)

**Comment by ThomasBurleson** [comment]
Please provide a plunker  and screen capture deemonstrating  your issue .

**Comment by allocenx** [comment]
@ThomasBurleson, updated first post, i can't make you a plunker exemple. I do not know how do i install this there, so anwyay, attached you a capture to see proof.

**Comment by ThomasBurleson** [comment]
@allocenx - I am not sure what `.fx-query` is... that is not part of `@angular/flex-layout`.
This does not look like a Flex-Layout problem.

**Comment by allocenx** [comment]
It is!!!! I've been looking through flex layout library and it is there "match-media.js", more specific function "prepareQueryCSS". How can you tell that is not part of it lmao.

**Comment by ThomasBurleson** [comment]
@allocenx - wow, you are so right... I totally forgot about the browser-patch feature. LMAO also. Currently there is not a way to disable this. 

> While this dynamically injects these style tags, the only way to disable this is via a new provider function. Is such a provider really necessary ?

**Comment by allocenx** [comment]
Yes, i need it gone, or a option to disable it or something, please. Thanks.

**Comment by ThomasBurleson** [comment]
@allocenx - please explain WHY this is an issue.

**Comment by allocenx** [comment]
Why is it? Simple. Why do i need to have injected a useless style into my page header anyway? Why can it just be removed? Its annoying.

**Comment by ThomasBurleson** [comment]
@allocenx - **it's annoying** is not a sufficient reason to change stable code. That particular code is implemented to resolve WebKit browsers quirks that do NOT trigger a mediaQuery listener unless a style media block has been defined for the document.

*  https://www.nczonline.net/blog/2012/01/19/css-media-queries-in-javascript-part-2/

Closing this issues as will not fix.

**Comment by ThomasBurleson** [comment]
@allocenx - what we CAN do is optimize the list so only a single stylesheet is appended to the document.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 00ac57a33c88463cf3e2064cc604dddc897426f0
