### ISSUE TITLE
Is it possible to use sidenav with flex?

### ISSUE THREAD

**Issue by henriqueweiand** [angular/flex-layout#304]
I'm trying to structure a responsive layout using fxFlexx and the sidenav of material2. But my attempts are not working ... Can anyone help me here?

Actually I would not need to use sidenav, but until somehow you can split it in two, keep the responsive and scroll it all over the page, not just the div with flex ...

But any help is welcome.
Thank you

![1](https://cloud.githubusercontent.com/assets/6539492/26706731/de7dd786-4715-11e7-843a-e00c21b6eb62.png)
![2](https://cloud.githubusercontent.com/assets/6539492/26706732/e220d014-4715-11e7-94f9-51e2d32ba883.png)

**Comment by ThomasBurleson** [comment]
Plz see https://github.com/EladBezalel/material2-start/tree/tutorial.
