### ISSUE TITLE
fxFlexAlign seems not to be working right

### ISSUE THREAD

**Issue by julianobrasil** [angular/flex-layout#305]
In the plunker bellow, the red item should be right aligned on the screen, shouldn't it?

Plunker: https://plnkr.co/edit/RX8hCgy1B8uzwPIcTUma?p=preview

![image](https://cloud.githubusercontent.com/assets/25405143/26723583/85c13e02-476b-11e7-9996-4e2127c36a32.png)

**Comment by julianobrasil** [comment]
Got it... it aims the column layout.

**Comment by ThomasBurleson** [comment]
See the demo [Flex with Align-Self](https://tburleson-layouts-demos.firebaseapp.com/#/docs). The fxFlexAlign positions the host element on the cross-axis.

**Comment by julianobrasil** [comment]
@ThomasBurleson , I had misunderstood the alignment. I thought I could send the red div to the right border of the preview panel, but I saw that behavior would be if I was using the column layout (the row layout combined with fxFlexAlign promote changes in the vertical position).
