### ISSUE TITLE
fxFlex="33" 3x in a row doesn't fill 100% of row

### ISSUE THREAD

**Issue by Splaktar** [angular/flex-layout#306]
Tried to use the Plunkr from the Wiki but it's broken by the Renderer2 change. It was easier to reproduce in the docs.

![screen shot 2017-06-04 at 4 41 11 am](https://cloud.githubusercontent.com/assets/3506071/26760194/67cae1ac-48e0-11e7-88b9-bfb6f842cf30.png)

See the third row. This is due to using `max-width: 33%;` instead of `max-width: 33.33%;` which is needed to fill up 100% of the row. I've reproduced on Chrome and Safari.

After digging into this a bit, it appears that you can work around this by using `fxFlex="33.33"` when defining your layout. 

![screen shot 2017-06-04 at 4 55 30 am](https://cloud.githubusercontent.com/assets/3506071/26760272/171ca8b0-48e2-11e7-92d8-bbbb82e2f23a.png)

Is this how the API is intended to work?

**Comment by Splaktar** [comment]
I'm happy to create a PR for the docs (from https://github.com/DevIntent/flex-layout/tree/updateDemoFor33Basis) but I wanted to make sure that there wasn't a desire to fix the library to make `fxFlex="33"` work as some devs might expect.

**Comment by ThomasBurleson** [comment]
@Splaktar -The Renderer2 issue has been fixed and is available in on `github.com/angular/flex-layout-builds#master`. Here is an updated, working [Plunkr](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview) that demonstrates the 33.33% working as intended.

> These fixes will be available in the NPM builds for v2.0.0-beta.9
