### ISSUE TITLE
fxShow is setting display:inline; in IE11 and Edge

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#310]
https://plnkr.co/edit/lF0h5ttXwFiOLrjIgKDr?p=preview

Discovered when using fxShow with md-menu-items. In the above plunkr, the last 4 items in the menu have `fxShow` on them. In IE11 and Edge, `display:inline` is applied to them, which ruins the layout.

**Comment by ThomasBurleson** [comment]
The `fxShow` works fine in Chrome and Safari. Please try the updated [Demo](https://plnkr.co/edit/j4SErSHgfJGfsBQ9f0m6?p=preview) in IE/Edge.

Will re-open issue if problem persists.

**Comment by adamdport** [comment]
I tried your updated plunker in IE11 and it still seems broken. Was it working for you? 

![ie11](https://user-images.githubusercontent.com/3020987/29078229-c19fc894-7c27-11e7-961e-72cb92b77d42.PNG)

**Comment by ThomasBurleson** [comment]
Yes on Mac OS (Chrome, Safari) it looks great. What is the `display` property value for `Item #6` ?

**Comment by adamdport** [comment]
It's still `display: inline` and still only on IE11 and Edge.

If you don't have access to Windows for testing, [Microsoft provides virtual machine images to do so](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

**Comment by ThomasBurleson** [comment]
`fxShow` internally calls `document.getComputedStyle('display').getPropertyValue()` which finds the `display:block` defined in **.mat-menu-item** css class.

I am confused/not sure why that code in an IE11 browser will calculate 'inline'.

**Comment by adamdport** [comment]
I just [added IDs to the non-`fxShow`ed menu items](https://plnkr.co/edit/V946SMfxCYD7W6vK4tHM?p=preview) and then ran `window.getComputedStyle(document.getElementById('item-1')).getPropertyValue('display')`. IE11 correctly computes "block". Not sure where flex-layout is getting `inline` from.

![ie11block](https://user-images.githubusercontent.com/3020987/29124452-f2349330-7ce6-11e7-93bd-9cc813f6cd81.PNG)

**Comment by ThomasBurleson** [comment]
Are you using the latest build from `https://github.com/angular/flex-layout-builds/`?
See https://github.com/angular/flex-layout-builds/blob/master/bundles/flex-layout.umd.js#L834-L835:

```js
var immediateValue = _angular_platformBrowser.ɵgetDOM().getStyle(element, 'display');
                value = immediateValue || _angular_platformBrowser.ɵgetDOM().getComputedStyle(element).getPropertyValue('display');
```

> Can you debug with a breakpoint at [this point](https://github.com/angular/flex-layout-builds/blob/master/bundles/flex-layout.umd.js#L814) and see what the code is doing on IE11 browser?
