### ISSUE TITLE
Can't compile my code

### ISSUE THREAD

**Issue by gtzinos** [angular/flex-layout#312]
<md-card [ngClass.xs]="['card-xs']">

Error message: Can't bind to 'ngClass.xs' since it isn't a known property of 'md-card'.

My package

   "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/core": "^4.0.1",
    "@angular/flex-layout": "^2.0.0-beta.7",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/router": "^4.0.1",
    "@swimlane/ngx-datatable": "^8.0.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "ng2-cookies": "^1.0.11",
    "ng2-file-upload": "^1.2.1",
    "primeng": "^4.0.0-rc.1",
    "rxjs": "^5.1.0",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.1",
    "@angular/compiler-cli": "^4.0.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine": "^2.5.3",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "^1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "protractor-browser-logs": "^1.0.350",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.2"
  }
}

**Comment by ThomasBurleson** [comment]
You did not include the FlexLayoutModule properly.

**Comment by gtzinos** [comment]
I did. The problem was that i had wrong versions of some packages.

**Comment by ThomasBurleson** [comment]
@gtzinos - If you are using ng 4.1.x (or higher) you will need @angular/flex-layout Beta.8 or higher
> I believe you discovered this ?
