### ISSUE TITLE
Column Layout Breaks in IE11

### ISSUE THREAD

**Issue by julianobrasil** [angular/flex-layout#314]
I opened a similar issue earlier this year about this. It was closed as it was a question, but it wasn't: I really think it's a bug, or, at least, an unforseen behavior in IE11. A column layout is working very diferent in IE11 and in Chrome. In fact it seems it is broken in IE11, as you can see in the two images bellow.

In IE11 the item in a `fxLayout="column"` container aparently collapses if you do both of this simultaneously:

- don't specify a height for the container;
- use `fxFlex` attribute in the contained items without a fixed height: it's not possible to leave it empy - just `fxFlex` -  or set a percentage value - for example `fxFlex="40%"` or `fxFlex="40"`. 

I think, in this case, in IE11, the behavior should be the same as the` fxFlex="nogrow"` option, as it is in other browsers.

plunker: https://plnkr.co/edit/zGMk1PaG5lCGsx2YAp79?p=preview

## **Chrome:**
![image](https://user-images.githubusercontent.com/25405143/27077046-42e32940-5005-11e7-83c6-436dfd9d7265.png)

## **IE11:**
![image](https://user-images.githubusercontent.com/25405143/27077012-26e36368-5005-11e7-988c-b4a6628ae4b9.png)

**Comment by adamdport** [comment]
Possibly related to #310 ?

**Comment by julianobrasil** [comment]
@adamdport , I don't think so. There's no display:inline applied:

![image](https://user-images.githubusercontent.com/25405143/27088761-f8e6a158-502e-11e7-88bd-7908d06e652c.png)

**Comment by Splaktar** [comment]
See https://github.com/angular/flex-layout/issues/201#issuecomment-310517875.

**Comment by julianobrasil** [comment]
@Splaktar , thank you. Right now I'm using fxFlex="nogrow" as a workaround.

**Comment by alberk8** [comment]
This is still not fixed in the latest version.

**Comment by MNorgren** [comment]
Also running into this issue with IE. Frustrating that I can't use fxLayout="column". The fxLayout="row" fxLayoutWrap worked in combination to fxFlex="100", but I'd really perfer to use fxLayout appropriately :-)

**Comment by CaerusKaru** [comment]
Update Plunkr: https://plnkr.co/edit/zGMk1PaG5lCGsx2YAp79

**Comment by CaerusKaru** [comment]
Will be fixed by #669

**Comment by julianobrasil** [comment]
Thanks for updating the plunk, @CaerusKaru! I put it in the former comment of this issue.

Good to know it'll be fixed.
