### ISSUE TITLE
Bad combination: [style] + *ngIf + fxLayoutGap

### ISSUE THREAD

**Issue by julianobrasil** [angular/flex-layout#319]
When I set a style (example: `[style.margin-top]="'5px'"`) in a `fxFlex` item and this very item has a `*ngIf` and is inside a flex container with `fxLayoutGap` attribute, the style is cleared.

  Use case: I'm trying to fix the alignment of two material inputs (using `[style.margin-top]="'5px'"`). But one of the inputs is inside a `fxFlex` div which, in turn, has a `*ngIf`. The container has a `fxLayoutGap` set. In this scenario, the `fxFlex` item is been rendered without the `[style.margin-top]="'5px'"`. 

  If I take away the `*ngIf` or the `fxLayoutGap`, everything works fine. Curiously, the simple presence of `*ngIf` causes the problem (even if you hardcode it to `true`)

  Plunker: http://plnkr.co/edit/OiKiYa?p=preview

## With the `*ngIf` directive present:

![image](https://user-images.githubusercontent.com/25405143/27194900-cd52b682-51da-11e7-8236-d8a891d59612.png)

## Without the `*ngIf` directive (the same efect would be achieved taking away the `fxLayoutGap` instead of `*ngIf`):

![image](https://user-images.githubusercontent.com/25405143/27195014-45acfdae-51db-11e7-8ad5-45d0713dd784.png)

The workaround is put the `*ngIf` inside the `fxFlex` item, not in the decorated `div` itself.

**Comment by ThomasBurleson** [comment]
@julianobrasil - `fxLayoutGap` has been improved significantly in the latest nightly builds. Please note that your layout will be much simpler if you do this:

```html
  <div fxLayout="row" fxLayoutGap="10px">
        <md-select placeholder="choose">
          <md-option>x</md-option>
          <md-option>y</md-option>
        </md-select>
      
        <md-input-container>
          <input mdInput placeholder="type">
        </md-input-container>
  </div>
```

![screen shot 2017-08-10 at 8 24 26 am](https://user-images.githubusercontent.com/210413/29172369-61abba86-7da5-11e7-9fec-5f51cfbc6e62.png)

Here is the [working plunker](http://plnkr.co/edit/bbmr721zpLgkmY82ucwY?p=preview).

> Closing as not-an-issue in flex-layout.
