### ISSUE TITLE
fxShow/fxHide is setting display: block on possibly inline elements.

### ISSUE THREAD

**Issue by vqtran** [angular/flex-layout#320]
For example:

```html
Some text <span fxHide.lt-md>some more text.</span>
```

renders the span as display: block and breaks up the text onto the next line.

Upon initial investigation this commit introduced this breakage: https://github.com/angular/flex-layout/commit/771f2c92ad75990a8c9c98d8de8278a61a16a400

However, it seems like the real problem is that calling `getComputedStyle(element)['display'] `does not properly return the computed style of the element, instead it returns empty string.

The only temporary work around is to set `style="display: inline;" ` (note setting CSS in a class does not work here). This is probably due to satisfying the first condition of: `(element.style as any)['display'] || getComputedStyle(element)['display'];`

**Comment by ThomasBurleson** [comment]
Fixed with SHA 635c4f587037cb8a86af8f07d9e76e0f077e833c

**Comment by matheo** [comment]
@ThomasBurleson I'm trying to control the display of a `md-cell`, and `fxShow/fxHide` removes the `display: flex` settled by the other directives:
```
<md-cell *cdkCellDef="let row" fxShow fxHide.md fxLayoutAlign=" center" fxFlex.xs="100%">
```
causing the content to not be centered. I had to add this to my global styles:
```
md-header-cell,
md-cell {
  display: flex;
}
```
to restore their normal appearance. Thanks

**Comment by zijianhuang** [comment]
In my case, the problem happens in Firefox only. fxHide works well in IE, Edge and Chrome. Hopefully the fix will be released soon.
