### ISSUE TITLE
ngc error:  Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by glebmachine** [angular/flex-layout#324]
I'm trying to compile my application with ```ngc```

It's not compiling with FlexLayoutModule, and throw this error:

```bash
./node_modules/.bin/ngc 
Unexpected value 'FlexLayoutModule in /Users/{projectroot}/frontend/node_modules/@angular/flex-layout/index.d.ts' 
imported by the module 'SharedModule in  /Users/{projectroot}/frontend/app/shared/shared.module.ts'. 
Please add a @NgModule annotation.
```

Could you please give me any hint?

**Comment by glebmachine** [comment]
Same with umd bundle.

**Comment by ThomasBurleson** [comment]
Can you share your code for `shared.module.ts` ?

**Comment by glebmachine** [comment]
It's not a problem of FlexLayoutModule it's self.
I will dig deeper, and let you know!

Thank you)

**Comment by ThomasBurleson** [comment]
@glebmachine - if you provide a plunkr, we can help. It may be an AOT/CLI issue with Angular 4.2.x.

**Comment by elerman** [comment]
Any update on this ?
