### ISSUE TITLE
Bug in Flex Layout demo in Chrome 58

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/flex-layout#327]
I check the sample below in my Chrome Version 58.0.3029.110 (64-bit) MacOSX

https://tburleson-layouts-demos.firebaseapp.com

See stranger behavior:

![sample](http://g.recordit.co/Q2n1m7tD4Z.gif)

in row mode, the vertical-align 'end' not works 

![sample](http://g.recordit.co/CWcReIlJgZ.gif)

and in column mode horizontal align 'end' not works

This sample works normally in my Firefox 53.0.3, but inspecting the 'flex container' the Angular Flex Layout add align-items: end; but the Google Chrome Inspect shows only the respective values 

![samples](https://s8.postimg.org/ee1ht1byt/Screen_Shot_2017-06-23_at_18.47.03.png)

Property 'end' does not exist in Chrome? It's strange.

**Comment by waterlooblue** [comment]
When I test locally with `fxLayoutAlign="space-around end"` it applies `flex-end` with `align-items` correctly.

![capture](https://user-images.githubusercontent.com/13106746/27504693-188c92e8-585d-11e7-898a-6e041914eeae.JPG)

I think it's related to it being loaded dynamically with the radio button.

**Comment by ThomasBurleson** [comment]
This has been fixed in `master` but the sample-demos application update has not been released; an updated will be provided with the upcoming Beta.9 release.

**Comment by ThomasBurleson** [comment]
Fixed. [Demo App](https://tburleson-layouts-demos.firebaseapp.com/#/docs) has been updated with latest changes in [master](https://github.com/angular/flex-layout/commits/master) with support for AOT, Angular 4.x, and more.
