### ISSUE TITLE
Unexpected behaviour: offset is always horizontal

### ISSUE THREAD

**Issue by sasensi** [angular/flex-layout#328]
Hi,
I found an unexpected behaviour when you set fxFlexOffset in a `fxLayout="column"` child, it result in a **margin-left** added; instead of a **margin-top** which is what I was expecting.

Demo here: https://plnkr.co/edit/PDOtQk?p=preview

Is it on purpose or a bug ? Thanks in advance.

**Comment by ThomasBurleson** [comment]
@sasensi  - This is a bug and will be addressed/fixe before Beta.9. Thank you.

**Comment by yobryon** [comment]
With this changed, is there any elegant way of getting the margin-left behavior in a column-oriented layout other than resorting to style="margin-left: #px"?
