### ISSUE TITLE
Strange bug: when using fxLayoutGap on container and *ngFor on child

### ISSUE THREAD

**Issue by sasensi** [angular/flex-layout#329]
Hi,

I found a strange bug which, I presume, has something to do with fxLayoutGap directive.

My use case was to use a component method to provide items for a *ngFor loop.
I noticed that if the parent of the loop has the directive fxLayoutGap, browser just crash (tested on Chrome and Firefox).
Demo here: https://plnkr.co/edit/paJ7Sb

Hoping you can help me on this.

Thanks in advance.

**Comment by ThomasBurleson** [comment]
@sasensi - that is a great, nasty bug discovery. We will investigate.

**Comment by lordjesus** [comment]
Any news on this? I am facing the exact same issue.

**Comment by ThomasBurleson** [comment]
@lordjesus - see PR #370.
