### ISSUE TITLE
Not all matching classes are being added

### ISSUE THREAD

**Issue by jarektomanek** [angular/flex-layout#333]
I'd like to have *all* matching classes being added to a single element:

```html
<div
    class.xs="xs"
    class.sm="sm"
    class.md="md"
    class.lg="lg"
    class.xl="xl"
    class.lt-sm="lt-sm"
    class.lt-md="lt-md"
    class.lt-lg="lt-lg"
    class.lt-xl="lt-xl"
    class.gt-xs="gt-xs"
    class.gt-sm="gt-sm"
    class.gt-md="gt-md"
    class.gt-lg="gt-lg">
    Not all matching classes are being added to this DIV
</div>
```

Expected classes when browser is in MD size: `md`, `lt-lg`, `lt-xl`, `gt-xs`, `gt-sm`
What happens:
1. Classes at page load in MD size: `gt-xs`
2. Classes after resizing up from MD to LG, then down to MD: `lt-lg`
3. Classes after resizing down from MD to SM, then up to MD: `md`

Seems like script stops adding another matching classes when it finds the first match.

Tried using the below, but also doesn't work as expected - it activates either `gt-*` or `lt-*`, not both:

```html
<div
[ngClass.sm]="['sm']"
[ngClass.md]="['md']"
[ngClass.lg]="['lg']"
[ngClass.xl]="['xl']"
[ngClass.gt-md]="['gt-xs', 'gt-sm', 'gt-md']"
[ngClass.gt-sm]="['gt-xs', 'gt-sm']"
[ngClass.gt-xs]="['gt-xs']"
[ngClass.lt-xl]="['lt-xl']"
[ngClass.lt-lg]="['lt-lg', 'lt-xl']"
[ngClass.lt-md]="['lt-md', 'lt-lg', 'lt-xl']"
[ngClass.lt-sm]="['lt-sm', 'lt-md', 'lt-lg', 'lt-xl']" ></div>
```

Demo: https://plnkr.co/edit/yKicwrNtHImJpZvLLvWQ?p=preview

**Comment by ThomasBurleson** [comment]
@jarektomanek - This is NOT the way the API works. Have you read the [Responsive API](https://github.com/angular/flex-layout/wiki/Responsive-API) usage documentation?

> Closing as 'not a valid issue'.
