### ISSUE TITLE
element.style parsing incorrect value

### ISSUE THREAD

**Issue by mcwebdev** [angular/flex-layout#336]
element.style parsing incorrect value.
![flex25](https://user-images.githubusercontent.com/14930146/27925682-8f0cee7c-623a-11e7-80c8-2fba8c8c0c1a.jpg)

**Comment by ThomasBurleson** [comment]
Due to [Flexbox Browser Known Issues](http://caniuse.com/#feat=flexbox), @angular/flex-layout sets a `max-width` or `max-height`  value. 

> This works as expected.

**Comment by mcwebdev** [comment]
This should not be closed, the big red arrow points to a value that is incorrectly parsed.
`1e-09px;` is not a supported value of any kind.
