### ISSUE TITLE
Project Status  Update

### ISSUE THREAD

**Issue by un33k** [angular/flex-layout#337]
Request [x]

This is a request to update the milestones with new dates to better help projects that have already invested in building against flex-layout.

Due to low activity of this `@angular/*` project, it is a possibility that this project is never going to come out of dormant state.

It would be nice for everyone to get a heads up to switch out of this project when it is not too late.

Everyone's time is appreciated.  Those who contribute directly, and those who participate and provide early feedback.

**Comment by ThomasBurleson** [comment]
This repository is not dormant and will is targeted for release [as v2.x] simultaneously with Angular Material (2.x) in the early fall. 

> Repo activity for the last 2-4 weeks has been reduced as a result of to team developers involved in offsite activities. The dev community should expect to see increased activity along with improved functionality during the next 8-12 weeks.
