### ISSUE TITLE
fxFlex not working properly

### ISSUE THREAD

**Issue by alobban** [angular/flex-layout#339]
**Currently installed, Flex-Layout 2.0.0-rc.1 and Angular 4.2.6**.

I performed an npm update and received a Release Candidate even though npm package page only mentions 2.0.0-beta.8 as the latest version. Is there a **Changelog** for 2.0.0-rc.1?

Page layout is NOT rendering to the full height.

    <div fxLayout="column" fxFlex="100%">

      <afn-navbar fxFlex="7%"></afn-navbar>

      <div fxLayout="row" fxFlex="88%">
        <afn-sidebar fxLayout="column" fxFlex="10%"></afn-sidebar>

        <div fxLayout="column" fxFlex="90%">
          <router-outlet></router-outlet>
        </div>

      </div>

      <afn-footer fxFlex="5%"></afn-footer>

    </div>

![screenshot from 2017-07-12 09-59-13](https://user-images.githubusercontent.com/3998145/28124301-deea693a-66e8-11e7-834a-c05676b82c08.png)

As you can see the footer is not being pushed to the bottom of the window. Everything was working fine on **2.0.0-beta.8**.

**Comment by ThomasBurleson** [comment]
RC.1 is not yet available. The early release of RC.1 was invalid and was renamed to Beta.7.

> Beta.8 is the most recent release. Beta.9 should be available next week.

**Comment by alobban** [comment]
Ok, I will be re-installing version 2.0.0-beta.8, but as evidence shows above in my screenshot version 2.0.0-rc.1 was released/leaked via npm!
