### ISSUE TITLE
Directives should support multiple selectors

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#34]
Currently only a single directive syntax is supported. Consider the Layout directive

```ts
@Directive({selector: '[fx-layout]'})
export class LayoutDirective {  
  @Input('fx-layout') layout = 'row';
  @Input('fx-layout.xs') layoutXs;
  @Input('fx-layout.gt-xs') layoutGtXs;
}
```

and its markup usage:

```html
<div  fx-layout="row" fx-layout.xs="column"></div>
```

All ^ works fine.  

## Issue

Consider the use of multiple selectors with non-default used in markup

```ts
@Directive({selector: '[fx-layout], [fx-layout.xs], [fx-layout.gt-xs]'})
export class LayoutDirective {  
}
```

The following does NOT throw any errors:

```html
 <div [fx-layout]="direction" [fx-layout.xs]="'column'"></div>
```

But consider this scenario:

```html
<div  [fx-layout.xs]="direction"></div>
````

or 

```html
<div  [fx-layout.xs]="'column'"></div>
````

In ^ this case, the expectation is a Layout directive instance would be created, and the `@Input('fx-layout.xs') layoutXs` would be assigned the value of the direction variable ( or 'column' string).

Instead, we get this error:

```sh
Template parse errors:(…) Error: Template parse errors:
Invalid property name 'fx-layout.xs' ("
          <div [ERROR ->][fx-layout.xs]="direction"></div>
```

> Note that the default value/input `@Input('fx-layout')` would not need to be defined in the markup, but would still be used (since its default value is assigned).

## Desired Result:

This should work without any errors:

```html
<div  [fx-layout.xs]="direction"></div>
````

**Comment by ThomasBurleson** [comment]
@tbosch - I really need your help with this one!

**Comment by emoralesb05** [comment]
Not sure if this helps, but this happens because of the `.` in the selector.

Angular2 appears to complain and not want to recognize it as part of a selector's directive. Maybe because `.` is used in `[class.className]`, `[style.styleProperty]` or `[attr.attributeName]` to selected specific ones.

You would have to probably use it as `fx-layout-xs` and so on.

**Comment by ThomasBurleson** [comment]
@emoralesb05 - You are correct. The `.` notation is the issue. The parser expects the input to be property of an object... and *now* I have an interesting idea to avoid this issue. ;-)

**Comment by ThomasBurleson** [comment]
@tbosch - converting the input property to a map also does not work and continues to throw a template parsing error!

```
@Directive({selector: `
  [fx-layout], 
  [fx-layout.xs], 
  [fx-layout.gt-xs], 
  [fx-layout.sm], 
  [fx-layout.gt-sm], 
  [fx-layout.md], 
  [fx-layout.gt-md], 
  [fx-layout.lg], 
  [fx-layout.gt-lg], 
  [fx-layout.xl]
  `
})
export class LayoutDirective {

  /**
   * Layout property: map default direction value and responsive keys that are optional
   */
  @Input('fx-layout') layout = { 'default' : 'row' };
}
```

**Comment by ThomasBurleson** [comment]
Support for **both** full property assignment or property chain assignments is in-progress.
