### ISSUE TITLE
Does it support layout resize by the user?

### ISSUE THREAD

**Issue by kchojhu** [angular/flex-layout#340]
I'm doing a research on flex-layout and like to know if it supports resizable layout.  For example, say I got flex vertical layout Top/Mid/Bottom.  I like to enable user to resize each section.  I believe some call this the 'Splitter' feature.  Please let me know if this library supports it.  Thank you!

**Comment by ThomasBurleson** [comment]
See the fixes and features merged with PR https://github.com/angular/flex-layout/pull/290.

#### Snapshot of Splitter Demo
<img width="1307" alt="screen shot 2017-05-18 at 7 19 36 pm" src="https://cloud.githubusercontent.com/assets/210413/26228394/f38fac5c-3bfe-11e7-9977-58fe79ab0d5e.png">

* [Demo Source](https://github.com/angular/flex-layout/blob/master/src/demo-app/app/github-issues/issue.266.demo.ts#L24-L27)
* [Demo Splitter Code](https://github.com/angular/flex-layout/tree/master/src/demo-app/app/github-issues/splitter)
* [ngx-ui splitter library](https://swimlane.github.io/ngx-ui/#split)

**Comment by kchojhu** [comment]
That's too awesome!!! I've officially declared flex-layout a must use with NG :+1:

**Comment by ThomasBurleson** [comment]
In fact,  [ShapeShifter](https://shapeshifter.design/) uses @angular/flex-layout with splitters.

**Comment by kchojhu** [comment]
That looks really good. One thing I would suggest is to have 'collapse'
mode.
