### ISSUE TITLE
fxLayoutGap API: wrong calc within example

### ISSUE THREAD

**Issue by tobiaskohlbau** [angular/flex-layout#341]
Within [this](https://github.com/angular/flex-layout/wiki/fxLayoutGap-API#using-fxlayoutgap-with-wrap) example the entries of `calc(50%-25px)` should be replaced by `calc(50% - 25px)`.

As stated [here](https://developer.mozilla.org/en-US/docs/Web/CSS/calc):
>Note: The + and - operators must always be surrounded by whitespace. The operand of calc(50% -8px) for instance will be parsed as a percentage followed by a negative length, an invalid expression, while the operand of calc(50% - 8px) is a percentage followed by a minus sign and a length. Even further, calc(8px + -50%) is treated as a length followed by a plus sign and a negative percentage.
The * and / operators do not require whitespace, but adding it for consistency is allowed, and recommended.

**Comment by ThomasBurleson** [comment]
Fixed.
