### ISSUE TITLE
Image on left when big screen

### ISSUE THREAD

**Issue by duard** [angular/flex-layout#345]
I'm trying to build cards like this 
https://codepen.io/anon/pen/aOGYjG?editors=1000

I'm using Angular 4 and latest flex layout. I need some help, here is my code : 

Github is processing my code, so here is the gist of my html code :
https://gist.github.com/duard/a0639a1aa55ebee303935c1da1dfa810
```
<md-card class="card-demo">
  <div fxLayout="row" fxLayout.xs="column" fxLayout.sm="column" fxFlex class="box">
    <div flex-gt-sm="33%" fxLayoutAlign="center center" fxLayout="column">
      <img src="https://i.imgur.com/2uL6DQ8.jpg" flex class="md-card-image">
    </div>
    <div fxFlex>
      <md-card-title>
        <h2>Segundo Título</h2>
      </md-card-title>
      <md-card-content class="md-content">
        <p>
          The titles of Washed Out's breakthrough song and the first single from Paracosm share the two most important words in Ernest
          Greene's musical language: feel it. It's a simple request, as well...
        </p>
      </md-card-content>
      <md-card-actions fxLayout="row " fxLayoutAlign="end center ">
        <button md-button>LIKE</button>
        <button md-button>SHARE</button>
      </md-card-actions>
    </div>
  </div>
</md-card>
```

**Comment by duard** [comment]
I think now I just need an responsive class for the image 
`
<md-card class="card-demo">
  <div fxLayout="row" fxLayout.xs="column" fxLayout.sm="column" fxFlex class="box">
    <div fxFlex class="box">
      
    </div>
    <div fxFlex>
      <md-card-title>
        <h2>Segundo Título</h2>
      </md-card-title>
      <md-card-content class="md-content">
        <p>
          The titles of Washed Out's breakthrough song and the first single from Paracosm share the two most important words in Ernest
          Greene's musical language: feel it. It's a simple request, as well...
        </p>
      </md-card-content>
      <md-card-actions fxLayout="row " fxLayoutAlign="end center ">
        <button md-button>LIKE</button>
        <button md-button>SHARE</button>
      </md-card-actions>
    </div>
  </div>
</md-card>
`

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.
