### ISSUE TITLE
Plunker template link fails with XHR 404

### ISSUE THREAD

**Issue by 0mpurdy** [angular/flex-layout#348]
The plunker template link from the [README](https://github.com/angular/flex-layout#quick-links) (https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview) fails with error:

<img width="494" alt="screen shot 2017-07-25 at 11 39 16" src="https://user-images.githubusercontent.com/11562338/28568548-25494c1c-712e-11e7-9ac9-94c98545f4fc.png">

I haven't made any changes to it.

## System info

>macOS Sierra 10.12.5
>Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Is there a setting I am likely to be missing?

**Comment by ThomasBurleson** [comment]
Fixed.

**Comment by 0mpurdy** [comment]
@ThomasBurleson thanks for fixing that - works perfectly now! 

However the link on the plunk to the GitHub repo is using `http://` which gives a `mixed content` error when clicked. Opening in a new tab works, which is probably what people will be doing anyway but just thought I'd let you know

**Comment by ThomasBurleson** [comment]
Thank you... We will fix that also
