### ISSUE TITLE
Vertical / column stretch issue 

### ISSUE THREAD

**Issue by Dutchboy** [angular/flex-layout#349]
App component has three sub components. Header, (side-nav with) router-link, bottom, all three called with their selectors. fxLayout horizontally (row) fills perfectly the whole screen width. But do not try to get it to fill vertically (column), because this will give you headaches.

**Comment by ThomasBurleson** [comment]
@Dutchboy - please do not submit discussions as issues. General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.

> Please see the **[Mozilla Holy Grail](https://tburleson-layouts-demos.firebaseapp.com/#/stackoverflow)** demo for a vertical fill.  [Link to Source](https://github.com/angular/flex-layout/blob/master/src/demo-app/app/stack-overflow/mozHolyGrail.demo.ts#L29-L31)
