### ISSUE TITLE
install fails!

### ISSUE THREAD

**Issue by lgt** [angular/flex-layout#35]
so I try to install over npm 

`npm install @angular/flex-layout -save`

but I get 

`'@angular/flex-layout' is not in the npm registry.`

**Comment by aveniri** [comment]
read the docs, it hasn't been published on npm yet

**Comment by lgt** [comment]
actually I took from docs `npm install @angular/flex-layout -save`

https://github.com/angular/flex-layout#fast-start

**Comment by lgt** [comment]
sorry I see now 
pending future
