### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by sheldonyss** [angular/flex-layout#350]
https://tburleson-layouts-demos.firebaseapp.com/?_sm_au_=i5VfWjvHNtTHMWnN#/stackoverflow

seems that the live demo is not working.

**Comment by ThomasBurleson** [comment]
This works:  https://tburleson-layouts-demos.firebaseapp.com/#/stackoverflow

**Comment by sheldonyss** [comment]
My bad. It was my company proxy blocked some script files.

![image](https://user-images.githubusercontent.com/15058152/28807935-18cbceba-76ab-11e7-8e7c-248ee06bdf3c.png)
