### ISSUE TITLE
Flex-Layout Crashes App With Angular 4 MD Data Table

### ISSUE THREAD

**Issue by svstartuplab** [angular/flex-layout#352]
Flex-Layout directives on pages that use the new MD Data Table component will crash the app recompile and throw errors.  If I remove these from pages containing MD Data Table then the page and app work fine.  

I'm using Flex-Layout and Material 2.0.0.beta8, Angular 4.3.0.

The console error message with `fxLayoutAlign="space-around center"`:

```term
TypeError: _this._renderer.setStyle is not a function
    at base.js:97
    at Array.forEach (<anonymous>)
    at LayoutAlignDirective.webpackJsonp.../../../flex-layout/flexbox/api/base.js.BaseFxDirective._applyStyleToElement (base.js:96)

The error message with fxLayout="row" fxLayoutAlign="space-around center":

Error: Uncaught (in promise): TypeError: _this._renderer.setStyle is not a function
TypeError: _this._renderer.setStyle is not a function
    at base.js:97
    at Array.forEach (<anonymous>)
    at LayoutAlignDirective.webpackJsonp.../../../flex-layout/flexbox/api/base.js.BaseFxDirective._applyStyleToElement (base.js:96)
```

**Comment by ThomasBurleson** [comment]
@svstartuplab - we just merged a huge PR which fixes builds on Flex-Layout for Angular 4.  Please use the latest code from our builds; see [Install Notes](https://github.com/angular/flex-layout/wiki/Integration-with-Angular-CLI#npm-install-angular-flex-layout-components) and retry.

> Angular 2.x is no longer supported with current HEAD and [future, post-Beta.8 releases].

**Comment by ThomasBurleson** [comment]
Also see https://plus.google.com/+ThomasBurleson/posts/S9bRDMimimo

**Comment by svstartuplab** [comment]
Thanks Tom, and big thanks for all your work!  Flex-layout works great!  I don’t have the skills to contribute to open source yet...
