### ISSUE TITLE
Universal issue due to packaging format issue

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/flex-layout#354]
I run an app with Material and FlexLayout, server-side rendered with the new option of `@angular/cli` 1.3.0-rc.

No  problem with Material, but FlexLayout generates this error : 

```console
/node_modules/@angular/flex-layout/media-query/breakpoints/break-points-token.js:8
import { InjectionToken } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
```

I suspect it's because flex-layout is not distributed in the official way like other Angular modules. Some entry points (`main`, `module`, `es2015`, `umd`...) are missing compared to other Angular packages.

**Comment by ThomasBurleson** [comment]
@cyrilletuzi: We recently upgraded our build process for Angular (v4.x) and AOT. Please retry wi the latest builds on HEAD: see [Installing @angular/flex-layout@HEAD](https://github.com/angular/flex-layout/wiki/Integration-with-Angular-CLI#npm-install-angular-flex-layout-components)

**Comment by cyrilletuzi** [comment]
Imports are working now, but I get this error : 

```
/Users/cyrille/Web/github/ngapi/node_modules/@angular/core/bundles/core.umd.js:382
            throw 'reflect-metadata shim is required when using class decorators';
            ^
reflect-metadata shim is required when using class decorators
```

It's OK if I include the polyfill, but all other librairies stopped using it, and it will be removed soon from `@angular/cli`.

It may be because `flex-layout` is not requesting the good format of other Angular packages (like `core`).

**Comment by ThomasBurleson** [comment]
@cyrilletuzi - what do you mean "it may be because flex-layout is not requesting the good format of other Angular packages (like core)" ?

**Comment by cyrilletuzi** [comment]
I'm not an expert about how official Angular packages are distributed, but the error seems to show `flex-layout` is importing `core` in umd format, and I think now Angular modules are imported via the `es2015` entry point. But I see that HEAD version of flex-layout has now the `es2015` entry point so I don't know what's the problem...

**Comment by ThomasBurleson** [comment]
@hansl, @Brocco  - any thoughts on the issue with the CLI rc ?

**Comment by cyrilletuzi** [comment]
And I may have been optimist about saying it works with reflect, rendering is not working anymore, but I think it's related to #353

**Comment by cyrilletuzi** [comment]
Yes, but I think the reflect issue is a different one. Will see.

**Comment by hansl** [comment]
@thomasburleson do you use reflect metadata outside of angular decorators?

**Comment by CaerusKaru** [comment]
This issue persists even with the merge of #353

**Comment by hansl** [comment]
@ThomasBurleson After talking to @chuckjaz, you can fix this by adding an `importAs` key to your `index.metadata.json` file. See this PR in Material: https://github.com/angular/material2/pull/6132

I suggest talking to Jeremy about it.

**Comment by ThomasBurleson** [comment]
@hansl - Thx Hans. I will investigate and review with @jelbourn. I do appreciate your help.

**Comment by hansl** [comment]
@ThomasBurleson actually after discussion with @chuckjaz and @tbosch it seems like using `flatModuleId` might be the way to go (see [here](https://github.com/angular/material2/blob/20cd8a1fb59eb1a590acb24942c793e492fe0dad/src/cdk/bidi/tsconfig-build.json)).

**Comment by cyrilletuzi** [comment]
As a more general perspective, shouldn't be the recommended configuration for building librairies for Angular available for every one ?

There will be similar problem with every third party librairies, and if even official librairies seems to don't know all what is necessary...

It's causing some important issues like angular/angular-cli#7200

**Comment by ThomasBurleson** [comment]
Depends on https://github.com/angular/material2/pull/6132

**Comment by ThomasBurleson** [comment]
Depends upon https://github.com/angular/material2/pull/6132

**Comment by cyrilletuzi** [comment]
Fixed in nightly builds.
