### ISSUE TITLE
fxShow and FxHide issue with Google Chrome Version 60.0.3112.78 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by harshaldhake** [angular/flex-layout#355]
I have two div element as below. I want to switch the screen base on the below setting for mobile and we screen. It works for Safari and FireFox but not working with Chrome
Can you please help.

<div fxLayout="row" fxHide.md="true" fxHide.sm="true" fxHide.xs="true">
  
</div>

<div fxHide="true" fxShow.md="true" fxShow.xs="true" fxShow.sm="true" >
  
</div>

        "@agm/core": "^1.0.0-beta.0",
        "@angular/animations": "^4.1.0",
        "@angular/common": "^4.1.0",
        "@angular/compiler": "^4.1.0",
        "@angular/core": "^4.1.0",
        "@angular/flex-layout": "^2.0.0-beta.8",
        "@angular/forms": "^4.1.0",
        "@angular/http": "^4.1.0",
        "@angular/platform-browser": "^4.1.0",
        "@angular/platform-browser-dynamic": "^4.1.0",
        "@angular/router": "^4.1.0",

**Comment by ThomasBurleson** [comment]
@harshaldhake - please provide a Plunkr that demonstrates the issue.
Here is a [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview).

**Comment by ThomasBurleson** [comment]
Closing as not-an-issue.

**Comment by harshaldhake** [comment]
Aplogies. I have resolved issue after removing ngStyle.md property.

Thanks.
