### ISSUE TITLE
umd bundles contain calls to Reflect.metadata

### ISSUE THREAD

**Issue by IgorMinar** [angular/flex-layout#359]
if you compare https://unpkg.com/@angular/flex-layout@2.0.0-beta.8/flexbox/api/flex-fill.js

and the same code section in the umd bundle: https://unpkg.com/@angular/flex-layout@2.0.0-beta.8/bundles/flex-layout.umd.js 

you'll see that the umd bundle contains code like:

```
FlexFillDirective = __decorate$11([
    _angular_core.Directive({ selector: "\n  [fxFill],\n  [fxFlexFill]\n" }),
    __metadata$9("design:paramtypes", [exports.MediaMonitor, _angular_core.ElementRef, _angular_core.Renderer2])
], FlexFillDirective);
```
as opposed to the esm version in flex-fill.js which looks like this:

```
FlexFillDirective.decorators = [
    { type: Directive, args: [{ selector: "\n  [fxFill],\n  [fxFlexFill]\n" },] },
];
/** @nocollapse */
FlexFillDirective.ctorParameters = function () { return [
    { type: MediaMonitor, },
    { type: ElementRef, },
    { type: Renderer2, },
]; };
```

This tells me that the umd bundles are produced from code that is processed differently from the ESM version. I'm guess that the ngc compiler is not involved.

It would be great to make the two equal, so that we don't need to depend on the reflect metadata polyfill in our applications.

**Comment by ThomasBurleson** [comment]
@IgorMinar - The weird part is that we are using the SAME build scripts and tools as @angular/material. Any thoughts as to what else might be causing the differences? I will investigate also...

**Comment by ThomasBurleson** [comment]
@IgorMinar, @jelbourn - The `ngc` appears to be used only 
* to re-compile RxJS sources into ES2015. 
* to build the universal app demo.
The `tsc` is used to build the library.

**Comment by jelbourn** [comment]
The material tooling uses `tsc-wrapped`, which is `ngc`; the import looks like 
```ts
import {main as tsc} from '@angular/tsc-wrapped';
```

**Comment by jelbourn** [comment]
Yeah, the import should probably be aliased to `ngc`

**Comment by DevVersion** [comment]
The version on `unpkg` still shows build artifacts from the old package structure which is no longer valid.

For Angular Material, the packaging has been already updated to follow the the new specifications (as in angular/angular).

In regards to flex-layout. Flex-Layout got the new packaging as well with SHA https://github.com/angular/flex-layout/commit/21c34f796fa5602df2d294d8f84922e325fb702c a few days ago.

This means that we should rather look at the build artifacts on the GitHub repositories than on NPM.

* https://github.com/angular/flex-layout-builds/blob/master/%40angular/flex-layout.js#L1462-L1472
* https://github.com/angular/flex-layout-builds/blob/master/bundles/flex-layout.umd.js#L1901-L1908

I think if we look at those files, we can see that there is no dependency on Reflect anymore.

**Comment by ThomasBurleson** [comment]
Oh my... I completely missed the fact that @IgorMinar was looking at the Beta.8 release code. 

> That code is very outdated. The latest code in master uses the new tooling that @DevVersion created (and also uses in Material2). 

I will close this as an invalid issue.

> Thx @DevVersion.

**Comment by IgorMinar** [comment]
Thanks for looking into this!
