### ISSUE TITLE
camelCase attribute selectors to align with Angular style guide

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/flex-layout#36]
The official Angular style guide states that attributes should be camel cased.

Should directives such as fx-layout and fx-layout-align be renamed to fxLayout and fxLayoutAlign? Or even flexLayout and flexLayoutAlign? 

Fixing existing projects that use flex-layout would be as simple as a series of search/replace steps to camelCase the directive selectors.

**Comment by ThomasBurleson** [comment]
@jelbourn - thoughts?

**Comment by jelbourn** [comment]
In material our approach has been that the _selector_ for a directive is dash-case, and the _properties_ on that directive are camelCase. These could go either way since they're technically both. I generally prefer the dash-case names, though.

**Comment by ThomasBurleson** [comment]
@jelbourn - agreed. Consistency is important...
Will not change.

**Comment by martinmcwhorter** [comment]
Fair enough. I opened up the issue out of a concern about consistency with the official angular 2 style guide from @johnpapa and idiomatic Angular naming. 

Many developers intuitite properties from attributes based on the naming case: components (kebab), directives (camel), properties (camel)  and attributes (kebab). 

As you would bind to a property but not an attribute, having a square brackets around a [kebab-case] named properly seems inconsistent in Angular. 

I'm not trying to start a holy war or anything. I am happy enough with this great project. Great work.

**Comment by ThomasBurleson** [comment]
@martinmcwhorter - you comments and thoughts are valid.  Thank you.

> If I was not seeking consistency with the style of Material2, then I would probably consider a non-dash-case approach.
