### ISSUE TITLE
Compatibility with Angular Material 1 flex directives

### ISSUE THREAD

**Issue by jhuang314** [angular/flex-layout#360]
I have an existing AngularJS + Angular Material 1 app. I plan on migrating it to Angular + Material 2.  

One of the existing components (```<site-card>```) that I'm trying to port over to Angular uses the Material 1 flex directives to style the component itself and the template of the component itself:
```<site-card flex layout-fill layout="center"></site-card>```

Do the Material 1 flex directives play nice with the flex-layout directives? I'd like to apply Material 1 flex directives on the Angular component (which will use flex-layout in its template).

**Comment by ThomasBurleson** [comment]
@jhuang314 the two layout systems are exclusive of each other. @angular/flex-layout works for angular components only and ngM1 flex directives for for AngularJS only... in fact the scopes for AngularJS and Angular are very different.

@angular/flex-layout will not support any usages in AngularJS.
