### ISSUE TITLE
Failed to compile -  no such file or directory, open...

### ISSUE THREAD

**Issue by svstartuplab** [angular/flex-layout#362]
I upgraded to @angular/flex-layout: 2.0.0-beta.8-0f13b14 so I could use the new MD Data Table with flex-layout and got the following message.  Flex-layout works on my other pages and worked on this page until I installed the data table.  Previously I displayed data in a more traditional Angular way.  I'm using Angular 4.3.0.  Previous flex-layout was 2.0.0-beta.8. 

Failed to compile.
./~/@angular/flex-layout/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/jmpreston/Documents/Websites/projectfuser/node_modules/@angular/flex-layout/index.js'
 @ ./src/app/app.module.ts 13:0-56
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts)

**Comment by CaerusKaru** [comment]
I know this seems like a simple fix, but did you try restarting your server instance? That’s what fixed this for me.

**Comment by ThomasBurleson** [comment]
@svstartuplab - You can install latest (not released to npm) builds from master/HEAD using:

```console
npm i github:angular/flex-layout-builds --save
```

> You should use HEAD with Angular 4.3.

**Comment by ThomasBurleson** [comment]
Closing as invalid issue. 

> Will reopen if your issue persists AND you provide an online demo.

**Comment by svstartuplab** [comment]
CaerusKaru - Yes, I restarted ng serve and it didn't help.  I'll try Tom's suggestion next.

**Comment by svstartuplab** [comment]
Thanks Tom, your suggestion worked!
