### ISSUE TITLE
fxLayoutWrap fxLayoutGap Margin Issue in last row

### ISSUE THREAD

**Issue by naveedahmed1** [angular/flex-layout#363]
Please take a look at the below plunker and notice the last row:

https://plnkr.co/edit/pBA4A55u3hQVfi1DkGdw?p=preview

Since the last box in the last row is missing the margin-right the boxes in this row are not properly aligned.

As per the documentation of fxLayoutGap it says:

"Note that the last child item will NOT have a margin gap specified; only the inside gaps are specified."

This works great when boxes can be accommodated in one row. But when we are using fxLayoutWrap and we need more than one rows to accommodate boxes the boxes in last row has alignment issue.

To address this, when using fxLayoutWrap, I think it should either add margin right to the last box as well or the margin right should be removed from the last element in each row.

**Comment by ThomasBurleson** [comment]
@naveedahmed1 - This is an interesting issue.

This is an issue that we should not solve programmatically: to determine the number of elements on a row and adjust the last right-gap accordingly.  The solution is super-easy from a CSS perspective:

![screen shot 2017-08-07 at 9 22 16 am](https://user-images.githubusercontent.com/210413/29030946-47031aa8-7b52-11e7-8cca-fb30c3a08743.png)

> Simply add a CSS style `[fxFlex]:last-of-type { margin-right:15px; }`

Closing as a will-not-fix issue.

**Comment by naveedahmed1** [comment]
Thank you so much @ThomasBurleson . I think css based solution wont cover all cases, please take a look at the updated plunker

https://plnkr.co/edit/pBA4A55u3hQVfi1DkGdw?p=preview

**Comment by ThomasBurleson** [comment]
Again you will have to be more specific with your CSS to affect only the sections desired. 
I this [working plunkr](https://plnkr.co/edit/KaEOvnomlVBSJg6y3dew?p=preview), I use a `.align` class.

> Again, we will not fix this.

**Comment by naveedahmed1** [comment]
@ThomasBurleson can you please take a look at the updated plunker 

https://plnkr.co/edit/XxnF3pXG1MkIrGZfgna3?p=preview

Though adding margin to the last child solves above problem but introduces another problem,  as shown in the updated plunker. I understand even this could be handles through css, but don't you think flex-layout should handle the row wrap more gracefully so that we dont have to use such hacks.

**Comment by jkossis** [comment]
Any update? With the proposed 'align' solution, the wrapped items are not centered, the right will always have more margin with respect to the container. I think an API solution would be desirable, and warranted.

**Comment by stoto34** [comment]
Is  there a solution ? I have the same problem with "padding-right" for the last element. 
The last element has no padding in the documentation, I don't understand.
