### ISSUE TITLE
[ObservableMedia]: isActive doesn't eval 'lt-lg' properly

### ISSUE THREAD

**Issue by denver-HJS** [angular/flex-layout#368]
**Expected Behavior:** the API method `isActive` should return `true` when passed the mqAlias "lt-lg" when the viewport matches the media query 'screen and (max-width: 1279px)'

**Actual Behavior:** the API method `isActive` is returning `false` when it should match for "lt-lg" mqAlias.

You can see here I've logged the behavior to the console:

![media-query-logs](https://user-images.githubusercontent.com/1916018/29049468-fa086256-7b8a-11e7-950a-4f5b84a1801a.png)

**Implementation**:
```
constructor(public mediaQueryService:ObservableMedia) {
  this.mediaWatcher = this.mediaQueryService
      .subscribe(mediaChange => {
        console.log("--------------------------------------------------------------------");
        console.log("LESS THAN LARGE", this.mediaQueryService.isActive(MaterialMediaQueries.LT_LARGE));
        console.log("GREATER THAN SMALL", this.mediaQueryService.isActive(MaterialMediaQueries.GT_SMALL));
        
        this.activeMediaViewport = mediaChange.mqAlias;
        console.log("ACTIVE mqAlias", this.activeMediaViewport);
      });
}

// enum definition
export const enum MaterialMediaQueries {
  EXTRA_SMALL = "xs",
  SMALL = "sm",
  MEDIUM = "md",
  LARGE = "lg",
  EXTRA_LARGE = "xl",
  LT_SMALL = "lt-sm",
  LT_MEDIUM = "lt-md",
  LT_LARGE = "lt-lg",
  LT_EXTRA_LARGE = "lt-xl",
  GT_EXTRA_SMALL = "gt-xs",
  GT_SMALL = "gt-sm",
  GT_MEDIUM = "gt-md",
  GT_LARGE = "gt-lg"
}
```

*Note: I've only tested aliases 'gt-sm' and 'lt-lg' at this time.*

**Comment by ThomasBurleson** [comment]
@denver-HJS - 

`ObservableMedia` currently excludes overlapping breakpoints and announces (via subscriptions) standard breakpoints activations ONLY.

The `.isActive(<mediaQuery | alias>)` does work. 

```js
this._media$.subscribe((e: MediaChange) => {
  this._activeMQC = e;

  console.log(`active: ${e.s}`);
  console.log(`lt-md active: ${_media$.isActive('lt-md')}`);
  console.log(`gt-md active: ${_media$.isActive('gt-md')}`);

});
```

You should:

```bash
npm uninstall @angular/flex-layout
npm i --save angular/flex-layout-builds   
```

>  NOTE: ^ installs the latest builds not yet released to npm.

**Comment by denver-HJS** [comment]
Thanks for the explanation and note. I've installed the latest build as you suggested, and the `isActive` result for the overlapping breakpoint is now correct.

**Comment by yarachid** [comment]
There should be an  isActive(query: string): Observable<Boolean> that react to changes.
