### ISSUE TITLE
fxFlexAlign="end" doesn't seem to be working

### ISSUE THREAD

**Issue by intergleam** [angular/flex-layout#371]
I am trying to do something like this 
![image](https://user-images.githubusercontent.com/2155554/29067629-1a339238-7c3c-11e7-990d-af1da5dbfb5d.png)

As described in [docs](https://github.com/angular/flex-layout/wiki/Declarative-API-Overview), but fxFlexAlign doesn't work
https://plnkr.co/edit/q7K5rfFM495yTJAVaXqf?p=preview

Am i missing something or this is a bug? If I missed something tbh it's because docs are not too clear

**Comment by mackelito** [comment]
fxFlexAlign needs fxLayoutAlign if you want to use it this way.
https://plnkr.co/edit/tB4M8cwodBHq96XWxV7X?p=preview

**Comment by intergleam** [comment]
it still doesn't do what I need, see the image above

**Comment by mackelito** [comment]
Updated the plunkr.. have a looksi 😃

**Comment by ThomasBurleson** [comment]
@mackelito - that is perhaps too complicated. Here is a much simpler approach:

```html
    <div class="containerX colored box nopad" 
         fxLayout="row" 
         fxLayoutAlign="space-between center" >      

        <div>1</div>
        <div>2</div>
        <div fxFlex>fill</div>
        <div>3</div>

    </div>
```

![screen shot 2017-08-08 at 11 57 05 am](https://user-images.githubusercontent.com/210413/29084198-db74169a-7c30-11e7-9e4f-8be14ad48955.png)

> Closing as not-an-issue.

General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Thank you.
