### ISSUE TITLE
The layout I am referring to build a form is column on outside and subsequent rows containing label and select tags but the fxLayout="row" does not work for all the rows , it works only for the 1st row, for "@angular/core": "^2.4.3", "@angular/flex-layout": "2.0.0-beta.1",

### ISSUE THREAD

**Issue by agrawalharsh** [angular/flex-layout#375]
<md-dialog-content class="accent-color">
                <p class="normal-gray-txt text-center"><b>Choose reference architecture</b></p>
                <form [formGroup]="custAppDetail" (ngSubmit)="submitDialogData()" fxLayout="column" >

                                 <div fxLayout="row">   
                                        <label fxFlex="1 6 60%"> Architecture file source</label>            
                                        <md-select fxFlex="3 1 40%" placeholder="Neomegha/Github"  formControlName="archFileSource" (ngModelChange)="toNeoGit($event)">
                                        <md-option *ngFor="let env of archFileSrc" [value]="env.value">
                                                    {{ env.viewValue }}
                                        </md-option>
                                        </md-select>         
                                 </div>  
                        

                                 <div fxLayout="row">
                                        <label fxFlex="1 6 60%"> Architecture file</label>        
                                            <md-select fxFlex="3 1 40%" placeholder="Choose file" formControlName="archFile">
                                            <md-option *ngFor="let env of archF" [value]="env.value">
                                                        {{ env.viewValue }}
                                            </md-option>
                                            </md-select>        
                                        
                                 </div>

                                  <div>  
                                            <label fxFlex="1 6 60%"> Name </label>   
                                            <md-input fxFlex="3 1 40%" type="text" placeholder="Enter Name" formControlName="name">
                                            </md-input>                         
                                    
                                 </div>

                            <div>
                                        <label fxFlex="1 6 60%"> Cloud </label>
                                            <md-select fxFlex="3 1 40%" placeholder="Choose Cloud" formControlName="cloudType" (ngModelChange)="toEnv($event)">
                                                <md-option *ngFor="let env of cloud" [value]="env.value">
                                                    {{ env.viewValue }}
                                                </md-option>
                                            </md-select>  
                            </div>

                            <div>
                                        <label fxFlex="1 6 60%"> Enviroment </label>
                                            <md-select fxFlex="3 1 40%" placeholder="Choose Environment" formControlName="selEnv">
                                                <md-option *ngFor="let env of enviroment" [value]="env.value">
                                                    {{ env.viewValue }}
                                                </md-option>
                                            </md-select>
                            </div>

                        <div class="box-btn-dialog" [hidden]="ftUser">
                            <button md-raised-button class="auto-btn-prime" [disabled]="!custAppDetail.valid" type="submit">LAUNCH</button>

                            <button md-raised-button class="auto-btn-gray" md-dialog-close="cancel" type="button">CANCEL</button>
                        </div>
                    </form>
           
</md-dialog-content>

**Comment by ThomasBurleson** [comment]
This is an invalid issue submission: title is wrong, plunkr demo is missing

**Comment by agrawalharsh** [comment]
Hi @ThomasBurleson thanks for pointing it out ,I watched ur nghouston video as well and tried implementing  from past 48hrs but not able to get the desired output, any lead would be appreciated
