### ISSUE TITLE
ImgSrcsetDirective - Polyfill support for IE11 

### ISSUE THREAD

**Issue by benbraou** [angular/flex-layout#377]
1. **Overview of the Issue** 
    - ImgSrcsetDirective injects &lt;source&gt; elements and makes sue of the srcset attribute. This is not supported in IE11 (http://caniuse.com/#search=picture)
2. **Flex-Layout version** v2.0.0-beta.9 (https://github.com/angular/flex-layout/pull/366)
3. **Motivation for or Use Case** Enhancements suggested by @ThomasBurleson 
4. **Browsers and Operating System** any
5. **Reproduce the Error** N.A
6. **Screenshots** N.A
7. **Related Issues** https://github.com/angular/flex-layout/pull/366#issuecomment-321072913
8. **Quoting @ThomasBurleson considerations**

@benbraou - Since the mediaActivationResponse will already tell use about MediaChange events, I think we should inject detect IE11 and update the imge.src value.
img-srcset.ts

```typescript
constructor(
    elRef: ElementRef, 
    renderer: Renderer, 
    monitor: MediaMonitor,
    @Inject(DOCUMENT) private _document:any ) {
  super(monitor, elRef, renderer);
}

 ngOnInit() {
   const isIE = !!this._document['documentMode'];
  

   this._listenForMediaQueryChanges('srcset', '', (change:MediaChange) => {
    if (isIE) {
       // IE11 does not support the <picture> element; so responsively change the <img src="">
       // Normally, there is no need to subscribe to mediaQuery changes as it is
       // up to the browser to use the relevant injected <source> element

       this._updateImageSrc(change.mqAlias);
    }   
   });
   
   if ( !isIE ) {
     this._injectSourceElements();
   }
 }
```

**Comment by benbraou** [comment]
I will be working on this issue at the end of the month (I will notify when I start)
Please note that this PR depends on #376 (use of rendering strategy, and the src value that has been cached)

**Comment by ThomasBurleson** [comment]
This is in-progress.

**Comment by CaerusKaru** [comment]
It looks like the `ImgSrcsetDirective` has been replaced by the `ImgSrcDirective`, which is more compatible with IE. Can you confirm?

**Comment by benbraou** [comment]
@CaerusKaru indeed. I see that `ImgSrcDirective ` responsively updates src attribute. So, there is no issue when using IE.
The issue can be vlosed
