### ISSUE TITLE
Angular CLI Integration wiki is inaccurate

### ISSUE THREAD

**Issue by fisherds** [angular/flex-layout#379]
@ThomasBurleson I checked your integration instructions for the Angular CLI with the current latest stable version: angular/cli 1.3.0 and it didn't work.

The old instructions where at:
https://github.com/angular/flex-layout/wiki/Integration-with-Angular-CLI

Summary of what it said:
```
npm install --save @angular/flex-layout@latest

import { FlexLayoutModule } from '@angular/flex-layout';
@NgModule({
  imports: [FlexLayoutModule],
})
```

The new page is:
https://github.com/angular/flex-layout/wiki/Using-Angular-CLI

Will flex layout be included in the future???  It does not appear to be true for the 1.3.0 angular/cli.  To be honest for me, the old instructions were perfect and the new instructions (changed on August 5th) are completely worthless.  Am I missing something?

**Comment by ThomasBurleson** [comment]
The current npm release Beta.8 does not support Angular 4.x
The latest builds (and upcoming Beta.9 DO support Angular 4.x and AOT and CLI 1.3.0)

I updated the WIKI docs with instructions to install from the nightly builds.
