### ISSUE TITLE
fxHide not working if child as fxFlex

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#385]
Perhaps this is as intended but found out that `fxHide.gt-sm`  will not work properly
https://plnkr.co/edit/ouK6V7u4VaatrBXlJo5c?p=preview

<img width="1247" alt="screen shot 2017-08-21 at 10 40 28 am" src="https://user-images.githubusercontent.com/210413/29527054-307b404c-865d-11e7-8aae-0962d8afa82e.png">

>  On resize `fxHide`  works as expected but not on initial pageload

**Comment by ThomasBurleson** [comment]
This does appear to be working; even for initial-page-loads:

<img width="736" alt="screen shot 2017-08-21 at 10 43 24 am" src="https://user-images.githubusercontent.com/210413/29527159-a77aa61a-865d-11e7-88b6-100b14e634f9.png">


Please try the above demo link (which uses the latest nightly build).

**Comment by mackelito** [comment]
Eeerhm.. what link? :)

**Comment by ThomasBurleson** [comment]
Closing as invalid issue.
