### ISSUE TITLE
subscribing to ObservableMedia doesnt start with value on load of XS mq

### ISSUE THREAD

**Issue by tuurbo** [angular/flex-layout#388]
Open the example below with a XS mobile size screen  and ObservableMedia doesn't fire on page load, but it seems to work fine for all other media query sizes.

![screen shot 2017-08-28 at 5 38 13 pm](https://user-images.githubusercontent.com/210413/29796611-bbbaf188-8c17-11e7-8e13-ab60fa40e33f.png)

https://angular-wfwpzp.stackblitz.io/

source:
https://stackblitz.com/edit/angular-wfwpzp?file=app%2Fapp.component.ts

**Comment by ThomasBurleson** [comment]
See [working Plunkr](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview)

![screen shot 2017-08-28 at 7 48 52 pm](https://user-images.githubusercontent.com/210413/29799560-020b41f8-8c2a-11e7-9a06-8de025cfdbbe.png)
