### ISSUE TITLE
flexLayout="column" not working on server platform

### ISSUE THREAD

**Issue by alirezamirian** [angular/flex-layout#389]
`fxLayout="column"` doesn't work when rendering on server. The applied `flex-direction` is always row.

#### version information:
- "@angular/flex-layout" : "github:angular/flex-layout-builds",
- "@angular/{almoseAnythingElse}": "4.3.5"

**Comment by ThomasBurleson** [comment]
I am NOT seeing any issues when using:

*  https://github.com/angular/universal-starter
*  Angular 4.3.x, and
* Flex-Layout v2.0.0-beta.9, 

```html
<div fxLayout="column" style="min-height:200px;">
    <h1>Universal Demo using Angular</h1>
    <a routerLink="/">Home</a>
    <a routerLink="/lazy">Lazy</a>
  </div>
```

works just fine with SSR.

Please provide a reproducible example.

**Comment by ThomasBurleson** [comment]
Closing as "not an issue". Will reopen with reproduce demo.

**Comment by alirezamirian** [comment]
Thanks a lot. I will check it again and provide a reproducible example.
