### ISSUE TITLE
 npm ERR! 404  '@angular/flex-layout' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

### ISSUE THREAD

**Issue by smile2014** [angular/flex-layout#39]
npm ERR! 404  '@angular/flex-layout' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by fxck** [comment]
I wonder why..

https://github.com/angular/flex-layout/issues/35

https://github.com/angular/flex-layout/issues/30

![image](https://cloud.githubusercontent.com/assets/1303561/21097777/856421c2-c066-11e6-9469-6cb4cdda523b.png)

**Comment by kuncevic** [comment]
I know a few more people including me who just cath that. It would of be great if the message **peanding feature** would of be better highlighted.

**Comment by ThomasBurleson** [comment]
Fixed with SHA d3ea8ad.

**Comment by smile2014** [comment]
thank you

2016-12-12 21:19 GMT+08:00 Thomas Burleson <notifications@github.com>:
