### ISSUE TITLE
Rows interfering each other, any clearfix?

### ISSUE THREAD

**Issue by matheo** [angular/flex-layout#392]
I have this subgrid inside responsive material grid, and it's bugging me off on mobile devices (`xs`):
```html
<md-grid-tile [rowspan]="2">
  <div fxLayout="row" fxLayoutWrap.xs fxLayoutGap.gt-xs="4%" fxFlex="99%">
    <div fxLayout="row" fxLayoutAlign=" center" fxFlex.gt-xs="48%" fxFlex.xs="100%" fxFlexOrder="1">
      <md-select required formControlName="clientFeet" [placeholder]="'BOARD.HEIGHT' | translate">
        <md-option *ngFor="let feet of feets" [value]="feet">{{ feet }}</md-option>
      </md-select>
      <span mdSuffix>feet</span>
    </div>
    <div fxLayout="row" fxLayoutAlign=" center" fxFlex.gt-xs="48%" fxFlex.xs="100%" fxFlexOrder="2">
      <md-select required formControlName="clientInches" floatPlaceholder="never">
        <md-option *ngFor="let inch of inches" [value]="inch">{{ inch }}</md-option>
      </md-select>
      <span mdSuffix>inches</span>
    </div>
  </div>
</md-grid-tile>
```
somehow the contents are interfering:

![flexbox](https://user-images.githubusercontent.com/260185/29698682-02c4a392-891d-11e7-8d01-2b8559579f38.png)

note that the `inches` row content ends on the upper selector end.

I've tried to apply a lot of different styles to the row elements with no luck, the screenshot has these:
```css

.mat-input-container,
.mat-select {
  flex: 1;
}
[mdsuffix] {
  flex: 0.1 0 auto;
}
```
I have verified element by element on the DOM checking any differences and nope, it's this Chrome v60 for Ubuntu or there's some clearfix that I can apply to avoid this?

Help please!

P/S: I notice that when I swap between mobile/tablet/desktop viewports on my Chrome console, it recalculates and render the containers properly. It's on the initial refresh that calculations goes wild, any known workaround or solution? :(

**Comment by ThomasBurleson** [comment]
@matheo - this is a classic issue with Flexbox `flex-direction: column`. Please provide a Plunkr and we can investigate/resolve: [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview)

**Comment by CaerusKaru** [comment]
It's been roughly four months since a demo was requested. If you can provide a demo, we will reopen this issue.

**Comment by matheo** [comment]
@CaerusKaru it's working Ok with the latest version, thx
