### ISSUE TITLE
ClassDirective throws renderer error with Angular 5.0.0-beta.5

### ISSUE THREAD

**Issue by PascalPrecht** [angular/flex-layout#398]
This is because `@angular/flex-layout` doesn't support Angular's `Renderer2` yet, which is the only supported version in Angular `5.0.0-beta.5`. Prior to that release, `Renderer` could be used as well and flex-layout takes advantage of that service in `NgClass` extensions.

<img width="721" alt="screen shot 2017-08-29 at 8 19 11 am" src="https://user-images.githubusercontent.com/210413/29823259-c8927a80-8c93-11e7-8808-8a8ca3161e8a.png">

I've opened the original issue over at `@angular/angular` right [HERE](https://github.com/angular/angular/issues/18922)

Also, it seems this will likely be fixed with https://github.com/angular/flex-layout/pull/391 which is pending right now.

**Comment by ThomasBurleson** [comment]
@angular/flex-layout has a ClassDirective to support responsive APIs for **class** and **ngClass**.

This directive no longer extends the ngClass fro @angular/core. Instead it internally composes an instances of this class (if needed) and delegates actions to that instance. 

> With @mhevery's help, the Flex-Layout now uses a Renderer2.

**Comment by kelsmj** [comment]
Any idea when this fix will be committed?

**Comment by ThomasBurleson** [comment]
The PR(s) are in the queue and should be merged into master today. We hope to publish Beta.10 soon.

**Comment by kelsmj** [comment]
Great, thanks....this one bit me

**Comment by spock123** [comment]
Dang cost me 2 days to figure out where it came from.. the old fashioned remove one component/module at a time until I was down to Angular/Flex :)

Looking forward to the update, guys :) thanks

**Comment by spock123** [comment]
Hi guys, any news about this?

It doesn't appear to have been merged into master yet... nobody is able to upgrade to Angular 5 beta 5 or beta 6... 

Thanks for your great work, really hoping for this to be merged soon.

**Comment by ThomasBurleson** [comment]
@spock123  - hopefully this will be merged today.
