### ISSUE TITLE
documentation for fxLayoutAlign

### ISSUE THREAD

**Issue by spottedmahn** [angular/flex-layout#399]
When I'm on the [api documentation page](https://github.com/angular/flex-layout/wiki/API-Documentation) and click on [fxLayoutAlign](https://github.com/angular/flex-layout/wiki/fxLayoutAlign-API) it takes me to the home page.  Is that b/c that doc has not been created yet or is there a bug?

**Comment by matheo** [comment]
the best documentation is a sandbox:
https://tburleson-layouts-demos.firebaseapp.com/#/docs
but yes, the links got broken in the last release
because I had them opened and suddenly a I got a redirect

**Comment by spottedmahn** [comment]
thanks for the link @matheo.  In the demo, I don't see `space-evenly` as an option.  I was trying to figure out if the demo was missing or the library.

You mentioned the link is broken.  I looked through the pages and I could find it.  Can you share the link?  Thanks!!

**Comment by matheo** [comment]
I meant that the page disappeared, like it was deleted or something.

**Comment by CaerusKaru** [comment]
Seems to be working again, can you confirm?

**Comment by spottedmahn** [comment]
sorry, still not working for me.  https://github.com/angular/flex-layout/wiki/fxLayoutAlign-API gets redirected to https://github.com/angular/flex-layout/wiki

![image](https://user-images.githubusercontent.com/14079228/33999515-b3c3afce-e0b8-11e7-9d77-c765b0fdbd0e.png)

![image](https://user-images.githubusercontent.com/14079228/33999618-ebe85f6c-e0b8-11e7-9239-a1f53255ea8c.png)

**Comment by CaerusKaru** [comment]
My mistake, thought you meant `fxLayout`. I've searched the source for the Wiki and its Git history looking for the original file, but it doesn't look like it ever existed. Does anyone have a cached copy? Otherwise it will have to be re-written and committed.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 67e4bf5bccc0ade
