### ISSUE TITLE
Input Field With Focus Is Hidden Behind The Keyboard

### ISSUE THREAD

**Issue by briantq** [angular/flex-layout#400]
When running an Angular 2/4 app on an Android device on Chrome, I am finding text inputs to be problematic.  When users set focus on a text input field, the native keyboard comes up and hides the text input field.  

We are also using Angular Material in our application and found a bug referencing the issue and suggesting it was a Flex Layout issue, https://github.com/angular/material/issues/1349.  In the issue, there is a test that reproduces the issue.  The bug is over quite old, but if you test it on a mobile device you will find it is indeed still failing.

**Comment by mackelito** [comment]
Could you create a plunkr to reproduce the issue?

**Comment by ThomasBurleson** [comment]
This appears to be a Chrome bug with flexbox css itself... which means this is not an issue that @angular/flex-layout should address.
