### ISSUE TITLE
Weird folding for safari

### ISSUE THREAD

**Issue by huttarichard** [angular/flex-layout#401]
Hi Guys, love flex, amazing job.

Just want to share what doesn't make sense to me. Maybe its just my problem, but maybe its a bug in flex api. or maybe this is just problem with safari and flex. But check this out.

I have html looking like this (I cut html which wanst related):
```html
<div fxLayout="row"  fxLayout.lt-md="column" fxLayoutAlign="space-between stretch">
		<div fxFlex="35" fxFlex.lt-md="grow">
			....
		</div>

		<div fxFlex="65" fxFlex.lt-md="grow" fxLayout="column" fxLayoutAlign="center stretch">
			<div fxFlex="50" fxFlex.lt-md="auto" fxLayout="row" fxLayout.lt-md="column" fxLayoutAlign="center stretch" class="orange-bg">
				<h1>Jeůůp</h1>
			</div>
			<div fxFlex="50" fxFlex.lt-md="auto" fxLayout="row" fxLayout.lt-md="column" fxLayoutAlign="center stretch" class="blue-bg">
				<h1>omg</h1>
			</div>
		</div>
	</div>
```

Chrome (working correctly):
![screen shot 2017-08-31 at 14 41 22](https://user-images.githubusercontent.com/1809268/29923653-8e24040e-8e5a-11e7-90a2-bfded07e7054.png)

Safari (wrong): 
![screen shot 2017-08-31 at 14 41 34](https://user-images.githubusercontent.com/1809268/29923652-8e22041a-8e5a-11e7-87f4-56d33a8426b4.png)

SO I replicated the issue on plunker:

https://plnkr.co/edit/PwomqwGNZpb6r8972AYW?p=preview

**Comment by huttarichard** [comment]
some happens for fxFlex="grow" btw...
```html
<div fxLayout="row"  fxLayout.lt-md="column" fxLayoutAlign="space-between stretch">
		<div fxFlex="35" fxFlex.lt-md="grow">
			....
		</div>

		<div fxFlex="65" fxFlex.lt-md="grow" fxLayout="column" fxLayoutAlign="center stretch">
			<div fxFlex="50" fxFlex.lt-md="grow" fxLayout="row" fxLayout.lt-md="column" fxLayoutAlign="center stretch" class="orange-bg">
				<h1>Jeůůp</h1>
			</div>
			<div fxFlex="50" fxFlex.lt-md="grow" fxLayout="row" fxLayout.lt-md="column" fxLayoutAlign="center stretch" class="blue-bg">
				<h1>omg</h1>
			</div>
		</div>
	</div>
```

**Comment by benbraou** [comment]
This is a Safari bug: https://bugs.webkit.org/show_bug.cgi?id=137730
It was fixed and will be available in Safari 11. I have tested with the latest [Safari Technology Preview ](https://developer.apple.com/safari/download/) and I don't reproduce.

FYI, below is the display in Safari Technology Preview
<img width="829" alt="safari technology preview" src="https://user-images.githubusercontent.com/14368835/29996184-04db4e18-8ffa-11e7-99f5-055ae2e2feb7.png">

and the display in Safari 10:

<img width="642" alt="safari 10" src="https://user-images.githubusercontent.com/14368835/29996207-8c92fdec-8ffa-11e7-85df-b5ce5eb791e1.png">

A workaround in Safari 10 is to set a height property on the parent div fxLayout="row" but is this really needed...

@ThomasBurleson do you think this issue can be closed ?

**Comment by huttarichard** [comment]
@benbraou thanks, I though so. You right safari 11 working great wish I tried that before.

**Comment by ThomasBurleson** [comment]
When using "column" mode, (with manual CSS or Flex-Layout) developers often must specify the height (or min-height) of the host element. This is a browser issue not a Flex-Layout issue.

Closing as not-a-valid-issue.
