### ISSUE TITLE
demo app wanted using angular material 2 plus flex layout

### ISSUE THREAD

**Issue by eddyzhu1980** [angular/flex-layout#407]
Is there a demo app using angular material 2 plus flex layout? so I can learn the best practice to use them together. Thank you.

**Comment by jotatoledo** [comment]
Please use the issue tracker to report issues/features/bugs, not general support or questions. There is a [gitter room for this](https://gitter.im/angular/flex-layout?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by ThomasBurleson** [comment]
Our demo-app uses @angular/material. See https://github.com/angular/flex-layout/blob/master/src/demo-app/app/shared/_module.ts#L15

> Updated source will be published soon. These are updates to use the latest release of Angular Material + CDK.
