### ISSUE TITLE
Documentation Sidebar 404

### ISSUE THREAD

**Issue by sneckelmann** [angular/flex-layout#412]
Sorry if this isn't the right place for this.

The documentation's sidebar under section "Demos" has a link to "[Source Code](https://github.com/angular/flex-layout/blob/master/src/demo-app/app/demo-app-module.ts)"

I believe the address should be corrected to 
https://github.com/angular/flex-layout/blob/master/src/demo-app/demo-app-module.ts

**Comment by BobbieBarker** [comment]
The demo application is also throwing 404 errors.

**Comment by ThomasBurleson** [comment]
Fixed.
