### ISSUE TITLE
The demo isn't working anymore.

### ISSUE THREAD

**Issue by aminecmi** [angular/flex-layout#413]
Hi,

The [demo](https://tburleson-layouts-demos.firebaseapp.com/) isn't working anymore.

These are the errors in the developer console.
![There are errors in the console](https://user-images.githubusercontent.com/510304/30200961-58f30242-9479-11e7-809b-307c46230f40.png)

Hope it helps.

**Comment by ThomasBurleson** [comment]
Fixed. See https://tburleson-layouts-demos.firebaseapp.com/#/docs
