### ISSUE TITLE
samsung built in browser layout problems

### ISSUE THREAD

**Issue by maku** [angular/flex-layout#414]
I have constantly problems with flex-layout and the build in browser on samsung phones.

Is there anywhere I guide what I have to consider in this context (how compatible is the samsung browser?)

**Comment by sylvaindumont** [comment]
I had problems with samsung browser too, i fixed them by replacing empty `fxFlex` by `fxFlex="auto"`.
It seems like samsung browser has a problem growing elements with: `flex: 1 1 1e-09px` specified by flex-layout on empty fxFlex.

**Comment by maku** [comment]
@sylvaindumont thanks for the hint. This worked for me...
