### ISSUE TITLE
latest package on unpkg.com reports wrong version

### ISSUE THREAD

**Issue by parker-mike** [angular/flex-layout#416]
`https://unpkg.com/@angular/flex-layout@2.0.0-beta.9/bundles/flex-layout.umd.js`
line 40 states:
 `var VERSION = new _angular_core.Version('2.0.0-beta.8-d171c33');`

**Comment by ThomasBurleson** [comment]
@parker-mike - yes the Beta.9 tag was not deployed properly. The nightly build has the proper version information: 

*  https://github.com/angular/flex-layout-builds/blob/master/bundles/flex-layout.umd.js#L40
*  `npm install https://rawgit.com/angular/flex-layout-builds/master/bundles/flex-layout.umd.js`

**Comment by demisx** [comment]
I believe there is still something off with the versioning. NPM currently reports beta 9 to be the latest, thus newer than the 2.0.0-rc.1 release candidate. After installing the latest `@angular/flex-layout`, here is what i see reported:

```
$ npm out @angular/flex-layout 
Package                    Current      Wanted        Latest  Location
@angular/flex-layout  2.0.0-beta.9  2.0.0-rc.1  2.0.0-beta.9  
```

Caused some confusion in #461

**Comment by ThomasBurleson** [comment]
@demisx - I just tried the same command:

```console
npm help out
~/Downloads/angular-flex-layout-seed []: npm out @angular/flex-layout
Package                            Current  Wanted  Latest  Location
@angular/flex-layout  2.0.0-beta.9-1267972     git     git  angular-template
```

**Comment by ThomasBurleson** [comment]
@parker-mike - this is fixed with the most recent *next* builds:  https://github.com/angular/flex-layout-builds/blob/master/bundles/flex-layout.umd.js

**Comment by demisx** [comment]
@ThomasBurleson  Perhaps you are pointing to the Github URL in your `package.json`? This is what I see on my end:

```
$ cat package.json | grep flex
"@angular/flex-layout": "^2.0.0-beta.9",

$npm out
Package                    Current      Wanted        Latest  Location
@angular/flex-layout  2.0.0-beta.9  2.0.0-rc.1  2.0.0-beta.9  dimaslist-org-fe
```
