### ISSUE TITLE
404: Not found

### ISSUE THREAD

**Issue by aleixsuau** [angular/flex-layout#417]
Hi,
I'm having a 404 apparently coming from fxLayoutWrap directive:
![captura de pantalla 2017-09-12 a las 12 33 35](https://user-images.githubusercontent.com/25689432/30321601-f7009158-97b6-11e7-80bd-6d7e065847d9.png)
I've tried using the same version for material, cdk and flex-layout but it has only changed the error source from core.es5.js to base.js.

Any idea about what is going on?

Awesome library btw :)

Thanks

**Comment by ThomasBurleson** [comment]
@aleixsuau - here provide a demo manifesting this issue. See [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview) which uses Material, CDK, and Flex-Layout.

**Comment by aleixsuau** [comment]
@ThomasBurleson I updated node modules and the error disappeared. 
Thanks for your replay anyway.
