### ISSUE TITLE
Angular 5 error: _this._renderer.addClass is not a function

### ISSUE THREAD

**Issue by WilhelmOlejnik** [angular/flex-layout#420]
Flex layout seems to not work on Angular 5. 
Using flex directives or even using `class` attribute with FlexLayoutModule imported results in error: `_this._renderer.addClass is not a function`

Plunkr: https://plnkr.co/edit/UF0nq5ZxNg2FdsVatu6z?p=preview

**Comment by ThomasBurleson** [comment]
This has been partially fixed here: SHA 816d85a6. 
And the `[style]` should NOT be creating a StyleDirective. Which is fixed in this PR #419.

**Comment by ThomasBurleson** [comment]
Fixed with SHA e461d17471f713deaf4663e0a0438822f8f0ad86

> This functionality is available in the [nightly build](https://github.com/angular/flex-layout-builds/blob/master/bundles/flex-layout.umd.js) and will be released to npm with the [upcoming] Beta.10 release.

**Comment by alexjlockwood** [comment]
Will flex-layout beta 10 be released with Angular 5.0.0?
