### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: using fxHide

### ISSUE THREAD

**Issue by dhuallanca** [angular/flex-layout#421]
Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'

I am using fxHide.gt-sm

**Comment by ThomasBurleson** [comment]
Please provide a Plunkr demo.

**Comment by ThomasBurleson** [comment]
Related to #415

**Comment by nadjem** [comment]
Had this same issue and fixit after reading [this blog post ](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4)

**Comment by ThomasBurleson** [comment]
@nadjem - There are several solution approaches...  I am curious how you fixed it on your version. 

> Maxim's blog article `Everything you need to know about the 'ExpressionChangedAfterItHasBeenCheckedError' error` is a great article.

**Comment by nadjem** [comment]
@ThomasBurleson 
In my case, I have two components that communicate together via a service and I added the "setTimeout" in both.
like this example from the article
 `ngOnInit() {
        setTimeout(() => {
            this.parent.text = 'updated text';
        });
    }`
and it work for me.
;)

**Comment by ThomasBurleson** [comment]
@nadjem - Understood. In this case, a settimeout **outside** the ObservableMedia seems like a *bandaid that simply hides the infection*.

**Comment by nadjem** [comment]
@ThomasBurleson ok I understand, if you have a better solution i am really interested

**Comment by mackelito** [comment]
I have the same issue but non fxFlex related.. the problem occurs when using md-accordion component from Material Design. I want to have the panel expanded on load if the route match "outerLinkActive #rla="routerLinkActive" [expanded]="rla.isActive"" this works but gives this error in the console.

I can solve this problem by using "changeDetection: ChangeDetectionStrategy.OnPush" but then I cant use outerLinkActive... still looking for a solution :)

**Comment by mackelito** [comment]
This is a race condition present in the RouterLinkActive. 
https://github.com/angular/material2/issues/6701
https://github.com/angular/angular/issues/18983

**Comment by CaerusKaru** [comment]
It's been three months since a demo was requested. If you can provide one with the specified behavior, we can reopen this issue.
