### ISSUE TITLE
Please cut a new beta

### ISSUE THREAD

**Issue by spock123** [angular/flex-layout#424]
I know the compatibility issues have been resolved in Master, but it's really not the best option having to rely on the master repo in our project dependencies... who knows what will break in upcoming commits? 

For my job, we're not even allowed to use github repos as dependencies... and I'm sure I'm not alone.

Would it be a big task to cut a new version from current master, so that we can sleep better at night?

The current beta breaks Angular 5 beta 5, 6 and 7.

Thanks a bunch.

**Comment by fxck** [comment]
Use https://github.com/angular/flex-layout-builds instead.

**Comment by spock123** [comment]
@fxck Thanks, I didn't know about flex-layout-builds.

I would still hope for a new beta, to me it seems a bit wild that for a month now, flex-layout does not work on Angular5..

**Comment by ThomasBurleson** [comment]
@fxck  - Thank you for your helpful comment. 

> Current Beta.9 has several known issues. [Nightly builds](https://github.com/angular/flex-layout/wiki/Fast-Starts#npm-install) has many fixes (ObservableMedia, Angular5, and more). Note that  the @angular/flex-layout Beta.10 release has been delayed while work on Angular Material resolves this week.

**Comment by mackelito** [comment]
@ThomasBurleson it´s been some time since a release (2017-08-22).. any idea when it might happen?

**Comment by spock123** [comment]
@mackelito

Seems like there isn't much going on here any more. I have migrated to Bootstrap4 grid system, works fine and is flexbox based. A shame really.

**Comment by mackelito** [comment]
@spock123 good for you.. but bootstrap is not for me ;)

**Comment by mackelito** [comment]
Btw.. they are working on Angular 5 features and support for SSR so I would still bet on flex-layout ;)

**Comment by ThomasBurleson** [comment]
During the past few weeks, intense efforts have been invested to prepare Angular Material for an RC release. Please expect to see a formal release of @angular/flex-layout v2.0.1-beta.10 release soon. In the interim, you should install [Nightly Builds for Angular 5](https://github.com/angular/flex-layout/wiki/NPM-Installs#install-from-nightly-build-head) compatibility.
