### ISSUE TITLE
Flex layout on Chrome overwriting rows

### ISSUE THREAD

**Issue by jtsom** [angular/flex-layout#425]
Trying a very simple example:
```
<div fxLayout="column">
  <header>Header</header>
  <div fxLayout="row" fxFlex>
    <nav fxFlex="1 6 20%">div</nav>
    <article fxFlex="3 1 60%">div</article>
    <aside fxFlex="1 6 20%">div</aside>
  </div>
  <footer>footer</footer>
</div>
```
Does not render correctly on Chrome
![screenshot at 2017-09-20 09-26-07](https://user-images.githubusercontent.com/13488/30646084-c5d9841a-9de5-11e7-9f37-63176840a2d0.png)

Angular version:
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 8.5.0
os: linux x64
@angular/animations: 4.4.3
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```

Seems to work ok on Firefox.

**Comment by mackelito** [comment]
Just remove the "fxFlex" on your row.
https://plnkr.co/edit/YU1ppT4JaURISbA4hGXb?p=preview

**Comment by CaerusKaru** [comment]
@mackelito is correct, this can be closed. 

The explanation is that the extra `fxFlex` is taking up all of the room in your column not used by previous elements, thus leaving the rest of the elements to get squeezed in at the end.

**Comment by CaerusKaru** [comment]
Closing as solution is provided. If this doesn't work for you, please provide a plunkr/StackBlitz demo similar to @mackelito and we will reopen.
