### ISSUE TITLE
ObservableMedia not working in Safari

### ISSUE THREAD

**Issue by adappter** [angular/flex-layout#427]
Hello,
the ObservableMedia Subscription is not working on Safari. IE, Chrome and Firefox are working.
Is there a workaround or something else?

```
 this.mediaChangeSubscription = this.media.subscribe((change: MediaChange) => {
      this.mqAlias = change.mqAlias;
      this.updateResponsiveGrid();
    );
```
This is what the console log looks like in Safari:
`MediaChange {matches: true, mediaQuery: "all", mqAlias: "", suffix: "", clone: function}`

**Comment by denver-HJS** [comment]
For what it's worth the service is working for me on the latest Safari using the following version:

```
 "@angular/flex-layout": {
      "version": "github:angular/flex-layout-builds#d2d390ce0fda1d010cfd0764e20dbdce6a1a6d3b",
      "requires": {
        "tslib": "1.7.1"
      }
    }
```

Maybe try updating yours and/or use the latest build via your package.json:

`"@angular/flex-layout": "github:angular/flex-layout-builds"`

**Comment by ThomasBurleson** [comment]
@denver-HJS - Thank you for the confirmation. 

> Yes, current Beta.9 has issues. [Nightly builds](https://github.com/angular/flex-layout/wiki/Fast-Starts#npm-install) has many fixes (ObservableMedia, Angular5, and more). Note that  the @angular/flex-layout Beta.10 release has been delayed while work on Angular Material resolves this week.
