### ISSUE TITLE
ngClass behavior change after latest nightly

### ISSUE THREAD

**Issue by naveedahmed1** [angular/flex-layout#428]
With latest release the below code is working perfectly:
 
`<button mat-raised-button color="primary" type="submit" [ngClass]="{'btn-xs':formButtonXs}">Save</button>`

But with latest nightly build, it no longer seems to work.

When value of formButtonXs is true the button has below classes:

`mat-primary btn-xs`

When value of formButtonXs is false the button has just below class:

`mat-primary`

**Expected behavior**

It should have `mat-raised-button mat-primary` when `formButtonXs` is `false` whereas, `mat-raised-button mat-primary btn-xs` when `formButtonXs` is `true`

**Comment by robisim74** [comment]
Same problem here. Using `ngClass`, all material classes are removed.
