### ISSUE TITLE
ngxSplitArea not working

### ISSUE THREAD

**Issue by snakeztc** [angular/flex-layout#429]
I have the following code in my html, but I am not able to resize the two columns. Moreover, I am implementing in WebStorm, which also gives me a warning "Attribute ngxSplit" not allowed here. It seems that the new split feature is not included. I install the latest flex-layout as in the master branch.

 `   "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",`

```
<div fxLayout="row" ngxSplit="row" fxFill>
<div fxFlex="70%" ngxSplitArea > .... </div>
<div fxFlex="30%" ngxSplitArea> .... </div>
```

**Comment by ThomasBurleson** [comment]
@snakeztc - ngxSplit is used in the Demos and is available in our [demo source](https://github.com/angular/flex-layout/blob/master/src/demo-app/app/github-issues/splitter/split.module.ts)... but it is NOT shipped with our @angular/flex-layout builds.

**Comment by snakeztc** [comment]
So how I can use this feature? Should I download the demo source code and incorporate manually or wait for this feature to be shipped to the master branch. If it will, when do you expect this feature will be put in the angular/flex-layout? Thank you!

**Comment by ThomasBurleson** [comment]
@snakeztc - General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Thank you.
