### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by einfallstoll** [angular/flex-layout#43]
> **This is just a preliminary documentation on how to use `flex-layout` with `npm` even though it's not yet supported. It's not recommended to use this in production!**

Install `flex-layout` using npm via GitHub
````
npm install --save https://github.com/angular/flex-layout.git
````
***This will save the current commit as installation candidate. Change this as `flex-layout` is published officially to npm!***

If you use the import as stated in the documentation you will receive an error that it can't find the module.
````
import { FlexLayoutModule } from '@angular/flex-layout';
// Cannot find module '@angular/flex-layout'.
````

therefore change the import to 

````
import { FlexLayoutModule } from '@angular/flex-layout/src/lib';
````

This is for development purposes only! **Do not use this in production!**

**Comment by ThomasBurleson** [comment]
Do not do this! We are working to fix the build tools
