### ISSUE TITLE
Is it correct for gt-lg and lt-xl to share the same pixel 1920?

### ISSUE THREAD

**Issue by qaznine** [angular/flex-layout#432]
DEFAULT_BREAKPOINTS
{alias: "lg", mediaQuery: "(min-width: 1280px) and (max-width: 1919px)", suffix: "Lg", overlapping: false}
{alias: "gt-lg", overlapping: true, mediaQuery: "(min-width: 1920px)", suffix: "GtLg"}
{alias: "lt-xl", overlapping: true, mediaQuery: "(max-width: 1920px)", suffix: "LtXl"}
{alias: "xl", mediaQuery: "(min-width: 1920px) and (max-width: 5000px)", suffix: "Xl", overlapping: false}

Should we change the max width for lt-xl to 1919px?

**Comment by ThomasBurleson** [comment]
Why would this not be correct?

*  The values should not overlap in the range set  `lt-<xxx>`, 
*  The values should not overlap in the range set  `gt-<xxx>`, 
*  The values should not overlap in the range set  `<xxx>`, 

Each range set is independent of the others.
