### ISSUE TITLE
fxLayoutGap not being updated after removing element from DOM

### ISSUE THREAD

**Issue by solkaz** [angular/flex-layout#433]
[Plunker](https://plnkr.co/edit/mwwofp51BtJf401Xa8dd?p=preview)
[Gif](http://recordit.co/uNHDjl4w1X)

I have some components that are utilizing `fxHide`/`fxShow`; when these components are made visible, the `fxLayoutGap` isn't being correctly applied, as you can see in the GIF/Plunker. Looking at the HTML, I can see that the `margin-right` property isn't being applied to the newly-visible component, and only happens to a component that was previously hidden at first, e.g. in the Plunker, you should notice that the desktop tile will still retain its `margin-right` property even after it is hidden, whilst the mobile-only tile will never have it.

**Comment by bcoutch** [comment]
I see a similar problem just using *ngIf:
[Plunker](https://plnkr.co/edit/V9wL37jImiGdGEbKUc5t?p=preview)

After the fxLayoutGap has set the margin-right property, it won't recompute if the last child in the flex layout disappears.

**Comment by aldo-roman** [comment]
Confirming this. I saw the issue on a column layout:
https://plnkr.co/edit/HI3gRMHlSS10RTSkERwv?p=preview

Notice:
1. The gap is not there when the app starts.
2. Gap is added after a node is added to DOM.
3. Gap is not removed after a node is removed from DOM.

BTW, I would rename the issue as "fxLayoutGap not being recalculated after removing element from DOM"

**Comment by aldo-roman** [comment]
Update: the issue only seems to appear when there are 2 nodes, and remove 1.

When there are 4 nodes, remove 1, 3 child lefts, the issue does not reproduce.
https://plnkr.co/edit/ClQx0ld1Dm1PYtesTq6M?p=preview
