### ISSUE TITLE
MediaQueries "lt" and "gt" are no longer working

### ISSUE THREAD

**Issue by josehernandezv** [angular/flex-layout#437]

**Comment by jhnoor** [comment]
Stopped working when I upgraded from beta as well

**Comment by ThomasBurleson** [comment]
Beta.9 does not work with Angular 5.
RC.1 is an **OLD** incorrect release that lingers in the npm registry (even after we cleaned it).
Please use the latest nightly builds https://github.com/angular/flex-layout/wiki/NPM-Installs#install-from-nightly-build-head
