### ISSUE TITLE
fix(demo): correct demo-app responsive layout issues

### ISSUE THREAD

**Issue by Splaktar** [angular/flex-layout#44]
These screenshots are on a 425x646 display, but they get worse if you try from a smaller resolution phone.

I noticed this some days ago when the initial announcement was made and the demo shared. Unfortunately I was viewing it on my phone and didn't have time to write up an issue at that point.

**Browsers and Operating System**
Chrome for Android (7.1.1), Chrome for OS X (El Capitan)

Issues

- Overlapping text
- Colored flex areas running out of cards

Responsive demo app: https://tburleson-layouts-demos.firebaseapp.com/#/responsive
![screen shot 2016-12-14 at 2 40 21 am](https://cloud.githubusercontent.com/assets/3506071/21173723/1bddf088-c1a7-11e6-87c5-f7dbc94b3e58.png)
![screen shot 2016-12-14 at 2 41 25 am](https://cloud.githubusercontent.com/assets/3506071/21173721/1bdc8c66-c1a7-11e6-8ba3-ba4a902cfe92.png)

Static mode: https://tburleson-layouts-demos.firebaseapp.com/#/docs
![screen shot 2016-12-14 at 2 40 45 am](https://cloud.githubusercontent.com/assets/3506071/21173722/1bddc158-c1a7-11e6-85d5-e4171d6a8e13.png)

I would love to help out with a fix, but my time is very limited atm and I need to focus on paying work to make ends meet.

**Comment by ThomasBurleson** [comment]
@Splaktar - Thx for creating this issue; it has been a known issue but not high priority before. Now with Beta.1 approaching, I think it best if our demo app is itself responsive.

**Comment by kuncevic** [comment]
I come across this one as well. Would be nice to see it fixed soon :)

**Comment by CaerusKaru** [comment]
Consolidating into #569
