### ISSUE TITLE
adding new breakpoint layoutGtXl not being executed; maybe missing bit in documentation

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/flex-layout#442]
Hi,

I followed the instructions (https://github.com/angular/flex-layout/wiki/Custom-Breakpoints)  to add new breakpoint, namely GtXl:
```
import { Directive, Input, ElementRef, Renderer2 } from '@angular/core';


import { LayoutDirective, MediaMonitor } from '@angular/flex-layout';

@Directive( {
  selector: `
  [fxLayout.gt-xl],
`} )
export class LayoutExtDirective extends LayoutDirective {

  constructor( monitor: MediaMonitor, elRef: ElementRef, renderer: Renderer2 ) {
    super( monitor, elRef, renderer );
  }

  @Input( 'fxLayout.gt-xl' )
  set layoutGtXl( val ) { this._cacheInput( 'layoutGtXl', val ); };

}
```

I have add LayoutExtDirective to the declarations of my app.module. I see that the directive is picked up when I log something in the constructor.
However, I have the feeling that I still haven't registered it completely.
If I look in the source code of flex-layout I see declarations of all `layoutXXX` breakpoints, which adds it to the Observable (I think). But I am pretty sure I haven't done that with the code above.

Can someone show me my mistake?

  
PS
I did this bit in the updateBreakpoint  provider:
```
 useFactory: function customizeBreakPoints(): any {
        const GT_XL = [ {
          alias: 'gt-xl',
          suffix: 'GtXs',
          mediaQuery: '(min-width: 1920px)',
          overlapping: false
        }];


        return validateSuffixes( [ ...DEFAULT_BREAKPOINTS.map( updateBreakpoints ), ...GT_XL ] );
      },
```

**Comment by janjachacz** [comment]
Got the same issue, using `Angular: 5.0.0-rc.6` and `@angular/flex-layout: 2.0.0-beta.9-e3b7fde`

**Comment by qaznine** [comment]
in the const GT_XL, suffix should be suffix: 'GtXl', instead of suffix: 'GtXs',

return validateSuffixes([...DEFAULT_BREAKPOINTS,...GT_XL]);

**Comment by mattiLeBlanc** [comment]
@qaznine  OMG what an oversight!!! Yes, that fixed the issue.
