### ISSUE TITLE
Documentation for building library is outdated

### ISSUE THREAD

**Issue by solkaz** [angular/flex-layout#443]
According to [this page on the wiki](https://github.com/angular/flex-layout/wiki/Developer-Setup#building-the-library)

> To build the library in dev mode, run gulp build:lib.

However, this isn't a valid Gulp task.

**Comment by Splaktar** [comment]
The docs are certainly out of date, but you can do this via `npm run demo:serve`. Check out the other NPM scripts in `package.json` for additional tasks to run.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 67e4bf5bccc0ade
