### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by solkaz** [angular/flex-layout#446]
[According to the wiki](https://github.com/angular/flex-layout/wiki/Contributing-to-Angular-2-Flex-Layout#-submitting-an-issue), there is some specific information that would help the developers with dealing/triaging new issues, which are listed out; however, when I go to create a new issue, I don't see this information, because there isn't an `ISSUE_TEMPLATE` for the project. Adding a issue template would thus aid the project for users who haven't seen that section of the wiki (which isn't very visible to begin with) and to help create a better issue description.

**Comment by ThomasBurleson** [comment]
Fixed.
