### ISSUE TITLE
BREAKPOINTS Documentation Seems Wrong/Outdated

### ISSUE THREAD

**Issue by tommyc38** [angular/flex-layout#447]
I followed the documentation [here](https://github.com/angular/flex-layout/wiki/BreakPoints) and it did not work.  I kept getting an error in my editor/browser when defining the super method in the constructor of the Directive (e.g. supplied parameters don't match any signature of call target).  I removed the constructor method and everything worked as expected.  However, the default settings would no longer work.  

Also, documentation shows the api using Renderer but its actually using Renderer2? 

I am using the latest stable version of Angular2 via CLI as of this writing.

Thanks!

**Comment by mattiLeBlanc** [comment]
Its working for me, however the directive for the new breakpoint I created does not fire.
My issue: https://github.com/angular/flex-layout/issues/442

**Comment by MikaAK** [comment]
I am adding
```
export const CustomBreakPointsProvider = {
  provide : BREAKPOINTS,
  useValue: DEFAULT_BREAKPOINTS
}
```
to my providers and this errors out with 
```
Cannot read property 'filter' of undefined
    at BreakPointRegistry.get [as sortedItems]
```

**Comment by tommyc38** [comment]
@MikaAK I can't see how you defined useValue but if its not an array similar to mine that might be the root of your issue.

```
export const CustomBreakPointsProvider = {
  provide: BREAKPOINTS,
  useValue: [...DEFAULT_BREAKPOINTS, ...NAV_BREAKPOINTS]
};

```

Below is my entire code base trying to use this library.

```
import {BREAKPOINTS, DEFAULT_BREAKPOINTS, LayoutDirective, MediaMonitor} from '@angular/flex-layout';
import {ShowHideDirective, negativeOf} from '@angular/flex-layout';
import {Directive, ElementRef, Input, Optional, Renderer2, Self} from '@angular/core';

const NAV_BREAKPOINTS = [{
  alias: 'sm.home',
  suffix: 'SmHome',
  mediaQuery: 'only screen and (max-width: 720px)',
  overlapping: false
}];

export const CustomBreakPointsProvider = {
  provide: BREAKPOINTS,
  useValue: [...DEFAULT_BREAKPOINTS, ...NAV_BREAKPOINTS]
};

@Directive({
  selector: `[fxHide.sm.home], [fxShow.sm.home]`
})
export class CustomShowHideDirective extends ShowHideDirective {

  @Input('fxHide.sm.home')
  set hideXs(val) {
    this._cacheInput('hideSmHome', negativeOf(val));
  }

  @Input('fxShow.sm.home')
  set showXs(val) {
    this._cacheInput('showSmHome', val);
  }

  constructor(monitor: MediaMonitor,
              @Optional() @Self() protected _layout: LayoutDirective,
              protected elRef: ElementRef,
              protected renderer: Renderer2) {

    super(monitor, _layout , elRef, renderer);
     if (_layout) {
      /**
       * The Layout can set the display:flex (and incorrectly affect the Hide/Show directives.
       * Whenever Layout [on the same element] resets its CSS, then update the Hide/Show CSS
       */
      this._layoutWatcher = _layout.layout$.subscribe(() => this._updateWithValue());
    }
  }


}


```

**Comment by MikaAK** [comment]
I am only providing the default breakpoints back without adding my own and it is blowing up

**Comment by tommyc38** [comment]
@MikaAK and @mattiLeBlanc, you should checkout Angular Material's CDK Layout module.  It works beautifully and really straightforward.

**Comment by mattiLeBlanc** [comment]
@tommyc38 I see, this is part of the new release, is it?
However, I do like the flex layout library too. It's very complete. I just hope somebody will look at my question (#442)

**Comment by ThomasBurleson** [comment]
@mattiLeBlanc - 

Consider your selector `fxHide.sm.home`. This means that want to extend the functionality in `fxHide` directive to use a new custom extension `.sm.home`. 

Currently the Angular compiler does NOT view the segments of the  selector as a property chain; instead it matches the complete selector as a single *key*.  

With the current Angular compiler, the only way to add custom suffices is to either:

*  modify the [ShowHideDirective](https://github.com/angular/flex-layout/blob/master/src/lib/api/ext/show-hide.ts#L83-L98) to add 
   ```js
   @Input('fxHide.xs')    set hideXs(val) {this._cacheInput('showXs', negativeOf(val));}
   ```
* subclass the **ShowHideDirective** similar to the Wiki example [Directive Subclassing](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints#directive-subclassing)

**Comment by ThomasBurleson** [comment]
@here - please use the [nightly build install](https://github.com/angular/flex-layout/wiki/NPM-Installs#install-from-nightly-build-head) for Renderer2, AOT, and Angular  5 support.

> We hope to release an npm version with the next week.

**Comment by mattiLeBlanc** [comment]
@ThomasBurleson Hi Thomas, in my issue #442 I do extend LayoutDirective as recommended in de the docs. I think I have it all. However, as I mentioned in my issue, it seems I am missing some kind of registration of that new breakpoint because it is not triggering.
