### ISSUE TITLE
Move flex-layout to CDK

### ISSUE THREAD

**Issue by lacolaco** [angular/flex-layout#451]
Current versioning of flex-layout is divided from Core and Material. the version `2.0.0-beta.9` is not friendly to tell us which is compatible with Core v5 and Material 2.0.0-beta.12.

In my opinion, it's better to merge CDK and flex-layout and set the same version with Material. (also repo)
Advantage of separation is few while it may confuse developers. 

@kara How do you think about that?

**Comment by ThomasBurleson** [comment]
Portions of Flex-Layout may be merged into the CDK. And the Flex-Layout repository may migrate to the Material2 repository... but these will not happen until late Q1. 

Meanwhile please expect to see a formal release of @angular/flex-layout v2.0.1-beta.10 release soon. In the interim, you should install [Nightly Builds for Angular 5](https://github.com/angular/flex-layout/wiki/NPM-Installs#install-from-nightly-build-head) compatibility.

**Comment by lacolaco** [comment]
Thank you @ThomasBurleson . I look forward to that migration. 👍
