### ISSUE TITLE
`npm cache clean` step gives errors

### ISSUE THREAD

**Issue by jplew** [angular/flex-layout#454]
I am installing Flex-layout for the first time using the Angular CLI installation instructions here: https://github.com/angular/flex-layout/wiki/Using-Angular-CLI#install-the-cli

When I enter the `npm cache clean` command, I get the following error:

```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```

Perhaps the documentation should be updated, and instruct the user to use `npm cache verify` instead. Either that or explain why it is necessary to delete the entire cache.

**Comment by ThomasBurleson** [comment]
@jplew - agreed. command has been redacted from the WIki.
