### ISSUE TITLE
build error under Angular 5.0.0-rc.1

### ISSUE THREAD

**Issue by byunru** [angular/flex-layout#455]
/node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts (8,10): Module '..../node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

Angular 5 removed OpaqueToken:
core: OpaqueToken has been removed as it was deprecated since v4. Use InjectionToken instead.
https://jaxenter.com/road-to-angular-5-133253.html

**Comment by ThomasBurleson** [comment]
Meanwhile please expect to see a formal release of @angular/flex-layout v2.0.1-beta.10 release soon. In the interim, you should install Nightly Builds for  **Angular 5** compatibility.
