### ISSUE TITLE
 Cannot find module '@angular/flex-layout'.

### ISSUE THREAD

**Issue by yasir-rafiq** [angular/flex-layout#457]
I've installed npm in angular 4 application, import package but got this error.

 Cannot find module '@angular/flex-layout'.

Please Help.

**Comment by merlosy** [comment]
Things you can do :
- Restart text editor/IDE: may be a misconfiguration
- Make sure you have installed The Flex Layout dependency : `node_modules/@angular/flex-layout` folder should be there
- Make sure you have imported the module:
```ts
import { FlexLayoutModule } from '@angular/flex-layout';
...
@NgModule({
    imports: [
        FlexLayoutModule,
        ...
    ],
    ...
})
```

**Comment by dhanarajp** [comment]
@merlosy i using flex-layout module, but not rendering properly, can you help me plz.
```
<div fxLayout="column" fxLayout-gt-xs="row" >
                  <mat-card fxflex fxflex-gt-xs="30" fxFlex="50">
                      <h2>Card title #1</h2>
                      <mat-card-content>
                          <p>Some content</p>
                      </mat-card-content>
                  </mat-card>
                  <mat-card fxflex fxFlex="50">
                      <h2>Card title #2</h2>
                      <mat-card-content>
                          <p>Some content</p>
                      </mat-card-content>
                  </mat-card>
              </div>   
```

above code i using but not working what i excepted, actually above code come side by side but its taking 100% width of the screen, plz suggest proper code

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.
