### ISSUE TITLE
Dynamically insert responsive columns until fills row; then insert on new row?

### ISSUE THREAD

**Issue by AlecTaylor** [angular/flex-layout#458]
This seems like a common use-case. How do I do it?

Attempt:
https://plnkr.co/edit/krnRk7DbyjhbAlYV3JC6?p=preview

Or it is a feature request rather than a misunderstanding of docs?

**Comment by ThomasBurleson** [comment]
This does work to add dynamic rows. See [Plunkr Demo](https://plnkr.co/edit/VoAyzyMCgR0LQuWxaqn3?p=preview)

![screen shot 2017-10-21 at 7 25 39 am](https://user-images.githubusercontent.com/210413/31851725-29783da0-b631-11e7-96b6-e2ee05e94d79.png)
