### ISSUE TITLE
fxFlex.gt-sm="" or fxFlex.gt-sm not working

### ISSUE THREAD

**Issue by jbojcic1** [angular/flex-layout#459]
Both fxFlex.gt-sm and fxFlex.gt-sm="" are treated like you just put fxFlex while it should mean apply fxFlex only when screen is greater than sm.

**Comment by ThomasBurleson** [comment]
Flex-Layout has a fundamental assumption:
----
If the html markup uses a responsive Flex-Layout API breakpoint **without** an associated non-responsive fallback, then a default fallback will be injected/used!
---
So  

```html
<div fxFlex.gt-sm="30">
```

is equivalent to

```html
<div fxFlex fxFlex.gt-sm="30">
```

**Comment by ThomasBurleson** [comment]
Closing as not an issue.

**Comment by jbojcic1** [comment]
@ThomasBurleson but is there a way to apply just fxFlex (not fxFlex=30) only for gt-sm?
