### ISSUE TITLE
feat(demo): provide source views and StackBlitz links

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#47]
Similar to usages on Angular.io and Material.angular.io, we should provide

*  toggle the demo view to show the source or the live demo
*  provide a link to open the demo in a StackBlitz demo.
* investigate the complexity of embedding StackBlitz demos; see [embedded example](https://stackblitz.com/edit/sdk-create-project).

![screen shot 2018-03-07 at 1 45 20 pm](https://user-images.githubusercontent.com/210413/37114397-dd09e6fa-220d-11e8-9109-fa1985277edf.png)

Show above is a tabbed view to toggle inline-demo, source view, or jump to StackBlitz.
> See https://medium.com/@ericsimons/stackblitz-sdk-instantly-add-live-environments-to-your-docs-blogs-more-73dab05c51ae

**Comment by d3viant0ne** [comment]
I was going to do this in the demo-app before I found the issue, I'll take care of it :)

**Comment by ThomasBurleson** [comment]
@d3viantone - I have a TS AceEditor component for our use

**Comment by CaerusKaru** [comment]
Consolidating into #569
