### ISSUE TITLE
bug(build): angular versions are not properly inserted

### ISSUE THREAD

**Issue by CaerusKaru** [angular/flex-layout#470]
Something's wrong with the build script that it's not correctly replacing `0.0.0-NG` with the proper version at build time.

```
npm WARN @angular/flex-layout@2.0.0-beta.9-99e7450 requires a peer of @angular/core@undefined but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-beta.9-99e7450 requires a peer of @angular/common@undefined but none is installed. You must install peer dependencies yourself.
```

https://github.com/angular/flex-layout-builds/blob/2ec7c6265aeccd88c3323307d17596b5f537457d/package.json#L26-L27

**Comment by ThomasBurleson** [comment]
@CaerusKaru - I am not sure what you mean. The builds do indeed have the version + SHA information:

**Comment by cyrilletuzi** [comment]
@ThomasBurleson it should be reopened, in beta.10 : 
```
@angular/flex-layout@2.0.0-beta.10 requires a peer of @angular/core@0.0.0-NG
@angular/flex-layout@2.0.0-beta.10 requires a peer of @angular/common@0.0.0-NG
```
