### ISSUE TITLE
Unexpected token import 

### ISSUE THREAD

**Issue by theShadow89** [angular/flex-layout#471]
#### Bug, feature request, or proposal:

"Unexpected token import <" error with angular/material2

#### What is the current behavior?
Rise error "Unexpected token import" when used with angular/material2

#### What are the steps to reproduce?
Import FlexLayout module with Material2 Module

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4
Material 2.0.0-beta.10
FlexLayout 2.0.0-beta.9

**Comment by ThomasBurleson** [comment]
Closing as invalid issue. This issue completely fails to articulate any reproducible scenario. Please use the nightly builds and provide a StackBlitz demo if your bug continues to manifest.
