### ISSUE TITLE
FlexLayout has no exported member 'MockMatchMedia'

### ISSUE THREAD

**Issue by phmello** [angular/flex-layout#473]
I've wrote some tests using this component some time ago, and now I'm getting error as if the component doesn't exist anymore.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.4.7
node: 7.10.0
os: win32 x64
@angular/animations: 4.4.5
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/platform-server: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.5.3

#### Is there anything else we should know?
import { MockMatchMedia } from '@angular/flex-layout';

**Comment by ThomasBurleson** [comment]
[MockMatchMedia](https://github.com/angular/flex-layout/blob/master/src/lib/media-query/mock/mock-match-media.ts) has not been published with the library. 

> Please directly use the source file here.
