### ISSUE TITLE
Angular v5

### ISSUE THREAD

**Issue by xban1x** [angular/flex-layout#478]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Work out of the box.

#### What is the current behavior?

Does not.

#### What are the steps to reproduce?

http://prntscr.com/h56trt

#### What is the use-case or motivation for changing an existing behavior?

Using the latest Angular version with FlexLayout.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

http://prntscr.com/h56uej

#### Is there anything else we should know?

Just replace `OpaqueToken` with `InjectionToken`.

**Comment by yuraantonov11** [comment]
the same problem

**Comment by kferstl** [comment]
for me it helped to install the latest flex-layout version by specifying the version explicitly:
```bash
npm install --save @angular/flex-layout@v2.0.0-beta.10
```
the problem behind that was:
@angular/flex-layout@v2.0.0-rc.1. was renamed back to  @angular/flex-layout@2.0.0-beta.7, updating npm packages often uses that version. Specify the latest beta manually to use it.
see: https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#200-beta7-2017-03-17

**Comment by xban1x** [comment]
@kferstl will try it out. But looking at current master you are correct. It is a NPM issue.

**Comment by kevindqc** [comment]
if I update to beta.10 (had rc.1 before), I get this:

> npm WARN @angular/flex-layout@2.0.0-beta.10 requires a peer of @angular/core@0.0.0-NG but none was installed.
> npm WARN @angular/flex-layout@2.0.0-beta.10 requires a peer of @angular/common@0.0.0-NG but none was installed.

**Comment by zhentian-wan** [comment]
OpqueToekn was removed form Angular5

**Comment by ThomasBurleson** [comment]
Beta.10 has been recently released. 

- We are fixing current peerDependency issues. 
- We are aware of the `npm update` issue. 
- 

> Both are known, registered issues.
