### ISSUE TITLE
Responsive Flex Layout Chrome Bug

### ISSUE THREAD

**Issue by JaimeStill** [angular/flex-layout#481]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When moving from row to column layout, controls should stack appropriately

#### What is the current behavior?
In Chrome, when transitioning from row to column layout with an element that has a nested column layout, all of the elements merge onto the same line.

##### Examples  

*Chrome at gt-md*  
![chrome-gt-md](https://user-images.githubusercontent.com/14102723/32330756-7884fb56-bfb7-11e7-8622-1318a80c987d.png)  

*Chrome at lt-lg*  
![chrome-lt-lg](https://user-images.githubusercontent.com/14102723/32330773-8880107c-bfb7-11e7-9425-294d0cc9c8ca.png)  

*Firefox at lt-lg*  
![firefox-lt-lg](https://user-images.githubusercontent.com/14102723/32330788-9112f7d6-bfb7-11e7-8218-854867e07a1b.png)  

#### What are the steps to reproduce?
[Repro](https://stackblitz.com/edit/angular-flex-layout-seed-dwwepm)  
*All of the relevant markup is in test.component.html*

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with the following:
Angular 4.4.4
Material 2 beta 12
flex-layout 2 beta 10

#### Is there anything else we should know?
While the following causes the mess in Chrome, but works in Firefox and Edge:  

``` html
<div fxFlex fxLayout="column" fxLayoutAlign="start stretch">
```

The following causes the intended behavior to work in all browsers:  

``` html
<div fxLayout="column" fxLayoutAlign="start stretch" [ngStyle.gt-md]="{'flex': '1 1 auto'}">
```

**Comment by largeDachshund** [comment]
@JaimeStill , I tried to run your repro on edge and the editor can't render your app!  The StackBlitz editor works fine on Chrome, but I think that defeats the purpose of your question.  Have you been successful with flex-layout on Edge?  I'm getting weird layouts, like super thin columns in Edge.

**Comment by JaimeStill** [comment]
@largeDachshund , In Edge, opening the repro in [full screen preview](https://angular-flex-layout-seed-dwwepm.stackblitz.io) appropriately shows the app. However, opening the repro from the link above generates the following error for me when instantiating:  

``` cmd
Fatal error:
Access is denied.

Evaluating https://unpkg.com/core-js@2.4.1/modules/_export.js
Evaluating https://unpkg.com/core-js@2.4.1/modules/es6.reflect.apply.js
Evaluating https://unpkg.com/core-js@2.4.1/es6/reflect.js
Evaluating polyfills.ts
Evaluating main.ts
Loading blitzapp
```

**Comment by largeDachshund** [comment]
@JaimeStill , thanks for the clarification.

**Comment by edisontito** [comment]
I'm having the same problem. The workaroud I did was to put the inner fxLayout inside a 'div'
for example:
<article fxLayout="column" fxLayoutAlign="none">
    <section fxLayout="row" fxLayoutAlign="center none">
        ....
    <section>
</article>

Workaroud:
<article fxLayout="column" fxLayoutAlign="none">
    <div>
        <section fxLayout="row" fxLayoutAlign="center none">
            ....
        <section>
    </div>
</article>

**Comment by edisontito** [comment]
I'm having the same problem. The workaroud I did was to put the inner fxLayout inside a 'div' element. For example:
`
<article fxLayout="column" fxLayoutAlign="none">
    <div>
        <section fxLayout="row" fxLayoutAlign="center none">
            foo
        </section>
    </div>
</article>
`

**Comment by ThomasBurleson** [comment]
We have a PR pending that should fix the use of `flex-basis` used with the **fxFlex** API.

**Comment by CaerusKaru** [comment]
The fix without using the `ngStyle` is the following:

`<div fxFlex="auto" fxLayout="column" fxLayoutAlign="start stretch">`

We'll look into changing the default behavior, but for now this is the prescribed solution.
