### ISSUE TITLE
BUG @angular/flex-layout AND Angular 4 - Cant use [ngStyle.lt-sm]= ""

### ISSUE THREAD

**Issue by Juliozen** [angular/flex-layout#482]
Hello Guys!! I am really in trouble with this.

I user this Dependencies:
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "^2.0.0-beta.10",
    "@angular/forms": "^4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/platform-server": "4.1.3",
    "@angular/router": "4.1.3",

"devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "4.1.3",

As you see i use  "@angular/flex-layout": "^2.0.0-beta.10", i simple i CAN`T use [ngStyle.lt-sm]="'min-height: 800px;'"

My console.log is:

Can't bind to 'ngStyle.lt-sm' since it isn't a known property of 'div'. ("<div class="box-container" fxLayout="column"  [ERROR ->][ngStyle.lt-sm]="'min-height: 800px;'">

i can still use style="min-height: 800px", etc... but this solution dosnt give the responsive feature to my system.

I use angular to be responsive and all platforms (as well).... So what should i do Guys?? Any one please can help me? Maybe it are deprecated? I really cant find the solution in changeLOG or docs ._.

Have a nice day if u read all....!

**Comment by qaznine** [comment]
do you import FlexLayoutModule?

**Comment by qaznine** [comment]
have you import FlexLayoutModule?

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.
