### ISSUE TITLE
npm update goes back to beta6

### ISSUE THREAD

**Issue by bracco23** [angular/flex-layout#484]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
if I use `npm update` the latest version of the package is installed or, if already installed is retained

#### What is the current behavior?
If I use `npm install --save @angular/flex-layout` version 2.0.0-beta10 is installed, as it should. After that, if I try to use `npm update` to update all my packages (flex-layout included), flex-layout is "updated" to version rc1, which is really beta6.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm on windows 10, Creator's Update, 
node --version: 8.6.0

**Comment by aamir1995** [comment]
Delete your `package-lock.json` and try again to see if it works.

**Comment by bracco23** [comment]
nothing, still the sames, `npm update` installs version beta.6.

Also, I just noticed that after `npm update`, if I try `npm install --save @angular/flex-layout`, it doesn't install beta.10, but it likes "reinstall" beta.6

to install beta.10 the only way is `npm install --save @angular/flex-layout@2.0.0-beta.10`

**Comment by bracco23** [comment]
Just tried a last time, with this sequence of commands:
```

npm install --save @angular/flex-layout@2.0.0-beta.10
del package-lock.json
npm update

```

and the result is npm installing 2.0.0-rc1, aka 2.0.0-beta.6.

**Comment by alexfung888** [comment]
yes @bracco23 this problem will not go away until flex goes out of beta, which probably means forever. Just hard code the latest beta into your package.json and stop using ^ or ~ for flex-layout

**Comment by ThomasBurleson** [comment]
This is a known issue. The plan is to release RC.1 next... which should resolve this issue.

**Comment by ThomasBurleson** [comment]
`npm install --save-dev @angular/flex-layout` will now install beta.12 or higher. Note: you may need first to remove `node_modules` directory.

>  Do **not** use `npm upgrade` which installs an OLD, incorrect deployment of rc.1 (this is really a beta.6 version).

**Comment by CaerusKaru** [comment]
Should be fixed by latest release to npm
