### ISSUE TITLE
Template plunker not working

### ISSUE THREAD

**Issue by jbojcic1** [angular/flex-layout#485]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Template should be working

#### What is the current behavior?
It fails due to the rxjs error

#### What are the steps to reproduce?
Run plunker template

**Comment by JaimeStill** [comment]
Why not use the [StackBlitz](https://stackblitz.com/edit/angular-flex-layout-seed) template?

**Comment by jbojcic1** [comment]
I didn't know about that one as in docs I see only plunker. Thx

**Comment by ThomasBurleson** [comment]
Updated [README](https://github.com/angular/flex-layout/blob/master/README.md) with StackBlitz Templates
