### ISSUE TITLE
ERROR in FlexLayoutModule is not an NgModule

### ISSUE THREAD

**Issue by terravibe** [angular/flex-layout#486]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should work

#### What is the current behavior?
Not working

#### What are the steps to reproduce?
`npm install https://github.com/angular/flex-layout-builds.git`
or
`npm install @angular/flex-layout@latest --save`
or
`npm install @angular/flex-layout --save`

app.module.ts:
`import { FlexLayoutModule } from '@angular/flex-layout/flex-layout';`
        
`@NgModule({
  imports: [
   ...
     ImageCropperModule
   ]
})`

then start building the app (not aot)

My versions are:
    
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.3.2",
    "@angular/http": "^4.0.0",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",      
    '@nguniversal/express-engine '  : "^1.0.0-beta.2",   
    "typescript": "^2.3.2",

After all try, i always got `ERROR in FlexLayoutModule is not an NgModule` error after trying to build the application.

**Comment by Varnesh** [comment]
Hi,

I am also getting the same issue. Any soultions found for this?

**Comment by Varnesh** [comment]
I am also getting the same issue. Any soultions found for this?

**Comment by ThomasBurleson** [comment]
Do not use 

```js
import { FlexLayoutModule } from '@angular/flex-layout/flex-layout';
```

Use 

```js
`import { FlexLayoutModule } from '@angular/flex-layout';`
```

**Comment by Richard-YAN** [comment]
Seems the package @angular/flex-layout is not installed. So to install it may help:
```
npm install @angular/flex-layout
```
