### ISSUE TITLE
class.<query> no longer works after beta 9

### ISSUE THREAD

**Issue by Pikachews** [angular/flex-layout#487]
#### Bug, feature request, or proposal:
Can no longer use class.\<query\> in templates after beta 9.

#### What is the expected behavior?
Queries on classes should work.

#### What is the current behavior?
They don't work at all.

#### What are the steps to reproduce?

Example StackBlitz: https://stackblitz.com/edit/angular-flex-layout-seed-6m2khk?file=app/test.component.ts

Remove beta 10 and add beta 9 and the example works. With beta 10, neither of the class.\<query\> work.

#### What is the use-case or motivation for changing an existing behavior?
Incorrect behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Flex-layout beta 10

#### Is there anything else we should know?
ngClass.\<query\> works, but class.\<query\> doesn't.

**Comment by HJordan35** [comment]
We are experiencing the same issue as well when using beta 10

**Comment by mackelito** [comment]
https://github.com/angular/flex-layout/wiki/ngClass-API

**Comment by mackelito** [comment]
https://github.com/angular/flex-layout/pull/419
