### ISSUE TITLE
Flex Layout Splitter only works with 2 panes at a time of same direction

### ISSUE THREAD

**Issue by kvanlaan** [angular/flex-layout#491]
If you want to have three or more resizable panes side-by-side, in the same direction, only the handle between the first two columns can move. The rest are disabled.

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as not a *flex-layout-library* issue. Thank you.
