### ISSUE TITLE
feat(api): support custom breakpoints

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#5]
Add ability to modify existing breakpoints (change, add, remove)

**Comment by TylerDev6** [comment]
does this exist yet? Is there an example of it?

**Comment by TylerDev6** [comment]
I'm really waiting on this feature here.... any way I can help with it?

**Comment by ThomasBurleson** [comment]
This feature is already available. See:

*  [Creating Custom Breakpoints (Wiki)](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints)
*  [Unit Tests for Custom BreakPoints](https://github.com/angular/flex-layout/blob/master/src/lib/media-query/breakpoints/break-point-registry.spec.ts#L51)

**Comment by TylerDev6** [comment]
are you missing an export?

export * from './breakpoints/break-point';

**Comment by ThomasBurleson** [comment]
@TylerDev6 - I do not understand what you are saying.

**Comment by TylerDev6** [comment]
I was getting a compiler error since BreakPoint was not exported from the index.d.ts file... that's how I corrected it.

**Comment by ThomasBurleson** [comment]
Ah... You are correct. **If** you want to use the BreakPoint interface, that is not currently exported as part of the barrel. This has been fixed in PR #158

**Comment by TylerDev6** [comment]
Ok, perfect. Thanks. I'm having a few other minor issues but I've already got one ticket open, so I may just add to that.

https://github.com/angular/flex-layout/issues/135
