### ISSUE TITLE
Proposal: FAQ on flex-layout version

### ISSUE THREAD

**Issue by alexfung888** [angular/flex-layout#500]
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

An FAQ to explain how to install the proper version of flex-layout

#### What is the current behavior?

People keep getting into trouble by getting 2.0.0-rc and are curious about 10.4905443
So they keep posting new Issues.

#### What are the steps to reproduce?

npm install

#### What is the use-case or motivation for changing an existing behavior?

fewer repeated Issues raised.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

any, a bit more problematic with Angular 5

**Comment by javahaxxor** [comment]
I have a suggestion: How about this, let the latest version be the proper version that works ?

**Comment by buu700** [comment]
@ThomasBurleson, why not just bump the @angular/* dependency versions and republish the current code as 5.0.0-beta.11?

flex-layout seems to work fine for me with Angular and Material 5, so the change wouldn't be misleading (even if the combination potentially has bugs), and from a glance at the issue queue it looks like it would really cut down on user confusion.

**Comment by ThomasBurleson** [comment]
When we are ready for RC releases Q1 2018, we will be changing the version # to 5.0.0.
> This week, I hope to release a Beta.12 that resolves many of the npm/build confusions.

**Comment by spock123** [comment]
Won't Angular hit v6 by then?
