### ISSUE TITLE
Angular (Material) 5 issues

### ISSUE THREAD

**Issue by adappter** [angular/flex-layout#503]
I have the current Version of flex layout: beta11
Currently I'm using the newest Angular 5 releases, including Angular Material 5.0.0-rc0.
I have a branch where Angular 4 and Angular Material 2 is running.

In the Angular 5 branch the content is scrollable. It seems that the mat-toolbar is calculated to the height of the content. 
In the Angular 4 branch everything works fine.

I didn't change my code just updated the angular versions.

Is it possible that flex layout is not compatible with angular material 5?

**Comment by akilinomendez** [comment]
Use "@angular/flex-layout": "^2.0.0-beta.10-4905443"  is running with material5 and angular 5

**Comment by EnricoPicci** [comment]
While installing @angular/flex I am getting a warning

`npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/core@~4.4.4 but none was installed.`

Can I ignore it

**Comment by akilinomendez** [comment]
yes, it should work

**Comment by adappter** [comment]
After hours of investigation it seems to be some divs which were changed or removed by angular material 5 release
