### ISSUE TITLE
ObservableMedia fires multiple times for the same value when Flex Layout directives are present

### ISSUE THREAD

**Issue by amorgulis** [angular/flex-layout#504]
#### Bug, feature request, or proposal:
ObservableMedia fires multiple times for the same value.

#### What is the expected behavior?
ObservableMedia should fire once to indicate the current media setting.

#### What are the steps to reproduce?
See demo: https://stackblitz.com/edit/angular-flex-layout-media-change-fires-multiple-times. Notice the multiple console messages. Additionally, removing the fxLayout directive from the template causes ObservableMedia to fire once instead of multiple times. It appears that the multiple firing of the event is tied to the presence of Flex Layout directives in the template.

**Comment by tmburnell** [comment]
Is this an issue?  In the Stackblitz it does load twice on load, however it looks like it only fires once after loaded.  But loading in my experience it normal for things to fire multiple times.

**Comment by CaerusKaru** [comment]
Regardless, we're looking into switching to the CDK media engine. In the meantime, this issue will be moved to the backlog.

**Comment by CaerusKaru** [comment]
I'm going to close this issue because OP hasn't responded to @tmburnell's comment, and `ObservableMedia` has been deprecated anyway. We can always reopen if there's an issue with its replacement, `MediaObserver`.
