### ISSUE TITLE
fxFlexOffset has wrong margin when container's flex-direction is switched

### ISSUE THREAD

**Issue by nysource** [angular/flex-layout#505]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Clear margin-left(or margin-top)

#### What is the current behavior?
Remained margin-left(or margin-top)

#### What are the steps to reproduce?
Run below code and rotate a device.
(test2 has both margin-top: 16px and margin-left: 10%;)
`<div fxLayout="row" fxLayout.lt-md="column">`
`  <p id="test1" fxFlex="45" fxFlex.lt-md="100">test1</p>`
`  <p id="test2" fxFlex="45" fxFlex.lt-md="100" fxFlexOffset="10" fxFlexOffset.lt-md="16px">test2</p>`
`</div>`
#### What is the use-case or motivation for changing an existing behavior?
Incorrect behaviour

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.6
material 2.0.0-beta.12
flex-layout 2.0.0-beta.10-4905443

**Comment by ilianiv** [comment]
👍  Hope it will be fixed in beta.14 🙏

**Comment by CaerusKaru** [comment]
This has been punted to the next beta release, as beta.14 should be going out in the next few days and we don’t yet have a fix ready for this

**Comment by issalafi** [comment]
Hope it will be fixed in 7.0.0-beta.21 👍
the 'margin-left' need to replace with 'margin-right' in RTL dir

Angular 7.0.0
flex-layout 7.0.0-beta.19

**Comment by issalafi** [comment]
its Working now Thanks 👍

**Comment by judedaryl** [comment]
Hi I was playing around with this and the margin's aren't clearing up when changing the layout.

I'm using ``^7.0.0-beta.19``

```
    <div fxLayout="row" fxLayoutAlign.gt-xs="start center" fxLayout.lt-sm="column" fxLayoutAlign.lt-sm="start start">
      <mat-form-field fxFlex fxFlex.lt-sm="100%" fxFlex.gt-xs="100%">
        <input matInput placeholder="First Name" name="first_name">
      </mat-form-field>
      <mat-form-field fxFlexOffset.lt-sm="10" fxFlexOffset="3" fxFlex.lt-sm="100%" fxFlex="100%">
        <input matInput placeholder="Last Name" name="last_name">
      </mat-form-field>
      <mat-form-field fxFlexOffset.lt-sm="10" fxFlexOffset="3" fxFlex.lt-sm="100%" fxFlex="20%">
        <input matInput placeholder="M.I." name="middle_initial">
      </mat-form-field>
    </div>
```

<img src="https://user-images.githubusercontent.com/13645031/48661671-c4b2dc80-eab0-11e8-9d84-7a70e50dc4f5.png" width="500px">
<img src="https://user-images.githubusercontent.com/13645031/48661672-c4b2dc80-eab0-11e8-9ece-7eb14bc34528.png" width="300px">
<img src="https://user-images.githubusercontent.com/13645031/48661674-c54b7300-eab0-11e8-9a7f-40dd88dc6c8b.png" width="500px">

**Comment by issalafi** [comment]
You need to update to latest one of flex-layout

**Comment by issalafi** [comment]
> Hi I was playing around with this and the margin's aren't clearing up when changing the layout.
> 
> I'm using `^7.0.0-beta.19`
> 
> ```
> <div fxLayout="row" fxLayoutAlign.gt-xs="start center" fxLayout.lt-sm="column" fxLayoutAlign.lt-sm="start start">
>       <mat-form-field fxFlex>
>         <input matInput placeholder="First Name" name="first_name">
>       </mat-form-field>
>       <mat-form-field fxFlexOffset.lt-sm="10" fxFlexOffset="3" fxFlex.lt-sm="100%" fxFlex="100%">
>         <input matInput placeholder="Last Name" name="last_name">
>       </mat-form-field>
>       <mat-form-field fxFlexOffset.lt-sm="10" fxFlexOffset="3" fxFlex.lt-sm="100%" fxFlex="20%">
>         <input matInput placeholder="M.I." name="middle_initial">
>       </mat-form-field>
> </div>
> ```
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/13645031/48661671-c4b2dc80-eab0-11e8-9d84-7a70e50dc4f5.png">
> 
> <img alt="" width="300px" src="https://user-images.githubusercontent.com/13645031/48661672-c4b2dc80-eab0-11e8-9ece-7eb14bc34528.png">
> 
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/13645031/48661674-c54b7300-eab0-11e8-9a7f-40dd88dc6c8b.png">

try to use this it's working fine 👍 

> npm install https://github.com/angular/flex-layout-builds --save

**Comment by judedaryl** [comment]
Ok thank you!

**Comment by CaerusKaru** [comment]
Closing for now, if this is still an issue we can reopen.

**Comment by Nodarii** [comment]
Found this issue after created new one =/
linking issues: https://github.com/angular/flex-layout/issues/1049
Please, see demo of it: https://stackblitz.com/edit/angular-flex-layout-seed-sxar9t
