### ISSUE TITLE
Demo not working in IE11 / Win 7

### ISSUE THREAD

**Issue by MarcusMorba** [angular/flex-layout#506]
#### Bug, feature request, or proposal:
Demos at https://tburleson-layouts-demos.firebaseapp.com/#/docs are not working in IE11 on Windows 7. 

#### What is the expected behavior?
Get the running demos.

#### What is the current behavior?
Page showing just "Loading ...".
JS Error message: Object doesn´t support property or method 'assign'

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### What is the use-case or motivation for changing an existing behavior?
Wider support. IE11 still matters especially for companies.

**Comment by javahaxxor** [comment]
I believe you need some polyfills to run on id11

**Comment by alberk8** [comment]
Yes, we need to have support for at least IE11.   I have simple Layout that works on Chrome and Firefox but on IE11 all the output are stacking on top of each other.  Can someone help here?  Thank

```
<div class="container">
  <div fxLayout="column" fxLayoutAlign="center center"   style="text-align:center" >
    <div fxFlex="grow" fxFlexAlign="center" >
      <p>First Div</p>
    </div>
    <div fxFlex fxFlexAlign="center" >
       <p>Display Count: {{cnt}} </p>
      <h1>Login</h1>
      <p>{{errorMessage}} </p>
    </div>
  </div>
  <div fxLayout="column" fxLayoutAlign="center center"  >
    <div  fxFlex="grow" >
          <button style="height:50px; width:200px" (click)="onClick()">Click for New Code</button>
    </div>
</div>
<div fxLayout="column" fxLayoutAlign="center center"  >
  <div fxFlex="grow" >
    <a href="https://play.google.com/store/apps/details?id=com.example.app" target="_blank">
          <img src="../assets/googleplay.svg" alt="Google Play" height="100px" width="400px" >
    </a>
  </div>    
</div>
</div>

```

**Comment by MarcusMorba** [comment]
I will have a closer look at it. When I install the demo locally (OS X) and access this installation from a Windows PC with IE11 it works.

**Comment by MarcusMorba** [comment]
I guess the issue is that in the "polyfill.ts" these lines are commented out:
/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/set';

**Comment by ThomasBurleson** [comment]
I updated the polyfills in the [StackBlitz Start](https://stackblitz.com/edit/angular-flex-layout-seed?file=app%2Ftest.component.ts) template
