### ISSUE TITLE
No matching version found for @angular/flex-layout@2.0.0-beta.11

### ISSUE THREAD

**Issue by aminebizid** [angular/flex-layout#507]
Could you please upload 2.0.0-beta.11 to npm.
Kr

**Comment by matpag** [comment]
https://github.com/angular/flex-layout/issues/489

**Comment by ThomasBurleson** [comment]
Fixed with today's 2.0.0-beta.12 release. See SHA 62457a5972 and [CHANGELOG](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md)
