### ISSUE TITLE
I have this error -> has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by George35mk** [angular/flex-layout#509]
ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"C:/Users/George35mk/Documents/PROGRAMMING/GitHub/GEORGE35MK/November 2017/Python-api-Angular-5/FRONTEND/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by aamir1995** [comment]
try this command `npm i --save  @angular/flex-layout@2.0.0-beta.10-4905443`

**Comment by javahaxxor** [comment]
similar issue and solution here https://github.com/angular/flex-layout/issues/494#issuecomment-343355178

**Comment by aarustar** [comment]
npm i --save @angular/flex-layout@2.0.0-beta.10-4905443 >>>> its not working for me , i have used ngx-s3-upload component .

**Comment by ThomasBurleson** [comment]
This sounds like an incorrect version of angular + flex-layout.

*  remove your **node-modules** directory, 
*  remove the `@angular/flex-layout` entry in your **package.json**
*  then run terminal `npm i; npm i @angular/flex-layout`

**Comment by eepstein** [comment]
Seems there's a (newish) rc-1 out that breaks this whereas it was ok in the -beta.10 pre-release.
maybe this will be fixed in rc-2 ?

**Comment by alexjlockwood** [comment]
I am having this issue with `beta.11` but not with `beta.10-4905443`.

**Comment by ThomasBurleson** [comment]
See [Install Comments & Note](https://github.com/angular/flex-layout/issues/484#issuecomment-352188833) here.  
See [ChangeLog here](https://github.com/angular/flex-layout-builds/blob/master/CHANGELOG.md#200-beta12-2017-12-14)
