### ISSUE TITLE
'@angular/flex-layout' is not in the npm registry.

### ISSUE THREAD

**Issue by vimalavinisha** [angular/flex-layout#51]
Hi,

          I have tried to install angular/flex-layout module by using the below command

npm install @angular/flex-layout. it thorws the below error

'@angular/flex-layout' is not in the npm registry.

May I know when is this availble in npm repository

**Comment by ThomasBurleson** [comment]
@vimalavinisha - I am confused. All of our docs clearly state that the `npm i @angular/flex-layout` is **NOT** available. Did you read the docs and Wikis?

> Please see [Wiki - Fast Start + Builds](https://github.com/angular/flex-layout/wiki/Fast-Starts)
