### ISSUE TITLE
Angular version support for 2.0.0-beta.10-4905443?

### ISSUE THREAD

**Issue by christian-vorhemus** [angular/flex-layout#511]
When I install the latest angular packages available from npm, I get

_npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself._

My @angular/common and @angular/core versions are 5.0.2 - are you planning to support v5 soon?

**Comment by wilhelmhb** [comment]
I'm currently using @angular/flex-layout@2.0.0-beta.10-4905443 with @angular/core and @angular/common v5.0.2, without warning.

1. These are only warnings, it should still work fine. Thus, you can let it be for now, if you don't have an aversion for warnings
2. Try deleting your node_modules folder, then run `npm install`. If the version of your packages is not fixed in pacage.json, it should install everything with the latest available version (you might not have the latest version of typescript for example)...

Cheers

**Comment by SamuelMarks** [comment]
Confirmed same warning:
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.

As always, I ran `rm -rf node_modules package-lock.json; npm i` to get this. npm 5.5.1 with node v8.9.1.

**Comment by inthegarage** [comment]
@SamuelMarks Were there any issues running, or does the package (your app) simply fail after this?

**Comment by SamuelMarks** [comment]
No issues whatsoever. Just the warning.

**Comment by wilhelmhb** [comment]
@SamuelMarks @christian-vorhemus which version of typescript are you using ?
I had warnings until at least 2.3.4, but I don't get any warning anymore with 2.6.2

**Comment by Karankang007** [comment]
These warnings must be fixed, as packages with PEER dependency warnings cannot use NPM shrinkwrap or package-lock.json files.

**Comment by jotatoledo** [comment]
Dup #489

**Comment by WaterBleu** [comment]
are we gonna have rc version anytime soon?

**Comment by SamuelMarks** [comment]
@wilhelmhb Tried again just now, got:
> npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
> npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.

node 8.9.1 npm 5.5.1 tsc 2.6.2

**Comment by DavidTheProgrammer** [comment]
Please don't abandon this project angular team. I'm looking at the releases, and it's version beta.11 but npm doesn't have it on record. I feel so conflicted right now

**Comment by ThomasBurleson** [comment]
Fixed with today's 2.0.0-beta.12 release. See SHA 62457a5972
