### ISSUE TITLE
display: grid

### ISSUE THREAD

**Issue by macjohnny** [angular/flex-layout#512]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
It would be nice to have to possibility to choose between using `display: flex` and `display: grid` for building layouts.
The `flex-layout` library could be copied to allow using all features like the responsive API, etc.

This could either fit into `flex-layout` itself or be provided as a new package, e.g. `grid-layout`.

I could imagine directives to be used like this:
```html
<div fxGridLayout="1fr 1fr 1fr 2fr">
  <div></div>
  <div></div> 
  <div></div>
  <div fxGridRow="span 2"></div>
  <div fxGridColumn="span 2"></div>
  <div></div>
</div>
```

![grid-layout](https://www.w3.org/TR/css-grid-1/images/grid-layout.png)

See https://www.w3.org/TR/css-grid-1 and https://css-tricks.com/snippets/css/complete-guide-grid/
and https://www.youtube.com/watch?v=txZq7Laz7_4

This feature would allow to dynamically arrange the items in the grid areas, depending on the viewport size, without having to copy / move the actual items in the DOM tree.

**Comment by ThomasBurleson** [comment]
We have plans to add CSS Grid APIs to flex-layout... perhaps the combined library will be called `@angular/ui-layout`; but that is TBD.

**Comment by danger89** [comment]
I really would like to see this indeed!

**Comment by CaerusKaru** [comment]
The updates are that this is something we're looking into, but it's not a priority right now. It would need a lot of design work before we could get started. Any discussion about desired features would help and should be posted here.

**Comment by kylecordes** [comment]
@CaerusKaru Is there any interest in a "make Grid convenient in Angular" library, being separate from the "make Flex convenient in Angular" library?  Having them together seems to add complexity in development, adoption, documentation, etc.; and doing them separately seems more modular.

**Comment by CaerusKaru** [comment]
@kylecordes The current idea is that they would be separate modules in the same package, as @ThomasBurleson alluded to above, something like `import {FlexModule, GridModule} from '@angular/layout';`.

The reasoning is that these libraries will need to share the same common utilities like the MediaQuery engine. Testing is also going to be the same across both.

As for documentation, we're planning on switching to Dgeni at some point in the future, which will allow us to seamlessly create docs from the TS source itself.

**Comment by kylecordes** [comment]
@CaerusKaru Thank you, that is very useful, really looking forward to it. This is a common thing that developer coming to the Angular world ask for - "official" tools to do layout.
