### ISSUE TITLE
Vendor prefixes missing

### ISSUE THREAD

**Issue by EricBichara** [angular/flex-layout#513]
#### Bug, feature request, or proposal:

Bug, vendor prefixes missing

#### What is the expected behavior?
Vendor prefixes should be added to elements when using flex-layout directives

#### What is the current behavior?
no vendor prefixes visible

#### What are the steps to reproduce?
https://angular-flex-layout-seed-mzsm5h.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Vendor prefixes should be added to support older browsers

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0 project created with Angular-Cli 1.5.0, IE11

#### Is there anything else we should know?
This worked before but unsure in which version, all polyfills in polyfills.ts are imported

**Comment by ThomasBurleson** [comment]
@angular/flex-layout is only supported on ever-green browsers (much like @angular/material). I do not believe that vendor prefixes for the flexbox styles are needed. Can you identify areas where that is not true?

**Comment by CaerusKaru** [comment]
Closing since it's been almost two months since clarification was requested and none was given. If you have anything more for us, we'll reopen this issue.
