### ISSUE TITLE
WARNING: sanitizing unsafe style value [object Object] (see http://g.co/ng/security#xss).

### ISSUE THREAD

**Issue by George35mk** [angular/flex-layout#514]
I have this error but why i dont bin the values from typescript 

if i remove all the , the error is vanish
```
    [style.xs]="{'min-width.px': 200}"
    [style.sm]="{'min-width.px': 280}" 
    [style.md]="{'min-width.px': 280}" 
    [style.lg]="{'min-width.px': 280}" 
    [style.xl]="{'min-width.px': 280}"
```

```html

<mat-sidenav-container>
  <mat-sidenav 
    [style.xs]="{'min-width.px': 200}"
    [style.sm]="{'min-width.px': 280}" 
    [style.md]="{'min-width.px': 280}" 
    [style.lg]="{'min-width.px': 280}" 
    [style.xl]="{'min-width.px': 280}"
    class="admin_sidenav"
    style="min-width:280px; padding: 0px;"
    opened="true"
    #adminNavMenu 
    mode="side" 
    align="start">
   
```

**Comment by ThomasBurleson** [comment]
Please provide a StackBlitz Demo that reproduces this.

Here is a Flex-Layout/Material starting point:  https://stackblitz.com/edit/angular-mat-formfield-flex-layout?file=app/app.component.ts

**Comment by twoheaded** [comment]
@George35mk, try using `[ngStyle.xs] ` directive instead of  `[style.xs]`

**Comment by ThomasBurleson** [comment]
@twoheaded - Thank you. You are correct: responsive APIs are not supported on the style attribute; only `[ngStyle.<xxx>]` are supported.
