### ISSUE TITLE
Fetch error: rxjs/operators.js 404 (Not Found)

### ISSUE THREAD

**Issue by wandera89** [angular/flex-layout#515]
#### Bug:
Hi there. I'm getting this error with flex-layout@latest - ^2.0.0-beta.10-4905443 as well as attempting to update to     "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git"

I downgraded my version of rsjx to an earlier build hower this breaks the rest of my @angular v5 build. 
The latest version of Angular/rsjx simply doesn't have an operators.js file

This is a System..js build if that helps.

![image](https://user-images.githubusercontent.com/945728/33253696-bf53107c-d312-11e7-8ec7-3ab1583ab11c.png)

**Comment by aciccarello** [comment]
`rxjs/operators` was added in a recent version of rxjs so this error is likely from downgrading rxjs.

**Comment by ThomasBurleson** [comment]
Flex-Layout requires **"rxjs": "^5.5.0"** [see package.json] for the following imports to work:

```js
import {map, filter} from 'rxjs/operators';
```

Will not fix.

**Comment by ThomasBurleson** [comment]
Reopening to address some outlier issues related to lettable operators.

**Comment by ThomasBurleson** [comment]
Fixed with today's 2.0.0-beta.12 release. See SHA 62457a5972

**Comment by pranitadesh** [comment]
I am getting the same issue with rxjs  version 6.1.0  with angular 6

**Comment by adal2404-Real** [comment]
Hello!, Work around on https://github.com/ReactiveX/rxjs/issues/2971, regards

**Comment by CaerusKaru** [comment]
Should probably be fixed by #751

**Comment by ThomasBurleson** [comment]
Fixed SHA ffb5c79be63ccc8d2d08003ca531e99d25a5cf75
