### ISSUE TITLE
flex-layout wrong on host component container

### ISSUE THREAD

**Issue by furyscript** [angular/flex-layout#517]
#### Bug, feature request, or proposal:
Bug when using dynamic content creation

#### What is the expected behavior?
API to set host component fxFlex columns and layout

#### Example and reporting issue and step to reproduce

I'm using `resolveComponentFactory` to create my component dynamic that is a child of parent and have `fxFlex`directive. The problem is that the fxFlex not apply the correcdt `width` to my host component.

I have attached the result of my page.

I have this main component html
```html
<div fxLayout="row" fxLayoutWrap fxLayoutAlign="start start">
    <template #widgetContainer></template>
</div>
```
And in the js I fire the `createComponent` for its children.

This is the content of children HTML:
```html
<div [fxFlex]="this.widget.options.columns">
    <mat-card>
        <mat-card-title>{{this.widget.options.title}}</mat-card-title>
        <mat-card-content>
            Grid {{this.widget.options.columns}}
        </mat-card-content>
    </mat-card>
</div>
```
And JS:
```javascript
@Component({
    selector: 'grid',
    templateUrl: './grid.component.html'
})
export class GridComponent implements OnInit {
    public widget: WidgetService;

    public constructor(
        public viewContainerRef: ViewContainerRef
    ) {

        this.widget = new WidgetService({
            title: "Tabella " + this.getIntNum(),
            originalX: 1,
            originalY: 1,
            x: 1,
            y: 1,
            base_columns: 50,
            base_rows: 2,
            columns: this.getIntNum() % 2 == 0 ? 50 : 25,
            rows: 2,
            type: "grid",
            resizable: true
        });
    }

    private getIntNum() {
        let n = Math.floor(+(Math.random()*100));
        return n;
    }

    public ngOnInit(): void {
    }
}
```

Page result
![schermata del 2017-11-27 14-19-39](https://user-images.githubusercontent.com/10270403/33268742-92eb9358-d37e-11e7-92f6-657ecf3ea7c8.png)

As you can see the card item not fit the correctly width of my container (container is a full browser page)

**Comment by ThomasBurleson** [comment]
This is an issue with the Angular compiler and host elements... not with @angular/flex-layout.
You should use raw flexbox CSS in this case.

Will not fix.
