### ISSUE TITLE
problem with fxLayout="column"

### ISSUE THREAD

**Issue by eudago** [angular/flex-layout#524]
I detected a problem with fxLayout="column", when a div is is a column not have height and not get the height of the sons div.

I use the version:  @angular/flex-layout@2.0.0-beta.11-b01c2d7

**Comment by jotatoledo** [comment]
Reproduction?

**Comment by ThomasBurleson** [comment]
@eudago - Flexbox CSS with flex-direction column has known browser render/layout issues when the parent height is ambiguous. This is not an @angular/flex-layout issue.
