### ISSUE TITLE
feature: support inline-flex similar to inline-block

### ISSUE THREAD

**Issue by dinony** [angular/flex-layout#525]
Feature request, or proposal:
Why is **inline-flex** not supported?

**Comment by ThomasBurleson** [comment]
Can you provide a usage example re why this should be added to the flex-layout API?

**Comment by dinony** [comment]
You can find an example linked in the referenced issue. Some folks using my virtual scroll lib would like to use `angular/flex-layout`. Basically, you have a virtualized grid system and each cell could use `inline-flex`.
Yep, would be really nice if `angular/flex-layout`would also reflect this feature of flex layout.

**Comment by ThomasBurleson** [comment]
@dinony - the question then becomes how to include this in the existing API?

*  `fxLayout="row"`
*  `fxLayout="row wrap"`
*  `fxLayout="row inline"`  ??
*  `fxLayout="column inline"`

**Comment by dinony** [comment]
Hm, I'm not that familiar with the current API, since I've used this lib just casually to figure out what the issue was in combination with the virtual scroll component.

**Comment by ThomasBurleson** [comment]
The current API for **fxLayout**:

*  `fxLayout="row | column | row-reverse | column-reverse"` sets the flex-direction for children items of the host element container.
*  `fxLayout="<direction> wrap" sets the `flex-direction` and `row-wrap` or `column-wrap`

The proposed enhancement: is to support an **inline** option that may be used with the above ^ options.

*  `fxLayout="row inline wrap"`
*  `fxLayout="column wrap inline"`  (rare use cases expected)

> The ordering these options is not mandatory; while it is recommend that the `flex-direction` be specified first.
