### ISSUE TITLE
(api): fxFlex ignores basis value when using .lt-md

### ISSUE THREAD

**Issue by alusev** [angular/flex-layout#528]
The following configuration `fxFlex="grow" fxFlex.lt-md="1 0 50%"` should set basis value to 50% when the screen size is less than 960px.

#### What is the current behavior?
Only the shrink value changes.

#### What are the steps to reproduce?
*  [StackBlitz Demo](https://stackblitz.com/edit/angular-flex-layout-seed-ywjru2)

**Comment by ThomasBurleson** [comment]
The [StackBlitz Demo](https://stackblitz.com/edit/angular-flex-layout-seed-5g6hjt?file=app/test.component.ts) has been upgraded to @angular/flex-layout 2.0.0-beta.12; and with changes to `fxFlex="1 1 50%"` it appears to be working now.

![screen shot 2017-12-15 at 7 38 53 am](https://user-images.githubusercontent.com/210413/34044558-0b185c7c-e16b-11e7-96fa-fa4484a95557.png)

**Comment by alusev** [comment]
I updated the package and it didn't work for me.

![captura-de-pantalla-2017-12-15-a-la s -10 23 10](https://user-images.githubusercontent.com/903378/34050897-2aed168e-e182-11e7-814b-925b29102242.png)

*  [StackBlitz Demo](https://stackblitz.com/edit/angular-flex-layout-seed-kiynqv)
