### ISSUE TITLE
Custom Breakpoint Sizes Don't Work

### ISSUE THREAD

**Issue by depiction** [angular/flex-layout#529]
#### Bug, feature request, or proposal:
Following instructions at https://github.com/angular/flex-layout/wiki/Custom-Breakpoints, I created a provider to change the default breakpoints.

Both fxFlex and fxFlexOffset don't work with the new custom breakpoint sizes.

#### What is the expected behavior?

Offset and flex sizes should work at the set breakpoint.

#### What is the current behavior?

The "gt-md" breakpoint alias is set to min-width: 667px with no max-width. An offset isn't applied to the first section in the Stackblitz until 1280px.

All three sections have a fxFlex of 15 by default. The fxFlex.gt-md attribute to change this isn't applied until 1280px.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-flex-layout-seed-yewvqp

**Comment by depiction** [comment]
I figured out the issue. The documentation isn't complete. It should include how to import the module and that it must be imported after FlexLayoutModule is imported.

https://stackblitz.com/edit/angular-flex-layout-seed-yewvqp

**Comment by ThomasBurleson** [comment]
@depiction - We updated the Wiki with a version of your StackBlitz and code improvements.

https://github.com/angular/flex-layout/wiki/Custom-Breakpoints

> See the notes/example regarding how the custom module specifies `exports : [ FlexLayoutModule ]`. This means developers do not need to import both the *FlexLayoutModule* and the custom module; only  the custom  MyBreakPointsModule needs to be imported into the app module.

**Comment by mattiLeBlanc** [comment]
@ThomasBurleson 

I noticed with new Angular 5.1.2 I need to explicitly inject the class type for my custom directive:

```
import { Directive, Input, ElementRef, Renderer2, Inject } from '@angular/core';
import { LayoutDirective, MediaMonitor } from '@angular/flex-layout';

@Directive( {
  selector: `
  [fxLayout.gt-xl],
`} )
export class LayoutExtDirective  extends LayoutDirective {

  constructor( @Inject( MediaMonitor ) monitor: MediaMonitor, @Inject( ElementRef ) elRef: ElementRef, @Inject( Renderer2 ) renderer: Renderer2 ) {
    super( monitor, elRef, renderer );
  }

  @Input( 'fxLayout.gt-xl' )
  set layoutGtXl( val ) {
    this._cacheInput( 'layoutGtXl', val );
  };
}
```

Any idea why that is?
Also I the wiki article seems a little bit out dated (https://github.com/angular/flex-layout/wiki/Custom-Breakpoints#customizing-with-your-own-media-query-ranges)?

The code for the custom directive is use is as follows:
```
import { NgModule } from '@angular/core';
import { DEFAULT_BREAKPOINTS, BreakPoint, BREAKPOINTS, validateSuffixes, FlexLayoutModule } from '@angular/flex-layout';

function updateBreakpoints( bp: BreakPoint ): any {
  switch ( bp.alias ) {
    case 'xs': bp.mediaQuery = '(max-width: 599px)'; break;
    case 'gt-xs': bp.mediaQuery = '(min-width: 600px)'; break;
    case 'sm': bp.mediaQuery = '(min-width: 600px) and (max-width: 767px)'; break;
    case 'lt-sm': bp.mediaQuery = '(max-width: 599px)'; break;
    case 'gt-sm': bp.mediaQuery = '(min-width: 768px)'; break;
    case 'lt-md': bp.mediaQuery = '(max-width: 767px)'; break;
    case 'md': bp.mediaQuery = '(min-width: 768px) and (max-width: 1023px)'; break;
    case 'gt-md': bp.mediaQuery = '(min-width: 1024px)'; break;
    case 'lt-lg': bp.mediaQuery = '(max-width: 1023px)'; break;
    case 'lg': bp.mediaQuery = '(min-width: 1024px) and (max-width: 1280px)'; break;
    case 'gt-lg': bp.mediaQuery = '(min-width: 1280px)'; break;
    case 'lt-xl': bp.mediaQuery = '(max-width: 1279px)'; break;
    case 'xl': bp.mediaQuery = '(min-width: 1280px) and (max-width: 1920px)'; break;
  }
  return bp;
}

@NgModule( {
  imports : [ FlexLayoutModule ],
  exports : [ FlexLayoutModule ],
  providers: [
    // register a Custom BREAKPOINT Provider
    {
      provide: BREAKPOINTS,
      useFactory: function customizeBreakPoints(): any {
        const GT_XL = [ {
          alias: 'gt-xl',
          suffix: 'GtXl',
          mediaQuery: '(min-width: 1320px)',
          overlapping: false
        }];
        return validateSuffixes( [ ...DEFAULT_BREAKPOINTS.map( updateBreakpoints ), ...GT_XL ] );
      },
    },
  ],
} )
export class MyBreakPointsModule { }
```
