### ISSUE TITLE
Insert dynamic component in fxFlex

### ISSUE THREAD

**Issue by ankur021188** [angular/flex-layout#530]
How to insert or load dynamic angular components in fxFlex layouts?

**Comment by denver-HJS** [comment]
This is really a question that belongs in a forum like gitter, or as a posted question in StackOverflow.

Angular has a guide for this that can be found [here](https://angular.io/guide/dynamic-component-loader). Even though it's not specific to FlexLayout you'll be able to use the FlexLayout features.

**Comment by ThomasBurleson** [comment]
Agreed. @angular/flex-layout has nothing to do with dynamic component injection. If you want to  layout dynamic content, however, that content should be injected into a container that already has fxLayout directives applied.
