### ISSUE TITLE
Object doens't support property or method 'assign'

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#532]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should not have errors

#### What is the current behavior?
console shows: "Object doens't support property or method 'assign'"
page does not render

#### What are the steps to reproduce?
visit https://tburleson-layouts-demos.firebaseapp.com

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
IE11 on Win8.1 (virutalbox)

**Comment by CaerusKaru** [comment]
Is this a bug you're having with your app, or is it just something you observed on the demo? It sounds like it's just a polyfill issue, which can be easily fixed for the demo, but you'll have to include it in your own app.
