### ISSUE TITLE
Angular core 5.0.0 Support

### ISSUE THREAD

**Issue by roydpnkr** [angular/flex-layout#533]
#### Bug, feature request, or proposal:
angular core 5.0.0 reference issue

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by ThomasBurleson** [comment]
Merged with SHA 62457a597244a9.

> Super... super helpful.  Great work @CaerusKaru !

**Comment by ThomasBurleson** [comment]
@roydpnkr - We hope to release Beta.12 to npm today.
