### ISSUE TITLE
No npm package for this module

### ISSUE THREAD

**Issue by ranbuch** [angular/flex-layout#54]
Can you please add this module as an npm package?

Thank you.

**Comment by d3viant0ne** [comment]
There is at least 4 closed issues around this topic, it isn't supposed to be published yet.

When @ThomasBurleson is ready, an alpha release will be published to npm. Until then, see https://github.com/angular/flex-layout/wiki/Fast-Starts as was stated in every one of the closed issues listed under https://github.com/angular/flex-layout/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20npm

**Comment by alxvallejo** [comment]
@d3viant0ne If its not in npm, you might want to remove it from the wiki. https://github.com/angular/flex-layout/wiki/Fast-Starts
