### ISSUE TITLE
docs: add missing API docs to Wiki

### ISSUE THREAD

**Issue by CaerusKaru** [angular/flex-layout#540]
- [x] fxLayoutAlign
- [x] fxFlexOrder
- [x] fxFlexOffset
- [x] fxFlexAlign
- [x] fxFlexFill
- [x] imgSrc

**Comment by CaerusKaru** [comment]
@ThomasBurleson

**Comment by mhosman** [comment]
FlexLayout Docs are such a PAIN!!!
