### ISSUE TITLE
I have this error -> has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by mhosman** [angular/flex-layout#541]
ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"D:/Dev/site/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

- Last FlexLayout version.
- Last Angular & CLI version.

**Comment by ThomasBurleson** [comment]
@mhosman - Try this:

* `npm uninstall @angular/flex-layout`
*  delete your `node_modules`
* `npm install`
* `npm install @angular/flex-layout --save`

Then rebuild...

**Comment by mohanrao** [comment]
It's not working with latest again it seems with below dependencies 

`"dependencies": {
    "@angular/animations": "^5.2.3",
    "@angular/cdk": "^5.1.1",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.1.1",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@angular/service-worker": "^5.2.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngx-carousel": "^1.3.5",
    "rxjs": "^5.5.6",
    "source-map": "^0.7.0",
    "zone.js": "^0.8.19"
  }`

**Comment by ThomasBurleson** [comment]
You have incorrectly installed rc.1. See Dec 21 notes above.
