### ISSUE TITLE
Update Documentation Page "Why-use-Flex-Layout" for Beta 12 & Angular 5.x

### ISSUE THREAD

**Issue by MarcusMorba** [angular/flex-layout#546]
#### Bug, feature request, or proposal:
Currently it contains: "requires Angular v4.1.x or higher."

#### What is the expected behavior?
Latest flexbox beta 12 should work with Angular 4.1 or documentation should be "requires Angular v5.x or higher."

#### What is the current behavior?
Does not work with Angular 4.1.

#### What is the use-case or motivation for changing an existing behavior?
Update outdated documentation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.x / Angular 5.x

**Comment by CaerusKaru** [comment]
Fixed. In the near future, #520 will allow you to submit a PR to change this yourself. Thanks for the catch!
