### ISSUE TITLE
feat(mediaMatch): add ScreenTypes and more Breakpoints

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#55]
Add the following screentypes:

```js
const HANDSET_PORTRAIT  = '(orientation: portrait) and (max-width: 599px)';
const TABLET_PORTRAIT   = '(orientation: portrait) and (min-width: 600px) and (max-width: 839px)';
const WEB_PORTRAIT      = '(orientation: portrait) and (min-width: 840px)';

const HANDSET_LANDSCAPE = '(orientation: landscape) and (max-width: 959px)';
const TABLET_LANDSCAPE  = '(orientation: landscape) and (min-width: 960px)  and (max-width: 1279px)';
const WEB_LANDSCAPE     = '(orientation: landscape) and (min-width: 1280px)';

export const SCREEN_TYPES = {
  HANDSET           : `${HANDSET_PORTRAIT}, ${HANDSET_LANDSCAPE}  `,
  TABLET            : `${TABLET_PORTRAIT} , ${TABLET_LANDSCAPE}   `,
  WEB               : `${WEB_PORTRAIT}    , ${WEB_LANDSCAPE}      `,

  HANDSET_PORTRAIT  : `${HANDSET_PORTRAIT}                        `,
  TABLET_PORTRAIT   : `${TABLET_PORTRAIT}                         `,
  WEB_PORTRAIT      : `${WEB_PORTRAIT}                            `,

  HANDSET_LANDSCAPE : `${HANDSET_LANDSCAPE}                       `,
  TABLET_LANDSCAPE  : `${TABLET_LANDSCAPE}                        `,
  WEB_LANDSCAPE     : `${WEB_LANDSCAPE}                           `
};
```

And the following BreakPoints: 

```js
[
{ 'alias': 'handset'            , 'mediaQuery': ScreenTypes.HANDSET           },
{ 'alias': 'handset.landscape'  , 'mediaQuery': ScreenTypes.HANDSET_LANDSCAPE },
{ 'alias': 'handset.portrait'   , 'mediaQuery': ScreenTypes.HANDSET_PORTRAIT  },

{ 'alias': 'tablet'             , 'mediaQuery': ScreenTypes.TABLET          },
{ 'alias': 'tablet.landscape'   , 'mediaQuery': ScreenTypes.TABLET          },
{ 'alias': 'tablet.portrait'    , 'mediaQuery': ScreenTypes.TABLET_PORTRAIT },

{ 'alias': 'web'                , 'mediaQuery': ScreenTypes.WEB           },
{ 'alias': 'web.landscape'      , 'mediaQuery': ScreenTypes.WEB_LANDSCAPE },
{ 'alias': 'web.portrait'       , 'mediaQuery': ScreenTypes.WEB_PORTRAIT  }
]
```

**Comment by bm-software** [comment]
That is a must have feature to handle portrait and landscape layouts!
When will you add this?

**Comment by ThomasBurleson** [comment]
Please review our [Custom BreakPoints wiki](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints).

> Note: current, in-progress work will change the documented solution for [customizing with your own mediaQueries](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints#customizing-with-your-own-media-query-ranges).

**Comment by bm-software** [comment]
With [Custom BreakPoints](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints) can I customize the existing aliases or can I create new ones?

**Comment by Neo-7** [comment]
hi
i have changed css brake-points based on my requirements.
(manually edited - flex-layout.umd.js, break-points-provider.js/map, break-points-provider.metadata.json, etc... )

my changed value's [width] as follows : 
xs		(max-width: 479px)						 	:: 		Up-to Mobile Portrait
gt-xs	(min-width: 480px)							:: 		From Mobile Landscape
sm		(min-width: 480px) and (max-width: 767px)		:: 		Mobile Landscape Only
gt-sm	(min-width: 768px)							:: 		From Tablet Portrait
md		(min-width: 768px) and (max-width: 1023px)		:: 		Tablet Portrait Only
gt-md	(min-width: 1024px)						:: 		From Tablet Landscape
lg		(min-width: 1024px) and (max-width: 1279px)	:: 		Tablet Landscape Only
gt-lg	(min-width: 1280px)						:: 		From Minimum Desktop
xl		(min-width: 1600px)						:: 		From Larger Desktop

it works for me. hope it helps

**Comment by Neo-7** [comment]
@ThomasBurleson 
const HANDSET_LANDSCAPE = '(orientation: landscape) and (max-width: 959px)';

- Opening the soft keyboard on most devices in portrait orientation will cause the viewport to become wider than it is tall, thereby causing the browser to use landscape styles instead of portrait.

i think this would solve that issue...
const HANDSET_LANDSCAPE = '(orientation: landscape) and (max-width: 959px) and (min-width:480px)';

**Comment by ThomasBurleson** [comment]
@bm-software - check the PR #204 for details on the upcoming custom breakpoints
@Neo-7 - thank you. We will adjust the mediaQueries in 204.

**Comment by ThomasBurleson** [comment]
@Neo-7 - why are you using `min-width:480px`? Where did you derive that value from on the referenced chart ?

**Comment by Neo-7** [comment]
@ThomasBurleson 
because sometimes the project i'm working is not focused on landscape mode. And they want me to show one static screen, asking user to rotate the screen, so user will not access the screen in the landscape mode.

small devices like **iphone 5s, iphone se, xperia z**, etc... device's landscape width is below **599px**;
so if user opens keyboard on screen, browser considers the screen is in landscape mode, 
because sometimes device **status bar + footer + browser header + keyboard height** is bigger than actual content area. And the browser shows landscape solution in portrait mode.

here is the reference
![untitled](https://cloud.githubusercontent.com/assets/11517705/23734691/d5cadf46-04a6-11e7-9627-09471d0389ed.png)

**Comment by imrvshah** [comment]
Hi @ThomasBurleson 

"Please review our Custom BreakPoints wiki." 

I have implemented custom breakpoint using the documentation. But I am getting error  `Cannot read property 'mediaQuery' of undefined`
![2017-03-22_1721](https://cloud.githubusercontent.com/assets/1934715/24223463/3ad8fd6e-0f24-11e7-8159-759ea6076d69.png)

Am I missing anything? 

Thanks in advance.

**Comment by nivram80** [comment]
@ThomasBurleson I'm getting the same error as @imrvshah.  Here is a plnkr showing the error:
http://plnkr.co/edit/8KN69A?p=info

**Comment by nivram80** [comment]
@imrvshah Did you ever find a solution for the `Cannot read property 'mediaQuery' of undefined` error?

**Comment by imrvshah** [comment]
@nivram80 I didn't find solution yet.

**Comment by ThomasBurleson** [comment]
@nivram80 - fixed with latests builds on master.
