### ISSUE TITLE
Support-Request: Device Detection

### ISSUE THREAD

**Issue by MarcusMorba** [angular/flex-layout#551]
#### Bug, feature request, or proposal:
How is the best practice to support "device detection"?

#### What is the expected behavior?
Be able to detect device and deliver different adaptive & responsive layouts and behaviours.

#### What is the current behavior?
Don´t know in detail. Default breakpoints currently don´t regard e.g. max-device-width or -webkit-device-pixel-ratio.

#### What is the use-case or motivation for changing an existing behavior?
The reason I ask is that I want to provide a different behaviour/layout within a complex app for ...
a) Desktop User
Desktop user has resized e.g. his browser window (e.g. 50% of width 2560px = 1280px ) for a multiwindow app use.

b) Tablet/Laptop User
Uses full screen width (e.g. 1280px).

c) Smartphone Users
Uses full screen width (e.g. 1280px).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular +4.1

**Comment by CaerusKaru** [comment]
You're looking for [angular/cdk/platform](https://github.com/angular/material2/blob/master/src/cdk/platform/platform.ts)

**Comment by CaerusKaru** [comment]
Closing this for now. If the above comment doesn't help, please clarify and we'll reopen.

**Comment by abhiamehta** [comment]
CDK provides you browser detection not Device detection please help me if any API of CDK provides support to detect device as well.
