### ISSUE TITLE
MediaChange not firing on lazy loaded route change. 

### ISSUE THREAD

**Issue by Defmetalhead** [angular/flex-layout#552]
#### Bug, feature request, or proposal:
ObservableMedia should fire on route change.

#### What is the expected behavior?
I have a lazy loaded module that should subscribe to ObservableMedia when routed too. 

#### What is the current behavior?
When I route to a lazy loaded module, the component does not subscribe to ObservableMedia on component Initialization. On page refresh the media query fires as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently using Angular 5.0.0 and flex layout 2.0.0-beta.12

This is how I have implemented Observable media. 

   ```
constructor(private media: ObservableMedia) {}
 ngOnInit() {
        console.log('init');
        this.mediaChange = this.media.subscribe((change: MediaChange) => {
            console.log(change);
            if (change.mqAlias == 'md' || change.mqAlias == 'lg' || change.mqAlias == 'xl')
                this.flexDirection = 'row';
            else this.flexDirection = 'column';
        });
    }

    ngOnDestroy() {
        console.log('unsubmedia');
        this.mediaChange.unsubscribe();
    }

```

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction using the StackBlitz template. Reproducing the exact behavior you're seeing is not possible using your provided code snippet.

**Comment by ThomasBurleson** [comment]
@Defmetalhead - are you importing the FlexLayoutModule into your lazy-loaded module ?

**Comment by Defmetalhead** [comment]
Actually, the problem is that I am subscribing to ObervableMedia in multiple components. I am using Angular Universal and RouteReuseStrategy. The first component to subscribe to Observable Media is a RouteReuse Component. So the subscription will not fire is all other components because the app is already listening. Any thoughts on how to get around this? I thought about unsubscribing on NavigationStart, but then the component using RouteReuse would no longer be listening for media changes. Thoughts on getting around this?

**Comment by CaerusKaru** [comment]
If this is a universal issue, you need to provide a minimal reproduction repository, possibly as a fork of the universal-starter. We cannot begin to debug this issue without it.

**Comment by Defmetalhead** [comment]
I got around this by creating a service that subscribes to the ObservableMedia. The service creates a BehaviorSubject that emits the mqAlias anytime it changes to those components listening. I believe this is the way it should be done when multiple components need to use ObservableMedia

**Comment by ThomasBurleson** [comment]
@Defmetalhead - [ObservableMedia](https://github.com/angular/flex-layout/blob/master/src/lib/media-query/match-media.ts#L63-L64) services also uses a BehaviorSubject.

**Comment by Defmetalhead** [comment]
I understand that @ThomasBurleson , unfortunately once the first subscription to ObservableMedia happens, it never fires again in other components that need the initial value from ObservableMedia. This is of course a subscription opened by a component that is never destroyed.

**Comment by CaerusKaru** [comment]
Can you embody this behavior in a StackBlitz demo so we can take a look? `BehaviorSubject`, and by virtue the Observables created from them, always emit the latest value when subscribed to.

**Comment by CaerusKaru** [comment]
Haven't gotten a demo in over two months, so closing for now. We can reopen if we get a demo to investigate.

For what it's worth, we're switching to the CDK media engine in the future, which may resolve this issue (or at least punt it to the Material team).
