### ISSUE TITLE
fxFlexAlign doesn't seems to work

### ISSUE THREAD

**Issue by mkdudeja** [angular/flex-layout#555]
#### Bug, feature request, or proposal:
fxFlexAlign should align the content within the container.

#### What is the expected behavior?
As per the docs, fxFlexAlign should align the element within the container.

#### What is the current behavior?
fxFlexAlign doesn't align the content within the container.
fxFlexAlign="start" or fxFlexAlign="end" doesn't seems towork

#### What are the steps to reproduce?
Link to stackblitz:
https://angular-flex-layout-seed-lnz9zu.stackblitz.io

**Expected behavior:**
_Register_ should be on the extreme left
_ForgotPassword_ should be on the extreme right

#### What is the use-case or motivation for changing an existing behavior?
Please elaborate the use case of using the _fxFlex_ and its other attributes like _fxFlexAlign_ and others. Current wiki docs explains only the definition of these declarative APIs.

#### Is there anything else we should know?
Posted the same Gitter channel and community member responded to use _fxLayoutAlign_ instead of _fxFlexAlign_ to align the elements. 

Example URL: https://angular-kt9gkd.stackblitz.io/

Not able to understand why _fxLayoutAlign_ instead of _fxFlexAlign_ to align the elements. on _fxFlex_ element.

**Comment by CaerusKaru** [comment]
You need to post the source links to the StackBlitz demos, just looking at the HTML is not enough.

**Comment by CaerusKaru** [comment]
Here's the elaboration you're looking for, which we'll add to the docs when #520 is resolved.

`fxFlexAlign` aligns the element with respect to _its parent_ container. When you apply `fxLayoutAlign` to a child element, it turns it into its own container element, where the `text inside` is now the child, and gets aligned to the end of the element (which in this case is your desired behavior).

**Comment by ThomasBurleson** [comment]
Fixed with SHA 67e4bf5bccc0ade
