### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by loganfreeman** [angular/flex-layout#558]
#### What is the current behavior?
```
error	11-Jan-2018 21:22:51	npm ERR! Error while executing:
error	11-Jan-2018 21:22:51	npm ERR! /bin/git ls-remote -h -t ssh://git@github.com/angular/flex-layout.git
error	11-Jan-2018 21:22:51	npm ERR! 
error	11-Jan-2018 21:22:51	npm ERR! ssh_exchange_identification: Connection closed by remote host
error	11-Jan-2018 21:22:51	npm ERR! fatal: Could not read from remote repository.
error	11-Jan-2018 21:22:51	npm ERR! 
error	11-Jan-2018 21:22:51	npm ERR! Please make sure you have the correct access rights
error	11-Jan-2018 21:22:51	npm ERR! and the repository exists.
error	11-Jan-2018 21:22:51	npm ERR! 
error	11-Jan-2018 21:22:51	npm ERR! exited with error code: 128
```

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
This looks like an independent connectivity issue, unrelated to Flex Layout. I just installed it myself on my own network and through a VPN. If this issue persists or gets community traction, we can reopen. Otherwise marking as invalid.
