### ISSUE TITLE
chore: deprecate fxLayoutWrap

### ISSUE THREAD

**Issue by CaerusKaru** [angular/flex-layout#564]
The `FlexLayoutWrapDirective` has been deprecated since at least beta.10. It is slated to be removed with the next release.

**Comment by aldo-roman** [comment]
is there any docs regarding the deprecation of `[fxLayoutWrap]`? I cannot find them in the changelogs.

**Comment by CaerusKaru** [comment]
It’s not in the CHANGELOG for some reason, but it is in the source for the directive. If you open up the source in an IDE, for instance, you would immediately see that it’s been marked as deprecated, and for a while.

**Comment by lebnic** [comment]
The link https://github.com/angular/flex-layout/wiki/fxLayoutWrap-API (found in this repo's wiki) for layoutWrap does not work ...

Maybe wiki's doc should be update to remove any mention of layoutWrap (eg: https://github.com/angular/flex-layout/wiki/API-Documentation)

**Comment by CaerusKaru** [comment]
The docs will be updated after the API is removed.

**Comment by RoestVrijStaal** [comment]
@CaerusKaru @ThomasBurleson 
https://archive.fo/KbHrX Oh-Oh! Someone did not do his job and this ticket got closed without result verification :sob:

And there is zero documentation about the new 'wrap' keyword for fxLayout https://github.com/angular/flex-layout/wiki/fxLayout-API#fxlayout-options

**Comment by CaerusKaru** [comment]
@RoestVrijStaal lack of documentation is not a lack of verification. On the master branch, it is not uncommon for features to be released without documentation. In fact, it is commonly the last thing to be added before the next published release. You can see that #540 will include the documentation updates you are so worried about. 

Current documentation for the wrap option, which is documented in the code, is also available on [this page](https://github.com/angular/flex-layout/wiki/Declarative-API-Overview). Currently not the easiest to find, and will be fixed in #540, but definitely not impossible to find.

**Comment by RoestVrijStaal** [comment]
> Current documentation for the wrap option, which is documented in the code, is also available on this page. Currently not the easiest to find, and will be fixed in #540, but definitely not impossible to find. 

Sounds promising but when I look there:

| HTML API &nbsp;&nbsp;&nbsp;    | Allowed values                                                          |
|--------------------|-------------------------------------------------------------------------|
|  [fxLayout](https://github.com/angular/flex-layout/wiki/fxLayout-API)          | `<direction>  \|  <direction> <wrap>` <br/> Use: `row \| column \| row-reverse \| column-reverse` 

It isn't there? 

I think you're pointing at a version of that page in a branch which isn't public yet.

**Comment by CaerusKaru** [comment]
Under allowed values, it’s the thing that says `<wrap>`

**Comment by martinsik** [comment]
I just stumbled upon this. It's not mentioned in the [CHANGELOG.md](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md) at all that `fxLayoutWrap` was removed.

**Comment by damoncasale** [comment]
What are the valid values for <wrap>?  nowrap doesn't seem to be working for me.

**Comment by crowmagnumb** [comment]
Well ```<wrap>``` in the docs doesn't make any sense unless you also provide the valid values. Thankfully they have since updated the docs to read ```[wrap]``` to make it clear that "wrap" is the only valid value here. "nowrap" is the default.

**Comment by simeyla** [comment]
I wish this had been set to give an error:

**Comment by simeyla** [comment]
Just to be clear - do this now:

     fxLayout="row wrap"

Not this:

     fxLayout="row"
     fxLayoutWrap

**Comment by spottedmahn** [comment]
> I just stumbled upon this. It's not mentioned in the CHANGELOG.md at all that fxLayoutWrap was removed.

@martinsik - looks like it got updated 😊

[CHANGELOG.md#breaking-changes-1](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes-1)

![image](https://user-images.githubusercontent.com/14079228/39959131-25cfc462-55db-11e8-966e-6350f00594f5.png)

**Comment by spottedmahn** [comment]
[wiki/fxLayout-API](https://github.com/angular/flex-layout/wiki/fxLayout-API#fxlayout--wrap) documentation updated 😊 thanks to @ThomasBurleson!

Related issue: https://github.com/angular/flex-layout/issues/740

**Comment by spottedmahn** [comment]
I feel like it should also be mentioned on the [API Doc page](https://github.com/angular/flex-layout/wiki/API-Documentation) too.

![image](https://user-images.githubusercontent.com/14079228/39959179-207b39fa-55dc-11e8-9a6e-c23f3a085fa8.png)

Thoughts?
