### ISSUE TITLE
I am using flex-layout 2.0.0-beta.12 version. I could not seen any release version. Could I get the release version in coming days? or only Beta? Because, I can not use a beta version in my projects. Please help to solve this.

### ISSUE THREAD

**Issue by Raj6583** [angular/flex-layout#570]
#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by ThomasBurleson** [comment]
@Raj6583 - On beta versions are available currently. Release is not expected for at least 6 months.

> Note: This is an invalid issue submission. Please review our issue-submission guidelines regarding proper notations.
