### ISSUE TITLE
is ngClass really merging correctly?

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#574]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
On gt.md both class "desktop" and "background-image" should be present.. right?

#### What is the current behavior?
looks like only gt-sm is used

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-b3yp5n?file=app/test.component.ts

**Comment by CaerusKaru** [comment]
`ngClass.<suffix>` is designed to merge with existing `ngClass` declarations, not other responsive declarations. For this, we use a [fallback algorithm](https://github.com/angular/flex-layout/wiki/Responsive-API#breakpoint-activation-fallback-algorithm) to decide which directive is active at a given time.

It's worth discussing possibly merging these values as an exception for `ngClass`, but there are definitely arguments for both sides.

**Comment by mackelito** [comment]
hmm.. well It was just not what I expected but now I'm not sure if a change is needed.. perhaps if a more clear example arises then we might revisit this issue.. :)
