### ISSUE TITLE
Configurable vendor prefixes

### ISSUE THREAD

**Issue by j-walker23** [angular/flex-layout#575]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Would like to disable vendor prefixes during dev. I don't need them at all right now so making it configurable would be very nice.

#### What is the current behavior?
Always enabled.

#### What is the use-case or motivation for changing an existing behavior?
It's painful while in chrome dev tools and i want to toggle a flex property. I have to toggle all prefixes because they act as fallbacks for the regular css property i am trying to toggle. It's actually faster to change in code and wait for rebuild sometimes. Where clicking one checkbox in dev tools would be greatly appreciated.

#### Is there anything else we should know?
Thanks for your help, and this crazy cool lib. Had no idea it would be considerably more powerful than ng-material1's layout. Pretty impressive.

**Comment by CaerusKaru** [comment]
We're going to add this in after #567 lands, since it bundles the code that applies the prefixes into a class; we can then inject a config token in as a result.
