### ISSUE TITLE
Deprecate version 2.0.0-rc.1 (from npm/yarn)

### ISSUE THREAD

**Issue by odahcam** [angular/flex-layout#578]
#### Bug, feature request, or proposal:
request

#### What is the expected behavior?
that my package manager (yarn, npm) downloads the latest version of this package.

#### What is the current behavior?
my package manager downloads version 2.0.0-rc.1 because they think rc.1 is the latest version.

#### Is there anything else we should know?
If it is already deprecated, the deprecation is not working well. 🤔

**Comment by CaerusKaru** [comment]
We are planning on bumping the next beta to version 5 to offset this issue. I'll keep this issue open until then in case anything changes.

**Comment by CaerusKaru** [comment]
Should be fixed by latest release to npm
