### ISSUE TITLE
fxHide & fxShow not working

### ISSUE THREAD

**Issue by paistipoikka** [angular/flex-layout#58]
Hi,

if I try to set up a responsive menu using [fx-hide] / [fx-show] the properties of the <div> do not get updated as the component property changes state. In other words, when the state changes from true--> false --> true it appears that the underlying state is not being reflected in the <div>.

Here's are the relevant snippets of code:

```html
<button class="nav-trigger" 
            (click)="toggleMenu(!menuOpen)" 
            color="primary" 
            md-icon-button>
     <md-icon class="md-24">menu</md-icon>
</button>

<div fx-layout="row" fx-show="true" [fx-show.xs]="menuOpen">blah</div>
```

```js
private menuOpen: boolean = true;


toggleMenu(show: boolean) {
        this.menuOpen = show;

    }
```

Hope this helps

JT

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates the issue. Here is a [Plunkr template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview)

The API has changed (and all the docs): 

*  `fx-layout` should be `fxLayout`
*  `fx-show` should be `fxShow`

**Comment by ThomasBurleson** [comment]
You realize that your logic in `toggleMenu()` **never** sets the menu to false ?

**Comment by ThomasBurleson** [comment]
The API has changed (and all the docs): 

*  `fx-layout` should be `fxLayout`
*  `fx-show` should be `fxShow`

Here is a your [Code Plunkr](https://plnkr.co/edit/3SKnjiop1QSXZaKjxHAQ?p=preview).

**Comment by paistipoikka** [comment]
Hi @ThomasBurleson 

Thanks for coming back so quickly. The toggle was happening up in the form using the '!' in toggleMenu(!menuOpen). 

It seems the button in the Plunkr is not working either. fxShow is reading the property. Just not showing anything.

```
import {Component} from '@angular/core'

@Component({
  selector: 'test-app',
  template: `
<button class="nav-trigger" 
            (click)="toggleMenu()" 
            color="primary" 
            md-icon-button>
     Toggle Button
</button>

<div fxLayout="row" 
    [fxShow]="menuOpen"
    fxShow.xs="true"
    style="margin-top:25px;background-color:#d9edf7">
  I should hide and show
</div>  `,
})
export class TestApp {
 private _menuOpen: boolean = true;

  toggleMenu(show: boolean) {
      this.menuOpen = !this.menuOpen;
  }
  
  set menuOpen(_menuOpen: boolean) {
    console.log(_menuOpen);
    return this._menuOpen = _menuOpen;
  }
  
  get menuOpen(): boolean {
    console.log(this._menuOpen);
    return this._menuOpen;
  }
}
```

**Comment by ThomasBurleson** [comment]
@paistipoikka - The Plunkr is not working because you discovered a pre-Beta bug ;-).

**Comment by ThomasBurleson** [comment]
@paistipoikka  - see the 

[Unit Test](https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/show.spec.ts#L85)
[Plunkr Demo](https://plnkr.co/edit/3SKnjiop1QSXZaKjxHAQ?p=preview)

**Comment by paistipoikka** [comment]
@ThomasBurleson That's not working in the Plunkr.

**Comment by ThomasBurleson** [comment]
@paistipoikka  - It is working now... just make sure the result view pane is > `xs` viewport size.

**Comment by paistipoikka** [comment]
Nice! 👍

**Comment by fdambrosio** [comment]
I'm using angular 2.1.0 and flex-layout alpha and we can't upgrade because we've started using https://github.com/qdouble/angular-webpack2-starter 
so now fx-layout & fx-flex works but fxShow & fxHide don't 
```
<div [fxShow]="menuOpen"
     fxShow.xs="true"
     style="margin-top:25px;background-color:#d9edf7">
  I should hide and show
</div> 
```
return this error 
"Uncaught (in promise): Error: Template parse errors:
Can't bind to 'fxShow' since it isn't a known property of 'div'"

**Comment by ThomasBurleson** [comment]
@fdambrosio - please report a new issue.

**Comment by IK-Hwan** [comment]
<div id="sideBar" fxLayout="column" fxFlex="202px" fxShow="{{sideBarOpen?'true':'false'}}">


export class MainpageComponent implements OnInit {
  sideBarOpen: boolean = true;

  private sideControlToggle() {
    this.sideBarOpen = !this.sideBarOpen;
  }
}


Good luck to you.....

**Comment by SamiHK** [comment]
@ThomasBurleson  I have Angular latest version 6.1.2 and fxHide and fxShow are not working.

**Comment by CaerusKaru** [comment]
@SamiHK If this is still a problem, please open a new issue with a demo and/or minimal reproduction.
