### ISSUE TITLE
fxLayout Direcitve throws 404 not found

### ISSUE THREAD

**Issue by aravindfz** [angular/flex-layout#582]
#### Bug, feature request, or proposal:
Documentation

#### What is the expected behavior?
User should be navigated flex layout code should be 

#### What is the current behavior?
404 Error

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
  - Go to the [fxLayout](https://github.com/angular/flex-layout/wiki/fxLayout-API) documentation
  - Click on the `fxLayout directive` hyper link which will be throwing 404 error.
  - Link - https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/layout.ts#L60-L69
*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/22231525/35179002-5218af60-fdb7-11e7-8325-e0e9250a0e6b.png)

**Comment by CaerusKaru** [comment]
Will be fixed by #573

**Comment by ThomasBurleson** [comment]
Fixed with SHA 67e4bf5bccc0ade
