### ISSUE TITLE
fxLayoutWrap.xs isn't actually following the rules when combine with fxLayout

### ISSUE THREAD

**Issue by MikaAK** [angular/flex-layout#592]
#### Bug, feature request, or proposal:
Using `fxLayout`  & `fxLayoutWrap.xs` is broken

#### What is the expected behavior?
 i would expect it to wrap only in mobile

#### What is the current behavior?
however this isn't the case, it wraps in desktop and the `xs` part is ignored

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 
<div fxLayout fxLayoutWrap.xs>
</div>

#### What is the use-case or motivation for changing an existing behavior?
wrapping in mobile

**Comment by CaerusKaru** [comment]
`fxLayoutWrap` has been deprecated for the past six months and was removed in one of the latest nightly releases. Please use the compatible `fxLayout` alternative, e.g.

`fxLayout="row" fxLayoutWrap` -> `fxLayout="row wrap"`

The documentation has been updated in the repo but not posted (this will happen with the next release).
