### ISSUE TITLE
material.angular.com broken on mobile

### ISSUE THREAD

**Issue by eTallang** [angular/flex-layout#594]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The website should work

#### What is the current behavior?
As the screenshot below illustrates, the page is broken. I have browsed many other websites, and angular.material.com is the only one behaving like that. The glitches gets worse by time, until Chrome force closes and restarts.
![screenshot_20180202-175309](https://user-images.githubusercontent.com/24789715/35758784-f75bd704-0875-11e8-86d5-b9ebe4d5377e.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular.material.com at Feb. 3.

**Comment by CaerusKaru** [comment]
This is not a Flex Layout issue, please file this in the **Angular Material2** repository.

**Comment by ThomasBurleson** [comment]
@eTallang - please reopen this is here [Angular Material Issue](https://github.com/angular/material2/issues/new)

**Comment by eTallang** [comment]
It's already been done:
https://github.com/angular/material2/issues/9766

I must somehow have mixed up repos when I created this issue.
