### ISSUE TITLE
ObservableMedia not emitting when *some* elements have flex-layout conditionals on attributes

### ISSUE THREAD

**Issue by strychnide** [angular/flex-layout#599]
#### Bug, feature request, or proposal:
ObservableMedia doesn't emit when *some* elements have a direcitve like
ngClass.gt-lm (the bug affects also "traditional" html attributes and fxFlex ones). 
For instance in the provided example, mat-card isn't affected by the bug, but h3 is. Your mileage may vary

#### What is the expected behavior?
ObservableMedia should emit whether or not the current template contains a .xx-xx condition.

#### What is the current behavior?
ObservableMedia has a fuzzy behavior: if a switch is made from an unaffected page to an affected page it emits correctly on the first time, but doesn't emit anything from the second time onwards.
example: A -> affected, U -> unaffected
U-> A  emits
A -> U emits
U -> A doesn't emit

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ax1now-b2tond

Important: extend the viewer to make the gt-md true or change the value in internal.component.ts under (app/pages/internal)
enter -> go back -> enter
the second time the sidenav will be in "over" mode instead of being in "push" mode, because the observable won't emit anything (You can check in the console, I put a console.log to help just in case)

#### What is the use-case or motivation for changing an existing behavior?
It's obviously a bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
(at least) 5.1.2 to 5.2.2 angular, 5.1.2 to 5.2.2 angular/material, 2.0.0beta12  angular/flex-layout

**Comment by CaerusKaru** [comment]
This is an excellent catch, and it's a shame I'm only getting to this now. The root cause was discovered in a post-mortem on the beta20/beta21 releases, and we're slating to resolve this in beta 23 (Jan 2019). Until then, we're tracking this in the similar issue #426.
