### ISSUE TITLE
flex-layout on version 2.0.0-beta.10 and above caused mat-chips to lose their design

### ISSUE THREAD

**Issue by yonarad** [angular/flex-layout#601]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/3831841/35960046-cd6d5500-0cb0-11e8-819a-80ff3fb2bd1f.png)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/3831841/35960067-ea422b06-0cb0-11e8-8546-2ccd6c8b1a0e.png)

#### What are the steps to reproduce?
add material chips to your project and see that in this combination of versions the css of the chips not exist in the page.

#### What is the use-case or motivation for changing an existing behavior?
the styles of the mat-chips should be displayed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "4.4.6",
"@angular/flex-layout": "2.0.0-beta.10",
"@angular/material": "2.0.0-beta.12",

OS and browsers - any.

#### Is there anything else we should know?
in "@angular/flex-layout": "2.0.0-beta.9" all working correctly.

"@angular/flex-layout": "2.0.0-beta.11" is not solve the problem
I can't check it in the last "@angular/flex-layout": "2.0.0-beta.12" because it require angular 5.
We can't move to this version in this time point.

Workaround is to add explicitly this code-block to styles.css:
mat-chip {
    padding: 7px 12px;
    border-radius: 24px;
    align-items: center;
    text-transform: capitalize;
}

**Comment by jotatoledo** [comment]
Add a repro with the latest version of flex-layout

**Comment by ThomasBurleson** [comment]
v5.0.0-beta.13 should be released tomorrow.   (note version change from 2 -> 5 to better align with Angular and Angular Material.)

**Comment by CaerusKaru** [comment]
@yonarad Since Flex-Layout is not in stable release, we don't have LTS for previous versions. Unfortunately without upgrading to Angular 5, you won't be able to get the fix for this. The current workaround is acceptable in the meantime, and thank you for posting that!

**Comment by CaerusKaru** [comment]
Closing since no repro for latest version. We can reopen this if it's still a problem with v5.0.0-beta.13
