### ISSUE TITLE
how can get the image fixed into a fxFlex="20" i need an example for this

### ISSUE THREAD

**Issue by abhimajeti** [angular/flex-layout#604]
#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
This repo is not a support forum. Better avenues for support are StackOverflow or Gitter.
