### ISSUE TITLE
fxLayoutGap doesnt work properly with fxFlexOrder

### ISSUE THREAD

**Issue by naveedahmed1** [angular/flex-layout#608]
#### Bug, feature request, or proposal:
`fxLayoutGap` doesn't seem to work properly with `fxFlexOrder`. Try the below code:

```
<div fxLayout="row wrap" fxLayoutGap="15px">
<div fxFlex="310px" fxFlex.xs="100" fxFlexOrder.gt-xs="2">
DIV A
</div>
<div fxFlex="calc(100%-325px)" fxFlex.xs="100" fxFlexOrder.gt-xs="1">
DIV B
</div>
</div>
```

In case of `gt-xs` `DIV A` is shown on right and has `margin-right` set to `15px`, whereas `DIV B` is shown on left without margin right.

#### What is the expected behavior?
In case of gt-xs `DIV A` should be shown on right and should have `margin-right` set to `0px`, whereas `DIV B` should be shown on left with margin right set to `15px`.

**Comment by CaerusKaru** [comment]
Please provide a StackBlitz demo so we can investigate.

**Comment by naveedahmed1** [comment]
Here you go https://stackblitz.com/edit/angular-material-flex-layout-seed-j1npac
preview https://angular-material-flex-layout-seed-j1npac.stackblitz.io/
