### ISSUE TITLE
yarn add @angular/flex-layout-builds --save not working

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#616]
#### Bug, feature request, or proposal:
https://github.com/angular/flex-layout/wiki/Fast-Starts
This page suggests me to run ```yarn add @angular/flex-layout-builds --save```

#### What is the expected behavior?
should install :)

#### What is the current behavior?
```
yarn add @angular/flex-layout-builds --save
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular%2fflex-layout-builds: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/markus/projects/fodi/market/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

#### What are the steps to reproduce?
run ```yarn add @angular/flex-layout-builds --save``` on a new cli project

#### What is the use-case or motivation for changing an existing behavior?
:)

**Comment by CaerusKaru** [comment]
Try this instead:

`yarn add angular/flex-layout-builds`

**Comment by CaerusKaru** [comment]
The yarn command has been removed from the latest version, which has not yet been published

**Comment by CaerusKaru** [comment]
Just tried this locally and it worked, closing.
