### ISSUE TITLE
Plunkr to show Flex-Layout Performance  

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#617]
#### Bug, feature request, or proposal:
Plunkr link on https://github.com/angular/flex-layout/wiki/Performance-Considerations is broken

**Comment by CaerusKaru** [comment]
This has been fixed in the latest version, found [here](https://github.com/angular/flex-layout/blob/master/docs/documentation/Performance-Considerations.md)

**Comment by CaerusKaru** [comment]
Oh I see what you mean. We'll have to convert this to a StackBlitz. Thanks for finding this!
