### ISSUE TITLE
flex-layout is not working when attributes are lower case

### ISSUE THREAD

**Issue by atmike** [angular/flex-layout#619]
Bug,

Hi I have allready posted this under Angular Issues but they mean that this is a flex layout problem

## Current behavior
When using Renderer2 to set Attributes on a DIV (in my case Felx Layout Attributes). The Renderer renders all Attributes in lower case. So fxFlex will get fxflex and the FlexLayout is no longer working
Here is the Code I'm using =>
```
          var rowcol = renderer.createElement('div');
          renderer.setAttribute(rowcol , "fxFlex", "");
          renderer.setAttribute(rowcol , 'fxLayout', "row");
          renderer.setAttribute(rowcol , "fxLayout.xs", "column");
          renderer.setAttribute(rowcol , "fxLayoutGap", "10px");
```

#### What is the expected behavior?
FleyLayout must work with lower and upcase 

#### Minimal reproduction of the problem with instructions
see my code above!

#### What is the use-case or motivation for changing an existing behavior?
At the moment it is not possible to render a FlexLayout from Code. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular CLI 1.6.8 / Angular 5.1.3 / Material ^5.2.0 / Node 9.5.0 / All Browser

#### Is there anything else we should know?
It would be nice for a lot of people how are search for a solution that you can fix this very soon or to provide a workaround. 

Thanks
Michael

**Comment by atmike** [comment]
One more thing. I tried this with Renderer and Renderer2 both are writing it in lower case.
Here is the post in angular 
https://github.com/angular/angular/issues/22230

**Comment by CaerusKaru** [comment]
Closing as not a Flex Layout issue.
