### ISSUE TITLE
Angular dependency should be more flexible

### ISSUE THREAD

**Issue by SchnWalter** [angular/flex-layout#620]
#### Bug, feature request, or proposal:

The package builds have a very strict dependency and and doesn't allow the package to be used with newer versions of Angular without displaying warnings.

#### What is the expected behavior?

I should be able to install the latest release in a project that depends on the latest release of Angular and NPM should not cry about this.

#### What is the current behavior?

Warnings are shown:
```bash
> npm install @angular/flex-layout@latest --save    
npm WARN @angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/core@~5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/common@~5.1.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by jotatoledo** [comment]
Thats why the project will get a version bump soon.

**Comment by CaerusKaru** [comment]
@jotatoledo is right, this restriction will be removed in the next version.
