### ISSUE TITLE
fxLayoutWrap directive not working

### ISSUE THREAD

**Issue by attilacsanyi** [angular/flex-layout#635]
#### Bug, feature request, or proposal:
`fxLayoutWrap` should apply `flex-flow: row wrap;` styles as in the **2.0.0-beta.12** version

#### What is the expected behavior?
`fxLayoutWrap` should wrap the content (generate `flex-flow: row wrap;` style) in version **5.0.0-beta.13** as well. `fxLayoutWrap="wrap"` should also work.

#### What is the current behavior?
`fxLayoutWrap` not wrap the content (the generated `flex-flow: row wrap;` is missing) in version **5.0.0-beta.13**. Neither `fxLayoutWrap` nor `fxLayoutWrap="wrap"` works.

#### What are the steps to reproduce?

*  [StackBlitz example](https://stackblitz.com/edit/angular-material-flex-layout-seed-j3b3su) with version **2.0.0-beta.12**. Expect `app.component.ts` inline template with `mat-button-toggle-group` where i applied the `fxLayoutWrap` directive.

After manually entering the new `@angular/flex-layout@5.0.0-beta.13` new dependency, StackBlitz replace the lib to the new version and you can experience that the wrapping not working anymore.

#### What is the use-case or motivation for changing an existing behavior?
Just be sure `fxLayoutWrap` directive still working as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.6, Material 5.2.3, MacOS, TS 2.6.2

#### Is there anything else we should know?
`fxLayoutWrap` was working well in **2.0.0-beta.12** version

**Comment by intellix** [comment]
`fxLayoutWrap` is deprecated, you're recommended to write: `fxLayout="row wrap"`

**Comment by ThomasBurleson** [comment]
@attilacsanyi - fxLayoutWrap was deprecated in earlier beta releases. With beta.13, this directive has been removed.  We updated the [CHANGELOG.md](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes) to highlight this.

**Comment by attilacsanyi** [comment]
@intellix @ThomasBurleson thanks its working like a charm! Thanks for pointing out to the deprecation log. Can be closed.
