### ISSUE TITLE
Move Dependencies to Peer Dependencies

### ISSUE THREAD

**Issue by amcdnl** [angular/flex-layout#636]
## Issue
In the package.json, you define dependencies like Angular:
https://github.com/angular/flex-layout/blob/master/package.json#L29-L39

Ideally these should be peer dependencies so to not duplicate dependencies and cause conflicts.

Example, I install later version of Angular than your dep declares, there will be 2 versions of angular trying to load.

**Comment by CaerusKaru** [comment]
When you install Flex Layout locally, it uses the package.json [here](https://github.com/angular/flex-layout/blob/master/src/lib/package.json), exactly the same as Material.

The top-level package.json is just for development.

**Comment by amcdnl** [comment]
Gotcha. Thanks for the feedback!
