### ISSUE TITLE
Beta 13: compilation error because of the OpaqueToken

### ISSUE THREAD

**Issue by yfain** [angular/flex-layout#637]
I can't compile my project that uses Flex Layout Beta.13. Getting the following error:

ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '".../client/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by yfain** [comment]
I've been using ^2.0.0-beta.13, but switching to ^5.0.0-beta.13 fixed the issue.

**Comment by Gajendrasinh** [comment]
Hello 

I am getting below error. version  "@angular/flex-layout": "^8.0.0-beta.26",

ERROR in Error during template compile of 'OpaqueToken'
  Function calls are not supported in decorators but 'makeDecorator' was called in 'Injectable'
    'Injectable' calls 'makeDecorator'.
