### ISSUE TITLE
Using responsive API with md-sidenav or other html elements

### ISSUE THREAD

**Issue by geelus** [angular/flex-layout#64]
At the moment thanks for Flex-Layout we can easily show or hide an element using the breakpoints. 

Is there anyway to use flex-api to open/close the side nav in different resolutions? Something lik:

```html
<md-sidenav opened.gt-sm>side nav contents </md-sidenav]>
```

**Comment by ThomasBurleson** [comment]
Use the mediaMatchObservable to be easily notified:

```css
html, body, material-app, md-sidenav-container, .my-content {
  margin: 0;
  width: 100%;
  height: 100%;
}
```

```html
<app>
  <md-sidenav-container>
    <md-sidenav mode="side" [opened]="isOpen">
      <ng-content>Projected Drawer Content</ng-content>
    </md-sidenav>    
    <div class="my-content">Main content</div>
  </md-sidenav-container>
</app>
```

```js
@Component({  selector : 'responsive-sidenav' })
export class ResponsiveSideNav implements OnDestory {
   private var _subscription; 
   isOpen = true;
 
   constructor(@Inject(MatchMediaObservable) media$) {
      this._subscription = media$.subscribe(change:MediaChange) => {
          let isMobile = (change.alias == 'xs') || (change.alias == 'sm');
          this.isOpen = !isMobile;
      });
   }
 
  ngOnDestory() {
    this._subscription.unsubscribe();
  }
}
```

**Comment by geelus** [comment]
You guys are awesome! Thank you very much for your rapid response. I didn't expect it to be this quick honestly.

**Comment by ThomasBurleson** [comment]
@geelus  - In the future, please post usage questions:

*  [Flex-Layout Groups](https://groups.google.com/forum/#!forum/angular-flex-layout), or 
*  [Gitter Chat Room](https://gitter.im/angular/flex-layout)

> Note: the Gitter room is not yet available. Check back after X-mas.

**Comment by ThomasBurleson** [comment]
Thx @geelus .  Sorry, I just made some corrections to my sample code ^. 

> I did not build a Plunkr to verify ;-)

**Comment by ThomasBurleson** [comment]
Here is a Link to the responsive code in the Demo-App source:  https://github.com/angular/flex-layout/blob/master/src/demo-app/app/docs-layout-responsive/responsiveFlexDirective.demo.ts#L45

**Comment by geelus** [comment]
Sure, I will. thanks again for your great help.

**Comment by ThomasBurleson** [comment]
@geelus - np. Give us a shoutout on Twitter. 🤓

**Comment by ThomasBurleson** [comment]
@geelus - I prepared a [Responsive-SideNav Plunkr](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview) showing how to use the MatchMediaObservable... only to discover a major bug. LOL

The Plunkr ^ has a work around and shows have a sidenav is now responsive.

> Thanks for posting this issue... it helped us make the library better!

**Comment by geelus** [comment]
@ThomasBurleson glad I could help. Yesterday I used your solution and it worked like a charm! I didn't notice the bug, maybe because I was so excited to see this working! 

Merry Christmas and Happy new year!

**Comment by joejordanbrown** [comment]
@ThomasBurleson you example has a spelling mistake `ngOnDestory`
