### ISSUE TITLE
fxLayoutWrap not wrapping in @angular/flex-layout ^2.0.0-beta.13 

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/flex-layout#641]
#### Bug
fxlayoutWrp does not wrap contents of container

#### What is the expected behavior?
Wrapping of container contents

#### What is the current behavior?
No wrapping

#### Is there anything else we should know?
fxLayoutWrap works in @angular/flex-layout ^2.0.0-beta.12

**Comment by CaerusKaru** [comment]
`fxLayoutWrap` has been deprecated, see [here](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes)
