### ISSUE TITLE
Link Demos to Stackblitz for live coding

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#644]
Similar to usages on Angular.io and Material.angular.io, we should provide
* link to run demo live on StackBlitz
* investigate the complexity of embedding StackBlitz demos; see [embedded example](https://stackblitz.com/edit/sdk-create-project).

![screen shot 2018-03-07 at 1 45 20 pm](https://user-images.githubusercontent.com/210413/37114397-dd09e6fa-220d-11e8-9109-fa1985277edf.png)

Show above is a tabbed view to toggle inline-demo, source view, or jump to StackBlitz.
> See https://medium.com/@ericsimons/stackblitz-sdk-instantly-add-live-environments-to-your-docs-blogs-more-73dab05c51ae

**Comment by CaerusKaru** [comment]
Duplicate of #47?

**Comment by ThomasBurleson** [comment]
Not quite duplicate. This one talks about embedded the demos in docs. #47 talks is focused on this:

![screen shot 2018-03-07 at 1 45 20 pm](https://user-images.githubusercontent.com/210413/37114397-dd09e6fa-220d-11e8-9109-fa1985277edf.png)

> We have a tabbed view to toggle inline-demo, source view, or jump to StackBlitz.

**Comment by ThomasBurleson** [comment]
@CaerusKaru - yes. closing this one.
