### ISSUE TITLE
ngClass.lt-* doesn't work when there is more than one breakpoint on an element

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#645]
#### Bug, feature request, or proposal:
If I have both `ngClass.lt-md` and `ngClass.lt-sm` defined on an element, only the `lt-sm` class will be applied in xs. 

#### What is the expected behavior?
BOTH classes should be applied, because xs is both less-than-medium and less-than-small

#### What is the current behavior?
Only the lt-sm class is applied in xs. The lt-md class is *not* applied despite xs matching lt-md

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
https://stackblitz.com/edit/angular-flex-layout-seed-ae6q2y

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to ADD (not replace) classes to the div as the resolution changes. Currently I have to duplicate my class list at each breakpoint (eg. `ngClass.lt-md="lt-md" ngClass.lt-sm="lt-sm lt-md"` which is not DRY

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "5.2.7"
"@angular/flex-layout": "5.0.0-beta.13"
"@angular/material": "5.2.3"
Chrome 64

**Comment by ThomasBurleson** [comment]
Your same code is:

```html
<div class="foo" ngClass.lt-sm="lt-sm" ngClass.lt-md="lt-md"></div>
```

the appropriate [current] usage would be:

```html
<div class="foo" ngClass.lt-sm="lt-sm" ngClass.sm="sm"></div>
```

Summary Notes:

*  Overlapping breakpoint (eg  `lt-<xxx>` and `gt-<xxx>`) were not designed to be used multiple times with overlaps on the same element. 
*  Overlapping breakpoints were designed to be used singularly; perhaps with other non-overlapping breakpoints.

>  This logic may not be perfect but it is in-general sufficient. I think an effort to support all combinations is noteworthy with little ROI otherwise. 

@adamdport, we would welcome a PR to enhance the library for all possible combinations of any set of breakpoints.
