### ISSUE TITLE
Could not resolve @angular/platform-server when using current build.

### ISSUE THREAD

**Issue by phamtec** [angular/flex-layout#646]
#### Bug, feature request, or proposal:

After the latest build, I get (when I build):

ERROR in Error during template compile of 'FlexLayoutServerModule'
  Could not resolve @angular/platform-server relative to /Users/paul/Dev/VOPPS/vopsDev/vops/myq-ui/node_modules/@angular/flex-layout/server/typings/index.d.ts. in 'SERVER_PROVIDERS'
    'SERVER_PROVIDERS' contains the error at ../@angular/flex-layout/server/typings/index.ts(82,42).

#### What is the expected behavior?

No error.

#### What is the current behavior?

Error produced.

#### Is there anything else we should know?

I can try to debug the problem, but I thought a developer of flex-layout might know what I am doing wrong. I tracked down an earlier incantation of this error from last year and the suggestion was to make sure "@angular/animations" was included, and in my package.json I have:

  "dependencies": {
    "@angular/animations": "^5.1.2",
...

I import flex-layout with:

    "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",

in app.module.ts my imports have:

  imports: [
    BrowserModule,
    FlexLayoutModule,
...
    BrowserAnimationsModule,
...

**Comment by ThomasBurleson** [comment]
@phamtec - my apologies. The Universal demo had a readme that documents using the `FlexLayoutServerModule`, but our wiki had not been updated. 

Please see our Wiki [Using SSR with Flex-Layout](https://github.com/angular/flex-layout/wiki/Using-SSR-with-Flex-Layout) for details.

**Comment by alvipeo** [comment]
Sorry, is there any fix for now?

**Comment by CaerusKaru** [comment]
https://github.com/angular/flex-layout/issues/646#issuecomment-371366508

**Comment by alvipeo** [comment]
Sorry, I don't get it. I don't have platform-server installed, I don't need SSR. So, should I just use it to fix this?

**Comment by CaerusKaru** [comment]
Yes, for now. It’s required for a secondary entry point which is being re-exported at the top-level at the moment. Again, this should be patched in an upcoming release

**Comment by CaerusKaru** [comment]
Reopening this because it's a real issue, and will be resolved by #656

**Comment by bostondevin** [comment]
There's always some never-ending build issue with flex-layout every time I run an npm update - EVERY time.
