### ISSUE TITLE
docs: update all links to reflect new refactor

### ISSUE THREAD

**Issue by CaerusKaru** [angular/flex-layout#654]
Almost all of the links in the docs are likely now outdated due to #631

**Comment by LauraKirby** [comment]
wiki right side nav: 

I was able to find the location for one of the broken links. 
issue 1: click, "Source Code", should be taken to the source code for the demo application
issue 1 (current behavior): 404
__solution__: `[Source Code](https://github.com/angular/flex-layout/tree/master/src/apps/demo-app)`

issue 2: click, "Browser Support",  should be taken to information about "Browser Support"
issue 2 (current behavior): "You do not have permission to update this wiki."

issue 3: click, "Adaptive Layouts",  then click, "Source", should be taken to the source code for the demo application. 
issue 3 (current behavior): 404

#### What are the steps to reproduce?

* Visit [flex-layout wiki](https://github.com/angular/flex-layout/wiki)
* issue 1: Click on "Source Code" 
* issue 2: Click on "Browser Support" 
* issue 3: Click, "Adaptive Layouts",  then click, "Source"

**Comment by CaerusKaru** [comment]
@LauraKirby This should be fixed by #664
