### ISSUE TITLE
Last line alignment of a flex-box grid

### ISSUE THREAD

**Issue by paulogr** [angular/flex-layout#66]
Anyone knows how to solve that?

I have a grid with multiple items, the grid layout alignment is set to "space-around", but the last line I want to align left not centered.

Here it goes a plunker with an example to solve.

https://plnkr.co/edit/TSznXSSxHcExaKSmyzfG

```html
<div class="containerX">
      <div fxLayout="row" fxLayoutWrap="wrap" fxLayoutAlign="space-around" >
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
        <div fxFlex="100px" class="item">  flex-item  </div>
      </div>
    </div>
```

I know this is a very know problem with flex-box grids, and I want to know how angular/flex-layout solve that problem.

Thank you!

**Comment by d3viant0ne** [comment]
@paulogr - Space Around isn't going to work the way you want it to. For a single item on the second line, the `space around` is all the white space left and right of the single item.

`space between` on the other hand should left align a single item on the second line

**Comment by paulogr** [comment]
Thank you @d3viant0ne for your very detailed answer.

Although the last line alignment of flex-box grid is a big problem dissussed on Stackoverflow and others forums. Would be nice to see an "Angular way" to solve that.

Flex-start, it's not enough, because the container are not centralized.

Here it goes some references.

http://stackoverflow.com/questions/16377972/how-to-align-left-last-row-line-in-multiple-line-flexbox
https://css-tricks.com/filling-space-last-row-flexbox/
https://teamtreehouse.com/community/flexbox-displaying-a-grid-of-images-but-having-issues-with-the-last-row-aligning-badly-codepen-within
http://stackoverflow.com/questions/18744164/flex-box-align-last-row-to-grid
http://stackoverflow.com/questions/16377972/how-to-align-left-last-row-line-in-multiple-line-flexbox

Thank you.

**Comment by ThomasBurleson** [comment]
@paulogr  - Issues should only be used to identify bugs or missing features. How-to discussions should be delegated to the discussion forum on [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout).
