### ISSUE TITLE
"row wrap" issue in Safari 10.1, 9.1

### ISSUE THREAD

**Issue by gbrath** [angular/flex-layout#660]
#### Bug:
flex-basis shouldn't be set as 100%, should follow the value in fxFlex or max-width.

#### What is the Expected behavior?
 Wrap should work as earlier before "row wrap" incorporation instead of fxLayout="row" fxLayoutWrap?

#### What is Current behavior?
 It wraps child irrespective of child width if "row wrap" is set on the parent in below mentioned platform?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/core": "5.2.8"
"@angular/flex-layout": "5.0.0-beta.13"
"@angular/material": "5.2.4"
OS:Mac OSx,
Browser: Safari9.1, 10.1

For reference: 
flex-basis is being set 100% irrsepective of max-width on element which might be causing the issue.
eg.
fxFlex="55"
was tunring into 
earlier:
flex: 1 1 55%;
box-sizing: border-box;
display: flex;
max-width: 55%;

now
flex: 1 1 100%;
box-sizing: border-box;
display: flex;
max-width: 55%;

**Comment by CaerusKaru** [comment]
Can you define “easier”? Also, please provide a minimal reproduction that we can investigate and track.

**Comment by gbrath** [comment]
@CaerusKaru  By earlier I meant not current updated safari version,  Kindly ignore "earlier" in title.
 Here is a demo to reproduce:
https://angular-flex-layout-seed-qdgtas.stackblitz.io/

**Comment by CaerusKaru** [comment]
Please add a link to the source for the StackBlitz as well

**Comment by gbrath** [comment]
Here are the links(updated):
Demo: https://angular-flex-layout-seed-kcyrv1.stackblitz.io
Source for the StackBlitz : https://stackblitz.com/edit/angular-flex-layout-seed-kcyrv1

**Comment by CaerusKaru** [comment]
Ok confirmed, will add a patch to set the flex-basis appropriately.

**Comment by CaerusKaru** [comment]
Should be fixed by #662
