### ISSUE TITLE
Helpers/Utility Directives..

### ISSUE THREAD

**Issue by shivarajnaidu** [angular/flex-layout#675]
#### What is the expected behavior?
Need more directives and helper classes for margin, padding, centring controls ..

#### What is the current behavior?
Now no helper classes available for controlling margin for layout or for positioning..etc..

#### What is the use-case or motivation for changing an existing behavior?
Need some helper classes/directives to control layout positions, margin, padding, offsets.. vertical centering.. container (Like in bootstrap..)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
None

#### Is there anything else we should know?
Please consider implementing these... Will be helpful while using Angular Material With Flex Layouts.. Thank You!

**Comment by CaerusKaru** [comment]
Please see the documentation in the [Wiki](../wiki), you'll find that everything you need has already been implemented.

**Comment by shivarajnaidu** [comment]
Thanks For Immediate Response @CaerusKaru 
But I can't understand which things we can use it as helper classes or directives.. Did you mean ngStyle and ngClass directives ?

**Comment by CaerusKaru** [comment]
`fxLayoutAlign` <- centering/vertical alignment
`fxOffset` <- offset
`fxLayout` <- continaer
`fxLayoutGap` <- margin/padding

**Comment by shivarajnaidu** [comment]
Thank You For Your Kind Response ! @CaerusKaru

**Comment by shivarajnaidu** [comment]
fxLayoutGap - It's for margin or for padding ?
