### ISSUE TITLE
Is flex-layout handset/tablet ready?

### ISSUE THREAD

**Issue by WaterBleu** [angular/flex-layout#679]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
ngStyle.handset.lt-sm="css" or ngStyle.lt-sm and it will know whether it is handset/tablet or web

#### What is the current behavior?
takes no effect

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
Check out the `ORIENTATION_BREAKPOINTS` [here](https://github.com/angular/flex-layout/blob/master/src/lib/core/breakpoints/data/orientation-break-points.ts).

If you're using the nightly build of Flex Layout, you can enable them by providing the following token in your app:

`{provide: ADD_ORIENTATION_BREAKPOINTS, useValue: true}`
