### ISSUE TITLE
Sizes not adjusting properly

### ISSUE THREAD

**Issue by paistipoikka** [angular/flex-layout#68]
Hi,

I am trying to create a layout that is 400px wide for use inside an `<md-dialog>`. 

```html
<form role="form" (ngSubmit)="authorize(loginForm)" novalidate  #loginForm="ngForm">
        <div fxLayout="row"> 
            <h3>Enter Login Credentials</h3>
        </div>
        <div fxLayout="row"> 
            <p class="validation-message" *ngIf="authorisationErrorMessage">{{authorisationErrorMessage}}</p>
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.gt-xs="400px" fxFlex.xs="300px">
                <md-input-container class="fullwidth"> 
                    <input md-input 
                        name="licenceNumber"
                        placeholder="Licence Number" >   
                </md-input-container>
            </div>
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.xs="300px">
                <md-input-container class="fullwidth"> 
                    <input md-input 
                        name="email"
                        placeholder="Email">       
                </md-input-container> 
            </div> 
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.xs="300px">
                <md-input-container class="fullwidth"> 
                    <input md-input 
                        name="plainPassword"
                        placeholder="Password"
                        type="password">     
                </md-input-container>
            </div>  
        </div>
        <div fxLayout="row">
            <div fxFlex="400px" fxFlex.xs="300px">
                <button md-raised-button color="primary" type="submit">Login</button>
            </div>
        </div> 
</form>
```

In this case I am expecting a form that is 400px wide yet when I measure it is only 320px. It appears as if the dimensions for the layout are being ignored. Can this be considered a bug or am I doing something wrong here? 

JT

**Comment by ThomasBurleson** [comment]
@paistipoikka - 

* Please provide a Plunkr demonstrating this issue. Here is a [Material+Flex-Layout Template](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview)
* When use the directives, the default (non-responsive version is always the fallback). so
```html
<div fxFlex="400px" fxFlex.gt-xs="400px" fxFlex.xs="300px">
```
could instead be:
```html
<div fxFlex="400px" fxFlex.xs="300px">
```

**Comment by paistipoikka** [comment]
Try this one:

https://plnkr.co/edit/ea51R3?p=preview

**Comment by paistipoikka** [comment]
@ThomasBurleson 

Also seems that this applies to the height as well which I've added. 

Also I've added fxLayoutAlign and fxAlign. I think there are problems here too.

**Comment by ThomasBurleson** [comment]
This is an issue with mdDialog. Please report on the Material 2 repos with a new [Angular Material 2](http://github.com/angular/material2/issues/new) issue.

![screen shot 2016-12-28 at 7 57 16 am](https://cloud.githubusercontent.com/assets/210413/21523415/a584d1d0-ccd3-11e6-973c-3cb0b32196e3.png)

> Closing as this does not appear to be a Flex-Layout issue.

**Comment by ThomasBurleson** [comment]
@paistipoikka - An important "rule of thumb":

*  If you cannot get Flex-Layout to work with an example, try to manually use CSS flexbox stylings. If that still does not work to achieve your goals, then Flex-Layout is <u>**not**</u> the issue.
*  If hand-crafted CSS resolves the issue, but Flex-Layout does not then we **definitely** have a bug in this repository.

**Comment by paistipoikka** [comment]
@ThomasBurleson Thanks for that. Seems Material 2 has a couple of little CSS problems like this.

**Comment by ThomasBurleson** [comment]
So if you add CSS to the [Plunkr Demo](https://plnkr.co/edit/ea51R3?p=preview)

```css
form > div {  
  min-width:400px;
}
```

it definitely seems to work better.  @crisbeto  - I will check... mostly I worry about regressions. Thx.
