### ISSUE TITLE
Q: Polyfills for older browsers

### ISSUE THREAD

**Issue by thekalinga** [angular/flex-layout#69]
Is it possible to use this in older browsers using polyfills such as [flexibility](https://github.com/jonathantneal/flexibility)?

**Comment by ThomasBurleson** [comment]
@thekalinga - This is interesting. It is easy to add - for example - the `-js-display:flex` styling to the directives. I would still worry about valid layouts in older browsers.

> Flex-Layout is designed for ever-green browsers. See [Browser Support](https://github.com/angular/flex-layout/wiki#browser-support)

**Comment by thekalinga** [comment]
> I would still worry about valid layouts in older browsers.
Do u mean, the polyfill might not work all versions of old browsers?

**Comment by d3viant0ne** [comment]
@thekalinga there is only so much you can do with older browsers. Flex as a technology has a support grid, anything beyond that may or most likely may not work properly.

To your specific question, flex-layout supports and is validated against what the flex-box standard supports. Older browsers not listed under `browser support` have no guarantee of displaying properly by either the standard or this library. 

That leaves you two choices, enforce browser compatibility for your application or don't use flex as a technology. In my experience, using a pollyfill to wedge new technology into older browsers has been a house of cards that becomes difficult / cumbersome to support.

The two options above are really the only viable ways to balance a consistent experience for your users and limit the complexity for the engineers supporting the application.

There comes a point where it's up to the user to properly maintain the software they are accessing the web with and the developer to define the browser support for their application based on the users they are targeting.

As a developer, if your requirements include supporting extremely old versions of IE, using flex as a technology isn't going to be the right choice for your application regardless of additional pollyfills that may exist to make that work.

**Comment by ThomasBurleson** [comment]
"... using a pollyfill to wedge new technology into older browsers has been a house of cards." 👍 

Closing this issue: current focus is on evergreen browsers.
