### ISSUE TITLE
fxLayoutGap and fxFlexOffset don't work together

### ISSUE THREAD

**Issue by mohlendo** [angular/flex-layout#692]
It seems that only you can have either Gap or offset but not both. See reproducer for details:

https://stackblitz.com/edit/angular-material-flex-layout-seed-tqyekw

**Comment by CaerusKaru** [comment]
This is an interesting issue, and I've been punting it for a reason. There are two obvious solutions to the problem:

1) We can have `fxLayoutGap` check for `fxFlexOffset` children, and simply apply addition to get the margin values, then have `fxFlexOffset` be a no-op if it has a `fxLayoutGap` parent
2) We can do the same, but reverse the direction

The only relevant question then becomes: how do we handle different responsive aliases, ie how do we coordinate the activated values? There may be an obvious solution to this too, but until I find it this issue remains in limbo.
