### ISSUE TITLE
...has no exported member 'validateSuffixes'

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [angular/flex-layout#694]
With 5.0.0-beta.14 version of flex-layout I am receiving the following error when importing `validateSuffixes`

ERROR in (FILENAME)... (7,3): error TS2305: Module '(PROJECT_PATH)/node_modules/@angular/flex-layout/flex-layout"'  has no exported member 'validateSuffixes'

**Comment by ThomasBurleson** [comment]
@wheredoesyourmindgo - sounds like you are doing a deep link into an internal package?

**Comment by CaerusKaru** [comment]
`validateSuffixes` was removed from public exposure and is now internal-only. If you want to use it (and you're not on the nightly builds), please use the `DEFAULT_BREAKPOINTS_PROVIDER_FACTORY` instead.

The new BreakPoint API documented [here](https://github.com/angular/flex-layout/wiki/Breakpoints) runs `validateSuffixes` by default.

**Comment by wheredoesyourmindgo** [comment]
Appreciate the clarification. Closing.
