### ISSUE TITLE
Static API, space-around with none alignment is not working 

### ISSUE THREAD

**Issue by Furqanaa** [angular/flex-layout#695]
#### Bug, feature request, or proposal:
space-around with none alignment and column\row layout is not working.

#### What is the expected behavior?
there should be spaces around item1, item2 just like [Demo](https://tburleson-layouts-demos.firebaseapp.com/#/docs).

#### What is the current behavior?
no spaces around items at all.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-7aewww?file=app%2Fapp.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest versions

**Comment by CaerusKaru** [comment]
You need to have your div expand to fill the entire window, otherwise there's no space for the child divs to "flex" to fill.
