### ISSUE TITLE
Feature request - compatibility with rxjs v6

### ISSUE THREAD

**Issue by mkurcius** [angular/flex-layout#696]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
compatibility with rxjs v6

#### What is the current behavior?
not compatible 

#### What is the use-case or motivation for changing an existing behavior?
migration to angular v6 and rxjs v6

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular v6

**Comment by CaerusKaru** [comment]
Duplicate of #693
