### ISSUE TITLE
fxLayoutGap not working with fxLayout fxFlexOrder

### ISSUE THREAD

**Issue by parindholakia** [angular/flex-layout#697]
#### Bug:
fxLayoutGap does not work when fxFlexOrder is given with responsive breakpoints.Initially it is rendered properly. But when the screen is resized,fxLayoutGap does not work.

#### What is the expected behavior?
fxLayoutGap should work when screen is resized.

#### What are the steps to reproduce?
[stackblitz](https://stackblitz.com/edit/angular-flex-layout-seed-xseaux?file=app/test.component.ts)

1. Initial Page rendered.

![image](https://user-images.githubusercontent.com/28738620/38351966-5ce3c3f0-38cf-11e8-9f51-c92c277f95b0.png)

2. After page resize
![image](https://user-images.githubusercontent.com/28738620/38352009-7b879bb0-38cf-11e8-8c46-77d88999d2d6.png)

3. normal mode after resizing.

![image](https://user-images.githubusercontent.com/28738620/38352068-995b98b2-38cf-11e8-86a5-2bd62b6ce228.png)

**Comment by CaerusKaru** [comment]
Related to #606, I have some fixes in mind that we'll try to get in by beta.16

**Comment by m-henderson** [comment]
@CaerusKaru do you need help with this issue? if so, could you give me a starting point?

**Comment by CaerusKaru** [comment]
@m-henderson If you want to pitch in, that'd be great! The starting point most likely involves adding a `MutationObserver` in the `LayoutGapDirective` that watches all immediate children for changes, particularly relating to ordering (essentially re-running the initialization logic).

**Comment by CaerusKaru** [comment]
Let's revisit this once #900 lands. @parindholakia would you be willing to test it out on the new version?

**Comment by CaerusKaru** [comment]
This is half-working after 7.0.0-beta.21. The gap now works after resizes, but only in row mode, not column mode. And now there's a new bug with `fxFlexOrder`, where it doesn't disengage afterwards (which is an easy fix).

**Comment by CaerusKaru** [comment]
Encapsulated the `fxFlexOrder` responsive issues here: https://github.com/angular/flex-layout/pull/918. Will start working on a fix, followed by the layout-gap issues.

**Comment by CaerusKaru** [comment]
I've tested the StackBlitz against the latest nightly build, and confirmed that this issue is fixed. To see for yourself, update all deps to latest, and then install `https://github.com/angular/flex-layout-builds#master-d322ea7`.
