### ISSUE TITLE
ERROR in node_modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts(1,22)

### ISSUE THREAD

**Issue by alvipeo** [angular/flex-layout#702]
Just created a new project with CLI, added Material, etc. Then added flex-layout. Now this:

>>ERROR in node_modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts(1,22): error TS2724: Module '"E:/Documents/repos/UrekiNgx/node_modules/rxjs/Rx"' has no exported member 'Subscribable'. Did you mean 'Subscriber'?

?

**Comment by CaerusKaru** [comment]
What version of RxJS do you have installed?

**Comment by alvipeo** [comment]
"rxjs": "^5.5.8",
    "zone.js": "^0.8.26"

**Comment by CaerusKaru** [comment]
Can you post the repo in question to GitHub?

**Comment by alvipeo** [comment]
https://github.com/alvipeo/flex-layout-not-working

**Comment by CaerusKaru** [comment]
Built locally with no issue. Closing unless there's a case I missed. I build locally, ran `npm i` and `npm i @angular/flex-layout` and then added `FlexLayoutModule` to `app.module.ts`. `ng serve` and `ng build --prod` both work flawlessly except for the warnings about TypeScript 2.8

**Comment by tccyp001** [comment]
saw the same issue...

**Comment by tccyp001** [comment]
looks like if use latest version("github:angular/flex-layout-builds") can see that issue, but if change to ^5.0.0-beta.14, it can build correctly.

**Comment by CaerusKaru** [comment]
That's because the nightly builds use RxJS v6. You can get around that by installing `rxjs@forward-compat`

**Comment by eeyago** [comment]
I am getting `Error: Metadata version mismatch for module D:/stuff/code/mean/projects/swgt-shop/node_modules/@angular/flex-layout/typings/index.d.ts, found version 4, expected 3, resolving symbol AppModule in D:/stuff/code/mean/projects/swgt-shop/src/app/app.module.ts, `  with the 5.0.0-beta.14 build. Any clues?

**Comment by Tyler-V** [comment]
Encountered the same error

**Comment by roneen31** [comment]
Encountered this error, had `^5.0.0-beta.13`,  updated to `^5.0.0-beta.14` and I still face it. 
My rxjs is: "^5.5.6" 
Also tried with `rxjs@forward-compat` and while the `Subscribable` error is gone, I get a wall of warnings just like @Tyler-V says

**Comment by JoannaG33** [comment]
I second @roneen31 . Followed the same steps and get a wall of the same errors as @Tyler-V. More on those here:

https://github.com/angular/material2/issues/10511

I also followed those steps and changed these versions:

 "@angular/cdk": "^5.2.4",
  "@angular/material": "^5.2.4",

Again, no luck. Seems like the only way now to use flex-layout is to upgrade to Angular 6?

**Comment by inthegarage** [comment]
Still happening flex-17 and rxjs 6.2.2 and Angular 6.1.6
Anyone any ideas here?

**Comment by alvipeo** [comment]
I run into similar issues with flex-layout from time to time. so I stopped using it completely.

**Comment by inthegarage** [comment]
@alvipeo seems to be all to do with the latest rxjs 6.3.0 which I had automatically moved onto. Ensure you stick to 6.2.2.

**Comment by Shukarity** [comment]
"@angular/flex-layout": "^6.0.0-beta.17",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",

Still happens

**Comment by inthegarage** [comment]
@Shukarity Note you have ^6.2.2 and not ~6.2.2 or just 6.2.2 you are probably still downloading (and therefore using 6.3.0) please review your package.json

**Comment by Shukarity** [comment]
Did, works
Thanks :)

**Comment by CaerusKaru** [comment]
@inthegarage Please update to beta 18. And see #827 for details

**Comment by inthegarage** [comment]
Thanks @CaerusKaru as that requires (or seems to require TS 2.9) we'll have to take that route a little more carefully. I do get errors if I don't move to 2.9

**Comment by sushobitha** [comment]
> @Shukarity Note you have ^6.2.2 and not ~6.2.2 or just 6.2.2 you are probably still downloading (and therefore using 6.3.0) please review your package.json

Thanks! It worked

**Comment by sushobitha** [comment]
@cici change the flexlayout version to ~6.2.2

**Comment by emontezuma** [comment]
Hello all
I see this ticket is closed, but what is the final solution (if exists)? 
I have the flex-layout version 7, and the issue persists..

**Comment by yunas44** [comment]
> Hello all
> I see this ticket is closed, but what is the final solution (if exists)?
> I have the flex-layout version 7, and the issue persists..

They closed the ticket because they couldn't solve it.

**Comment by Jeklah** [comment]
I am getting this error as well.

"@angular/flex-layout": "^5.0.0-beta.15",
"rxjs": "^6.3.3",
"rxjs-compat": "^6.4.0",
"typescript": "~3.2.2"
