### ISSUE TITLE
validateBasis is not longer exported

### ISSUE THREAD

**Issue by amcdnl** [angular/flex-layout#705]
In 5.0.0-beta.14 the `validateBasis` function is no longer exported. I used it for a split component I built. Can we get it re-exported?

**Comment by CaerusKaru** [comment]
I've put together a PR for this, and I think so long as there's a use case to support, @ThomasBurleson will be ok with it.

For future reference, anything that is located in `utils` is meant to be considered internal. The fact that it was exported previously was a packaging error. That being said, we are open to moving utilities should they prove useful to others.

**Comment by amcdnl** [comment]
@ThomasBurleson - I use this method in my splitter code.

**Comment by CaerusKaru** [comment]
@amcdnl Would it be ok if this were in the 6.x release? It's fine if it's not, but it's easier for us if we can avoid a 5.x branch

**Comment by amcdnl** [comment]
Yup thats fine :)
