### ISSUE TITLE
How do I vertically stretch an element? 

### ISSUE THREAD

**Issue by HNeukermans** [angular/flex-layout#71]
I want my homepage to show a menu on the top and a router outlet underneath.
I want my router outlet to both stretch vertically and horizontally.
How do I do this?

current markup that doens't work:

```html
<div class="flex-container">

  <div fxLayout="row"  
     fxLayout.xs="column"  
     fxLayoutAlign="center center" 
     fxLayoutAlign.xs="start">

    <div class="flex-item" fxFlex="20%" fxFlex.xs="40%"> link 1 </div> 
    <div class="flex-item" fxFlex>link 2      </div> 
    <div class="flex-item" fxFlex="25px"> link3 </div> 
    
  </div>

  <div class="flex-container" fxLayout="row"> 
    <div fxLayout="column">
      <router-outlet></router-outlet>
    </div> 
  </div>      

</div>
```

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.
