### ISSUE TITLE
Feature Request: fxFlex targetParent

### ISSUE THREAD

**Issue by dszidi** [angular/flex-layout#718]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
I would like the ability to apply the flex css rules to the parent element instead of the host element.

#### What is the current behavior?
Currently fxFlex applies inline css to the host element only. 

#### What is the use-case or motivation for changing an existing behavior?
In the case of dynamically created components the wrapping element breaks the layout. It is one layer between the parent's layout directive and the host's flex directive.

For now and the forseeable future dynamically applying directives is not possible. Having an attribute selector (targetParent maybe?) that tells the directive to apply the rules to the parent node instead of the host would solve this problem

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
Been poking around the source code. I noticed in your src/lib/base/base.ts BaseDirective abstract class that the parent node is already an available property. It seems in theory, it would only require a small adjustment to make this a reality. 

I thought I might try this on my local system and submit a PR or fork and provide it locally. Unfortunately it won't build because npm says the grpc-precompiled-binaries don't exist for my platform (this is for the FreeNAS project).

This would be a really useful feature. Please consider implementing this. As always, thanks for the fantastic work you've done here. Have a great day

**Comment by CaerusKaru** [comment]
Try adding the following token to your configuration:

```ts
import {ADD_FLEX_STYLES} from '@angular/flex-layout';

{provide: ADD_FLEX_STYLES, useValue: true}
```

**Comment by dszidi** [comment]
I'm sad to say I tried that and it hasn't made any difference. What is that supposed to do exactly?

**Comment by CaerusKaru** [comment]
The point of the token is to do exactly what you said. The default behavior for `fxFlex` used to be exactly what you wanted: apply `flex-direction` to the parent if it's not already present. This was turned off in 5.0.0-beta.14 and replaced with the configuration token to avoid confusion from new devs as to why these stylings were being applied without `fxLayout`.

The token preserves this behavior, and has been used successfully by others since its deployment. Please check your configuration, and if it doesn't work for you, try to create a minimal reproduction StackBlitz that we can investigate.

**Comment by CaerusKaru** [comment]
Ah, I see. Then this is simply a duplicate of https://github.com/angular/angular/issues/8785. This feature will likely be implemented in a minor version of v6 (or maybe v7). We will not be implementing this workaround in Flex Layout.

A reasonable alternative is to define your component this way:

```html
<page>
	<div fxLayout-stuff>
		<div fxFlex-stuff>
			<mycard>
		</div>
	</div>
</page>
```

**Comment by dszidi** [comment]
Ok so essentially dynamically generated components aren't supported. It might be helpful to add a footnote in the README to let users know. It will probably prevent quite a few of us from wasting time trying to make it work.

**Comment by CaerusKaru** [comment]
I mean it's more of a global Angular issue than something specific to Flex Layout

**Comment by dszidi** [comment]
True. Not trying to cast blame here at all. Hoever at the end of the day, there will probably somebody else that comes along needing this in the future. It might save somebody some headaches

**Comment by CaerusKaru** [comment]
If you want to open a PR to add a notice for this (and the workaround) to the README, I'd be happy to review.
