### ISSUE TITLE
directive something similar to angular1 material layout-padding.

### ISSUE THREAD

**Issue by pranavneeraj** [angular/flex-layout#719]
#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
This is not behavior that we will support in this library because `layout-padding` can easily be substituted by classes or using `ngStyle` (which has responsive aliases in this library).

**Comment by mackelito** [comment]
@pranavneeraj if you want this just add something like this to your styles.scss file

````
.margin-8,
[margin-8] {
  margin: 8px;
}

.margin-16,
[margin-16] {
  margin: 16px;
}

.margin-32,
[margin-32] {
  margin: 32px;
}
