### ISSUE TITLE
fxLayoutGap puts the gap on the wrong side when using rtl

### ISSUE THREAD

**Issue by critchie** [angular/flex-layout#723]
I see a couple of bugs regarding this issue have been closed and it appears the fixes are in 5.0.0-beta.14. But from what I can tell 5.0.0-beta.14 didn't fix this.

Expected behavior is to have the fxLayoutGap margin be placed on the left if rtl.

Current behavior is the margin is on the right when rtl.

[StackBlitz](https://stackblitz.com/edit/angular-flex-layout-rtl)

What am I missing?

**Comment by CaerusKaru** [comment]
Ok this is a weird one, because I can clearly see that in your reproduction this isn't working, but the code has an explicit case to handle this. I'll investigate more starting next week, but good catch!

**Comment by critchie** [comment]
I see you have it marked for v6.0.0-beta.17.

If the solution requires a code change is it possible to make it available to us Angular 5 developers that aren't ready or can't go to Angular 6 just yet?

**Comment by CaerusKaru** [comment]
Sure, I've created a new milestone to back-patch the latest fixes onto the 5.x branch. That should be ready to go next week as well.

**Comment by critchie** [comment]
Thank you.

**Comment by CaerusKaru** [comment]
So for BiDi, we rely on the Angular CDK's Directionality service. It looks like that only checks the top-level (HTML) or body-level (`body`) for the presence of a `dir` attribute. If you want them to expand this, I suggest you file an issue with them. Closing as not an issue.

**Comment by critchie** [comment]
I’m ok with their setup.  I’m able to do what I need through a directive. Thanks for following up on this.
