### ISSUE TITLE
Better Documentation / Reference

### ISSUE THREAD

**Issue by dreamid27** [angular/flex-layout#726]
Hi, before started. thank for your awesome library.  but I need to say this, I'm not too care about how you explain documentation or something about your explain your code to the user, because i'm believed people know what he does.

but the documentation it's really  - really hard to understand and spend more time for search about function user want.

I hope you could create better documentation about this awesome library. 

Thank Grateful .

**Comment by CaerusKaru** [comment]
Duplicate if #569
