### ISSUE TITLE
fxFill no longer working as expected

### ISSUE THREAD

**Issue by jkang027** [angular/flex-layout#728]
#### Bug, feature request, or proposal:
Change to fxFlex (changed from 1e-09px to auto) breaks functionality of fxFill in 5.0.0-beta.14 release.

#### What is the expected behavior?
Element using fxFill to fill height and width to the parent element.
[Expected behavior using 5.0.0-beta.13 (StackBlitz)](https://stackblitz.com/edit/fxfill-test)

#### What is the current behavior?
Element does not fill remaining space of parent element, and when the content exceeds the available height, the child grows further than the max.
[Current behavior using 5.0.0-beta.14 (StackBlitz)](https://stackblitz.com/edit/fxfill-test-suw9ph)

#### What are the steps to reproduce?
Please see [StackOverflow question](https://stackoverflow.com/questions/50120537/fxfill-doesnt-work-as-expected-with-5-0-0-beta-14-update)

#### What is the use-case or motivation for changing an existing behavior?
fxFill no longer works as expected due to change to fxFlex

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.0-beta.14

**Comment by CaerusKaru** [comment]
For the record, the `fxFill` is not the issue at all. If you remove them from your template (the first one shouldn't be necessary regardless), you'll see that it's solely the `flex` property that is causing a bad layout.

I'm looking into this. Ideally we wouldn't revert back to the `1e-9px` hack because it leads to issues of its own (we didn't change it without reason), but this is probably more critical than those issues.

**Comment by CaerusKaru** [comment]
@jkang027 Ok in this case it looks like you just need to shuffle some stuff around, and add `ADD_FLEX_STYLES` to your app.module. I've linked the modified StackBlitz [here](https://stackblitz.com/edit/fxfill-test-46snnz?file=styles.css)

**Comment by tmburnell** [comment]
@CaerusKaru can you explain what the following code is doing?
```javascript
  providers: [{provide: ADD_FLEX_STYLES, useValue: true}],
```

**Comment by CaerusKaru** [comment]
It's telling the `fxFlex` directive that if there is no `flex-direction` set on its immediate parent, the directive should add them.

**Comment by jkang027** [comment]
@CaerusKaru Correct me if I'm wrong and just not getting it, but this only solves half of the issue. It prevents the child component from growing larger than its parent, but it doesn't fill to the height of the parent, if it is smaller, as fxFill should, which is why I was using fxFill on the child component.

See updated [Expected Behavior StackBlitz](https://stackblitz.com/edit/fxfill-test?file=app%2Fsub-header%2Fsub-header.component.html)

[New Behavior StackBlitz w/ ADD_FLEX_STYLES](https://stackblitz.com/edit/fxfill-test-5sb6sc?file=app%2Fsub-header%2Fsub-header.component.html)

**Comment by jkang027** [comment]
@CaerusKaru Can we reopen this issue? The underlying issue with FxFill not adjusting its height/width because of the change to the `flex` property hasn't been solved with the proposed solution.

**Comment by dzonatan** [comment]
I'm having similar problem.
Same code different versions:
5.0.0-beta.13 https://stackblitz.com/edit/fxfill-test-ppeare
5.0.0-beta.14 https://stackblitz.com/edit/fxfill-test-qwfjmn
