### ISSUE TITLE
Alignment not being recognised

### ISSUE THREAD

**Issue by paistipoikka** [angular/flex-layout#73]
The alignment for the first `<div>` inside the row is not being recognised. The second `<div>` inside the container seems to be ok.

```html
<div fxLayout="row" 
       class="flex-container" 
       style="border: 1px solid">
        <div class="flex-item" 
              style="border: 1px solid"
              fxFlex="grow" 
              fxAlign="center center" >
            Authorised Users
        </div>
        <div class="flex-item" 
              style="border: 1px solid"
              fxFlex="25" 
              fxAlign="end center" >
            <button md-button (click)="openSideNav(searchDrawer)">+ Add User</button>
        </div>
    </div>
```

See this plunk

http://plnkr.co/edit/ea51R3?p=preview

**Comment by ThomasBurleson** [comment]
@paistipoikka - Please review our online API documents: https://github.com/angular/flex-layout/wiki/API-Overview

> These are admittedly brief and will be improved.

*  `fxAlign` affects the host element layout in its parent container.
*  pehraps you want `fxLayoutAlign="center center"` on the parent... which would affect all children of that container.

**Comment by ThomasBurleson** [comment]
Closing as not an API issue.

**Comment by chpasha** [comment]
I think the problem here is that directive called fxFlexAlign, not fxAlign as stated in documentation

**Comment by ThomasBurleson** [comment]
Updated - https://github.com/angular/flex-layout/wiki/API-Overview
