### ISSUE TITLE
in 6.0.0_beta.15 fxLayoutWrap="wrap" stops working

### ISSUE THREAD

**Issue by Son-Lam** [angular/flex-layout#732]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
if fxLayoutWrap="wrap" items within the div should wrap.

#### What is the current behavior?
if fxLayoutWrap="wrap" items within the div act as if fxLayoutWrap="nowrap" 

#### What are the steps to reproduce?
just setup some div with fxLayoutWrap="wrap" and resize browser

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
Duplicate of #635
