### ISSUE TITLE
Stable published version is still 5.x

### ISSUE THREAD

**Issue by buu700** [angular/flex-layout#738]
Just in case this slipped through the cracks: to use flex-layout with the latest stable `@angular/core` and friends currently requires installing `@angular/flex-layout@next`.

Is this intentional?

**Comment by CaerusKaru** [comment]
It was our intention to move the 6.x branch to latest with the stable release of Angular v6 and Material v6. Now that both are out, we'll move the tag. This should be taken care of some time this week.

**Comment by darkbasic** [comment]
Any news on this?

**Comment by danwulff** [comment]
@CaerusKaru ^ ?

**Comment by CaerusKaru** [comment]
@danwulff We have to land #729 and #730 before the next version bump, and that should happen this week.

**Comment by danwulff** [comment]
@CaerusKaru it looks like those two PRs got merged. ETA on a release?

**Comment by CaerusKaru** [comment]
Working on it, will close this issue when it's been published.

**Comment by danwulff** [comment]
Thanks!

**Comment by CaerusKaru** [comment]
Stable published version is now 6.0.0-beta.16.
