### ISSUE TITLE
Layout-Wrap Documentation?

### ISSUE THREAD

**Issue by spottedmahn** [angular/flex-layout#740]
#### Bug, feature request, or proposal:
Question: On the [demo site](https://tburleson-layouts-demos.firebaseapp.com/#/docs), there is an example of `Layout-Wrap` but I can't find that on the [API Documentation page](https://github.com/angular/flex-layout/wiki/API-Documentation).

![image](https://user-images.githubusercontent.com/14079228/39958178-74730fd8-55cd-11e8-8836-f226b1a8c175.png)

#### What is the expected behavior?
Documentation on `Layout-Wrap`.

#### What is the current behavior?
Appears to be missing from the API documentation.

#### Is there anything else we should know?
Keep up the good work 👍

**Comment by spottedmahn** [comment]
I think I found it:

![image](https://user-images.githubusercontent.com/14079228/39958307-472d2e94-55cf-11e8-983f-41e69c5eeade.png)

---

I don't see anything on [fxLayout-API](https://github.com/angular/flex-layout/wiki/fxLayout-API) though.  Shouldn't there be something about this there?  (happy to help add it 😀)

**Comment by ThomasBurleson** [comment]
On Jan 15, we removed [fxLayoutWrap as a deprecated API](https://github.com/angular/flex-layout/commit/9f32c7b20b07275e6263ea40af442cb7d4486d02#diff-25d902c24283ab8cfbac54dfa101ad31
); since that functionality is easily exposed as part of fxLayout. 

The [fxLayout wiki docs](https://github.com/angular/flex-layout/wiki/fxLayout-API#fxlayout--wrap) have been updated.

**Comment by spottedmahn** [comment]
Man, that was quick ⚡!  Especially on a Saturday!

Reviewing now... thanks @ThomasBurleson!

**Comment by ThomasBurleson** [comment]
@spottedmahn - Angular devs have `no lives` 😇  and are obsessed with coding.

**Comment by zbagley** [comment]
Any chance we can get the standard API wiki page updated to reflect? Been using flex-layout for a couple years now, and took me 30 minutes to find this thread and find the new way to declare wrap!

tyty
