### ISSUE TITLE
no such file or directory: '...dist\releases\flex-layout\angular-flex-layout.tgz'

### ISSUE THREAD

**Issue by spottedmahn** [angular/flex-layout#741]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
`npm install` on `flex-layout\src\apps\demo-app` should work on fresh clone

#### What is the current behavior?

> npm ERR! enoent ENOENT: no such file or directory, stat 

> 'C:\Users\mdepouw\source\repos\GitHub\spottedmahn\flex-layout\dUsers\mdepouw\source\repos\GitHub\spottedmahn\flex-layout\dist\releases\flex-layout\angular-flex-layout.tgz'npm ERR! enoent This is related to npm not being able to find a file.

#### What are the steps to reproduce?

- Clone Repo
- Navigate to `src\apps\demo-app`
- Peform `npm install`

#### What is the use-case or motivation for changing an existing behavior?
So I can contribute to the demo site

#### Is there anything else we should know?

Is the flex-layout depenendcy correct?  `@angular/flex-layout`

```json
{
  "name": "demo-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
   ...
    "@angular/flex-layout": "file:../../../dist/releases/flex-layout/angular-flex-layout.tgz",
   }
  ...
}
```

**Comment by CaerusKaru** [comment]
The command you need to run to serve the demo app is `npm run demo:serve`. It runs an automated set of tasks that sets up the demo app, because it's not as trivial as `npm i && ng build`, as you can see.
