### ISSUE TITLE
Can't use calc() on fxFlex Expression

### ISSUE THREAD

**Issue by spottedmahn** [angular/flex-layout#743]
#### Bug, feature request, or proposal:
Bug (or Feature request if it is not supposed to work this way)

#### What is the expected behavior?
That I can use `calc()` in a `fxFlex` expression: `[fxFlex.xs]="myCondition ? calc(55% - 3em) : 30"`

#### What is the current behavior?

```html
<div fxFlex="15" class="sec1" [fxFlex.xs]="myCondition ? calc(55% - 3em) : 30">
  first-section
</div>
```

>Template parse errors:
Parser Error: Unexpected token Lexer Error: Invalid exponent at column 26 in expression [myCondition ? calc(55% - 3em) : 30] 

#### What are the steps to reproduce?

[stackblitz.com/edit/angular-flex-layout-expression-flex-calc](https://stackblitz.com/edit/angular-flex-layout-expression-flex-calc?file=app/test.component.ts)

#### What is the use-case or motivation for changing an existing behavior?

Dynamically control `fxFlex` when using [`fxLayoutGap`](https://github.com/angular/flex-layout/wiki/fxLayoutGap-API#using-fxlayoutgap-with-wrap)

**Comment by sarora2073** [comment]
not sure if you can use a ternary operator there..does it work with a getter instead?

e.g. 

get flexValue(): number {
   return  this.myCondition ? calc(55% - 3em) : 30
}

**Comment by spottedmahn** [comment]
Thanks 🙏 @CaerusKaru

>The solution is to wrap it in a string

Just to clarify **"it"**.  You meant the calc function by it.  I wasn't sure what it was... took me a while to figure that out.  I first tried the whole expression and that of course didn't work.

I'm pretty sure you meant: `[fxFlex]="value ? 'calc(50% - 1em)' : 50"` will work.

---

To complete the circuit, if you will, I am able to do this:

```html
<div fxFlex="15" class="sec1" [fxFlex.xs]="myCondition ? 'calc(55% - 3em)' : 30">
  first-section
</div>
```

[stackblitz.com example](https://stackblitz.com/edit/angular-flex-layout-expression-flex-calc-3?file=app%2Ftest.component.ts)
