### ISSUE TITLE
perf: getComputedStyles on directives init

### ISSUE THREAD

**Issue by levgaas** [angular/flex-layout#754]
#### Bug / Perf
If child element dynamically sets a style which is animated (via transitions, for example) and `flex-layout` directive is applied to parent, this child gets animated on init.

```
<div fxLayout="row wrap"
     fxLayoutGap="24px">

     <div *ngFor="let elem of elems"
          [ngStyle]="{ width: '50px', marginTop: '10px', backgroundColor: 'red' }"
          style="transition: all 0.4s linear;">
     </div>
</div>
```

> It has huge impact on performance since, depending on number of children and styles we animate, we have extra `Painting / Rendering` phases

Almost every `flex-layout` directive extends `BaseDirective` which invokes `getComputedStyles` on init. To get `display` style.

https://github.com/angular/flex-layout/blob/086d038c713f2aff72dbf8a316a26a23b1ee138f/src/lib/core/style-utils/style-utils.ts#L90

#### Before I start explaining here are test examples:

I went rogue and tested it for 5000 elements on the page.

1) Styles are not animated. i.e. without transition

    ![screen shot 2018-05-25 at 3 41 59 pm](https://user-images.githubusercontent.com/10091564/40544832-3c30d60e-6032-11e8-93ec-dadc5cbd1ede.png)

2) The same test when properties that I set dynamically are animated. Let's assume I animate `bad props` such as width, height, background-color, margins, colors. Etc:

    ![screen shot 2018-05-25 at 3 41 07 pm](https://user-images.githubusercontent.com/10091564/40544895-70600ac6-6032-11e8-9175-773bde560704.png)

> As you can see initialization of 5000 children drops my fps almost to 0.

 
#### Let's do the same example but for 50 elements which could be a reasonable number of elements on the page
3) Without animation

   ![screen shot 2018-05-25 at 3 07 24 pm](https://user-images.githubusercontent.com/10091564/40545136-689e74ca-6033-11e8-9335-c2f51eb7f5b2.png)

4) With animation
  ![screen shot 2018-05-25 at 3 08 22 pm](https://user-images.githubusercontent.com/10091564/40545143-6fbb9f08-6033-11e8-985d-eb33fc96fc4e.png)

**Test example** can be found on [StackBlitz](https://stackblitz.com/edit/angular-8h1dcb-mbfkoh)
 

### Some explanations:

When parent which has `flex-layout` directive gets initialized, it calls `getComputedStyles` in `ngOnInit` hook which forces browser to compute styles for each child and therefore inits initial state for animation.

Our child's `Lifecycle hooks` haven't been called yet. But when they eventually get called and bindings are set, we get 2nd state of animation.

Without `getComputedStyle` we don't force browser to set initial state for animation.
Thus, no animation is performed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3, 5.2.4
Flex-Layout 6.0.0-beta.15, 5.0.0-beta.14
Chrome 66

cc. @ThomasBurleson @CaerusKaru @AdamPlumer

**Comment by CaerusKaru** [comment]
Personally, I would love to be able to ditch `getComputedStyle`, due the aforementioned performance hits, and also because we currently don't have an implementation for it on SSR. However, we currently need it to detect if flex stylings have been set on parent containers to avoid overwriting them with inline styles. If you have a proposed alternative, I would love to hear it.

**Comment by levgaas** [comment]
Could you please provide **.spec** or test example on StackBlitz with use cases which are broken by that line?

I have bunch of ideas. But I want to give them a shot before giving them a light

**Comment by CaerusKaru** [comment]
* flex directive with static features should CSS stylesheet and not inject flex-direction on parent FAILED
* grid gap directive with responsive features should add gap styles for a parent FAILED
* grid gap directive with static features should add gap styles for a parent FAILED
* grid gap directive with static features should add dynamic gap styles FAILED
* grid gap directive with static features should add inline grid css style FAILED
* layout-gap directive with static features should adjust gaps based on layout-wrap presence FAILED
* layout-gap directive with static features should recognize hidden elements when applying gaps FAILED
* styler testing display styles should find `display` from component styles FAILED
* styler testing display styles should find `display` from html style element FAILED
* show directive without `responsive` features should use "block" display style when not explicitly defined FAILED
* flex-offset directive with static features should CSS stylesheet and not inject flex-direction on parent FAILED
* hide directive without `responsive` features should use "block" display style when not explicitly defined FAILED
* hide directive with responsive features should restore proper display mode when not hiding FAILED

**Comment by CaerusKaru** [comment]
It's been a few months, so I'm going to close this. We are always open to performance enhancements for the library, and if necessary we can always reopen this.
