### ISSUE TITLE
v6 beta still with rxjx 5.5?

### ISSUE THREAD

**Issue by RichardC64** [angular/flex-layout#755]
Apparently, v6 (beta) is still using rxjs 5.5. All v6.x from @angular use v6.0.

Am I wrong?

**Comment by andresbm05** [comment]
Yes you are wrong, v6 beta uses rxjs6, make sure you have 6.0.0-beta.15 installed, there was a mistake naming a previous versión so a v6 beta was not using rxjs6, to make sure you have this one installed run `npm i --sabe @angular/flex-layout@6.0.0-beta.15`

**Comment by RichardC64** [comment]
You're right. Thank's for your answer.

**Comment by juristr** [comment]
@RichardC64 please make sure to close the issue if it's solved for you 😉
