### ISSUE TITLE
A comment in master.ts is confusing vscode

### ISSUE THREAD

**Issue by mottykohn** [angular/flex-layout#756]
#### Bug, feature request, or proposal:
Not sure

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/17966568/40749830-4b901a10-6433-11e8-9683-e406732bf0f3.png)

#### What are the steps to reproduce?
Just hover over FlexLayoutModule in VS code

#### What is the use-case or motivation for changing an existing behavior?
Misleading help

Probably the comment shout not be a Doc comment just a regular one.
Also it might be a bug VS code that it's taking that comment even though there is a comment subsequently.

**Comment by ThomasBurleson** [comment]
@mottykohn - which version of Flex-Layout have you installed ?

**Comment by mottykohn** [comment]
"@angular/flex-layout": "^6.0.0-beta.15",
"@angular/...": "^6.0.3",
VS Code Version 1.23.1
Architecture x64

**Comment by julianobrasil** [comment]
I can see it over here too. My configs are similar to @mottykohn's.

**Comment by CaerusKaru** [comment]
@mottykohn @julianobrasil I've created a patch for this in #772. Can either of you review this locally to see if it patches this? Neither I nor @ThomasBurleson use VS Code

**Comment by mottykohn** [comment]
@CaerusKaru 
![image](https://user-images.githubusercontent.com/17966568/41233612-fa1d18a8-6d57-11e8-9a0b-2c5eb7c576ab.png)

**Comment by mottykohn** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/17966568/41251195-2a2a9fd2-6d87-11e8-9576-5372ae098f37.png)
