### ISSUE TITLE
Angular Material 6 + FlexLayout 6

### ISSUE THREAD

**Issue by Saliot** [angular/flex-layout#757]
#### Bug, feature request, or proposal:
![image](https://user-images.githubusercontent.com/21266950/40860444-a9ab9800-65e5-11e8-8ff6-e8bb08e99bf8.png)

#### What is the expected behavior?
 I'd like to vertically align the "Last Name" field with the other fields below. 
For the "Last Name" is exceeding the Mat-Card.

Is it possible to achieve this with using AngularLayout property ?
Thanks for your answer.

Below is my code:
![image](https://user-images.githubusercontent.com/21266950/40860520-f2f664d6-65e5-11e8-9f52-da0e8ffc858c.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
![image](https://user-images.githubusercontent.com/21266950/40860632-60e96862-65e6-11e8-9ea6-8e14e1f38a58.png)

**Comment by ThomasBurleson** [comment]
@Saliot 
*  does `<div class="input-row">` have a width 100%?
Please provide a StackBlitz demo that shows this.

**Comment by CaerusKaru** [comment]
It's been over a week since @ThomasBurleson asked for a demo. If one is provided, this can be reopened.
