### ISSUE TITLE
flex-basis alias for "1 1 auto"

### ISSUE THREAD

**Issue by darkbasic** [angular/flex-layout#759]
https://github.com/angular/flex-layout/wiki/fxFlex-API

We have an alias called `fxFlex="grow"` for `1 1 100%`.
Unfortunately it doesn't work as expected in Firefox, in fact Firefox doesn't show anything at all if you use 100% and the container width/height is set to auto.
Also in most use cases we really want `auto` instead of `100%`, because that's what it's used by flex to decide which elements to grow/shrink the most (depending on their base-size). If everything has a base size of 100% this is not going to work well.

Is there any reason why `grow` defaults to `1 1 100%` instead of `1 1 auto`?
Should we change `grow` to `1 1 auto` or maybe add a new alias for it?

**Comment by CaerusKaru** [comment]
I'll discuss this with @ThomasBurleson offline, but we may end up offering a series of configs to override the alias (unless there's no reason for `1 1 100%`, in which case we'll just switch)

**Comment by darkbasic** [comment]
Hi, any news on this?

**Comment by CaerusKaru** [comment]
The news is that right or wrong, it's too finely ingrained in the library for us to change now. However, we've introduced a feature that should allow you to change the algorithm yourself. They're called `StyleBuilder`s, and they allow you to take control of the style generation process. Learn more [here](https://github.com/angular/flex-layout/wiki/Style-Builders#overriding-defaults).
