### ISSUE TITLE
Possible performance issue with double forced reflow

### ISSUE THREAD

**Issue by PierreDuc** [angular/flex-layout#761]
#### Bug, feature request, or proposal:
Bug/performance proposal

#### What is the expected behavior?
Not having two forced reflows on directive initialisation

#### What is the current behaviour?
Two (or more) forced reflows on directive initialisation

#### What are the steps to reproduce?
One example is in the [`fxLayoutDirective`](https://github.com/angular/flex-layout/blob/master/src/lib/flex/layout/layout.ts#L93). You can see the `_updateWithDirection` being called inside the `ngOnChanges` and after that in the `ngOnInit`. 

I might be wrong, but from what I can tell from the profiler this calls the heavy `_updateWithDirection` twice on initalisation. Because you initialise the directive by using the `layout` input, it will always go through the `ngOnChanges` hook anyways. Which makes [this line](https://github.com/angular/flex-layout/blob/master/src/lib/flex/layout/layout.ts#L109) obsolete, or better yet, causing unnecessary recalculations.

I noticed in the profiler that these updates are pretty intensive for the cpu, by causing forced reflows

Other examples:

[FlexAlignDirective._updateWithValue](https://github.com/angular/flex-layout/blob/master/src/lib/flex/flex-align/flex-align.ts#L84)
[FlexOrderDirective._updateWithValue](https://github.com/angular/flex-layout/blob/master/src/lib/flex/flex-order/flex-order.ts#L81)
[FlexDirective._updateStyle](https://github.com/angular/flex-layout/blob/master/src/lib/flex/flex/flex.ts#L128)
[FlexLayoutAlignDirective._updateWithValue](https://github.com/angular/flex-layout/blob/master/src/lib/flex/layout-align/layout-align.ts#L97)

Instead of removing the corresponding lines, you could also check inside the `ngOnChanges` if the `ngOnInit` hook has already ran. And if so, execute the function. This needs to be done for the `LayoutGapDirective` anyways, because it needs to be executed inside the `ngAfterViewInit`.

Another thing that I noticed is the cpu hungry [`_getDisplayStyle`](https://github.com/angular/flex-layout/blob/b8c86be1d167f6e4842cf82f6e3358087dcd0038/src/lib/core/base/base.ts#L100) inside every directive that extends the `BaseDirective`. If the current element does not use the media queries `.xs, .xl ...`, how necessary is this call?

#### What is the use-case or motivation for changing an existing behaviour?
To have a faster flex framework

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
Like I said, my assumptions might be wrong, and there is actually a valid reason for executing it twice.

**Comment by CaerusKaru** [comment]
@PierreDuc Thank you for tracking this down. I've removed the duplicate function calls in #773. As for the calls to `_getDisplayStyle`, can you provide a profiling breakdown of where it's called, and how it's affecting performance? It's called primarily to determine show/hide or if there is a `flex-direction` present on a parent container.

**Comment by PierreDuc** [comment]
@CaerusKaru It's seems like that `_display` is only used in the `ShowHideDirective`, but it's set in the `ngOnInit` of every directive that extends the `BaseDirective`, by calling `_getDisplayStyle`. So perhaps it's better to move this call to just `ShowHideDirective`.

**Comment by CaerusKaru** [comment]
Excellent suggestion, it's been moved in the latest commit on the PR.

**Comment by PierreDuc** [comment]
Nice, just an easy benchmark shows that the flex-layout library is now 75% faster 👍
