### ISSUE TITLE
How to customise FlexDirective with custom breakpoints?

### ISSUE THREAD

**Issue by Mufasa** [angular/flex-layout#767]
I have defined a set of custom breakpoints and have successfully managed to create custom directives for:

- LayoutDirective
- ShowHideDirective

However, I ran into a problem when trying to customise the FlexDirective. A snippet of my customised code looks like this
```import { Directive, ElementRef, Input, Optional, Self, Inject } from '@angular/core';
import { FlexDirective, LayoutDirective, StyleUtils, MediaMonitor } from '@angular/flex-layout';
import { LAYOUT_CONFIG, LayoutConfigOptions } from '@angular/flex-layout/core';

@Directive({
  selector: `
    [fxFlex.mobile],
    [fxFlex.s.tablet],
    [fxFlex.l.tablet],
    [fxFlex.l.tablet.landscape],
    [fxFlex.web]
  `
})
export class CustomFlexDirective extends FlexDirective {
  constructor(monitor: MediaMonitor,
              elRef: ElementRef,
              @Optional() @Self() layout: LayoutDirective,
              styleUtils: StyleUtils,
              @Inject(LAYOUT_CONFIG) layoutConfig: LayoutConfigOptions) {
    super(monitor, elRef, layout, styleUtils, layoutConfig);
  }

  ...
}
```

The problem I get is that the elements LAYOUT_CONFIG and LayoutConfigOptions do not seem to be available anywhere - the import for LAYOUT_CONFIG and LayoutConfigOptions fails. I also did a search across all of @angular/flex-layout in my node_modules folder and could not find these anywhere.

**Comment by CaerusKaru** [comment]
Can you provide either a minimal reproduction repository, or a StackBlitz example?

**Comment by Mufasa** [comment]
Here is a StackBlitz example that I was developing: https://stackblitz.com/edit/flexlayout-eg9xpj

You can see that it currently doesn't compile because it cannot resolve the **LAYOUT_CONFIG** and **LayoutConfigOptions** in the file **src/app/custom-flex.directive.ts**.

**Comment by CaerusKaru** [comment]
You need to upgrade to version 6.0.0-beta.16

**Comment by Mufasa** [comment]
D'oh!

Thanks for pointing that out - it is now working.

**Comment by simeyla** [comment]
The documentation for custom breakpoints really needs to be made clearer with better examples, and explanation on overriding defaults.

The default breakpoints for tablet sized devices are 600 and 960 and the width of an iPad (most of them) is 768. So 600 is way too small and 960 won't get triggered.

So many people will be wanting to add a breakpoint corresponding to that size and the documentation essentially just talks about printing breakpoints.

**Comment by MarcusMorba** [comment]
Totally agree to @simeyla . An example with modifying the default breakpoints and adding additional ones and add e.g. a "lt-xl"-directive would be very useful.

**Comment by ndl7** [comment]
Agreed. Couldn't find a single _complete_ guide or article on how to implement custom breakpoints. Does anyone have a working StackBlitz for Angular 7?
