### ISSUE TITLE
update to firebase@5

### ISSUE THREAD

**Issue by amitport** [angular/flex-layout#768]
# Bug Report

#### What is the expected behavior?
installing flex-layout for dev should work

#### What is the current behavior?
installing flex-layout for development fails on windows with node 10

#### Is there anything else we should know?
Root `package.json` uses `firebase@4` which transitively uses `grpc@1.10.1` which fails to build on win+node 10. `firebase@5` does not have this issue.

See also:
https://github.com/grpc/grpc/issues/15403
https://github.com/angular/material2/issues/10401
https://github.com/angular/material2/issues/11735

**Comment by CaerusKaru** [comment]
Closing based on https://github.com/angular/material2/issues/11735#issuecomment-396028014

**Comment by amitport** [comment]
@CaerusKaru I don't really get it. Angular may not officially support `Node.js@10`, but it's not like it an esoteric end of life product. It's going to be LTS in October. You will need to update from `firebase@4` soon enough and it should be an issue IMO (maybe not a very urgent one).

**Comment by CaerusKaru** [comment]
We will upgrade if and when Material upgrades, since we just use their build system and configuration. When the material issue gets resolved, it will be resolved here. I don't see any point in having multiple issues for the same thing.
