### ISSUE TITLE
flex-attribute dynamically changes, inline styling does not update

### ISSUE THREAD

**Issue by mcwebdev** [angular/flex-layout#77]
I have a radio button form control that changes the [fxLayout] attribute [column, row].
When this attribute changes in the DOM it doesn't update the Inline Styling.

(See attached screens)

![column-example](https://cloud.githubusercontent.com/assets/14930146/21573758/2ab9509a-ce9d-11e6-9d10-acf9a872e350.png)
![row-example](https://cloud.githubusercontent.com/assets/14930146/21573757/2ab83f5c-ce9d-11e6-908f-867421a71bea.png)

**Comment by ThomasBurleson** [comment]
@mcwebdev - submitting issues with a Plunkr is not a valid issue. 

> Imagine how hard it is for us on our end to resolve the issue without a reproducible, debuggable demo.

**Comment by ThomasBurleson** [comment]
You are also use 

```html
<vps-navigator fxLayout="row">
````

which is a static binding. You need to use a dynamic binding:

```html
<vps-navigator [fxLayout]="direction">
````

where direction is property on the parent component.
