### ISSUE TITLE
import DISABLE_DEFAULT_BREAKPOINTS has gone missing since upgrading to v6.0.0-beta.16

### ISSUE THREAD

**Issue by Mufasa** [angular/flex-layout#770]
# Bug Report

#### What is the expected behavior?
`import { DISABLE_DEFAULT_BREAKPOINTS } from '@angular/flex-layout';` should work as documented in your Wiki (https://github.com/angular/flex-layout/wiki/Breakpoints).

#### What is the current behavior?
The import is not found.

#### What are the steps to reproduce?
Here is a StackBlitz example that demonstrates the issue: https://stackblitz.com/edit/flexlayout-eg9xpj

**DISABLE_DEFAULT_BREAKPOINTS** is no longer found as an import in **src/app/app.module.ts**.

#### What is the use-case or motivation for changing an existing behavior?
I want to disable the default breakpoints and have my app only use the custom breakpoints that I have defined.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.2.0
macOS High Sierra v10.13.4
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

#### Is there anything else we should know?
This import used to work in `@angular/flex-layout` `v6.0.0-beta.15`.

**Comment by CaerusKaru** [comment]
https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes and https://github.com/angular/flex-layout/wiki/Configuration

**Comment by Mufasa** [comment]
@CaerusKaru
Apologies - I should have read the change log.

**Comment by jrhite** [comment]
I ran into the same problem. Wiki should still be updated and consistent with the code though.

**Comment by CaerusKaru** [comment]
@jrhite Updated the docs. Apologies for the confusion

**Comment by jrhite** [comment]
Super quick turnaround time, thanks!
