### ISSUE TITLE
Applying flex to parent which is an app has unexpected results

### ISSUE THREAD

**Issue by hags033** [angular/flex-layout#775]
# Bug Report

#### What is the expected behavior?
The app-* tags shouldn't have any styles applied to them

#### What is the current behavior?
Flex applies styles to the parent, including app-* tags as of the latest release

#### What are the steps to reproduce?
Have the first div inside your component.html apply an fxFlex directive.

#### What is the use-case or motivation for changing an existing behavior?
Applying flex to parents are fine, as long as they aren't app-* tags. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
This should be the same across all versions

#### Is there anything else we should know?
This seemed to be changed awhile back to not automatically apply this, and then now re-appeared with the latest release.

**Comment by CaerusKaru** [comment]
See https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes and https://github.com/angular/flex-layout/wiki/Configuration

**Comment by hags033** [comment]
I understand that, but why would it be an all or nothing thing? Applying the flex properties to parents have positive results, but again, they should NOT be applied to <app-*> parents.

**Comment by hags033** [comment]
We have went down the route of applying addFlexToParent: false, but now AOT doesn't build throwing the error: Function calls are not supported in decorators but ‘FlexLayoutModule’ was called.

**Comment by CaerusKaru** [comment]
If you have a separate issue, please open a separate issue, with a minimal reproduction.
