### ISSUE TITLE
Wiki: Link to Browser-Support is broken

### ISSUE THREAD

**Issue by danmana** [angular/flex-layout#777]
The link to Browser Support in the [github Wiki](https://github.com/angular/flex-layout/wiki) is broken (the one in the sidebar on the right):

wrong url: https://github.com/angular/flex-layout/wiki/Browswer-Support
right url: https://github.com/angular/flex-layout/wiki/Browser-Support

**Comment by CaerusKaru** [comment]
Fixed by https://github.com/angular/flex-layout/commit/28bc2ae7476367f111edfce39a05b3f9041501f7

**Comment by danmana** [comment]
Thanks. 
I didn't realise the wiki was part of the repo, or I would have made a pull request :)
