### ISSUE TITLE
fxLayoutGap not applying on mat-form-field elements

### ISSUE THREAD

**Issue by morr0350** [angular/flex-layout#786]
# Bug Report

#### What is the expected behavior?
mat-form-field elements within a form that is styled as a flex layout container should honor the fxLayoutGap directive

#### What is the current behavior?
mat-form-field elements do not apply the gap from the fxLayoutGap directive on the parent form

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-jtwvet

#### What is the use-case or motivation for changing an existing behavior?
Currently, various form layouts in my production application are broken due to frequent use of fxLayoutGap between form fields, labels, and icons

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 6.0.7
Node: 8.11.3
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.7
@angular/cdk                      6.2.0
@angular/cli                      6.0.7
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.2.0
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by CaerusKaru** [comment]
There are quite a few things wrong with your StackBlitz, any number of which could've been deduced by looking at the app setup or the console. First, for Material, you need to include `BrowserAnimationsModule` in your module and install `@angular/animations`. Finally, to get Flex Layout features, you actually need to include `FlexLayoutModule` in your app's imports.
