### ISSUE TITLE
Wiki - Best performance is unavailable

### ISSUE THREAD

**Issue by andrewtw** [angular/flex-layout#790]
# Bug(github wiki) Report

#### What is the expected behavior?
The wiki document should be loaded

#### What is the current behavior?
Unable to load with no permission warning

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

https://github.com/angular/flex-layout/wiki/Best-Performance

![jietu20180629-125035](https://user-images.githubusercontent.com/12085701/42073780-357b0fc6-7b9b-11e8-8371-387b5eba48cc.png)

This is actually not a bug to the project directly, however, it would be great if this article being available again.

**Comment by CaerusKaru** [comment]
Closed by renaming to `Performance Consideration`
