### ISSUE TITLE
Cannot find module '@angular/cdk/bidi'

### ISSUE THREAD

**Issue by panagulis72** [angular/flex-layout#796]
I'm using RxJS 6, Angular 6 and this version of flex-layout: "^6.0.0-beta.16". If I try to compile with Angular-CLI I get the following error: 

> ERROR in node_modules/@angular/flex-layout/flex/typings/flex-offset/flex-offset.d.ts(9,32): error TS2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/flex-layout/flex/typings/layout-gap/layout-gap.d.ts(9,32): error TS2307: Cannot find module '@angular/cdk/bidi'.

I guess it is for Angular Material dependency missing. Is it possibile to use flex-layout withouth Angular Material?

**Comment by CaerusKaru** [comment]
You only need `@angular/cdk`, not `@angular/material`
