### ISSUE TITLE
Support for Angular 6.1.x

### ISSUE THREAD

**Issue by MarcusMorba** [angular/flex-layout#799]
# Feature Request
Support for Angular 6.1.x in general and the latest 6.1.0-rc.0.

#### What is the desired behavior?
Flex-Layout works with Angular 6.1.x

#### What is the use-case or motivation for the desired behavior?
Have a more stable base Angular Environment with 6.1.x for Upgrading a 5.x app.

#### Is there anything else we should know?
Would the latest 6.0.x beta work with Angular 6.1.x beta?

Current given dependencies of the latest 6 beta are:
"dependencies": {
    "@angular/cdk": "6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^6.0.0",
    "systemjs": "0.19.43",
    "tsickle": "^0.27.0",
    "tslib": "^1.8.0",
    "zone.js": "^0.8.18"
  },

**Comment by MarcusMorba** [comment]
Thanks in advance for the feedback!

**Comment by MarcusMorba** [comment]
Should work, made a test on stackblitz.io: https://stackblitz.com/edit/angular-flex-layout-seed-kxsq7d

**Comment by MarcusMorba** [comment]
Tested also successfull with the rc.0 versions.

**Comment by CaerusKaru** [comment]
So there a few blockers on this, one of which I'm working to resolve, but the main one is that the CDK and Material don't support Angular v6.1 yet, and likely won't until the next RC at the earliest. Until that happens, we can't move since we have a peer dependency on them.

**Comment by mackelito** [comment]
@CaerusKaru I thought that one of the ideas was to have this lib as a standalone thing? If it has a dep on Materials then why keep it as a separate project? Perhpas you guys would benefit from working closer together? :)

Any how.. keep up the good work!

**Comment by CaerusKaru** [comment]
@mackelito The library is _mostly_ standalone, but part of the point is to not reuse code as much as possible, and the Angular CDK already implemented some of the library's codebase. It's more of the dependency on the CDK, we don't really have a dependency on Material (except for our own demo app).

There might be some closer collaboration in the future at least in regards to build and release schedules, but nothing is certain for now.

**Comment by fxck** [comment]
Any progress on this since 6.4.1 is out?

**Comment by CaerusKaru** [comment]
@fxck It’s blocked on https://github.com/angular/material2/pull/12182

**Comment by CaerusKaru** [comment]
I’d like to be clear that the library has support for all 6.x versions of Angular, and I’m treating this issue more as the TS 2.9 migration than anything else. Material does not yet support TS 2.9 even though Angular Core does, so we’re waiting until Material jumps before we jump.

**Comment by Springrbua** [comment]
[angular/material2#12182](https://github.com/angular/material2/pull/12182) has been merged and will hopefully land in a version soon.

**Comment by MarcusMorba** [comment]
Isn´t this already achieved? In the latest beta18 "^6.1.6"is even required:
  "version": "6.0.0-beta.18",
  "requiredAngularVersion": ">=6.0.0 <7.0.0",
  "dependencies": {
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/platform-browser": "^6.1.6",
    "core-js": "^2.5.7",
    "rxjs": "^6.3.0",
    "systemjs": "0.19.43",
    "tsickle": "^0.32.1",
    "tslib": "^1.9.3",
    "zone.js": "^0.8.26"
  },

**Comment by CaerusKaru** [comment]
To be honest, I forgot about this issue entirely, but yes it has been resolved with the release of beta 18
