### ISSUE TITLE
fxLayout column has uneven gaps in left column in 2 column display

### ISSUE THREAD

**Issue by codemonkey00** [angular/flex-layout#801]
# Bug Report

#### What is the expected behavior?
There would be no gaps or even gaps in both columns.

#### What is the current behavior?
When 2 columns are displayed the boxes on the left have large gaps between them, but the boxes on the right have no gaps.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  https://next.plnkr.co/edit/DFGju7uMoBEWzpoKGhMf

#### What is the use-case or motivation for changing an existing behavior?
The right example of fxLayout="column" displays with no gaps in the 3 columns, but my 2 columns has gaps in the left column.  Changing the fxLayout="row" displays the same way.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
        "@angular/common": "^5.2.4",
        "@angular/compiler": "^5.2.4",
        "@angular/core": "^5.2.4",
        "@angular/flex-layout": "5.0.0-beta.13",
        "jquery": "3.2.1",
        "@angular/platform-browser": "^5.2.4",
        "@angular/platform-browser-dynamic": "^5.2.4",
        "core-js": "^2.5.3",
        "rxjs": "^5.5.6",
        "zone.js": "^0.8.20"

Same behavior in latest versions of Chrome, FF and Edge

#### Is there anything else we should know?
Make sure to increase the preview window so it displays 2 columns.

**Comment by CaerusKaru** [comment]
The Plunkr no longer works. Can you create a StackBlitz demo for this issue?

**Comment by CaerusKaru** [comment]
Closing since it's been a month since I asked for a demo and none was provided. We can reopen this if a demo is provided.
