### ISSUE TITLE
flex-layout adding styles to parent element

### ISSUE THREAD

**Issue by StickNitro** [angular/flex-layout#804]
# Bug Report

#### What is the expected behavior?

Expected behaviour is that when adding `fxFlex` et al that style attributes are only applied on those elements where flex has been applied. For example:

```
<div [formGroup]="form”>
  <div fxFlex fxLayout="row" fxLayout.xs="column”>
    <div fxFlex="25" fxLayoutAlign="center center" class="logo-wrapper”>
    …
    </div>
  </div>
</div>
```

#### What is the current behavior?

The current behaviour is that flex attributes are getting injected into the parent elements, please see below:

**Component Template**
```
<h2>Assessment Center Settings</h2>
<div>
  <div fxFlex fxLayout="row" fxLayout.xs="column">
    XXXX
  </div>
</div>
```

**Rendered HTML**
```
<h2 _ngcontent-c19="">Assessment Center Settings</h2>
<div _ngcontent-c19="" style="flex-direction: row; box-sizing: border-box; display: flex;”> <--- why is this getting added??
  <div _ngcontent-c19="" fxflex="" fxlayout="row" fxlayout.xs="column" ng-reflect-layout="row" ng-reflect-layout-xs="column" ng-reflect-flex="" style="flex-direction: row; box-sizing: border-box; display: flex; flex: 1 1 0%;"> XXXX </div>
</div>
```

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular v6.0.3
@angular/flex-layout: "^6.0.0-beta.16"
Typescript 2.7.2
OS: macOS
Browsers: Chrome and Safari

**Comment by CaerusKaru** [comment]
The current behavior _is_ the expected behavior, but can be overridden using the static config initializer:

`FlexLayoutModule.withConfig({addFlexToParent: false})`

**Comment by rmathi** [comment]
@CaerusKaru  When am setting the config like as u said `FlexLayoutModule.withConfig({addFlexToParent: false})`.
but it doesn't help. and also its not working as expected when AOT compiler ON. Please help.
