### ISSUE TITLE
breakpoint on xl

### ISSUE THREAD

**Issue by maxisam** [angular/flex-layout#805]
https://github.com/angular/flex-layout/blob/32e65209b15e4f9ef93b608511872efe32cf99a6/src/lib/core/breakpoints/data/break-points.ts#L69

shouldn't it be like the below code instead of 1920px

```
{
    alias: 'lt-xl',
    overlapping: true,
    mediaQuery: '(max-width: 1919px)'
  },
```

**Comment by MainaWycliffe** [comment]
Yea, I agree
