### ISSUE TITLE
Flex layout is not aligning full width in tablets

### ISSUE THREAD

**Issue by shankargurutarikere** [angular/flex-layout#810]
This my login page in laptop
![flex-2](https://user-images.githubusercontent.com/31584520/42997547-c38efe2c-8c34-11e8-9a45-c69942d53c99.PNG)

But when it comes to tab size.It is not fitting to full height of the screen.I have tried many css properties still no use.Unable to configure that which property is overriding.

Hers is the tab-size screenshot 
![flex-1](https://user-images.githubusercontent.com/31584520/42997567-d7082ef6-8c34-11e8-85b2-10f40c8e4926.PNG)

This my html code(login-page.component.html)

`<!doctype html>
<html>
<head>
  <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.min.css" />
  <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css" />
  <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js"></script>

</head>
<body>

  

  <div class="ylet_header">
    <p class="ylet_business">My Business</p>
  </div>

  
  <div class="container" fxLayout="row" fxLayout.xs="column" fxLayoutWrap fxLayoutGap="0%">

    <div fxFlex="76%" class="left-sidebar">
      <img id="ylet_img" src="assets\img\ylet_1.jpg">

    </div>

    <div fxFlex="25%" style="background-color:;" id="Login-form">
      <div id="Login-form">

        <p class="login" align="left">Login</p>

        
        
        <label class="ms-Label is-required login-email">Email address</label>

        <div class="ms-TextField ms-TextField--underlined" align="left">
          
          <input class="ms-TextField-field" type="text" id="placeholder_1" placeholder="Enter your email address">
        </div>

        <script type="text/javascript">
          var ToggleElements = document.querySelectorAll(".ms-Toggle");
          for (var i = 0; i < ToggleElements.length; i++) {
            new fabric['Toggle'](ToggleElements[i]);
          }
        </script>
        
        

        <label class="ms-Label is-required login-password">Password</label>

        <div class="ms-TextField ms-TextField--underlined" align="left">
          
          <input class="ms-TextField-field" type="text" value="" placeholder="Enter your secret password">
        </div>

        <script type="text/javascript">
          var ToggleElements = document.querySelectorAll(".ms-Toggle");
          for (var i = 0; i < ToggleElements.length; i++) {
            new fabric['Toggle'](ToggleElements[i]);
          }
        </script>
        
        
        <div class="ms-Toggle">
          <span class="ms-Toggle-description">Remember me</span>
          <input type="checkbox" id="demo-toggle-3" class="ms-Toggle-input" />
          <label for="demo-toggle-3" class="ms-Toggle-field" tabindex="0">
            <span class="ms-Label ms-Label--off">Off</span>
            <span class="ms-Label ms-Label--on">On</span>
          </label>
        </div>

        <script type="text/javascript">
          var ToggleElements = document.querySelectorAll(".ms-Toggle");
          for (var i = 0; i < ToggleElements.length; i++) {
            new fabric['Toggle'](ToggleElements[i]);
          }
        </script>

        
        <br><br>
        <div fxLayoutAlign="space-around">
          <a [routerLink]="['../signup-form']">
            <button class="ms-Button" id="btn-1">
              <span class="ms-Button-label" id="Sign_up_btn">Sign Up</span>

            </button>
          </a>

          <a [routerLink]="['../']">
            <button class="ms-Button ms-Button--primary" align="right">
              <span class="ms-Button-label">Login</span>
            </button>
          </a>
        </div>

        <br><br>

        <div class="forget-sec">
          <a [routerLink]="['../forget-pass']" style="text-decoration:none;">
            <p style="color:#e600e6;font-size:13px;" align="center">Forgot password?</p>
          </a>
          <hr width="100%">

          <p style="" align="center" id="footer-text">Powered By Pvt Ltd</p>
        </div>

      </div>
    </div>

  </div> 

  <router-outlet></router-outlet>

</body>
</html>

`
and the css (login-page.component.css) is like this

`/*************
Login page css
************/
body {
  font-family: Open sans;
}

.login {
  color: #cc00cc;
  font-size: 20px;
  margin-top: 100px;
 
}
#Login-form {
  padding-left: 10px;
  padding-right: 10px;
}

.container {
  flex: 100%;
}

.ylet_header {
  background-color: #990099;
  height: 45px;
  width: 100%;
  position: absolute;
  top: 0;
  left: 0;
}

.ylet_business {
  color: #ffffff;
  font-size: 18px;
  text-align: left;
  text-indent: 5%;
  margin-top: 11px;
}

.left-sidebar {
  width: 100%;
  height: auto;
  top: 0;
  left: 0;
}

  .left-sidebar img {
    min-width: 100%;
    margin-left: -16px;
    background-size: cover;
  }
  .forget-sec {
  /*position:fixed;*/
  bottom: 0;

}
.ms-TextField-field {
  margin-left: -12px !important;
}

@media (max-width: 600px) {
  .left-sidebar {
    display: none;
  }
}
  /*#Login-form {
    margin-top: -290px;
  }
}*/
`

One more issue is that,I want align forget password on the bottom,fixed for every devices.

**Comment by CaerusKaru** [comment]
This looks like an issue with your own responsive breakpoints, since you're not using Flex Layout's responsive engine, just the fallback styles. Closing unless it's shown this is actually a Flex Layout issue
