### ISSUE TITLE
fxLayout.gt-xs setting inside dialog affects non-dialog layout

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/flex-layout#819]
# Bug Report

#### What is the expected behavior?
setting fxLayout should not affect unexpected areas

#### What is the current behavior?
please see [demo](https://stackblitz.com/edit/angular-material-flex-layout-bug)

#### What are the steps to reproduce?
*  [StackBlitz demo](https://stackblitz.com/edit/angular-material-flex-layout-bug)
* Please read steps in the demo

#### What is the use-case or motivation for changing an existing behavior?
It should work properly

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.3
Material: 6.4.5
OS: Windows
TypeScript: whatever StackBlitz uses
Browsers: Chrome, Fireefox, Edge

**Comment by DmitryEfimenko** [comment]
can anyone please help?

**Comment by mackelito** [comment]
It works fine.. https://stackblitz.com/edit/angular-material-flex-layout-bug-txha3g?file=app/random-dialog.component.ts

**Comment by DmitryEfimenko** [comment]
Thanks for the quick reply. So adding `fxShow.gt-sm` for some reason fixed the issue. It will work as a workaround though I would not call it "it works fine" :)

The workaround is unintuitive and it should work without it. The fact that it does not might be pointing on a bigger issue in the core implementation.

**Comment by mackelito** [comment]
'fxShow.gt-sm' is not the reason why it works.. if you remove it, it still works..

I believe the problem was that you applied it fxLayout.gt-xs property to the same element you expected to change.. the property applies to it's child element

**Comment by CaerusKaru** [comment]
@mackelito is correct, so I'm going to close this issue. If there is a deeper issue present, we can reopen it.
