### ISSUE TITLE
Use of fxLayoutAlign with fxLayout="row-reverse" causes the row-reverse to be ignored

### ISSUE THREAD

**Issue by adrian-heath** [angular/flex-layout#82]
After issue #78 was closed I was still getting the same issue with row-reverse not working on my inner container.  Turns out it is because I also have fxLayoutAlign="center center" which I missed from my original plunkr.  I created a new one here showing the problem

https://plnkr.co/edit/hjPV8y?p=preview

![image](https://cloud.githubusercontent.com/assets/13252125/21638623/ed7c44ba-d263-11e6-8db9-2bb7bbe6ab23.png)

Hopefully this will help

**Comment by ThomasBurleson** [comment]
@adrian-heath - we love these types of submissions 👍 . We are investigating...
