### ISSUE TITLE
Is CSS grid making flex layout obsolete ?

### ISSUE THREAD

**Issue by sevenOneHero** [angular/flex-layout#824]
I have several angular 2 universal projects running on flex layout library and now I just tried CSS grid. I think CSS grid can do everything that flex layout can and it is also compatible with other frameworks like Vue and React and plain JS.  Would it be a wise decision to migrate entire codebase to  use CSS grid instead of flexlayout ?

**Comment by CaerusKaru** [comment]
The main detractor for using CSS Grid is its lack of legacy browser support (IE 11 doesn't support the new spec for example). Flex Layout is an excellent fallback for this case, and is in some cases easier to understand than CSS Grid (which has an entire other dimension to navigate, as well as many more CSS properties).

It comes down to personal preference and levels of understanding. CSS Grid is in almost every way a superset of Flex Layout, but with any migration comes the risk of bumps in the road.

Please note that this library contains dedicated support for CSS Grid (see [here](https://github.com/angular/flex-layout/blob/master/guides/Grid.md)) to help manage the transition.
