### ISSUE TITLE
Configurable default value for fxLayoutGap & gdGap

### ISSUE THREAD

**Issue by dnemoga** [angular/flex-layout#825]
# Feature Request

#### What is the desired behavior?
Would be nice to implement configurable default gap for `fxLayoutGap` & `gdGap` directives.

```
import { FX_DEFAULT_GAP } from '@angular/flex-layout/flex';
import { GD_DEFAULT_GAP } from '@angular/flex-layout/grid';

@NgModule({
  providers: [
    { provide: FX_DEFAULT_GAP, useValue: '24px' },
    { provide: GD_DEFAULT_GAP, useValue: '24px' }
  ]
})
```

#### What is the use-case or motivation for the desired behavior?
It makes templates nice and clean + allows you to keep gutter sizes in one place.

**Comment by CaerusKaru** [comment]
We'll try to fold this in once #884 lands. I don't know if introducing a token for every directive makes the most sense, but I'll have to think about it more.

**Comment by CaerusKaru** [comment]
Now that we've introduced `StyleBuilders`, it's pretty seamless to override default styles. An example for how to do this has been added to the Wiki [here](https://github.com/angular/flex-layout/wiki/Style-Builders#overriding-defaults). We won't be providing tokens for each directive because that includes too much clutter in the library, whereas adding a `StyleBuilder` ad hoc is pretty straightforward.

**Comment by sebrojas14** [comment]
I didn't understand

**Comment by bricepepin** [comment]
I had to override the sideEffect function for the default value to work with fxLayoutGap. In case it save time to anyone, here is my implementation : 
```ts
import { Injectable } from '@angular/core';
import { StyleDefinition, LayoutGapStyleBuilder, LayoutGapParent } from '@angular/flex-layout';

@Injectable()
export class DefaultLayoutGapStyleBuilder extends LayoutGapStyleBuilder {
  sideEffect(gapValue: string, _styles: StyleDefinition, parent: LayoutGapParent) {
    super.sideEffect(gapValue || '16px', _styles, parent);
  }
}
```

and then add this to your module : 

```ts
providers: [
  {provide: LayoutGapStyleBuilder, useClass: DefaultLayoutGapStyleBuilder}
]
```
