### ISSUE TITLE
Using Splitter from Issue 266 don`t work with production mode

### ISSUE THREAD

**Issue by sebfischer83** [angular/flex-layout#826]
# Bug Report

#### What is the expected behavior?
The splitter should work also in production mode with AOT compiler.

#### What is the current behavior?
When trying to drag the splitter I got `TypeError: Cannot read property 'activatedValue' of null
`
It seems that in the `SplitAreaDirective` the value here
```
export class SplitAreaDirective {
  constructor(@Optional() @Self() public flex: FlexDirective) {}
}
```
for the FlexDirective is always null.
So in the SplitDirective this will fail
```
 this.areas.forEach((area, i) => {
      // get the cur flex and the % in px
      const flex = (area.flex as FlexDirective);
      const delta = (i === 0) ? dragAmount : -dragAmount;
      const currentValue = flex.activatedValue;
```
the flex is null and area is an object that will only show QS.
#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
When needed I try to get a simple application.

#### What is the use-case or motivation for changing an existing behavior?
Because it should also work with AOT.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.3 Material 6.4.6

**Comment by sebfischer83** [comment]
It works when I remove `@Optional() @Self()` from the constructor but doesn't really know why...

**Comment by CaerusKaru** [comment]
The splitter is not an actively supported feature of this library. The one that we use in the demo-app (which is AOT compiled) is working without issue for me in Chrome and Firefox.

If you can find an issue with the demo-app that is present in a supported browser, we can reopen this issue.
