### ISSUE TITLE
fxShow & fxHide don't work 

### ISSUE THREAD

**Issue by fdambrosio** [angular/flex-layout#83]
I'm using angular 2.1.0 and flex-layout Alpha, we can't upgrade because we've started using Webpack2/Universal starter kit, and "the universal starter repo is only updated to 2.1.2... Universal breaks with the newer angular updates as the angular team doesn't currently include it in their tests, that's why I've been updating the universal branch slower than the other branches"
https://github.com/qdouble/angular-webpack2-starter/issues/191

So now fx-layout & fx-flex works but fxShow & fxHide don't 

trying 
```
<div [fxShow]="menuOpen"
     fxShow.xs="true"
     style="margin-top:25px;background-color:#d9edf7">
  I should hide and show
</div> 
```
return this error
"Uncaught (in promise): Error: Template parse errors: Can't bind to 'fxShow' since it isn't a known property of 'div'"

**Comment by ThomasBurleson** [comment]
When you see this error, it often means that the Flex-Layout directives are not running and have not been registered with your application [and the angular compiler]. 

> See our our Demo application for examples on integrating FlexLayout within your app:
*  [Root Module Usages](https://github.com/angular/flex-layout/blob/master/src/demo-app/app/demo-app-module.ts#L19)
*  [Sub Modules with Routing](https://github.com/angular/flex-layout/blob/master/src/demo-app/app/docs-layout-responsive/DemosResponsiveLayouts.ts#L43)

> Please upgrade to Beta.2 (coming soon).

----

Closing as not-an-issue.

**Comment by fdambrosio** [comment]
thanks @ThomasBurleson now check better, but I can use in the same page this code 
```
 <div class="containerX">
       <div fxLayout="row" fxLayout.xs="column" fxLayout.sm="column" fxFlex class="coloredContainerX box" >
            <div fxFlex> I'm above on mobile, and to the left on larger devices.   </div>
            <div fxFlex> I'm below on mobile, and to the right on larger devices.  </div>
       </div>
  </div>
```
this works, so I think that Flex-Layout directives are running, now I do more tests

**Comment by lafiza** [comment]
@ThomasBurleson  The link pages are not working -
    Root Module Usages
    Sub Modules with Routing

I have FLexLayoutModule imported. But getting the error ->
Uncaught Error: Template parse errors:
Can't bind to 'fx-layout' since it isn't a known property of 'div'. ("

<div fx-layout="row">

**Comment by ThomasBurleson** [comment]
@lafiza - links above fixed.
Your errors result from not loading the `FlexLayoutModule` into your own module.
