### ISSUE TITLE
wiki: fxLayoutAlign default cross-axis is align-items: stretch; align-content: stretch;

### ISSUE THREAD

**Issue by aleixsuau** [angular/flex-layout#834]
# Proposal

#### What is the summary of the proposal?
Modify the docs https://github.com/angular/flex-layout/wiki/fxLayoutAlign-API regarding the default cross-axis value.

#### What is the proposal?
The docs say that the default cross-axis value is "align-items: flex-start; align-content: flex-start" but in the browser, when fxLayoutAlign doesn't have second parameter, the default cross-axis value is align-items: stretch; align-content: stretch;

![captura de pantalla 2018-09-06 a las 10 49 28](https://user-images.githubusercontent.com/25689432/45146147-90729400-b1c2-11e8-839b-28bec5dde17e.png)

Thanks

**Comment by CaerusKaru** [comment]
Finally got around to fixing this, thanks for catching it!
