### ISSUE TITLE
How to set indent fxFlexOffset = "20" + 25px?

### ISSUE THREAD

**Issue by 4val0v** [angular/flex-layout#836]
My code [stackblitz](https://stackblitz.com/edit/rest-request-jm9knt?file=src%2Fapp%2Fapp.component.html) _(Line 29)_
![image](https://i.imgur.com/FKEj6D7.png)

Is it possible to set the values ​​in percent + px? `fxFlexOffset="20+25px"`

To get an analog of this: `style="margin-left: calc(20% + 25px)"`

**Comment by CaerusKaru** [comment]
You would have to do `fxFlexOffset="calc(20% + 25px)"`, but otherwise I see no issue. If that doesn't work, we can reopen this issue.
