### ISSUE TITLE
Typescript API ?

### ISSUE THREAD

**Issue by maxime1992** [angular/flex-layout#84]
Thanks for this library it is very handy :)

I was wondering if there's a Typescript API so we can subscribe to screen changes ?

For example with angular-material : 
I want to have a sidenav in `over` mode on mobile and `side` mode on tablet and desktop.

Can I do that with this lib or not ?

Thanks for any help

**Comment by ThomasBurleson** [comment]
Yes you can. Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)

**Comment by Splaktar** [comment]
@maxime1992 I think that you meant angular-material2. Since you just mentioned angular-material, Thomas pointed you to that project's forum instead of the [angular-material2 forum](https://groups.google.com/forum/#!forum/angular-material2).

**Comment by Splaktar** [comment]
You may also want to take a look at https://github.com/angular/flex-layout/issues/86.

**Comment by maxime1992** [comment]
@Splaktar thank you, this exactly the kind of thing I was looking for !
