### ISSUE TITLE
fxLayoutAlign: Allow to specify align-items value as a third value

### ISSUE THREAD

**Issue by aleixsuau** [angular/flex-layout#842]
# Proposal

#### What is the summary of the proposal?
Allow to specify align-items value as a third value of the fxLayoutAlign directive.

#### What is the proposal?
Flex allows to control the cross-axis layout in two ways: 
- align-content: flex-start | flex-end | center | space-between | space-around | stretch;
  Aligns all the lines as a block, with regard to the flex container.
- align-items: flex-start | flex-end | center | baseline | stretch;
  Aligns the items with regard to the line where they are.

With the actual configuration of fxLayoutAlign, it's not possible to specify cross-axis layouts with different align-content and align-items values (ie: align-content: start, align-items: baseline) since it applies the same value to both align-content and align-items css properties:
![captura de pantalla 2018-09-14 a las 16 38 32](https://user-images.githubusercontent.com/25689432/45556889-a88a8900-b83c-11e8-8740-82dfdd4186ee.png)

With this proposal, we could do it: <div fxLayoutAlign="start space-between baseline"><div>

Furthermore, <div fxLayoutAlign="start space-between"></div> wouldn't be correct since align-items doesn't have the 'space-between' option (https://www.w3.org/TR/css-flexbox-1/#align-items-property).

#### Is there anything else we should know?
Thanks!

**Comment by CaerusKaru** [comment]
I'll have to discuss this offline with @ThomasBurleson, but it should be doable. We have a few other priorities right now that are taking precedence though, so it might be a while before I can open a PR.

**Comment by CaerusKaru** [comment]
While we continue to consider this, the newly-introduced `StyleBuilders` may be your best bet at patching this in the interim. See more details [here](https://github.com/angular/flex-layout/wiki/Style-Builders)

**Comment by aleixsuau** [comment]
Thank you for letting me know @CaerusKaru 👌

**Comment by CaerusKaru** [comment]
I've discussed this with @ThomasBurleson and we both agree that this would serve no utility. If you try and change the flex settings without our directives, changing those attributes as you suggest do not result in an overall layout change.

If you insist that this is important to your app, you can use the StyleBuilder API that I linked to above.
