### ISSUE TITLE
withConfig requires breakpoints with AOT

### ISSUE THREAD

**Issue by gatimus** [angular/flex-layout#846]
# Bug Report

#### What is the expected behavior?
`FlexLayoutModule.withConfig({useColumnBasisZero: false})` as suggested [here](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#600-beta16-2018-06-07) to work with AOT compile

#### What is the current behavior?
produces
> Cannot read property 'alias' of undefined

#### What are the steps to reproduce?
https://github.com/gatimus/flex-layout-demo
`npm i`
`ng serve`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    Angular CLI: 6.2.3
    Node: 8.12.0
    OS: win32 x64
    Angular: 6.1.8
    ... animations, common, compiler, compiler-cli, core, forms
    ... http, language-service, platform-browser
    ... platform-browser-dynamic, router

    Package                           Version
    -----------------------------------------------------------
    @angular-devkit/architect         0.8.3
    @angular-devkit/build-angular     0.8.3
    @angular-devkit/build-optimizer   0.8.3
    @angular-devkit/build-webpack     0.8.3
    @angular-devkit/core              0.8.3
    @angular-devkit/schematics        0.8.3
    @angular/cdk                      6.4.7
    @angular/cli                      6.2.3
    @angular/flex-layout              6.0.0-beta.17
    @ngtools/webpack                  6.2.3
    @schematics/angular               0.8.3
    @schematics/update                0.8.3
    rxjs                              6.2.2
    typescript                        2.9.2
    webpack                           4.20.2

#### Is there anything else we should know?
`FlexLayoutModule.withConfig({ useColumnBasisZero: false }, DEFAULT_BREAKPOINTS)` works

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction. This does not come up in our testing, which uses AOT.

**Comment by CaerusKaru** [comment]
I had no issue running both `ng build --prod` and `ng serve`

**Comment by CaerusKaru** [comment]
I see what you're seeing now. Let me dive into this and see if there's an easy fix.
