### ISSUE TITLE
used fxFlexOffset - Why css assigns (margin-top)

### ISSUE THREAD

**Issue by 4val0v** [angular/flex-layout#847]
# Bug Report
`<div fxLayout="row" fxLayoutGap="15px" fxFlexOffset="calc(10% + 15px)">`
#### What is the expected behavior?
`margin-left:calc(10% + 15px);`

#### What is the current behavior?
`margin-top:calc(10% + 15px);`

#### Steps to reproduce?
*  [Providing a StackBlitz _**(Line: 29)**_](https://stackblitz.com/edit/fxflexoffset-margintop) using latest `npm` 

#### 
**OS:** MacOs High Sierra _(10.13.6 64-bit)_
**Browsers:** Opera 55.0.2994.61 _(Stable)_

_Screenshot:_
![screenshot](https://user-images.githubusercontent.com/11297476/46115752-15b8f980-c201-11e8-86a7-4a89481102ec.png)

**Comment by CaerusKaru** [comment]
This is an excellent catch, and at first glance I can't tell you why this is happening. It has to do with how we detect flow direction for the flexbox, which apparently isn't working in this case. I'll look into this and try go get a patch in

**Comment by 4val0v** [comment]
**thanks**, I'll wait

**Comment by CaerusKaru** [comment]
So it turns out this isn't a bug. When you set `fxLayout="column"`, all children elements that use `fxFlexOffset` apply `margin-top`, because that's the flow-direction. If you set the parent to `fxLayout="row"`, you would get the `margin-left` behavior
