### ISSUE TITLE
Need programmatic notifications of  breakpoints changes

### ISSUE THREAD

**Issue by amcdnl** [angular/flex-layout#85]
## Requirement
In a situation where there is multiple layouts based on screen breakpoints and the contents include components that use dynamic sizing (with boundings to window resize events) do not allow the layout to be re-calculated. Example:

### Desktop
![wide](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/90611ad5-e529-4ec3-825b-93b1cb2667f3/2017-01-04_08-17-04.png)

### Mobile
![mobile](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/61b85c64-9e6a-4e5b-aefb-22ed43a32649/2017-01-04_08-18-36.png)

## Use Case
In [ngx-charts](https://github.com/swimlane/ngx-charts), we have the option to dynamically size the chart based on the container [code reference](https://github.com/swimlane/ngx-charts/blob/master/src/common/base-chart.component.ts#L67-L77). We also listen for window resize events to recalculate the dimensions of the chart [code reference](https://github.com/swimlane/ngx-charts/blob/master/src/common/base-chart.component.ts#L104-L115). However, when a user resizes the screen to switch layout alogs say from `row` to `column` it doesn't resize properly. This is not an issue with a pure css grid system since the css calculations are not fixed widths and pre-calculated before JavaScript is ran.

## Proposal
I'm not sure there is a great way to accomplish this, best I can think of is a custom `(resize)` event on a `fxFlex` directive.

**Comment by splintercode** [comment]
I think the custom event to listen to is the best option. With that you can manually re-trigger the resize of the chart. I would think its the only way to guarantee that the resize event of the chart occurs after the layout lib has done it's calculations.

**Comment by ThomasBurleson** [comment]
@amcdnl - We have a great solution for this. Inject the ** MatchMediaObservable** into your component and subscribe to mediaQuery change activity and then call `bindWindowResizeEvent()` to programmatically recalculate the dimensions.

NOTE: You may need to delay a tick for the style changes to reflow... before your recalculate the dimensions.


> I you provide a Plunkr Demo for your issues, I will add a fix **AND** add it to our online Demo Samples.

**Comment by d3viant0ne** [comment]
I'd personally love to see this in the demo samples. Responsive data visualization ftw :)

**Comment by amcdnl** [comment]
That's really clever! 

Thanks, I wanted to throw out the question as an hypothetical and if it was really an issue then build the case out.

**Comment by d3viant0ne** [comment]
@amcdnl And now you know why I like this project :) Responsive layout as a stream opens up all kinds of cool possibilities in the realm of user experience.

**Comment by ThomasBurleson** [comment]
@amcdnl - can you provide an Angular Plunkr with an easy D3 pie chart one that listens to window resize events? Thx.

**Comment by amcdnl** [comment]
Is `MatchMediaObservable` version published on npm? 

When it injects I get a empty object, I'll make a demo of the bug and the charts for your demo page ;)

**Comment by ThomasBurleson** [comment]
For now, either use `master` or wait for the beta.2 coming on Monday.
