### ISSUE TITLE
fxHide/Show changes behavior of matProgressBar from Angular Material

### ISSUE THREAD

**Issue by agentnico** [angular/flex-layout#852]
# Bug Report

#### What is the expected behavior?
The progress bar is expected to start from 0% width and grow to the given value on page load.
This works fine when we don't use fxHide/Show.

#### What is the current behavior?
When applying fxHide/Show on the progress bar (or siblings by the way), the progress bar shrink from 100% width to the given value on page load.

#### What are the steps to reproduce?
Apply fxShow="true" on a MatProgressBar and reload the page. You can notice the progress bar behaving differently than when the fxShow directive is not applied.

https://stackblitz.com/edit/angular-material-flex-layout-fxhide-matprogressbar-conflict
Note: on stackblitz, you can easily see the issue by changing the color attribute of the progress bar. It triggers a hot reload, the page does not blink and you see the behavior.

The following demo shows:
- first the issue when fxShow is applied on MatProgressBar
- then the normal behavior when fxShow is not applied
- finally the issue when fxShow is applied on a sibling of the MatProgressBar
![2018-10-01_16h22_06](https://user-images.githubusercontent.com/3932348/46294565-59f82100-c596-11e8-889a-e561ef810653.gif)

#### What is the use-case or motivation for changing an existing behavior?
I believe the fxHide/Show directive must not affect the initial behavior of the MatProgressBar.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.9
Angular Material 6.4.7
Angular Flex Layout 6.0.0-beta.18
Chrome 69.0.3497.100

#### Is there anything else we should know?
The issue also appears on the MatProgressBar if the directive fxHide/Show is applied on a sibling.

**Comment by agentnico** [comment]
There is a workaround using ObservableMedia and ngIf but it would be great that the fxHide/Show directive works too.

[https://stackblitz.com/edit/angular-material-flex-layout-fxhide-matprogressbar-workaround](url)

**Comment by mackelito** [comment]
Perhaps you can use the *ngIf ?

**Comment by agentnico** [comment]
Yes *ngIf works with ObservableMedia.
It would still be better to be able to use fxHide/Show directly.

**Comment by agentnico** [comment]
> Perhaps you can use the *ngIf ?

**Comment by mackelito** [comment]
Perhaps the issue is that fxShow/hide is just a css property being set. The animation is still running even though you can't see it. NgIf removes the Dom element and the animation will start from scratch each time it's added

**Comment by agentnico** [comment]
I tried to use [style.display]="media.isActive('lt-md') ? 'block' : 'none'" and this works fine too. This is probably similar to what fxHide/Show does and it doesn't seem to cause any issue.

Also I find it odd that even if the fxShow/Hide directive is not applied on the progress bar but on another element on the page, the issue reproduces too.

I haven't dug into the code of the fxShow/Hide directive but could it be that the directive applies something globally ?

**Comment by adamdport** [comment]
Can someone check if it's related to #724?

**Comment by agentnico** [comment]
Great news! I have tested the latest nightly build and the issue seems to be gone.
I have updated my stackblitz project if anyone wants to have a look:
https://stackblitz.com/edit/angular-material-flex-layout-fxhide-matprogressbar-conflict

Angular 7.0.4
Angular Material 7.0.4
Angular Flex Layout 7.0.0-beta.19-9148e87
Chrome 70.0.3538.102

Thank you for your work!
