### ISSUE TITLE
Flex-layout not working in index.html

### ISSUE THREAD

**Issue by Roman-Simik** [angular/flex-layout#856]
# Bug Report

#### What is the expected behavior?

- Flex layout working in the index.html

#### What is the current behavior?

- Flex layout not working in the index.html

#### What are the steps to reproduce?

-Here is the Stackblitz example  https://stackblitz.com/edit/angular-flex-layout-seed-rqa89e

- Just test it removing an my-app element in the index.html to see the difference.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular 6

#### Is there anything else we should know?

- I just wanna know if this is a bug, or there's reason for that. 

- Why I want this work in the index.html? Because I want to make loading screen and it's not so great making it without flex-layout (ofcourse I could use something different for that like Bootstrap,.. but when Im using flex-layout I dont wanna use also Bootstrap).

**Comment by mackelito** [comment]
This is not a bug but how Angular works..
Stuff outside the app root (in your case <my-app>) is "No go" for angular.. it's just outside the angularverse ;)

**Comment by mackelito** [comment]
Just use plain css/flex if you need to have it in the index.html

**Comment by Roman-Simik** [comment]
Ok, thanks for information.
