### ISSUE TITLE
Flex-layout try to load unexisting url

### ISSUE THREAD

**Issue by Twois** [angular/flex-layout#862]
# Bug Report

flex-layout version: 6.0.0-beta.18

![kep](https://user-images.githubusercontent.com/24283373/46922924-7cffe780-d010-11e8-872a-4690fde5a541.png)

![kep](https://user-images.githubusercontent.com/24283373/46922931-92751180-d010-11e8-8c09-92bffed9b704.png)

#### What is the expected behavior?
Do not try to get en undefined page

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.9
typescritp: 2.9.2
os: windows

**Comment by CaerusKaru** [comment]
This is very likely not a Flex Layout issue. If you really think it is, please provide a demo. Otherwise, this issue will be closed.

**Comment by Twois** [comment]
Yes, you are right, I found the problem just a minute ago. You can close it.
