### ISSUE TITLE
All the design is broken

### ISSUE THREAD

**Issue by osnersanchez** [angular/flex-layout#865]
# Bug Report

So it looked before updating
![image](https://user-images.githubusercontent.com/12916793/47225688-af04a700-d38c-11e8-9145-eb5ffd023cde.png)

And so now with version 7.0.0-beta.19
![image](https://user-images.githubusercontent.com/12916793/47225657-9eecc780-d38c-11e8-8051-1170778f2191.png)

https://stackblitz.com/edit/flex-layout-bug-demostration

It was necessary to update angular dependencies

Previously the application worked correctly with the version @angular/flex-layout@6.0.0-beta.15
When you upgrade to the version ^ 7.0.0-beta.19 everything broke

this is the dependencies of package.json with the version @ angular / flex-layout @ 6.0.0-beta.15
"dependencies": {
    "@angular/animations": "^6.0.2",
    "@angular/cdk": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/flex-layout": "^6.0.0-beta.15",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "@kolkov/ngx-metrika": "^0.3.2",
    "@ngu/carousel": "^1.4.8",
    "angular2-moment": "^1.9.0",
    "angulartics2": "^6.2.0",
    "bootstrap": "^4.1.1",
    "chart.js": "^2.7.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "ng-http-loader": "^2.3.0",
    "ng-intercom": "^6.0.0-beta.1",
    "ng2-odometer": "^1.1.3",
    "ngx-countdown": "^3.0.1",
    "ngx-toastr": "^8.8.0",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.3",
    "@angular/cli": "~6.0.3",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2",
    "@types/google.analytics": "0.0.39",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }

This are the dependencies of package.json with version ^ 7.0.0-beta.19
"dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "@kolkov/ngx-metrika": "^0.3.2",
    "@ngu/carousel": "^1.4.8",
    "angulartics2": "^6.2.0",
    "bootstrap": "^4.1.1",
    "chart.js": "^2.7.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "ng-http-loader": "^2.3.0",
    "ng-intercom": "^6.0.0-beta.1",
    "ng2-odometer": "^1.1.3",
    "ngx-countdown": "^3.1.0",
    "ngx-toastr": "^8.8.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.1",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",
    "@types/google.analytics": "0.0.39",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.4",
    "codelyzer": "~4.4.4",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.3",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~3.1.3"
  }

**Comment by Hack31** [comment]
I have the same problem my project worked well with version 6.0.0-beta.18 of flex-layout, but when I updated everything was out of line

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction repo. We have absolutely no way of knowing, ~~without some power of omniscience~~ without this, what could be wrong with your application.

**Comment by osnersanchez** [comment]
> # Bug Report
> So it looked before updating
> ![image](https://user-images.githubusercontent.com/12916793/47225688-af04a700-d38c-11e8-9145-eb5ffd023cde.png)
> 
> And so now with version 7.0.0-beta.19
> ![image](https://user-images.githubusercontent.com/12916793/47225657-9eecc780-d38c-11e8-8051-1170778f2191.png)
> 
> https://stackblitz.com/edit/flex-layout-bug-demostration
> 
> It was necessary to update angular dependencies
> 
> Previously the application worked correctly with the version @angular/flex-layout@6.0.0-beta.15
> When you upgrade to the version ^ 7.0.0-beta.19 everything broke
> 
> this is the dependencies of package.json with the version @ angular / flex-layout @ 6.0.0-beta.15
> "dependencies": {
> "@angular/animations": "^6.0.2",
> "@angular/cdk": "^6.0.2",
> "@angular/common": "^6.0.2",
> "@angular/compiler": "^6.0.2",
> "@angular/core": "^6.0.2",
> "@angular/flex-layout": "^6.0.0-beta.15",
> "@angular/forms": "^6.0.2",
> "@angular/http": "^6.0.2",
> "@angular/material": "^6.0.2",
> "@angular/platform-browser": "^6.0.2",
> "@angular/platform-browser-dynamic": "^6.0.2",
> "@angular/router": "^6.0.2",
> "@kolkov/ngx-metrika": "^0.3.2",
> "@ngu/carousel": "^1.4.8",
> "angular2-moment": "^1.9.0",
> "angulartics2": "^6.2.0",
> "bootstrap": "^4.1.1",
> "chart.js": "^2.7.2",
> "classlist.js": "^1.1.20150312",
> "core-js": "^2.5.4",
> "font-awesome": "^4.7.0",
> "hammerjs": "^2.0.8",
> "jquery": "^3.3.1",
> "moment": "^2.22.2",
> "ng-http-loader": "^2.3.0",
> "ng-intercom": "^6.0.0-beta.1",
> "ng2-odometer": "^1.1.3",
> "ngx-countdown": "^3.0.1",
> "ngx-toastr": "^8.8.0",
> "rxjs": "^6.1.0",
> "rxjs-compat": "^6.1.0",
> "web-animations-js": "^2.3.1",
> "zone.js": "^0.8.26"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "~0.6.3",
> "@angular/cli": "~6.0.3",
> "@angular/compiler-cli": "^6.0.2",
> "@angular/language-service": "^6.0.2",
> "@types/google.analytics": "0.0.39",
> "@types/jasmine": "~2.8.6",
> "@types/jasminewd2": "~2.0.3",
> "@types/node": "~8.9.4",
> "codelyzer": "~4.2.1",
> "jasmine-core": "~2.99.1",
> "jasmine-spec-reporter": "~4.2.1",
> "karma": "~1.7.1",
> "karma-chrome-launcher": "~2.2.0",
> "karma-coverage-istanbul-reporter": "~1.4.2",
> "karma-jasmine": "~1.1.1",
> "karma-jasmine-html-reporter": "^0.2.2",
> "protractor": "~5.3.0",
> "ts-node": "~5.0.1",
> "tslint": "~5.9.1",
> "typescript": "~2.7.2"
> }
> 
> This are the dependencies of package.json with version ^ 7.0.0-beta.19
> "dependencies": {
> "@angular/animations": "^7.0.0",
> "@angular/cdk": "^7.0.0",
> "@angular/common": "^7.0.0",
> "@angular/compiler": "^7.0.0",
> "@angular/core": "^7.0.0",
> "@angular/flex-layout": "^7.0.0-beta.19",
> "@angular/forms": "^7.0.0",
> "@angular/http": "^7.0.0",
> "@angular/material": "^7.0.0",
> "@angular/platform-browser": "^7.0.0",
> "@angular/platform-browser-dynamic": "^7.0.0",
> "@angular/router": "^7.0.0",
> "@kolkov/ngx-metrika": "^0.3.2",
> "@ngu/carousel": "^1.4.8",
> "angulartics2": "^6.2.0",
> "bootstrap": "^4.1.1",
> "chart.js": "^2.7.2",
> "classlist.js": "^1.1.20150312",
> "core-js": "^2.5.7",
> "font-awesome": "^4.7.0",
> "hammerjs": "^2.0.8",
> "jquery": "^3.3.1",
> "moment": "^2.22.2",
> "ng-http-loader": "^2.3.0",
> "ng-intercom": "^6.0.0-beta.1",
> "ng2-odometer": "^1.1.3",
> "ngx-countdown": "^3.1.0",
> "ngx-toastr": "^8.8.0",
> "rxjs": "^6.3.3",
> "rxjs-compat": "^6.3.3",
> "web-animations-js": "^2.3.1",
> "zone.js": "^0.8.26"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "~0.10.0",
> "@angular/cli": "~7.0.1",
> "@angular/compiler-cli": "^7.0.0",
> "@angular/language-service": "^7.0.0",
> "@types/google.analytics": "0.0.39",
> "@types/jasmine": "~2.8.8",
> "@types/jasminewd2": "~2.0.3",
> "@types/node": "~10.9.4",
> "codelyzer": "~4.4.4",
> "jasmine-core": "~3.2.1",
> "jasmine-spec-reporter": "~4.2.1",
> "karma": "~3.0.0",
> "karma-chrome-launcher": "~2.2.0",
> "karma-coverage-istanbul-reporter": "~2.0.3",
> "karma-jasmine": "~1.1.2",
> "karma-jasmine-html-reporter": "^1.3.1",
> "protractor": "~5.4.0",
> "ts-node": "~7.0.1",
> "tslint": "~5.11.0",
> "typescript": "~3.1.3"
> }

**Comment by osnersanchez** [comment]
this is demostration
https://stackblitz.com/edit/flex-layout-bug-demostration

**Comment by osnersanchez** [comment]
> @osnersanchez 6.0.0-beta.16 has some breaking changes, you have to convert your `FlexLayoutModule` import from `FlexLayoutModule` to `FlexLayoutModule.withConfig({useColumnBasisZero: false})` as documented in [the changelog](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#600-beta16-2018-06-07)

Thanks a lot for the suggestion. I can see a change, but the problem persists
![image](https://user-images.githubusercontent.com/12916793/47240248-cad07300-d3b5-11e8-85d4-851b26fa8c2c.png)

**Comment by CaerusKaru** [comment]
@osnersanchez The demo you provided is not minimal. It would also help to have a separate demo with a version of Flex Layout where it works as intended.

**Comment by osnersanchez** [comment]
Try to reproduce the project with the package.json of the previous version, but for a strange reason in the stackblitz I would throw the same behavior of the packge.json with the most recent version, however in the original project if I have the desired behavior, always and when you do not delete and reinstall the node_module.

I was able to solve the problem by implementing part of the solution suggested by @sylvaindumont . Adding the following configuration:
`FlexLayoutModule.withConfig ({useColumnBasisZero: false, addFlexToParent: false})`

But it gives me a bit of intrigue because I have another project with version 6.0.0-beta.18 that works without problems and without adding that configuration, and I would like to know why that happens?

**Comment by CaerusKaru** [comment]
🤷‍♂️

**Comment by margru** [comment]
> @osnersanchez 6.0.0-beta.16 has some breaking changes, you have to convert your `FlexLayoutModule` import from `FlexLayoutModule` to `FlexLayoutModule.withConfig({useColumnBasisZero: false})` as documented in [the changelog](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#600-beta16-2018-06-07)

This is working only when not using AOT. I would consider it as a bug, not sure whether a new ticket should be created though...

Please, see https://stackblitz.com/edit/angular-flex-layout-seed-mhpfqh. You have to download it, run `npm install`, and `ng server --aot`.  The code is based on #961 as the cause of the issue described there seems to be similar to this one.

You can also check the attached screenshots. The first one is using AOT the second one is not. Using flex-layout 7.0.0-beta.23.

Or, am I doing anything wrong?

![flex_layout_screen_01](https://user-images.githubusercontent.com/1311837/51859845-69b32680-2338-11e9-835c-d2c2d7163f87.png)
![flex_layout_screen_02](https://user-images.githubusercontent.com/1311837/51859846-69b32680-2338-11e9-889e-e1ba641b6fc4.png)

**Comment by kthomas182** [comment]
@margru did you resolve this? If so, what did you end up doing? I'm running into the same issue. It only occurs when I run 

"aot": true,

**Comment by margru** [comment]
@kthomas182 Actually not. I had to use `fxFlex="auto"` instead of just `fxFlex` everywhere as a workaround.
