### ISSUE TITLE
Compilation error when angular update to version 7

### ISSUE THREAD

**Issue by apicito** [angular/flex-layout#867]
**I have package.json:**

`{
  "name": "xxxxx",
  ......
  },

  "private": true,

  "dependencies": {

    "@angular/animations": "^7.0.0",

    "@angular/cdk": "^7.0.0",

    "@angular/common": "^7.0.0",

    "@angular/compiler": "^7.0.0",

    "@angular/core": "^7.0.0",

    "@angular/flex-layout": "^7.0.0-beta.19",

    "@angular/forms": "^7.0.0",

    "@angular/http": "^7.0.0",

    "@angular/material": "^7.0.0",

    "@angular/material-moment-adapter": "^7.0.0",

    "@angular/platform-browser": "^7.0.0",

    "@angular/platform-browser-dynamic": "^7.0.0",

    "@angular/router": "^7.0.0",

    "core-js": "^2.5.4",

    "moment": "^2.22.2",

    "ngx-model": "^6.0.1",

    "promise-mysql": "^3.3.1",

    "rxjs": "^6.3.3",

    "zone.js": "~0.8.26"

  },

  "devDependencies": {

    "@angular-devkit/build-angular": "~0.10.0",

    "@angular/cli": "~7.0.2",

    "@angular/compiler-cli": "^7.0.0",

    "@angular/language-service": "^7.0.0",

    "@types/jasmine": "~2.8.6",

    "@types/jasminewd2": "~2.0.3",

    "@types/node": "~8.9.4",

    "codelyzer": "~4.2.1",

    "jasmine-core": "~2.99.1",

    "jasmine-spec-reporter": "~4.2.1",

    "karma": "^3.0.0",

    "karma-chrome-launcher": "~2.2.0",

    "karma-coverage-istanbul-reporter": "~2.0.0",

    "karma-jasmine": "~1.1.1",

    "karma-jasmine-html-reporter": "^0.2.2",

    "protractor": "~5.4.0",

    "ts-node": "~5.0.1",

    "tslint": "~5.9.1",

    "typescript": "^3.1.3"

  }

}`

**With ng serve get this error:**

`ERROR in ./node_modules/@angular/flex-layout/esm5/flex-layout.es5.js
Module not found: Error: Can't resolve '@angular/flex-layout/core' in 'F:\xxxxxxxx\node_modules\@angular\flex-layout\esm5'

ERROR in ./node_modules/@angular/flex-layout/esm5/flex-layout.es5.js
Module not found: Error: Can't resolve '@angular/flex-layout/extended' in 'F:\xxxxxxxx\node_modules\@angular\flex-layout\esm5'

ERROR in ./node_modules/@angular/flex-layout/esm5/flex-layout.es5.js
Module not found: Error: Can't resolve '@angular/flex-layout/flex' in 'F:\xxxxxxxx\node_modules\@angular\flex-layout\esm5'

ERROR in ./node_modules/@angular/flex-layout/esm5/flex-layout.es5.js
Module not found: Error: Can't resolve '@angular/flex-layout/grid' in 'F:\xxxxxxxx\node_modules\@angular\flex-layout\esm5'`

**This is a bug?**

**Comment by CaerusKaru** [comment]
It's not a bug, and without a minimal reproduction, we cannot investigate.

**Comment by apicito** [comment]
I can not reproduce problem in a new project. I will review what happend in my project.

**Comment by garyascott** [comment]
I am have a similar issue on a brand new project when I run ng serve.

I get this compilation error 
This has only happened recently ("@angular/flex-layout": "^7.0.0-beta.19") as 2 weeks ago I created a project and this error didn't happen("@angular/flex-layout": "^6.0.0-beta.18")

92% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMapERROR in node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(25,15): error TS2416: Property '_registry' in type 'MockMatchMedia' is not assignable to the same property in base type 'MatchMedia'.
  Type 'Map<string, MockMediaQueryList>' is not assignable to type 'Map<string, MediaQueryList>'.
    Type 'MockMediaQueryList' is not assignable to type 'MediaQueryList'.
      Types of property 'removeListener' are incompatible.
        Type '(_: EventListenerOrEventListenerObject) => void' is not assignable to type '(listener: MediaQueryListListener) => void'.
          Types of parameters '_' and 'listener' are incompatible.
            Type 'MediaQueryListListener' is not assignable to type 'EventListenerOrEventListenerObject'.
              Type 'MediaQueryListListener' is not assignable to type 'EventListenerObject'.
                Property 'handleEvent' is missing in type 'MediaQueryListListener'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(82,5): error TS2416: Property 'removeListener' in type 'MockMediaQueryList' is not assignable to the same property in base type 'MediaQueryList'.
  Type '(_: EventListenerOrEventListenerObject) => void' is not assignable to type '(listener: MediaQueryListListener) => void'.
    Types of parameters '_' and 'listener' are incompatible.
      Type 'MediaQueryListListener' is not assignable to type 'EventListenerOrEventListenerObject'.
        Type 'MediaQueryListListener' is not assignable to type 'EventListenerObject'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(83,38): error
TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(83,99): error
TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(84,41): error
TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(84,102): error TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(95,67): error
TS2304: Cannot find name 'MediaQueryListEvent'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(30,5): error TS2416: Property 'removeListener' in type 'ServerMediaQueryList' is not assignable to the same property
in base type 'MediaQueryList'.
  Type '(_: EventListenerOrEventListenerObject) => void' is not assignable to type '(listener: MediaQueryListListener) => void'.
    Types of parameters '_' and 'listener' are incompatible.
      Type 'MediaQueryListListener' is not assignable to type 'EventListenerOrEventListenerObject'.
        Type 'MediaQueryListListener' is not assignable to type 'EventListenerObject'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(31,38): error TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(31,99): error TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(32,41): error TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(32,102): error TS2304: Cannot find name 'MediaQueryListEventMap'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(46,15): error TS2416: Property '_registry' in type 'ServerMatchMedia' is not assignable to the same property in base
type 'MatchMedia'.
  Type 'Map<string, ServerMediaQueryList>' is not assignable to type 'Map<string, MediaQueryList>'.
    Type 'ServerMediaQueryList' is not assignable to type 'MediaQueryList'.
      Types of property 'removeListener' are incompatible.
        Type '(_: EventListenerOrEventListenerObject) => void' is not assignable to type '(listener: MediaQueryListListener) => void'.
          Types of parameters '_' and 'listener' are incompatible.
            Type 'MediaQueryListListener' is not assignable to type 'EventListenerOrEventListenerObject'.
              Type 'MediaQueryListListener' is not assignable to type 'EventListenerObject'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(58,15): error TS2416: Property '_buildMQL' in type 'ServerMatchMedia' is not assignable to the same property in base
type 'MatchMedia'.
  Type '(query: string) => ServerMediaQueryList' is not assignable to type '(query: string) => MediaQueryList'.
    Type 'ServerMediaQueryList' is not assignable to type 'MediaQueryList'.
node_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts(60,67): error TS2304: Cannot find name 'MediaQueryListEvent'.

**Comment by CaerusKaru** [comment]
@garyascott Please make sure you have also upgrade TypeScript to v3.x
