### ISSUE TITLE
Issue when upgrading from .17 to .18 (v6)

### ISSUE THREAD

**Issue by inthegarage** [angular/flex-layout#871]
# Bug Report

#### What is the expected behavior?
Upgrading from 6.beta.17 to 6.beta.18 should not cause --prod compilation errors.

#### What is the current behavior?
The following error output is seen during compilation and appears to be source code related (as in the compiled sources of Flex.
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

(angular command used = ng build --prod --aot)

#### What are the steps to reproduce?
I upgraded a small project and no other changes. I get the errors when set on .18 if I reset this in my package.json to .17 I do NOT get the above errors.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular = 6.1.6
Material = 6.4.1
Windows = 10
TS= 2.7.2
Browser - NA

#### Is there anything else we should know?
Not sure what is causing this, any other "minor" version change has caused no such problems.

**Comment by CaerusKaru** [comment]
You need to upgrade TypeScript to v2.9 to work with beta.18

**Comment by inthegarage** [comment]
@CaerusKaru Many thanks for the reply. We will stay at .17 for the moment.
Please note the dependencies do not mention this:

```
  "peerDependencies": {
    "@angular/cdk": "^6.0.0",
    "@angular/core": ">=6.0.0 <7.0.0",
    "@angular/common": ">=6.0.0 <7.0.0",
    "rxjs": "^6.0.0"
  },
```
And therefore npm i did not mention this.
