### ISSUE TITLE
fxLayoutAlign 'Cross Axis' option is conflicting with Angular Material Tabs collapsing

### ISSUE THREAD

**Issue by wduville** [angular/flex-layout#873]
# Bug Report

#### What is the expected behavior?
`<mat-tab-group>`  should collapse on small screens

#### What is the current behavior?
When fxLayoutAlign Cross Axis is set, Tabs are not collapsing

#### What are the steps to reproduce?
Add a `<mat-tab-group>` under a `<div fxLayoutAlign="space-around start">` and shrink the screen

*  [StackBlitz](https://stackblitz.com/edit/angular-xgtd1r-4fdv1n?file=app%2Ftab-group-align-example.html)

#### What is the use-case or motivation for changing an existing behavior?
Breaking Angular Material Tabs component normal behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6 / 7
Angular Material 7.0.1, 7.0.2
on Firefox, Opera

**Comment by CaerusKaru** [comment]
This isn't an issue with Flex Layout. The cross-axis is actually provided when left out, the default value is set to `stretch`. This is likely an issue with how `mat-tabs` are picking up flex stylings and responding accordingly.
