### ISSUE TITLE
Angular 6.x LTS Version

### ISSUE THREAD

**Issue by MarcusMorba** [angular/flex-layout#874]
# Feature Request
A version which supports the latest Angular 6.x LTS Version.

#### What is the desired behavior?
Be able to use FlexLayout in projects which rely on Angular 6.x LTS.

#### What is the use-case or motivation for the desired behavior?
Especially in enterprise development projects it´s difficult to use always the latest Angular Version as often the governance and policy in bigger companies/institutions is to use a LTS version for projects. Therefore it would be great to have a non beta version which can be used with the latest LTS version. I am also of the opinion that I have read, that every 2nd major Angular release should be a LTS version, not every major release as now mentioned on https://angular.io/guide/releases#schedule

#### Is there anything else we should know?
In our case this may be a major reason not to be able to use flex-layout in the future for the project. Developers have here a more flexible opinion than the stakeholders / managers or the CTO. Especially when a Components Library is in use and a major angular version update has a big impact on several other projects.

Is there any possibility that the latest v7 beta19 and future betas could still work with Angular 6 with minor custom fixes?

**Comment by CaerusKaru** [comment]
It's something we want, obviously, but I don't think we're going to get a commitment from the Angular team on this. They don't view this project as a priority and most likely won't allocate the resources necessary to maintain a LTS version. That being said, it's something I can look into if there's enough interest.

**Comment by MarcusMorba** [comment]
Thanks for the feedback. I´ll meanwhile try to convince my managers, that it´s best to use the "latest" major Angular version. Especially in our case a
the upgrade to v7 is recommended, because of performance and feature improvements. They love the virtual scroll introduced with v7. Hope I can sell this as a reason as also the longer maintenance period.

**Comment by CaerusKaru** [comment]
@MarcusMorba This is something that we're willing to commit to. @ThomasBurleson and I will discuss a regular schedule for applying patches to a 6.x branch and cutting releases.

Ideally this would coincide with exiting beta, but it's unlikely, so we'll proceed with the 6.x branch anyway.

**Comment by CaerusKaru** [comment]
@MarcusMorba Thanks for the feedback, we'll discuss it this week at our meeting and update here if we decide on something.

**Comment by ThomasBurleson** [comment]
Consider the stable nature of Angular 7.x and the upcoming early builds on Angular 8.x. We will not be providing explicit support for Angular 6.x. 
>  We are committed, however, to LTS support for Angular 7 when Angular 8.x is released.
