### ISSUE TITLE
fxShow not working on mat-tab

### ISSUE THREAD

**Issue by besireren** [angular/flex-layout#878]
`<mat-tab  fxShow="false">` or `<mat-tab  fxHide>` not working
versions
 "@angular/flex-layout": "7.0.0-beta.19",
"@angular/material": "7.0.2",

**Comment by IvanBarayev** [comment]
same issue with us too.
when we use fxShow and fxHide attr with mat-tab  it's not affect the current status.

**Comment by IvanBarayev** [comment]
same issue with us too.
when we use fxShow and fxHide attr with mat-tab it's not affect the current status.
current version same with @besireren

**Comment by CaerusKaru** [comment]
Closing as this doesn't follow the issue template.
