### ISSUE TITLE
your search terms include a misspelled item: 'adapative'. This prevents finding this repo under the search term 'adaptive'.

### ISSUE THREAD

**Issue by kimballjohnson** [angular/flex-layout#879]
# Bug Report

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
Thanks for the catch! @jelbourn just fixed it
