### ISSUE TITLE
Merge conflict on license, @angular/flex-layout version 7.0.0-beta.19

### ISSUE THREAD

**Issue by vemuez** [angular/flex-layout#880]
# Bug Report

#### What is the expected behavior?
I'm not tracking anything from node_modules, it's in my .gitignore, so none of this should be shown.

#### What is the current behavior?
Displays merge conflict on license.

#### What are the steps to reproduce?
npm install @angular/flex-layout

#### What is the use-case or motivation for changing an existing behavior?
I did ng build --prod on my angular application which used this, out of curiosity, I clicked on 3rdpartylicenses and found this problem. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0-beta.19

#### Is there anything else we should know?

- I've uninstalled it on my project, reinstalled it. Same thing.
- I've created a new folder  (Has not got git instantiated), and only installed @angular/flex-layout
- Lastly, I npm cache clean --forced, conflict is still shown 

P.S. The conflict isn't related to my repo

![image](https://user-images.githubusercontent.com/9627828/48212390-67fa4800-e373-11e8-983c-155f48646c3a.png)

**Comment by CaerusKaru** [comment]
This library has always, and I mean [always](https://github.com/angular/flex-layout/commits/master/LICENSE), been under the MIT License. I don't know what got screwed up on your end, but it's not an issue with our library.

**Comment by jaysaikia** [comment]
Well, I am facing the same issue. Since, this is always autogenerated, I am not sure where to look to fix this.
