### ISSUE TITLE
Updating to 7.0 totally wrecks my design

### ISSUE THREAD

**Issue by Vingtoft** [angular/flex-layout#882]
# Bug Report
Updating to 7.0 totally destroys design. 
I have followed the instructions, but I'm not sure how to comply with "...and change the MatchMedia interface  to match updated spec".

#### What is the expected behavior?
Same layout as 6.0: 
<img width="1569" alt="screen shot 2018-11-11 at 11 32 23" src="https://user-images.githubusercontent.com/1752080/48311807-a24b2b80-e5a5-11e8-83d0-60eb66298363.png">

#### What is the current behavior?
See image: 
<img width="1573" alt="screen shot 2018-11-11 at 11 33 49" src="https://user-images.githubusercontent.com/1752080/48311816-b2630b00-e5a5-11e8-972e-ac32ca8a90a7.png">

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
Updating to 7.0. My package.json: 
```
{
  "name": "gefion-demo",
  "version": "0.0.0",
  "scripts": {
    "postinstall": "node patch.js && ts-node ./tools/postinstall/patch-ngcli-webpack.ts",
    "ng": "ng",
    "start": "ng serve --open --host 0.0.0.0 --port 8080 --disable-host-check",
    "start-prod": "ng serve --prod --open --host 0.0.0.0 --port 8080 --disable-host-check",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@angular/animations": "^7.0.3",
    "@angular/cdk": "^7.0.3",
    "@angular/common": "^7.0.3",
    "@angular/compiler": "^7.0.3",
    "@angular/core": "^7.0.3",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.0.3",
    "@angular/http": "^7.0.3",
    "@angular/material": "^7.0.3",
    "@angular/platform-browser": "^7.0.3",
    "@angular/platform-browser-dynamic": "^7.0.3",
    "@angular/router": "^7.0.3",
    "@auth0/angular-jwt": "^2.0.0",
    "@ngrx/store": "^7.0.0-beta.0",
    "@types/googlemaps": "^3.30.9",
    "amazon-cognito-identity-js": "^3.0.3",
    "animate.css": "^3.6.1",
    "animsition": "^4.0.2",
    "aws-mqtt": "^0.2.2",
    "aws-sdk": "^2.353.0",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "grunt": "^1.0.3",
    "hamburgers": "^1.1.3",
    "material-design-iconic-font": "^2.2.0",
    "ng2-odometer": "^1.1.3",
    "ng2-password-strength-bar": "^1.2.1",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "sleep": "^5.2.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.5",
    "@angular/cli": "~7.0.5",
    "@angular/compiler-cli": "^7.0.3",
    "@angular/language-service": "^7.0.3",
    "@types/jasmine": "~2.8.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.3",
    "codelyzer": "~4.5.0",
    "fs-extra": "^7.0.0",
    "grunt-cache-bust": "^1.7.0",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.4",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.1",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}

```

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### What is the use-case or motivation for changing an existing behavior?
A very angry client

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See package.json

#### Is there anything else we should know?
I really appreciate this library

**Comment by CaerusKaru** [comment]
Please provide a StackBlitz reproduction of your issue. We cannot simply look at an image and know instantly what the issue is.

**Comment by maku** [comment]
The same effect here...

**Comment by waterskier2007** [comment]
@Vingtoft do you notice this in a particular browser? I am seeing some layout issues in a pre-existing project chrome, but not in firefox

**Comment by Vingtoft** [comment]
I cant say exactly what the problem was, but changing `"rxjs": "^6.2.2"` to `"rxjs": "6.2.2"` seems to fix the issues.

**Comment by CaerusKaru** [comment]
@Vingtoft so can this issue be closed?
