### ISSUE TITLE
docs(core): add documentation on StyleBuilders

### ISSUE THREAD

**Issue by CaerusKaru** [angular/flex-layout#889]

**Comment by CaerusKaru** [comment]
First draft: https://github.com/angular/flex-layout/wiki/Style-Builders

**Comment by julianobrasil** [comment]
Greeeeat idea, guys!! Currently all that is available in the library is enough for my daily usage. But this seems to take it to another level of resilience.

**Comment by ThomasBurleson** [comment]
[Final Draft](https://github.com/angular/flex-layout/wiki/Style-Builders) Ready @CaerusKaru
