### ISSUE TITLE
Cannot find declarations.

### ISSUE THREAD

**Issue by bowenni** [angular/flex-layout#89]
Hi,
I'm having a problem that a generated library (`src/lib/media-query/_module.ngfactory.ts`) can't find declarations for `src/lib/media-query/breakpoints/break-point-registry.d.ts` because `break-point-registry.d.ts` is empty.
This is related to https://github.com/angular/flex-layout/blob/2ecf23338b8c803aba9f749120119b8df2291384/src/lib/media-query/breakpoints/break-point-registry.ts#L7 and TypeScript [`--stripInternal`](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md) compiler option.
Is this intended?
Thank you.

**Comment by ThomasBurleson** [comment]
No in fact that was NOT intended. Thank you for this alert.

**Comment by d3viant0ne** [comment]
Note to me, add ngc to the travis matrix when I fix this to prevent things like this in the future.

**Comment by ThomasBurleson** [comment]
@bowenni - Which version of Flex-Layouts are you using?  The latest builds on `master` are correctly building the [break-point-registry.d.ts](https://github.com/angular/flex-layout-builds/blob/master/media-query/breakpoints/break-point-registry.d.ts)

Closing as invalid issue.

**Comment by amcdnl** [comment]
I'm seeing this `Cannot find name 'MatchMediaObservable'.` when I try to `import { MatchMediaObservable, MediaChange } from '@angular/flex-layout';`

**Comment by ThomasBurleson** [comment]
@amcdnl - The [online Plunkr](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview) uses this:

```
import {
    MediaChange, 
    MatchMedia,
    MatchMediaObservable, 
    BreakPointRegistry
    } from "@angular/flex-layout";
```
without any issues. But... it is using the **flex-layout.umd.js**:

```js
'@angular/flex-layout' : 'https://rawgit.com/angular/flex-layout-builds/master/bundles/flex-layout.umd.js',
```

Are you using WebPack with the un-bundle files?

> I need more information before I can track this down...

**Comment by ThomasBurleson** [comment]
Here is the snippets to the Angular-Cli version:


```js
import {Component, Inject} from '@angular/core';
import {MatchMediaObservable} from '@angular/flex-layout';

@Component({
  selector: 'app-root',
  template: `
    <div fxLayout="row" style="height:300px;" >
      <div  class="left" fxFlex="20"> {{title}}</div>
      <div *ngIf="media.isActive('md')" class="md"></div>
      <div fxFlex style="background-color: saddlebrown"></div>
    </div>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(@Inject(MatchMediaObservable) private media) {}
  title = 'app works!';
}
```

![screen shot 2017-01-05 at 1 17 29 pm](https://cloud.githubusercontent.com/assets/210413/21694154/682f9c26-d349-11e6-8052-f12993fb5d81.png)

**Comment by bowenni** [comment]
@ThomasBurleson Thanks for looking into this.
I'm using the latest version of flex layout.

For my use case, I need to turn the `--stripInternal` compiler option on when building. And it doesn't emit the `.d.ts` then.

```
^0 11:14:34 ~/workspace/flex-layout:tsc --p src/lib/tsconfig.json
^0 11:14:43 ~/workspace/flex-layout:du -h dist/@angular/flex-layout/media-query/breakpoints/break-point-registry.d.ts
4.0K	dist/@angular/flex-layout/media-query/breakpoints/break-point-registry.d.ts
^0 11:14:46 ~/workspace/flex-layout:tsc --stripInternal --p src/lib/tsconfig.json
^0 11:14:51 ~/workspace/flex-layout:du -h dist/@angular/flex-layout/media-query/breakpoints/break-point-registry.d.ts
0	dist/@angular/flex-layout/media-query/breakpoints/break-point-registry.d.ts
```

I was wondering if there are any concerns removing the `@internal` annotation?

**Comment by ThomasBurleson** [comment]
Why do you need to use `--stripInternal == true` ?

**Comment by ThomasBurleson** [comment]
@bowenni - Why are you rebuilding/compiling the FlexLayout source? You should be using only the builds.

> The builds have  the generated files for:
* UMD, 
* CJS, and 
* AOT
