### ISSUE TITLE
fxFlexAlign="start" or fxFlexAlign="end" not working in angular 7

### ISSUE THREAD

**Issue by yantrab** [angular/flex-layout#893]
I simply add code from examples, and it seems that is not working.

https://stackblitz.com/edit/angular-7str8u

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular  7.0.5, material 7.0.4

**Comment by MainaWycliffe** [comment]
Seem to be working fine in your example, once you give a width and height to the parent container. https://stackblitz.com/edit/angular-7str8u

**Comment by CaerusKaru** [comment]
@MainaWycliffe is correct

**Comment by yantrab** [comment]
@MainaWycliffe Thanks.
There is options to set start/end relative to row rather than column? (when the parent container is row, as example above).

**Comment by MainaWycliffe** [comment]
@yantrab I don't get what you mean?
