### ISSUE TITLE
Support rem units

### ISSUE THREAD

**Issue by charsleysa** [angular/flex-layout#898]
# Feature Request

#### What is the desired behavior?
Support `rem` units along with `em` units

#### What is the use-case or motivation for the desired behavior?
`rem` units behave a little differently to `em` units and both should be supported as the code to support them is essentially the same.

#### Is there anything else we should know?
My use of this library and a quick scan of the source code shows me that mostly everything already supports `rem` units with a code change. The only code change that I can see necessary is in the Flex directive, specifically [this line](https://github.com/angular/flex-layout/blob/master/src/lib/flex/flex/flex.ts#L64) needs `String(basis).indexOf('rem') > -1 ||` added to it and [this line](https://github.com/angular/flex-layout/blob/master/src/lib/flex/flex/flex.ts#L169) needs to be changed to `css[min] = isFixed || (isValue && grow) ? basis : null;`
Please note I have only performed quick tests of those code changes against our code base by modifying the lib in the node_modules folder.

**Comment by CaerusKaru** [comment]
I think this would be a great addition. While waiting for the feature in the meantime, feel free to use the new Style Builders API (docs on the Wiki) if you're using the nightly builds.

Would you like to submit a PR for this feature? It would be a great first community contribution. It only requires one small unit test and the change itself.
