### ISSUE TITLE
FxFlexOrder Tab Index

### ISSUE THREAD

**Issue by ryanpconnors** [angular/flex-layout#904]
# Bug Report

#### What is the expected behavior?
`fxFlexOrder` should set the tab index based on the current value.

#### What is the current behavior?
Setting the `fxFlexOrder` for a given element should also set the tab index.

#### What are the steps to reproduce?
[StackBlitz Flex Order Tab Index](https://stackblitz.com/edit/angular-flex-layout-fx-order-tab-index)

#### What is the use-case or motivation for changing an existing behavior?
Accessibility

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
N/A

**Comment by CaerusKaru** [comment]
This goes against the intention behind `flex-order`, as defined in the [spec](https://www.w3.org/TR/css-flexbox-1/#order-accessibility). We will therefore not be adding this feature to the library.

You are, however, at liberty to define your own style generator using the new `StyleBuilder` API (details can be found on the Wiki) to implement this behavior yourself.
