### ISSUE TITLE
Unexpected behaviour of empty fxFlex directive with fxLayout

### ISSUE THREAD

**Issue by krzysztofadamczak** [angular/flex-layout#906]
# Bug Report

#### What is the expected behavior?
Element with empty directive `fxFlex` and `fxLayout` e.g. `<div fxFlex fxLayout></div>` should have basis = `auto`.

#### What is the current behavior?
Element have basis = `1e-09px` e.g. `<div style="flex-direction: row; box-sizing: border-box; display: flex; flex: 1 1 1e-09px;"></div>`;

#### What are the steps to reproduce?
*  [StackBlitz repro](https://stackblitz.com/edit/angular-tbv7am)

#### What is the use-case or motivation for changing an existing behavior?
Empty `fxFlex` directive should have `flex-basis: auto;`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.2
OS: Windows 10
TypeScript 3.1.6
Browser: Chrome, IE 11

#### Is there anything else we should know?
On Edge/Firefox working properly. 
On Chrome/IE11 need to set `fxFlex="auto"` to fix it.

**Comment by CaerusKaru** [comment]
That behavior is expected, and is done to avoid browser quirks for defined behavior. That being said, if you really want to override it, you can with the introduction of `StyleBuilder`s in the next release.

You can read more about them [here](https://github.com/angular/flex-layout/wiki/Style-Builders).
