### ISSUE TITLE
fxFlex angular flex layout not working as expected version 7.0.0-beta.19

### ISSUE THREAD

**Issue by billyjov** [angular/flex-layout#909]
# Bug Report

Flex layout does not work as expected using the latest version `7.0.0-beta.19` and work fine with the version `5.0.0-beta.13`

#### What is the expected behavior?
![flex-bug-expected](https://user-images.githubusercontent.com/18737653/49935152-88687580-fed0-11e8-9de0-1615833b0f7e.png)

#### What is the current behavior?
![flex-bug-current](https://user-images.githubusercontent.com/18737653/49935154-8c949300-fed0-11e8-918e-f293d9f05d26.png)

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  Working version using `5.0.0-beta.13`: https://stackblitz.com/edit/angular-flex-layout-seed-working-flex
* *NON-WORKING VERSION using `7.0.0-beta.19` or `6.x.x`*: https://stackblitz.com/edit/angular-fx-layout-testing

#### What is the use-case or motivation for changing an existing behavior?

The behavior should match the flex layout idea and principle.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: `Windows 10`
Typescript:  `3.1.6`
Angular: `7`
Angular-CLI: `7.1`

#### Is there anything else we should know?
HERE the code snippet

```
<div fxLayout="row wrap" fxLayoutGap="32px" fxLayoutAlign="start start">
  <ng-container *ngFor="let _ of [1,2,3,4,5,6]">
    <p fxFlex="0 1 calc(33.3% - 32px)">Flex</p>
  </ng-container>
</div>

**Comment by billyjov** [comment]
Sorry... solved.

**Comment by ramprakashSeepana** [comment]
How is that working for you? I'm using the same versions still having the issue while compiling.. what is the @angular/flex-layout version that you are using?

**Comment by billyjov** [comment]
@ramprakashSeepana i use the `7.0.0-beta.19` version of `@angular/flex-layout`. Make sure `FlexLayoutModule` amd `LayoutModule` are correctly imported inside your feature module.
