### ISSUE TITLE
fxHide.lt-md (and others) is broken in 7.0.0-beta.20

### ISSUE THREAD

**Issue by cfeltz34** [angular/flex-layout#915]
# Bug Report

#### What is the expected behavior?
When I use "fxHide.lt-md" attribute in a Angular project 7.x the component need to be hidden

#### What is the current behavior?
"fxHide" attribute hide the component
"fxHide.lt-md" attribute not hide the component with Angular 7.x
"fxHide.lt-md" attribute hide the component with Angular 5.4

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-piagbq?file=src%2Fapp%2Fapp.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.1 on Windows + Chrome (Version 70.0.3538.110 (Build officiel))

**Comment by jefbarn** [comment]
Also seeing this with "fxLayoutGap.gt-sm"

**Comment by CaerusKaru** [comment]
@jefbarn Yeah that tracks. I'm hunting down the fix now.

**Comment by CaerusKaru** [comment]
If anyone could test that it works using the nightly builds (`npm i angular/flex-layout`), that would be really helpful.

**Comment by CaerusKaru** [comment]
7.0.0-beta.21 has been released to address this issue

**Comment by cfeltz34** [comment]
Hi,
I have updated my projet with 7.0.0-beta.21 but... same problem :-(
-->
https://stackblitz.com/edit/angular-piagbq?file=src%2Fapp%2Fapp.component.html
[image: image.png]

Le sam. 15 déc. 2018 à 01:48, CaerusKaru <notifications@github.com> a
écrit :7.0.0-beta.21 has been released to address this issue

**Comment by paulstelzer** [comment]
Can confirm that beta.21 is not working. For example this:

```
<div class="app-info-box" fxFlex="50" fxFlex.gt-sm="25">
...
</div>
```

`fxFlex.gt-sm` has no function:

![chrome_2018-12-15_11-50-32](https://user-images.githubusercontent.com/20501666/50042111-a57f7e80-005f-11e9-8b01-37618d146de1.jpg)

**Comment by CaerusKaru** [comment]
Can anyone confirm if this is fixed for the other directives like `fxLayoutGap`? I feel like with the newest release it might just be a `fxHide` issue

**Comment by CaerusKaru** [comment]
I know this is an incredibly urgent issue, but at the moment I'm at a loss. The patch in 7.0.0-beta.21 added a test for this case _explicitly_, which is passing.

I'm still actively working on this, and we'll try to get a patch by next week.

**Comment by cfeltz34** [comment]
It is not only on StackBlitz.
I have exactly the same issues in my computer (New project created with the
CLI)

**Comment by CaerusKaru** [comment]
@cfeltz34 I believe you! It's just so bizarre that our demo app works flawlessly with the same build artifacts.

**Comment by cfeltz34** [comment]
I'm newbie on Angular, but I have some experience on javascript and object
programming.
It's late here, in France,  but I will try to have a look tomorrow to give
you more informations

**Comment by CaerusKaru** [comment]
I tracked it down! And just when I thought I was losing the last remnants of my sanity. The issue with our demo app is that we have an `ObservableMedia` instance running that is doing something to properly register the overlapping breakpoints. Now we just have to make sure the `MediaMarshaller` is doing it too and it should solve the problem :tada:

**Comment by CaerusKaru** [comment]
@cfeltz34 Can you test this in your app? Please install the new version with `npm i angular/flex-layout` (note lack of `@`)

**Comment by CaerusKaru** [comment]
Anecdotally with the StackBlitz provided, installing the latest nightly (enter `https://github.com/angular/flex-layout-builds#master-232fc6e` as the dependency) fixes this issue, so I'm going to unpin this and mark as resolved.

**Comment by paulstelzer** [comment]
@CaerusKaru Can confirm, it's workin in my stackblitz, too :)

**Comment by cfeltz34** [comment]
Great's!
It's work on Stackblitz :-)

But I have some difficulties to test in my platform.
I jave uninstalled "npm uninstall @angular/flex-layout" and installed your
branch "npm i angular/flex-layout" but my project can't find the module.
I have tested with :
 - [ts] Cannot find module 'angular/flex-layout'. [2307]
 - [ts] Cannot find module '@angular/flex-layout'. [2307]

I can wait the next version, it's not  problem for me. But I sorry if I can
test your fix.

Thank !

Christophe Feltz
Ingénieur en développement Informatique
Responsable bénévole des projets :
 - la carte des dons : https://www.lacartedesdons.fr
 - PermaGuildes : https://www.permaguildes.fr/
 - Comment sortir, la carte des randonneurs : https://map.commentsortir.fr/
 - Infor'ma Planète (http://www.informaplanete.org)

Blog of my travels : http://cfeltz.blogspot.com
--
Tél : (+33) 6 60 17 25 11
105 avenue de la Méditerranée
34 970 Lattes (France)


Le dim. 16 déc. 2018 à 09:17, Paul Stelzer <notifications@github.com> a
écrit :

**Comment by xmlking** [comment]
Combine Uses of `fxShow + fxHide` not working for me as stated here

https://github.com/angular/flex-layout/blob/master/docs/documentation/fxShow-API.md

Env: @angular/core : 7.1.3 , angular/flex-layout: ^7.0.0-beta.21
```html
    <div fxHide fxShow.gt-sm>test</div>
```

**Comment by paulstelzer** [comment]
Should fixed with beta.22 - or revert back to beta.19 if you cannot wait until the new beta release

**Comment by Trojaner** [comment]
I had the same issue, I can confirm that this issue is fixed with beta.22.
