### ISSUE TITLE
(demo): FlexLayout Splitter demo not working

### ISSUE THREAD

**Issue by lBilali** [angular/flex-layout#922]
# Bug Report

#### What is the expected behavior?
the splitter should be dragable

#### What is the current behavior?
the splitter is not dragable

#### What are the steps to reproduce?
go to https://tburleson-layouts-demos.firebaseapp.com/#/issues and test `example 266 Using ngxSplit with Flex-Layout:`

#### What is the use-case or motivation for changing an existing behavior?
Fix the split directive example

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Version: 7.0.0-beta.20
tried on Firefox and chrome on Linux 

#### Is there anything else we should know?
Changing FlexDirective with DefaultFlexDirective seems to work.

**Comment by CaerusKaru** [comment]
Nope turns out this is an AOT issue. Investigating further.

**Comment by CaerusKaru** [comment]
Resolved in latest docs. Thanks for reporting!
