### ISSUE TITLE
wrong directive for fxAlign and fxFill 

### ISSUE THREAD

**Issue by chpasha** [angular/flex-layout#93]
Documentation states that the directive is called fxAlign, but it won't work, since the code recognises only fxFlexAlign. Besides that, is it intentional that all element directive names start with fxFlex except for fxFill?

**Comment by ThomasBurleson** [comment]
@chpasha 

* Docs have been updated with `fxFlexFill` and `fxFlexAlign`.
* The directive will support `fxFill` or `fxFlexFill` (pending).
