### ISSUE TITLE
style attribute is not applied anymore when using ngStyle (version 7.x)

### ISSUE THREAD

**Issue by maku** [angular/flex-layout#936]
# Bug Report

#### What is the expected behavior?

In the following div the style attribute should work...

```

<div style="background-color: red; height: 100px; width: 100px;" [ngStyle]="this.divStyle">
  First div
</div>


```
#### What is the current behavior?

When I import FlexLayoutModule with @angular/flex-layout - version 7.x the style attribute does not work as expected.. This means it is ignored and only the settings from ngStyle are used.

When I use version 6.x of @angular/flex-layout the style attribute works as expected

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-cavljx - shows the non working version - updating the angular-flexlayout version to 6 shows the working version

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.1.3, @angular/flex-layout 7.0.0-beta.21

**Comment by CaerusKaru** [comment]
This will be patched by #936. Thanks for catching this!
