### ISSUE TITLE
IntelliJ only sees flex directives when used as inputs

### ISSUE THREAD

**Issue by longwa** [angular/flex-layout#943]
In Beta 19, IntelliJ/WebStorm was happy with:

<div fxLayout fxLayoutAlign="start start">...</div>

<img width="355" alt="screen shot 2018-12-19 at 12 07 09 pm" src="https://user-images.githubusercontent.com/361184/50235966-353a6b00-0387-11e9-9680-d802099904f6.png">

Starting with Beta 20, IntelliJ only seems to know about directives when used in the input form, ex. [fxLayout] and [fxLayoutAlign]. This seems to be true for all flex-layout directives.

<img width="385" alt="screen shot 2018-12-19 at 12 07 45 pm" src="https://user-images.githubusercontent.com/361184/50235949-2e135d00-0387-11e9-8044-f5745d32a9d2.png">

This is using Angular 7.0.7 and IntelliJ 2018.3.2 Build 183.4886.37

I'm able to switch back and forth and see the warning appear and disappear so I know it's not some kind of index issue.

**Comment by longwa** [comment]
It's possible it could be related to this ticket: https://youtrack.jetbrains.com/issue/WEB-32129

However, something definitely changed from 19 -> 20 that caused this to start showing up.

**Comment by CaerusKaru** [comment]
Under the hood we’be changed a lot, but that shouldn’t affect how IntelliJ/WebStorm reads the metadata. This is definitely a bug on their end, but I’ll leave this issue open until it’s resolved.

**Comment by longwa** [comment]
I suppose it could be an IDEA issue, but so far, I haven't seen anything else with the same issue. For example, the material directives are working just fine in the same project.

Maybe there's something invalid in the metadata.json that's causing it to bail out? I noticed that a couple of the directive DO show up.

<img width="559" alt="screen shot 2018-12-19 at 2 19 14 pm" src="https://user-images.githubusercontent.com/361184/50242708-2c529500-0399-11e9-999b-5b46df9141ee.png">

**Comment by CaerusKaru** [comment]
The reason `fxFill` and `fxFlexFill` are still there is because the selector metadata for that directive (it's actually the same directive) is the same as in beta.19. I maintain that this is an IDEA issue, because using the directives still works as expected everywhere else.

**Comment by longwa** [comment]
Ok, playing around with it, it looks like IDEA doesn't like it when the metadata has both `selector` and `inputs` for the same directive.

For example:
![image](https://user-images.githubusercontent.com/361184/50246733-22825f00-03a4-11e9-82b4-0a77e6a5aebb.png)

It seems like if something is listed as `selector`, it shows up with both the `foo` and `[foo]` syntax, whereas, if it's an input, it ONLY shows `[foo]` as a valid option. I checked a few of the material typings and it seemed similar.

I'm not sure exactly how the metadata.json files are generated, but if I manually change them I can get it working properly.

**Comment by longwa** [comment]
Looking at the code changes in 19 vs 20, when you switched away from using `@Directive` explicitly, the additional duplicated `inputs` were added, for ex. in `layout.ts`.

**Comment by CaerusKaru** [comment]
`Directive` is still used explicitly, just not on the base directive.

**Comment by longwa** [comment]
Oh, sorry yes. But you are giving both `selector` and `inputs` now and you weren't before.

If you reserve `inputs` for things that are ONLY inputs, I think it will fix it.

**Comment by CaerusKaru** [comment]
Before, we had `@Input` for everything in the inputs array. I maintain that this is an IDEA bug, because this should be a supported use-case (especially because we're using it).

**Comment by longwa** [comment]
It looks like you were only passing `selector` to the `@Directive` in beta 19 and it worked. Now you are putting all of the selectors into the inputs array and passing that as well. I'm not sure why you need to copy all the selectors into the inputs. When I look at the material package, for instance, I don't see this same use case. The `inputs` seems to be reserved for things that don't support the non-input syntax.

It seems like with `fxLayout` in only the `selector` list, it works fine both ways both in the editor and in the real world. Maybe IDEA should handle it, but would it hurt to remove the duplicated lists?

**Comment by longwa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-204522

**Comment by CaerusKaru** [comment]
Awesome, you rock! Thanks for tracking this, I'm sure it's going to impact quite a few people. Again, I'll keep this open so long as that issue is open so people can get to the right place.

**Comment by longwa** [comment]
No problem, sorry to be so dense on the discussion. I didn't quite understand what all had changed and was just looking at it from the metadata viewpoint backward. 

I see what you are saying now about the `@Input`s being moved into the `@Directive`. I tried to reproduce in a small application using a custom directive, but it doesn't seem to happen there. My guess it only affects cases where it's building the index from metadata and not directly from a source directive.

**Comment by longwa** [comment]
IntelliJ ticket has some traction and feedback from one of their developers so that's good news.

**Comment by CaerusKaru** [comment]
The ticket has been marked as fixed, so I'm going to close this issue as well. Thanks again for reporting this and coordinating with the IntelliJ team!
