### ISSUE TITLE
ngStyle will override style instead of merge

### ISSUE THREAD

**Issue by kimjuan** [angular/flex-layout#944]
ngStyle will override style tag instead of merging.

**Version affect:** >= 7.0.0-beta.20

`<div style="position: relative" [ngStyle]="{ 'maxHeight.px' 48 }"></div>`

The position:relative above will be removed. Workaround:

`<div [ngStyle]="{ 'maxHeight.px' 48, 'position': 'relative' }"></div>`

**Comment by CaerusKaru** [comment]
Please upgrade to 7.0.0-beta.22
