### ISSUE TITLE
fxLayoutGap not applied to children inserted after initial render

### ISSUE THREAD

**Issue by drew-moore** [angular/flex-layout#95]
[Plunk.](https://plnkr.co/edit/d73shDnX64Lx56EbcReJ?p=preview) 

When a container with a layout gap has a child that isn't present initially (e.g. has an ngIf condition that evaluates to false), the gap is not applied to the child when it is subsequently inserted. 

Worth noting: layoutAlign is working as expected (presumably because alignment is implemented via a rule on the parent whereas gaps are implemented as margins on the children, which isn't happening for children added after the initial layout computation).

**Comment by drew-moore** [comment]
FWIW, I wouldn't expect this to work for dynamically-inserted elements in general, but the fact that it didn't work with angular's core structural directives (ngIf, ngSwitch, et al) was unexpected, particularly with this project being under the @angular umbrella,

Also, without having dug into this library's source yet, intuitively I would expect that supporting these directives would be feasible given that the elements are present at compile time. I can try to put a PR together next week if you think it'd be worthwhile.

**Comment by ThomasBurleson** [comment]
Definitely an oversight. We will fix. Thx

**Comment by ThomasBurleson** [comment]
@drew-moore - this issue is non-trivial to solve since the `@ContentChildren` does not support the **`*`** selector to match all content-children. Currently the developer must know the Type or the template variable ref name... neither of which is practical for our needs.

The only other current option is to watch with a MutationObserver. 

> This is a known issue in Angular:  https://github.com/angular/angular/issues/9989

@pkozlowski-opensource - any thoughts

**Comment by ThomasBurleson** [comment]
@drew-moore - see pending Pull Request #124
