### ISSUE TITLE
Can Ionic App implement Angular Flex Layout

### ISSUE THREAD

**Issue by Thomas0921** [angular/flex-layout#956]
# Bug Report

#### What is the expected behavior?
1. Angular flex layout should be working in ionic app too. Or maybe It can, just the way I was doing wrong maybe.

#### What is the current behavior?
I got this error, after adding it in my app.module.ts

`core.es5.js:487 Uncaught TypeError: Object(...) is not a function
    at core.es5.js:487
    at Object.<anonymous> (core.es5.js:489)
    at __webpack_require__ (bootstrap 41c5c4a066bb227b5140:54)
    at Object.<anonymous> (flex-layout.es5.js:1)
    at __webpack_require__ (bootstrap 41c5c4a066bb227b5140:54)
    at Object.375 (main.ts:5)
    at __webpack_require__ (bootstrap 41c5c4a066bb227b5140:54)
    at Object.370 (main.ts:1)
    at __webpack_require__ (bootstrap 41c5c4a066bb227b5140:54)
    at webpackJsonpCallback (bootstrap 41c5c4a066bb227b5140:25)`

#### What are the steps to reproduce?
1. npm i angular flex layout
2. include it in app.module.ts

#### What is the use-case or motivation for changing an existing behavior?
1. let's ionic fans have a chances to love Flex Layout too.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
1. `"@angular/flex-layout": "^7.0.0-beta.22",
"@angular/compiler-cli": "5.2.11",`
2.  CLI PRO 4.3.1
3. node v8.11.4

**UPDATE**
I found these error in my terminal, might be useful to know what was wrong

[app-scripts] [08:28:31]  typescript: ...de_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts, line: 29
[app-scripts] [08:28:31]  typescript: ...de_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts, line: 30
[app-scripts] [08:28:31]  typescript: ...de_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts, line: 30
[app-scripts] [08:28:31]  typescript: ...de_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts, line: 40
[app-scripts] [08:28:31]  typescript: ...de_modules/@angular/flex-layout/core/typings/match-media/server-match-media.d.ts, line: 56
[app-scripts] [08:28:31]  typescript: ...modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts, line: 1
[app-scripts] [08:28:31]  typescript: ...modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts, line: 1
[app-scripts] [08:28:31]  typescript: ...Bean/node_modules/@angular/flex-layout/flex/typings/flex-offset/flex-offset.d.ts, line: 9
[app-scripts] [08:28:31]  typescript: ...edBean/node_modules/@angular/flex-layout/flex/typings/layout-gap/layout-gap.d.ts, line: 9

**Comment by paulstelzer** [comment]
I am using Ionic with `@angular/flex-layout` without any problems, but I am already using `"@ionic/angular": "^4.0.0-rc.0"`.

**Comment by ThomasBurleson** [comment]
You can install the latest build:

```shell
 yarn add https://github.com/angular/flex-layout-builds#master-1c136bc @angular/cdk --save
```

then add the FlexLayoutModule to your app module:

```
import { FlexLayoutModule } from '@angular/flex-layout';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    FlexLayoutModule
    ...
  ]
})
export class AppModule
```

This works for me with the `@ionic/angular` 4.0 rc1:

```js
    "@angular/cdk": "^7.2.1",
    "@angular/common": "~7.1.4",
    "@angular/core": "~7.1.4",
    "@angular/flex-layout": "https://github.com/angular/flex-layout-builds#master-1c136bc",
    "@angular/forms": "~7.1.4",
    "@angular/http": "~7.1.4",
    "@angular/platform-browser": "~7.1.4",
    "@angular/platform-browser-dynamic": "~7.1.4",
    "@angular/router": "~7.1.4",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.1",
    "@ionic/pro": "2.0.4",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
```

> Closing this issue as invalid.

**Comment by bhandaribhumin** [comment]
still facing issue 
```
 ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,19): error TS2305: Module '"/Users/rac/Desktop/git/rti-v-4/node_modules/@angular/common/common"' has no exported member 'ɵNgClassImpl'.
[ng] node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,33): error TS2305: Module '"/Users/rac/Desktop/git/rti-v-4/node_modules/@angular/common/common"' has no exported member 'ɵNgClassR2Impl'.
[ng] node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,19): error TS2305: Module '"/Users/rac/Desktop/git/rti-v-4/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleImpl'.
[ng] node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,33): error TS2305: Module '"/Users/rac/Desktop/git/rti-v-4/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleR2Impl'.
```
