### ISSUE TITLE
npm repo version problem

### ISSUE THREAD

**Issue by brunopereira27** [angular/flex-layout#96]
I'm having some dependency problems trying using flex-layout with my project.

In last angular blog post, which announced material beta release, it was stated that flex-layout was also available for angular 2.4.0+.

I'm using angular 2.4.1, however when trying to install flex-layout with:

`npm install @angular/flex-layout
`
Which fails because of dependency issue saying that angular ~2.2.3 is required. That's fine, but it doesn't corresponds to what the blog post stated, neither to current master package.json angular version. 

I also tried by the way, to install it with npm install https://github.com/angular/flex-layout-builds.git to have latest change from master, but still, it says it requires angular ~2.2.3. npm view @angular/flex-layout also shows peerDependency at angular ~2.2.3. 

Also I saw some closed issues where people managed to use flex-layout with angular 2.3.0 (which doesn't match ~2.2.3), so I apologize for the useless issue if the problem comes from my bad understanding, but I think that it is a real issue.

**Comment by ThomasBurleson** [comment]
This should be fixed with SHA 36e8703 and available on **npm** with the upcoming beta.2 release.
