### ISSUE TITLE
please document or force dependency on @angular/cdk

### ISSUE THREAD

**Issue by amitport** [angular/flex-layout#960]
currently on running flex-layout without cdk we gives an error: 'Cannot find module '@angular/cdk/bidi'.'

people need to search in closed issues to find that this dependency is required and why.

**Comment by CaerusKaru** [comment]
I've updated the following docs pages:
* https://github.com/angular/flex-layout/wiki/NPM-Installs
* https://github.com/angular/flex-layout/wiki/Using-Angular-CLI
* https://github.com/angular/flex-layout/wiki/Fast-Starts

Please let me know if there are any other pages that need to be updated.
