### ISSUE TITLE
fxHide with custom breakpoint directive not working in AOT

### ISSUE THREAD

**Issue by hags033** [angular/flex-layout#961]
# Bug Report

#### What is the expected behavior?
Expect for the element to hide at desired custom breakpoint

#### What is the current behavior?
Element hides at desired custom breakpoint when not running aot, but does not hide in aot

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-j5xkix

#### What is the use-case or motivation for changing an existing behavior?
Adding in a min-height breakpoint 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.4, Typescript 3.1.6 Flex Layout 7.0.0-beta.22 all browsers

#### Is there anything else we should know?
You'll need to download the stackblitz and run ng serve (angular.json already set to run aot build)

**Comment by CaerusKaru** [comment]
The StackBlitz you've provided contains no trace of custom breakpoints. Please add it and then follow-up here.

**Comment by hags033** [comment]
Forgot to hit save on the stackblitz, the demo link is now up to date.

**Comment by CaerusKaru** [comment]
Damn that is a terrible bug. I'll investigate this weekend and hopefully track this down. Thanks for catching this!

**Comment by ThomasBurleson** [comment]
@CaerusKaru - this is working **great** with the latest code base. 
>  I will add this to our online demos.

**Comment by CaerusKaru** [comment]
There's a chance this was patched by #978. @hags033 can you build this against 7.0.0-beta.23 and see if the issue still exists?

**Comment by CaerusKaru** [comment]
Anecdotally I can confirm this has been patched by updating the StackBlitz and running `ng serve --aot` locally. If this is still an issue, we can reopen later.

**Comment by hags033** [comment]
@CaerusKaru works great, thanks for addressing this so quickly.
