### ISSUE TITLE
IE11: Column layout doesn't work

### ISSUE THREAD

**Issue by starquake** [angular/flex-layout#966]
# Bug Report

Column layout doesn't seem to work correctly in IE11. Unless I'm doing something wrong. In that case I would love to hear what. :-)

#### What is the expected behavior?

![image](https://user-images.githubusercontent.com/1044544/50599261-d0663100-0ead-11e9-8167-96ff7a010230.png)

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/1044544/50599245-c7755f80-0ead-11e9-8ca4-207a3806023c.png)

#### What are the steps to reproduce?
Just create a simple column with some divs:
https://stackblitz.com/edit/angular-flex-layout-seed-yjuuv6

#### What is the use-case or motivation for changing an existing behavior?
The site looks totally different in IE11. I hoped this library would take into account cross browser differences.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
IE11

**Comment by CaerusKaru** [comment]
Set `height: 100%` on the flex container and it should work. Let me know if it doesn't.

**Comment by starquake** [comment]
Setting height: 100% indeed fixes this problem. I created this simplified sample of a problem having in a real world application. Unfortunately setting height: 100% there doesn't work.

I'll try to replicate the full problem in another stackblitz.

**Comment by starquake** [comment]
Yeah so this can be closed. I just learnt this:
```
CanIuse.com reports and tracks many browsers issues using FlexBox; especially with IE browsers and Column stacking layouts.
```
Turns out I need to figure out all the implementation issues. I'm getting flashbacks to IE6 times...

Thanks for helping though!
