### ISSUE TITLE
fxLayoutAlign="space-between" ...Help?

### ISSUE THREAD

**Issue by Kizmar** [angular/flex-layout#97]
I can't get "space-between" to work with my limited understanding of this framework. Can you provide an example of a column with two rows in it that have space between them (without setting a height)?

I ended up having to do something like this to get what I wanted:
```
<div fxLayout="column">
	<div fxLayout="row">
		<div fxFlex>
			<md-card>Test</md-card>
		</div>
	</div>
	<div fxFlex="20px"></div>
	<div fxLayout="row">
		<div fxFlex>
			<md-card>Test</md-card>
		</div>
		<div fxFlex="20px"></div>
		<div fxFlex>
			<md-card>Test</md-card>
		</div>
	</div>
	<div fxFlex="20px"></div>
</div>
```

**Comment by ThomasBurleson** [comment]
Please look at our online - [Layout Children with fxLayoutAlign](https://tburleson-layouts-demos.firebaseapp.com/#/docs):

```html
<div fxLayout="row" fxLayoutAlign="space-between center" >
```

**Comment by Kizmar** [comment]
I have reviewed that, and it doesn't help because it doesn't show you how the child elements should be set up.

**Comment by ThomasBurleson** [comment]
Apologies that our demo "source view" is not yet ready. See the demo source here:

https://github.com/angular/flex-layout/blob/master/src/demo-app/app/docs-layout/layoutAlignment.demo.html#L7

> If this does not help, please prepare a Plunkr with the issue OR post questions on the [Gitter](https://gitter.im/angular/flex-layout) channel
