### ISSUE TITLE
fxLayoutGap grid does not seem to work

### ISSUE THREAD

**Issue by literalpie** [angular/flex-layout#970]
# Bug Report

#### What is the expected behavior?
`fxLayoutGap="16px grid" fxLayout="rowWrap"  should result in a gutter between all elements in a grid.

#### What is the current behavior?
adding `fxLayoutGap="16px grid"` causes no gaps between flex elements, and seems to add a 16px margin on the right side

#### What are the steps to reproduce?
In the stackblitz, change `fxLayoutGap="16px"` to `fxLayoutGap="16px grid"`

*  [Stackblitz](https://stackblitz.com/edit/flex-layout-grid-bug?file=src/app/app.component.html)

#### What is the use-case or motivation for changing an existing behavior?
It seems to be a bug. It's possible that I am _totally_ misunderstanding the expected behavior, in which case, I will offer documentation wording suggestions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.x, flex-layout beta 22

**Comment by CaerusKaru** [comment]
You have to be extra careful when working with flex, margins, and padding. I think this template is what you're looking for:

```html
<div style="background-color: red;" fxLayout="row wrap" fxLayout.xs="column" fxLayoutGap="16px grid">
  <div *ngFor="let i of cards" style="height: 200px;  background-color: blue;">
    <div fxFlex="1 0 200px" style="background-color: green"></div>
  </div>
</div>
```

**Comment by literalpie** [comment]
Okay, that worked. It looks like you had to remove fxFlex from the direct (blue) child and put it in a (green) grandchild. I can still add flex to the blue child to make the green grandchildren grow to fit the container. 

So is the rule that the grid option will not apply gutters on any direct children that have fxFlex?

**Comment by CaerusKaru** [comment]
I don't have a complete rationale for it, but yes that's generally the rule. I haven't been able to come up with a good way to phrase that for the docs, but we'll try to add it some time this week.

**Comment by literalpie** [comment]
Okay, I think I've been causing confusion by using background color as an indicator of where there's padding. the padding (gutter) is included in the background color, so it's impossible to tell where the lines between elements are. 

Direct children have perfectly fine gutters around _content_, but if you want gutters around a whole element (gutters around mat-cards, or gutters around an element of a color), that's when you need two levels - a child that contains the gutter, and a grandchild that fits between the gutters.

Maybe the docs could say something like:
> Unlike the standard gap functionality, fxLayoutGap with the grid keyword uses the padding of each element to add a gutter.

It kind of already says that, but maybe this is more clear

**Comment by BenDevelopment** [comment]
Here is a specific case where fxLayoutGap is not managed when fxHide changes:
https://stackblitz.com/edit/angular-pnh2nf
As you can see, when a div is hidden, gap is not removed. And when a div is shown, gap is not added.

Should I open a new issue?

**Comment by CaerusKaru** [comment]
@BenDevelopment check out PR #983

**Comment by BenDevelopment** [comment]
I've added another case when using column instead of row (the problem looks the same):
https://stackblitz.com/edit/angular-fxhidegap
