### ISSUE TITLE
Layout 2 columns full height Adjustable content

### ISSUE THREAD

**Issue by miguelsmuller** [angular/flex-layout#981]
![captura de tela 1](https://user-images.githubusercontent.com/4589909/51078714-15097d80-16a1-11e9-9054-f5e6df6dc356.png)

I'm trying to make this layout stay with the full height of the window or the internal content. But I never can.
Below is my code and I do not know where I might be wrong.
I know it might not be the right place, but could anyone help me?

```
<!-- FLEX-CONTAINER - WRAP - INLINE STYLES FOR CORRECTION -->
<div fxLayout="row nowrap" fxFlexFill fxLayoutAlign="start stretch">

  <!-- FLEX-CHILD - LEFT -->
  <div id="login-information" fxFlex="1 1" fxFlexFill>
    <div style="height: 850px; width: 300px; background-color: red;"></div>
  </div>

  <!-- FLEX-CHILD - RIGHT -->
  <div id="login-form" fxFlex="1 1" fxFlexFill>
    <div style="height: 900px; width: 300px; background-color: green;"></div>
  </div>

</div>
```

**Comment by CaerusKaru** [comment]
The correct place to get support for this would be [Gitter](https://gitter.im/angular/flex-layout) or StackOverflow.
