### ISSUE TITLE
ngClass with breakpoints doesn't remove class once added.

### ISSUE THREAD

**Issue by mhosman** [angular/flex-layout#992]
# Bug Report

#### What is the expected behavior?
When ngClass is used with breakpoint then it should add specified class for that breakpoint and remove once breakpoint changes

for below example
`[ngClass.lt-md] = "'test'"`

#### What is the current behavior?
ngClass is not removing class when screen size changes.

#### What are the steps to reproduce?
Try to resize the screen and observe behavior. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7+
flex-layout 7.0.0-beta23

#### Is there anything else we should know?
It was working fine till 7.0.0-beta.19

**Comment by CaerusKaru** [comment]
Workaround in the meantime is to add `ngClass=""` to any element without it.

**Comment by CaerusKaru** [comment]
This will be fixed by #995. Thanks for catching this!
